### ISSUE TITLE
Are nested ifs permitted?

### ISSUE THREAD

**Issue by Muzical84** [wycats/handlebars.js#1000]
I have an object that has either phone or e-mail per array item.  Is the following legal?  (The "s-start-with? is from dashbars https://github.com/pismute/dashbars and follows its documentation, though it doesn't answer the nested-if question, either =-\ )  I'm getting a parse error in Chrome, but even if I take out all of the nested ifs, it still gives the error:

```
Uncaught Error: Parse error on line 142:
...                    {{else}}           
-----------------------^
Expecting 'OPEN_ENDBLOCK', got 'INVERSE'
```

```handlebars
    <td>{{#each phone}}
                        {{#if (s-start-with? 'Y' PRIMARY_FLAG)}}
                            <span class="primaryInformation">
                        {{/if}}

                        {{#if this.PHONE}}
                            {{this.PHONE}}
                        {{else}}
                            {{#if PHONE_SEARCH}}
                                {{PHONE_SEARCH}}
                            {{else}}
                                No phone or e-mail data found
                            {{/if}}
                        {{/if}}
                        <span class="lightBlue">
                            {{#if COMM_LOCATION_CODE}}
                                {{COMM_LOCATION_CODE}}
                            {{else}}
                                {{#if PHONE_TYPE}}
                                    {{PHONE_TYPE}}
                                {{else}}
                                    Type not given
                                {{/if}}
                            {{/if}}
                        </span>

                        {{#if (s-start-with? 'Y' PRIMARY_FLAG)}}
                            </span>
                        {{/if}}
                        <br />
                    {{/each}}
                </td>
```

Actually...what about nested each?  IE for processing arrays of arrays?  Because the parent context is being iterated over with each (see https://github.com/wycats/handlebars.js/issues/997 )
Thanks!

**Comment by kpdecker** [comment]
You can have any combination of nested helpers. I'm not sure why you're getting a syntax error, but I can't really help diagnose your issue as that error message doesn't seem to relate to the posted snippet. As always if you post a fiddle/codepen/whatever showing the error you are having and not another error, I might be able to assist.
