### ISSUE TITLE
What is the difference between @index and @key  ?

### ISSUE THREAD

**Issue by nimojs** [wycats/handlebars.js#1001]
```
{{#each array}}
  {{@index}}
{{/each}}
```

```
{{#each array}}
  {{@key}}
{{/each}}
```

Can you provide the demo.
Please tell me,thank you!

**Comment by kpdecker** [comment]
The two values are identical for arrays. If iterating over an object, `@key` will be the name of the key value. and `@index` will be a zero-based integer indicating the loop iteration.
