### ISSUE TITLE
Suggestion: Include minified library for download?

### ISSUE THREAD

**Issue by Muzical84** [wycats/handlebars.js#1002]
I've created my own handlebars-vxxx.min.js via the Google compiler tool, but I always prefer to use a minified library produced by the library team, when possible--they'll test if it works properly far better than I will.  I've just noticed that, since minifying, my page loads 75% faster, on average.  That's...significant.  Also, it just seems that using minified JS is considered a "best practice," currently, by the community in general.  For my project, pre-compiling isn't an option, so I can't take advantage of those performance gains.

**Comment by kpdecker** [comment]
Minimized libraries are available here:
https://github.com/components/handlebars.js

But I would recommend using the non-minimized form and link them to your project through your own build tool that concatenates and minimizes. No testing is done on the minimized libraries directly and generally it makes things easier to not have the minimized code if your build pipeline support sourcemaps or non-optimized mode for development.
