### ISSUE TITLE
how to make sure handlebars.js template complete, beacuse I want to use highlight.js

### ISSUE THREAD

**Issue by childeYin** [wycats/handlebars.js#1010]
how to make sure handlebars.js template complete, beacuse I want to use highlight.js

**Comment by kpdecker** [comment]
I'm not sure what you are asking here. Can you provide more details?

**Comment by childeYin** [comment]
I solved it ,because I can't make sure the template was compiled and render complete,so that when I use highlight is not available, I can't find any function (for example callback) to make sure  render complete, I use window.load solve it; so sorry for my english

**Comment by kpdecker** [comment]
Closing as it sounds like this is up and running.
