### ISSUE TITLE
Debug Mode

### ISSUE THREAD

**Issue by alexortiz201** [wycats/handlebars.js#1012]
E.g. when flagged on, if re-declaring a fn or partial throw an warning. Might be intentional, so a warning should do, had an issue where two devs declared different fn's with the same name. Nightmare

**Comment by kpdecker** [comment]
I'm conflicted between implementing this in the library itself and suggesting that people monkey patch. I see the value but I'm also concerned about the overhead that this adds in the form of sanity code that is effectively dead code outside of development time.

**Comment by kpdecker** [comment]
Thinking about this a bit more, I think that redeclaration is a valid use case. Something like this monkey patches can be used if you want to add this to your own codebase:

```
(function() {
  var $registerHelper = Handlebars.registerHelper;

  Handlebars.registerHelper = function(name, fn) {
    if (Object.prototype.toString.call(name) === '[object Object]') {
      for (var key in name) {
        if (Object.prototype.hasOwnProperty.call(name, key)) {
          if (this.helpers[key]) {
            throw new Handlebars.Exception('Helper "' + key + '" redefined');
          }
        }
      }
    } else {
      if (this.helpers[name]) {
        throw new Handlebars.Exception('Helper "' + name + '" redefined');
      }
    }

    $registerHelper.call(this, name, fn);
  };
}());

```
(You will want to test this for yourself as I did not test that this works properly)
