### ISSUE TITLE
Proposal - partials with body content

### ISSUE THREAD

**Issue by mattkime** [wycats/handlebars.js#1014]
I'm working with some very simple template content that wraps body content. Currently, I must create a helper to make this happen. It would be nice to be able to use a partial

```
{{#> partial/path}}
    inner content
{{/>}}
```
and the inner content would be available via a var named 'body' (could be named something else)

any thoughts? love it or hate it?

**Comment by waynedpj** [comment]
:+1:

**Comment by tbranyen** [comment]
@mattkime that looks really similar to template inheritance.  I've implemented something similar that looks like: https://github.com/tbranyen/cropcircle/blob/master/views/pages/index.html#L1

I think it's really useful for page/layouts esp. with express view rendering.

**Comment by Florian-R** [comment]
See #208 or for now just use https://github.com/shannonmoeller/handlebars-layouts

**Comment by kpdecker** [comment]
I think a feature like this would be beneficial, but I think having things be named is very important as only having one instance is somewhat limiting.

Closing this in favor of #208, which is still open but has not really received much attention lately :(

**Comment by mattkime** [comment]
>I think having things be named is very important as only having one instance is somewhat limiting.

having only one body instance is a very common use case as it mirrors the structure of html. 

i think part of the reason why the partial/body helper syntax hasn't gotten more traction is because there's a lack of clarity regarding the relationship between the partial helper and the partial itself. this is easily resolved if some sort of "close partial" tag is provided.

**Comment by mattkime** [comment]
+1 @Florian-R i really like whats going on there
