### ISSUE TITLE
Register media/ mime type with IANA

### ISSUE THREAD

**Issue by vanthome** [wycats/handlebars.js#1017]
It would be great, if you could register the mime type here:

http://www.iana.org/assignments/media-types/media-types.xhtml

The data from this registry is used by other projects (especially in the node.js eco system).
A registration would solve many issues like templates being detected to be compressible with gzip etc.

**Comment by kpdecker** [comment]
I'm familiar with the use of MIME types for HTTP transfer, but handlebars templates really shouldn't be sent raw over the wire, not concatenated with anything else. What other benefits would this provide?

**Comment by vanthome** [comment]
Well, we have a use case where we do transfer HBS templates on-the-go and compile them on the client side after they are loaded. This is because we have a lot of templates of which a user only needs a few and we cannot know which ones beforehand. 
I know that this is bad practise and usually you compile and bundle everything at build time but let's just assume this is not feasible.
Also we have an admin application where we allow editing templates in an s3 like object store and also in this case they should be compressed on-the-fly on the server side.

**Comment by kpdecker** [comment]
Why not precompile them on the server and send down the javascript? Sending the full compiler to the client is normally something to avoid for a variety of reasons.

I don't know what is involved with registering with IANA and don't see a huge benefit for the ecosystem as a whole. That being said, if you wanted to register something and submit a PR with documentation on this, I would not be opposed.

**Comment by vanthome** [comment]
Well again, if your server is just an s3 like remote filesystem and you have neither the possbilitiliy nor any benefits from precompiling, why would you do that?!
Also I think this discussion is to problem centric. 
On a meta level, you should have a strong motivation to register it with IANA to manifest handlebars as a well known media type.
Again, this stuff may be used for purposes we don't even think about, so why preventing it?!
