### ISSUE TITLE
The each-helper ignores the Empty-String property

### ISSUE THREAD

**Issue by stephangiesen** [wycats/handlebars.js#1021]
Hello,
thank you for this nice tool, it helped us a lot.

I'm stumbled on a problem with the each-helper.

It ignores the Empty-String property. When you iterate thru an object like this
```javascript
{
 "": "Please Select" , 
 "adult": "Adult", 
 "teenager": "Adolescents aged 13 - 18 years", 
 "child": "Children under 12 years"
}
```
The first option with the empty string as key will be ignored.
To fix this I changed in handlebars.runtime-v3.0.3.js the two lines 325 and 332 from

```javascript
if (priorKey) {
```
to
```javascript
if (priorKey !== undefined) {
```

So it works fine for me.

Nice regards 
Stephan

**Comment by kpdecker** [comment]
Thanks for the report. Will have this fixed by the next release.
