### ISSUE TITLE
handlebars requires source-map.js in v3.0.3

### ISSUE THREAD

**Issue by HoffmannP** [wycats/handlebars.js#1022]
Hy, I have an request for source-map.js if I use Handlebars together with require.js. Any Idea why that?

**Comment by kpdecker** [comment]
Source maps are used for the precompiler. What build are you trying to load with require.js?

**Comment by kpdecker** [comment]
Closing this as there aren't enough details. If you are using one of the normal builds or even the amd specific build, this should not be happening. If you can put together a jsfiddle demonstrating the issue then I'm glad to reopen.
