### ISSUE TITLE
is it possible for nested custom helpers to communicate between each other?

### ISSUE THREAD

**Issue by mattkime** [wycats/handlebars.js#1023]
i'm curious if its possible or if anyone has created something like this -

```
{{#customHelper}}
    {{attr key="id" value="unique_val"}}
    {{attr key="class" value="not_unique"}}
{{/customHelper}}
```

where the customHelper either has some knowledge of the tag structure within it 

OR 

the attr helper is able to set values such that customHelper is aware of them.

this could be a very useful tool for composing content.

**Comment by kpdecker** [comment]
Right now, you could create a data object that you intend to be mutated. The bigger problem, which #1018 is attempting to solve is there is no way to define these things without executing the child function so you end up with a convoluted exec flow if you have these sorts of helpers and other normal generation logic. Closing this in favor of #1018 as those will hopefully be generic enough to handle this use case cleanly.
