### ISSUE TITLE
Document #each list as |blah| etc

### ISSUE THREAD

**Issue by rclai** [wycats/handlebars.js#1025]
Wouldn't it be incredibly valuable to document [this use of #each](https://github.com/wycats/handlebars.js/blob/c6ab044fa88d54ace17200b47213c80cdb24ead6/spec/builtins.js#L124)? It would really be a great alternative (and less of an eye-sore) than to have to do `../parentField`, especially when nesting `#each`'s.

**Comment by kpdecker** [comment]
Looks like we missed these docs when implementing. We should document this. Anyone who wants to take a crack at this, the best location is somewhere around here:
https://github.com/wycats/handlebars-site/blob/master/src/pages/builtin_helpers.haml#L133

**Comment by zordius** [comment]
A small question, the `|foo bar|` is only valid for `#each` , or we can think it is a generic array syntax for all custom helper? For example maybe we can do this: `{{#myLoop |a b c|}}` and it should be cool.

**Comment by kpdecker** [comment]
Any helper can use providing they pass the proper args. I'm not in front of
a computer right now but the each impl should provide example.

**Comment by kpdecker** [comment]
We also need to improve the documentation on how to write helpers for block parameters as well. @ErisDS has a good high level summary in #907 that covers a lot of the things that we will need to document.
