### ISSUE TITLE
about UI customize

### ISSUE THREAD

**Issue by aj4g** [wycats/handlebars.js#1030]
Hi Yehuda,

This isn't a issue, but I didn't find "send message" on github.

I split a page into many components for reusing,, such as user login, user avatar, footer and header.  
each component is wrapped in a <div>, Then I wrote a helper {{include}} to load the components in the page 
(I also wrote a handlebars.java helper to render page on server too), eg:

```` html
<html>
...
<body>
{{include "/common/header"}}
...
<div>
	<div>...</div>
	{{include "/user/login"}}
</div>
...
{{include "/common/footer"}}
</html>
````

The problem is: every time I create a new page, I have to write code manually, 
Is there a source projects can help me to design page in browser? 
For example, A blank page is a bootstrap like grid system , we can create rows, columns and cells using menu,
then add the handlebars component that we defined to grid, finally, 
save the component information(page layout, path, width, height...) to the DB?

Do you know some open source project like that?

**Comment by kpdecker** [comment]
I'm not aware of any such projects that are targeting Handlebars. If you write something I'd be glad to link to it from the projects using handlebars section!
