### ISSUE TITLE
Is Handlebars designed with concurrency in mind?

### ISSUE THREAD

**Issue by sdeleuze** [wycats/handlebars.js#1031]
That may sounds like a strange question, but I am trying to implement server-side rendering of Handlebars templates based on Nashorn Javascript engine. See http://mail.openjdk.java.net/pipermail/nashorn-dev/2015-May/004594.html for more details.

There is some kind of isolation in Nashorn (`loadWithNewGlobal` mechanism) to run each rendering call isolated, but we are using the same Handlebars global object. It seems it is safe to do concurrently multiple calls to `Handlebars.compile()`, but the compiled handlebars functions seems not been designed  to be call concurrently.

That's strange because we are generating a new function each time the page is rendered.
Is there some kind of shared state stored in `Handlebars` object used when the handlebars template rendering function is called?

Thanks in advance for your feedback.

**Comment by kpdecker** [comment]
Handlebars.compile performs [lazy evaluation](https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/compiler/compiler.js#L471-L473) of templates so this might be where your multiple function behavior comes from.

I would say that Handlebars has zero consideration for concurrency outside of standard javascript single threaded async behaviors. Formally handlebars supports running in any normal javascript environment but we/I don't really have bandwidth for specific environments. That being said, I'm glad to accept pull requests that resolve issues you might be seeing in your environment as long as they don't adversely impact our primary user base.

**Comment by sdeleuze** [comment]
@kpdecker Thanks for your feedback. I will do my best to see if I can contribute a PR, can you provide me any guidance about how to achieve that?

**Comment by kpdecker** [comment]
https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md should have the main points. The Pull Requests and Building section are the most pertinent.

**Comment by cemo** [comment]
:+1:

**Comment by sdeleuze** [comment]
My guidance request was more about having some hints about what part of Handlebars I should have a look to make it possible to render template concurently.

Any thoughts?

**Comment by kpdecker** [comment]
Not really. It's built on javascript's single thread model and no analysis
was done for other threading models. Try it and see what breaks perhaps?

**Comment by jfrantzius** [comment]
Hi @sdeleuze 
if you look at https://github.com/wycats/handlebars.js/blob/e8ceafa6525a5d41a20aa74dfe24bf99d0bc2fcd/lib/handlebars/compiler/compiler.js#L442 then you can see that in theory, the compilation/parsing should happen only on first call of the template-function.

Unfortunately, when running Handlebars in Nashorn, with the result of `Handlebars.compile()` being reused, I see it compiling/parsing again even though it shouldn't:

>         at jdk.nashorn.internal.scripts.Script$Recompilation$1245$119328$\^eval\_.L:36$L:2733$compile-1$compileInput(<eval>:3247)
        at jdk.nashorn.internal.scripts.Script$Recompilation$1244$119696AA$\^eval\_.L:36$L:2733$compile-1$ret(<eval>:3256)
        at jdk.nashorn.internal.scripts.Script$Recompilation$1714$616AA$\^function\_.L:1$register$L:25(<function>:41)
        at jdk.nashorn.internal.scripts.Script$Recompilation$1836$51AAAAA$\^function\_.L:1(<function>:9)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:670)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:228)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.internal.scripts.Script$Recompilation$1404$31688AA$\^eval\_.L:36$L:989$template$ret$main(<eval>:1160)
        at jdk.nashorn.internal.scripts.Script$Recompilation$1399$31070AA$\^eval\_.L:36$L:989$template$ret(<eval>:1163)
        at jdk.nashorn.internal.scripts.Script$Recompilation$1244$119696AA$\^eval\_.L:36$L:2733$compile-1$ret(<eval>:3258)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:644)

I was hoping that only the compilation on first call of the template must be single-threaded, and that afterwards it could be thread-safe to call the template. I have no clue, though, how the state of `let compiled` should survive multiple invocations. So I guess at least on server-side it's not reliable that Handlebars is compiling only once per template function, and so may never be thread-safe.

**Comment by kpdecker** [comment]
If that is the case, I would run away from that VM as fast as you can. :) If the output of `Handlebars.compile(template)` it truly being reused and the internal parser is running multiple times that can only occur due to the closure being corrupted at the VM level, which is highly improbable. Have you verified that the compile API is only being called once by logging the preface there? I.e. https://github.com/wycats/handlebars.js/blob/e8ceafa6525a5d41a20aa74dfe24bf99d0bc2fcd/lib/handlebars/compiler/compiler.js#L432

**Comment by jfrantzius** [comment]
thx @kpdecker you are right, the templates that I explicitly compile do pass through `compileInput()` only once (verified with log statements that show the name of the file being compiled, passed in via options). Luckily the VM seems to be alright :)

There must be something else in the rendering tree that invokes compile() and then discards the result, maybe some helper. Will try to find out ...

**Comment by jfrantzius** [comment]
Hi @kpdecker it seems that the `#extends` Helper discards the result from `Handlebars.compile()`: https://github.com/assemble/handlebars-helpers/blob/master/lib/helpers/helpers-layouts.js#L37

Do I get it right that `Handlebars.partials[]` may contain both templates as Strings and precompiled template functions? The documentation for `Handlebars.registerPartial()` sounds a bit like that (http://handlebarsjs.com/partials.html#basic-partials).

So maybe the `#extends` Helper should assign back the template function to `Handlebars.partials[layout]`?
