### ISSUE TITLE
Minification of handlebars.js verion 3.0.3

### ISSUE THREAD

**Issue by emilic** [wycats/handlebars.js#1036]
I have a recommendation.  It is not actually a problem with handlebars.js but rather a result of using JSMin for minification on the uncompressed version of handlebars version 3.0.3.

On line 1160:
varDeclarations += ', alias' + ++aliasCount + '=' + alias;

is minified to :

varDeclarations+=', alias'+++aliasCount+'='+alias;

according to author of JSMin :
a+++b
which is interpreted as

a++ + b
which is wrong. You can avoid this by using parens:

a + (++b)

Source: http://www.crockford.com/javascript/jsmin.html

I would suggest changing line 1160 to : 
varDeclarations += ', alias' + (++aliasCount) + '=' + alias;

I have tried other minifiers online and they don't seem to have this issue.  It is doubtful that JSMin will be updated since there is a specific warning not to write code this way.  I am also locked in for the moment to using JSMin.

**Comment by kpdecker** [comment]
We can't really maintain hacks for tools bugs, someone will come by in the
future and trying to simplify the code. I'd recommend filing a bug with
jsmin or switching to use uglify.

**Comment by emilic** [comment]
Yes you are right.  It is a limitation of JSMin.  Thanks for suggesting Uglify.  I was using JAWR and after a little digging found that it supports it.
