### ISSUE TITLE
Potential Bypass of EscapeExpression

### ISSUE THREAD

**Issue by adon-at-work** [wycats/handlebars.js#1039]
From https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/utils.js#L63-L82, escapeExpression assumes an object having a prototype of `.toHTML()` as equivalent of an instance of `SafeString`.

This may cause unintended bypass of `escapeExpression()` if it so happens that a developer has initiated something like `Object.prototype.toHTML`. So, anything that is NOT a `SafeString` instance will have the escaping bypassed. 

We'd like to recommend changing `toHTML` of `SafeString` to a less commonly used name (e.g., `toSafeStringHTML`) to avoid the potential problem. Checking `instanceof SafeString` will do as well.

Thanks.

Reference: https://github.com/yahoo/secure-handlebars/pull/72

**Comment by kpdecker** [comment]
We actively moved away from `instanceof` checking as it presented problems for cross context behaviors and the `toHTML` change was made in a breaking change, version 3.0, to allow people to account for this.
01a22e61df48eb512ba5dc0316855c1a8dd25956

There's not much we can do to help protect people from themselves if they are defining things like `Object.prototype.toHTML` that emits unsafe code. Renaming `toHTML` is just playing a game of whackamole that someone will come and complain about down the road.

@mmun, @wycats any differing opinions before I close this? Were we to change this, it would require a 4.0 release.

**Comment by mmun** [comment]
I agree with you @kpdecker.

**Comment by adon-at-work** [comment]
no problem.
