### ISSUE TITLE
Handlebars.compile function is missing on current (3.0.3) bundle

### ISSUE THREAD

**Issue by bwindels** [wycats/handlebars.js#1040]
Using the bundle mentioned on the handlebars website (```http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars.runtime-v3.0.3.js```), the compile function seems to be missing on the HandlebarsEnvironment:

https://jsfiddle.net/gjyL2k5L/

**Comment by jakkor** [comment]
Shouldn't the runtime version be only for precompiled templates?

**Comment by bwindels** [comment]
Ah, yes, somehow took the wrong link from the homepage. Thanks!
