### ISSUE TITLE
the handling of {{&expression}}?

### ISSUE THREAD

**Issue by neraliu** [wycats/handlebars.js#1041]
i have inspected the source code of the handlebars and find that the {{&expression}} will set the "escaped" field as false, does it mean that the expression will be handled like {{{raw expression}}}?

function prepareMustache
https://github.com/wycats/handlebars.js/blob/2c1d509c6cafea145ece5ff9bc8b5c2ca98f9749/lib/handlebars/compiler/helpers.js#L67

ast structure of the Mustache Statement
https://github.com/wycats/handlebars.js/blob/2c1d509c6cafea145ece5ff9bc8b5c2ca98f9749/lib/handlebars/compiler/ast.js#L18

**Comment by mmun** [comment]
Yes, it's for compatibility with the mustache specs: 

https://github.com/mustache/spec/blob/83b0721610a4e11832e83df19c73ace3289972b9/specs/interpolation.yml#L52-L66

**Comment by neraliu** [comment]
got it. thanks
