### ISSUE TITLE
Use of `as ||` in `with`

### ISSUE THREAD

**Issue by agladysh** [wycats/handlebars.js#1042]
I'd like to create an alias to outer `this` in my template.

```
{{#with this as |foo|}
  {{#each bar}}
    Foo: {{foo.baz}} 
    bar: {{bar}}
  {{/each}}
{{/with}
```

But the code above doesn't work... What am I doing wrong? Is `each` the only standard template that supports the `as ||` feature?

Fiddle: http://jsfiddle.net/xmeq3x76/1/

**Comment by kpdecker** [comment]
`with` does not support block parameters right now but this seems like a useful feature to have
