### ISSUE TITLE
#If returns true when you pass variable that is false

### ISSUE THREAD

**Issue by AndrewEastwood** [wycats/handlebars.js#1044]
I have this statement:
```{{#if this}}ture{{else}}false{{/if}}``` where ```this===false``` but the result will be ```true```

**Comment by kpdecker** [comment]
Works for me. Closing but if you post a fiddle showing the failure I can reopen.

```
> Handlebars.compile('{{#if this}}ture{{else}}false{{/if}}')
> var template = Handlebars.compile('{{#if this}}ture{{else}}false{{/if}}')
> template(false)
'false'
```
