### ISSUE TITLE
integration with angular

### ISSUE THREAD

**Issue by wormen** [wycats/handlebars.js#1049]
tell me reap there a way to use your template along with the angular if more precisely, in your template, you can transfer data from another framework

**Comment by jakkor** [comment]
I use handlebars with Backbone, so probably other frameworks or no framework are also possible.

**Comment by wormen** [comment]
and can be an example of how to implement a bunch?

**Comment by kpdecker** [comment]
I would raise this with the Angular community. Handlebars compiles to text. That text would need to then be evaluated by Angular and it seems like overkill but I'm not an Angular user so I don't really know if it has value nor how it would be done exactly.
