### ISSUE TITLE
How to do i18n work with Handlebars?

### ISSUE THREAD

**Issue by littlee** [wycats/handlebars.js#1051]
How to do i18n work with Handlebars?
I want to precompile my handlebars files, and in my .hbs file, there is some constant code, like:
```html
<button class="btn btn-default ">Click Me</button>
```
How can I make "Click Me" i18n?

**Comment by kpdecker** [comment]
Some common solutions I've seen are helpers to replace the text, i.e.

```
<button class="btn btn-default">{{i18n "Click Me"}}</button>
```

I'm not aware of any libraries that do this but you might try search for one a bit. Otherwise it's not too hard to implement yourself.
