### ISSUE TITLE
Nest raw blocks

### ISSUE THREAD

**Issue by jmm** [wycats/handlebars.js#1056]
Is there any reason handlebars can't / shouldn't be able to handle nested raw blocks, e.g.:

```handlebars
{{{{a}}}}
  {{{{b}}}}
  {{{{/b}}}}
{{{{/a}}}}
```

Expected result:
Compiling and executing that template invokes handler `a`. Executing `options.fn()` there yields:

```handlebars
  {{{{b}}}}
  {{{{/b}}}}
```

Actual result:
Exception `Error: a doesn't match b - 1:4`

Handlebars does handle these cases:

```handlebars
{{#a}}
  {{#b}}
  {{/b}}
{{/a}}

{{#a}}
  {{#a}}
  {{/a}}
{{/a}}

{{{{a}}}}
  {{#b}}
  {{/b}}
{{{{/a}}}}
```

**Comment by agladysh** [comment]
Raw blocks are, well, raw. By definition, any Handlebars markup inside is ignored. Including nested raw blocks.

**Comment by jmm** [comment]
@agladysh Sorry, I didn't explain that clearly enough. I updated my post.

> By definition, any Handlebars markup inside is not handled. Including nested raw block markup.

By "handled" I mean it can parse it, like it can parse regular nested blocks.

> The content of a raw block is always used verbatim, as it should be.

That's what I want. But it errors.

**Comment by agladysh** [comment]
@jmm Ah, sorry. It seems to be a bug then.

**Comment by kpdecker** [comment]
Tracking under #1060
