### ISSUE TITLE
Passing array as partial parameter

### ISSUE THREAD

**Issue by harrymilne** [wycats/handlebars.js#1058]
This doesn't seem to work when I try it but Handlebars doesn't give me any errors.

```
{{> myPartial test=["hello", "world"] }}
```

It doesn't seem to parse this as a string nor a array since iterating or echoing it doesn't seem to yield anything.

**Comment by kpdecker** [comment]
That is not support and should be a syntax error... Can you post a fiddle (template provided in the contributing.md doc in the repo) that shows this live?

**Comment by harrymilne** [comment]
Can't show this on jsfiddle since the {{> path/to/file.hbs }} uses an external file.

**Comment by kpdecker** [comment]
I missed this previously, this is using the [segment literal notation](http://handlebarsjs.com/expressions.html#basic-blocks), so it ends up evaluating to something like `context["\"hello\", \"world\""]`, thus no syntax error.

**Comment by smohadjer** [comment]
@kpdecker Do you know why this is not supported, I mean sending arrays to a partial?

**Comment by nknapp** [comment]
You can use a simple helper to achieve this. Its not part of the core to keep the core small. 

(...args) => args

**Comment by smohadjer** [comment]
An example would be nice, let's say we want to call a partial with two parameters, one that is a string and one that is an array, something like this:

{{> myPartial test=["hello", "world"] id="abcd" }}

How would a helper do this?

**Comment by nknapp** [comment]
I was on my cell, when I wrote my last comment, so I couldn't write a lot of text: 

I've created a fiddle with the helper that I am using in some projects: https://jsfiddle.net/9D88g/811/
String-splitting is also possible, of course.

**Comment by nknapp** [comment]
The EcmaScript 5 version of the helper is 

```js
// Array helper. Remove the last item, because that is the "options" object
Handlebars.registerHelper("arr", function () { 
	return Array.prototype.slice.call(arguments, 0, -1)
})
```

**Comment by smohadjer** [comment]
@dhollenbeck Your solution breaks if array members have semicolon in them. I can not make such assumption over value put into the array.

**Comment by dhollenbeck** [comment]
This entire thread including your request for an example is regarding how to **hardcode** array data inside a template syntax. Since you are hardcoding the array data there is no assumptions regarding the array data. If your desire is pass an array into a partial then just pass the array into the partial.

```js
var template = '{{> myPartial test=myArray id="abcd" }}';
var fnc = Handlebars.compile(html);
var context = {myArray: []};
var html = fnc(context);
```

**Comment by smohadjer** [comment]
@dhollenbeck Actually there is, otherwise I would't be asking this question. We are using handlebars in a build framework that is used by other developers. I have no idea what parameters they pass to their templates or what they put in their arrays.
