### ISSUE TITLE
Parent template indentation preserved for only first line of partial

### ISSUE THREAD

**Issue by jlutzhbo** [wycats/handlebars.js#1061]
I have the following template:

```
{
{{#with fields}}
    {{> general/partials/images}},
{{/with}}
}
```

Note the four-space indentation of the partial call. This uses the following partial template (which is compiled using Handlebars.compile and registered with the name 'general/partials/images':

```
"images": {
{{#each images}}
    "{{@key}}": "{{url}}"
{{/each}}
}
```

(Note: I realize this does not produce valid JSON, but I have replaced my call to my custom helper which appends trailing commas to simplify reproduction of the issue).

Next, I apply this input data:

```
{
    "fields": {
        "images": {
            "thumbnail": {
                "url": "/images/image1"
            },
            "detail": {
                "url": "/images/image2"
            }
        }
    }
}
```

And get this result:

```
{
    "images": {
    "thumbnail": "/images/image1"
    "detail": "/images/image2"
},
}
```
Notice that the indentation only works on the first line of the partial template, but not the subsequent lines. I expect to see this instead:

```
{
    "images": {
        "thumbnail": "/images/image1"
        "detail": "/images/image2"
    },
}
```

I am using Handlebars version 3.0.3 using NodeJS.

Thanks for looking into this!

**Comment by kpdecker** [comment]
Thanks for the thorough write up. Could you post this as a jsfiddle or
other live example of this failing so we can take a look. The contributing
doc has a temple.

**Comment by jlutzhbo** [comment]
@kpdecker Ok, I've got a Fiddle reproducing the issue: http://jsfiddle.net/9D88g/42/

I noticed that the template still pulls in Handlebars version 2.0.0. May want to fix that :-)

(Just in case the fiddle link doesn't work, here's the HTML:

```
<div id="output"></div>
<script type="template/handlebars" id="template">{
{{#with fields}}
    {{> general/partials/images}},
{{/with}}
}</script>

<script type="template/handlebars" id="partial">"images": {
{{#each images}}
    "{{@key}}": "{{url}}"
{{/each}}
}</script>
```

And here's the JavaScript:

```
var TEST_DATA = {
    "fields": {
        "images": {
            "thumbnail": {
                "url": "/images/image1"
            },
            "detail": {
                "url": "/images/image2"
            }
        }
    }
};

Handlebars.registerPartial('general/partials/images',             
    Handlebars.compile(document.getElementById('partial').innerHTML));

var template = Handlebars.compile(document.getElementById('template').innerHTML);


var output = template(TEST_DATA);
document.getElementById('output').innerHTML = output;
alert(output);
```

It seems the newlines are stripped from the result pane, so you have to look to the alert dialog that pops up to see the formatting issue.

**Comment by kpdecker** [comment]
The trailing `,` that you have on the partial call causes the partial to no longer be standalone. The indent behavior only occurs when the partial call is the only call on a given line. 

You could move the comma into the partial itself to fix this, but I would recommend not using handlebars for this particular case unless you have a very good reason to. `JSON.stringify` should handle almost all requirements for JSON generation and will require less work on your end.

**Comment by kpdecker** [comment]
An example of it working how I presume you want: http://jsfiddle.net/9D88g/44/

**Comment by jlutzhbo** [comment]
@kpdecker Not sure what you mean by no longer standalone. I opened this issue with a very simplified example to make it easy for you to reproduce / debug. My real use case is much more complex :-). So is this desired behavior, or a bug? Can we please re-open this issue until we come to a resolution? Even if that resolution is simply clearer documentation?

**Comment by jlutzhbo** [comment]
To clarify, I understand the meaning of the word "standalone" (i.e. in my example, the partial call is not the only call on the line), but I do not understand why this should affect the indentation.

**Comment by kpdecker** [comment]
Standalone is a behavior defined by the mustache spec. A particular
statement is standalone if it's the only thing on a given line other than
white space. Different statements have different behaviors when standalone
vs. not. Partials will indent all lines when standalone but do not when not
standalone. For block declarations, the line is omitted when standalone,
but included if not.

**Comment by jlutzhbo** [comment]
I may have reproduced the issue with a partial that IS standalone. I will update with an example when I get time this week.

**Comment by kpdecker** [comment]
Ok, please make a comment here when it's updated and I'll take a look.
