### ISSUE TITLE
Ability to pass in options when evaluating templates

### ISSUE THREAD

**Issue by jlutzhbo** [wycats/handlebars.js#1062]
Submitting this issue for discussion. Basically, what I am seeking is the ability to pass in options when evaluating a template. One purpose of this would be to induce subtle changes of the rendering of the template -- subtle enough that they perhaps would not warrant the creation of a separate template.

As a variation on an existing example:
```
<script id="entry-template" type="text/x-handlebars-template">
  <div class="entry">
    {{if @opts.includeTitle}}  <--- HERE
    <h1>{{title}}</h1>
    {{/if}}
    <div class="body">
      {{body}}
    </div>
  </div>
</script>
```

And the template could be invoked like so:

```
var html = template(context, { includeTitle: false });
```

Of course, there are other ways to achieve this, but I thought this would be useful. Thoughts? Thanks!

**Comment by kpdecker** [comment]
This would require that we have every helper defined, available, and able to execute at compile time which is not guaranteed and also implies that the code paths are going to be the same. Likely not something that we can do in the project proper, but it is potentially possible with the compiler AST API. Effectively you would have an AST parser that would be aware of what `if` does etc and inlines those behaviors.

Leaving open for now to mull over a little bit more, but I don't think we can support this in a generic manner across all platforms. For now I'd recommend normal parameter handling or `@data` parameters that are evaluated at runtime.

**Comment by jlutzhbo** [comment]
@kpdecker I think there may be a misunderstanding here. What I'm looking for is not compile-time behavior but rather _runtime_ behavior. In my example above (which mimics the example on the Handlebars webpage), calling template is the runtime invocation of an already compiled template. Essentially this:

```
var template = Handlebars.compile('{{foo}}');
var result = template({});   // <--- this call
```

The `context` is what is to be rendered. What I'm asking for is an additional parameter to the template method. A good way to think about it is this: if the context is the "data" to be rendered, the additional parameter contains "metadata" about the context. Your suggestion about using `@data` is fine, but I'm not sure how to inject information into that when invoking a template. (It's clear how to do it within a helper, but not on the initial invocation).

**Comment by kpdecker** [comment]
`template(context, {data: {includeTitle: true}})`. Hope that helps!

**Comment by jlutzhbo** [comment]
@kpdecker That's perfect. Thanks!!!
