### ISSUE TITLE
Bump babel to fix default export

### ISSUE THREAD

**Issue by thejameskyle** [wycats/handlebars.js#1067]
There is now an agreed upon flag for module interop that will allow transpiled modules to work together.

```js
exports.__esModule = true;
```

You should be able to just bump babel to the latest version and be set.

**Comment by kpdecker** [comment]
Won't this create an interop issue for people still using older versions of babel? Which version of our library are you using?

**Comment by thejameskyle** [comment]
No it won't, it'll just be ignored in earlier versions

**Comment by kpdecker** [comment]
Actually looking at our code, this is being set:

```
exports.__esModule = true;
```

In the compiled versions. What issue did you see that prompted you to file this?

**Comment by kpdecker** [comment]
Closing this as I believe this is being done already. Glad to reopen if you can point me to what exact package or file is incorrect.
