### ISSUE TITLE
How can I use the Node precompiler with strings instead of files?

### ISSUE THREAD

**Issue by himedlooff** [wycats/handlebars.js#1071]
I'd like to pass templates as strings instead of files to this command `$ handlebars <input> -f <output>`. Is there a way to do this?

**Comment by kpdecker** [comment]
It's not possible right now. For now I would recommend just writing your own script that does this and just calls `Handlebars.precompile` but we can look into adding support for this to the CLI.

**Comment by himedlooff** [comment]
Thanks!

![excited-harry](https://cloud.githubusercontent.com/assets/1093373/9073396/10bc98d6-3acf-11e5-9dea-23ddf4c2bb68.gif)
