### ISSUE TITLE
Whitespace management

### ISSUE THREAD

**Issue by pizzafroide** [wycats/handlebars.js#1072]
New line characters after the start tag of a section, or after a comment, are discarded. I may be wrong but I think they shouldn't be.

Here is the example from the doc with a little modification (the `~` at the of the `{{#each}}` expression was removed):
```handlebars
{{#each nav}}
  <a href="{{url}}">
    {{~#if test}}
      {{~title}}
    {{~^~}}
      Empty
    {{~/if~}}
  </a>
{{~/each}}
```
with:
```js
{
  nav: [
    {url: 'foo', test: true, title: 'bar'},
    {url: 'bar'}
  ]
}
```
results in:
```html
  <a href="foo">bar</a>  <a href="bar">Empty</a>
```
Instead of:
```html
  <a href="foo">bar</a>  
  <a href="bar">Empty</a>
```

**Edit:** When rereading the documentation, I see that:
> This expands the default behavior of stripping lines that are "standalone" helpers (only a block helper, comment, or partial and whitespace).". 

So I guess this post is most likely an enhancement request: would it be possible to disable this default behavior?

**Comment by kpdecker** [comment]
It shouldn't be that hard to add a flag to disable this behavior, but I looking at your template, your issue is not due to the standalone behavior, but due to the use of whitespace control, as those will consume newlines (standalone does not). Removing the last `~`, along with some cleanup that isn't substantial to the behavior seems to fix the issue:

```
    let string = `{{#each nav}}
  <a href="{{url}}">
    {{~#if test ~}}
      {{title}}
    {{~^~}}
      Empty
    {{~/if~}}
  </a>
{{/each}}`;

    let hash = {
      nav: [
        {url: 'foo', test: true, title: 'bar'},
        {url: 'bar'}
      ]
    };

    shouldCompileTo(string, hash, '  <a href="foo">bar</a>\n  <a href="bar">Empty</a>\n');
```
