### ISSUE TITLE
Remove the AST structures

### ISSUE THREAD

**Issue by kpdecker** [wycats/handlebars.js#1077]
These are difficult to maintain as an external API because of the array parameter mapping and they are basically just JSON generators that can be moved into the parser without much loss in fidelity or API functionality.

Filing issue to see if community has any input prior to making these changes.

/cc @mmun

**Comment by kpdecker** [comment]
As an example, most use of the `AST` methods would be converted to follow patterns like this:

```diff
 content
-  : CONTENT -> new yy.ContentStatement($1, yy.locInfo(@$))
-  ;
+  : CONTENT {
+    $$ = {
+      type: 'ContentStatement',
+      original: $1,
+      value: $1,
+      loc: yy.locInfo(@$)
+    };
+  };
 
```

**Comment by mmun** [comment]
This would be nice.
