### ISSUE TITLE
handlebars with grunt

### ISSUE THREAD

**Issue by douglasdeodato** [wycats/handlebars.js#1078]
I am using grunt to compile my handlebars templates, I got stuck when I try run my template in my HTML, if I Use chrome console I can run my template, but it not load when I call inside my javascript.

I using handlebars.runtime.js, I can see in my code its getting compiled looks great I just have no idea how to implement that in my HTML.

if I use that on my console prints my template, i would like run and see that on my HTML:

myapp.templates.user({name:"doug"});
http://pastebin.com/ZWiDzWS2

I really sure the error is in: lib/call-templates.js on that line:

html = Handlebars.template['./templates/user.hbs'](context);

I tried any path and config but I have no sucess. 

grunfile.js
http://pastebin.com/BimnAydn

lib/ call-templates.js
http://pastebin.com/qD3QEMQh

templates/user.hbs
http://pastebin.com/sUbnJYLD

tmp/templates.js
http://pastebin.com/AzBPPNyC

**Comment by kpdecker** [comment]
You're attempting to use a template name that is not defined in tmp/templates.js. You should use `this.myapp.templates.user()`

**Comment by douglasdeodato** [comment]
really sorry for ask that, I just learning, but should i should implement like that?

$(document).ready(function() {
var context = {
		name: "doug",
		}

html = Handlebars.templates['this.myapp.templates.user'](context);
$(document.body).html(html);

});

**Comment by kpdecker** [comment]
No, your template is being assigned to `this.myapp.templates.user` on line 4 of this file http://pastebin.com/AzBPPNyC.

That's a javascript path, not a key on the `Handlebars.templates` object.

Assuming that nothing is erroring for init, you want something like this:

```
html = this.myapp.templates.user(context);
```

**Comment by douglasdeodato** [comment]
Thanks a lot, i am getting this error:
Uncaught ReferenceError: require is not defined(anonymous function) @ myapp.development.js:20
myapp.development.js:16

Uncaught TypeError: Cannot read property 'this.myapp.templates.user' of undefined

in my file: http://pastebin.com/yjGiXXpH

again if i type in my console: this.myapp.templates.user()  i get 

"<div>

<p class="user">

hi , my name is .

</p>

</div>"

anyway thanks for the help, i really appreciate

**Comment by kpdecker** [comment]
It sounds like you have some sort of startup error that you'll have to debug, I can't really help without seeing the whole thing up and running somewhere.

**Comment by douglasdeodato** [comment]
Hi , thanks again for your reply : actually you can test and see everything here in my project: https://github.com/douglasdeodato/mygruntconfig

you need do npm install and bower install to get the packages :)

feel free to fork my project, i will be very helpful for me have a professional touch there, i am stucking in that stuff for a week i can not resolve.

again thanks a lot.
