### ISSUE TITLE
Vulnerability reported in NSP in uglify-js which is a dependency

### ISSUE THREAD

**Issue by stephanbakker** [wycats/handlebars.js#1085]
source: https://nodesecurity.io/advisories/uglifyjs_incorrectly_handles_non-boolean_comparisons

Handlebars has a dependency on uglify-js.

We use NSP for scanning our dependencies for vulnerabilities, and get this error, due to our handlebars dependency.

**Comment by agladysh** [comment]
See #1084

**Comment by stephanbakker** [comment]
Cool! Already working on it!

**Comment by kpdecker** [comment]
Closing in favor of #1085
