### ISSUE TITLE
publish new version to npm with vulnerability 'fix' PR #1084

### ISSUE THREAD

**Issue by fidgety** [wycats/handlebars.js#1086]
Any chance? so I can then get other npms that use handlebars to bump their version?

**Comment by nkbt** [comment]
:+1:

**Comment by Cowa** [comment]
:+1:

**Comment by agladysh** [comment]
It seems that GitHub doesn't see issue references in the issue headers: #1084

**Comment by kpdecker** [comment]
Released in 4.0.0

**Comment by fidgety** [comment]
ace. thanks.
