### ISSUE TITLE
Square braces in key name

### ISSUE THREAD

**Issue by distantnative** [wycats/handlebars.js#1092]
I have the following data structure:
```
[Log] [ (panel, line 126)
Object
countries[]: Array[2]
    0: "de"
    1: "en"
rate: "3 %"
]
```

And would like to output it with:

```
{{rate}}: {{countries[]}}
```

Sadly, this isn't working. The square brackets in the key name `countries[]` seem to be the problem. They get created by the CMS. If I remove them manually, `{{rate}}: {{countries}}` works. Any idea how to make it work with the square brackets in the key?

**Comment by BenjaminHorn** [comment]
I can not see any different between your "working" and "not working" example.
What is the desired result?

**Comment by distantnative** [comment]
Sorry, the working example should be without the brackets: `{{rate}}: {{countries}}` (edit above). This works after manually changing the data structure to

```
[Log] [ (panel, line 126)
Object
countries: Array[2]
    0: "de"
    1: "en"
rate: "3 %"
]
```

(`countries` key without brackets)

But since the CMS usually gives me that array with `countries[]` as key, I would be happy to find a working way to get this working as well.

`{{rate}}: {{countries[]}}` throws the following error:

```
[Error] Error: Parse error on line 12:
...        {{rate}}: {{countries[]}}      <
-----------------------^
Expecting 'ID', 'DATA', got 'INVALID'
```

**Comment by kpdecker** [comment]
`[]` is used for ID lookups so this is being parsed as a language operator. For values in the first position you can do `{{"foo[]"}}` and it will lookup  the value. This will not work for arguments to helpers though. We need to allow for some sort of escaping of these values, or alternatively treat them as part of the ID when not in the leading position.

**Comment by kpdecker** [comment]
Released in 4.0.3

**Comment by wojcikstefan** [comment]
@kpdecker unless I'm missing something, this still doesn't work. Consider the example that you use in 0878179 for the tokenization unit test: https://github.com/wycats/handlebars.js/commit/08781798f564a68abee11c74e2b98272657b2a56#diff-03f34a34f3e0cca43f4403093688e205R150

Trying it out via http://tryhandlebarsjs.com/ fails:

<img width="1108" alt="screen shot 2017-01-17 at 3 21 33 pm" src="https://cloud.githubusercontent.com/assets/1718372/22038437/3048a3d2-dcc9-11e6-8707-63a813022876.png">

**Comment by trieu-hphuc96** [comment]
I stuck at here too, Is there another way? It doesn't work. Thanks in advance.
