### ISSUE TITLE
#each skips entry of dict with empty value since 4.0.0

### ISSUE THREAD

**Issue by florianpilz** [wycats/handlebars.js#1093]
If I have an template like this:

    {{#each data}}
    <span class="{{@key}}">{{this}}</span>
    {{/each}}

Handlebars will render nothing when data is a dict entry with empty value, i.e. if I render above template with

    template({data: {
        'first': null,
        'second': 'bar',
    }});

Only `second` will be rendered, but `first` will be ignored.

I have made a JSFiddle to demonstrate the behaviour:

* old behaviour with Handlebars 3.0.3, where it will **render** `first` https://jsfiddle.net/jag017t2/1/
* new behaviour with Handlebars 4.0.2, where it will **skip** `first` https://jsfiddle.net/5n6t61kz/5/

I have tested the behaviour with 4.0.0 and it is skipped there as well, so it's a problem introduced in 4.0.0.

Is this the intended behaviour now? It is not stated in the documentation and I can't see a good match in the release notes. It breaks our application, since we expect to have 7 `<td>` columns rendered by Handlebars, but 2 are missing due to `null` values.

**Comment by kpdecker** [comment]
This was changed due to #1065 where helpers fail when executing against a null context for non-strict mode. I would suggest using `''` rather than `null` as this will render safely for all contexts. Baring that we might be able to implement a flag to allow for this unsafe iteration but I'm not sure on what sort of ETA that might have.

**Comment by Marsup** [comment]
Same problem with undefined values on lout for me where I try to iterate over objects.
I'm not sure I see why it's related to sparse arrays, can't we make a difference between objects and arrays ?

**Comment by kpdecker** [comment]
@Marsup the root problem is that helpers were being called like `helper.call(undefined)` and under non-strict mode this would execute against the global object leading to surprises. I'm now starting to think that it's better to:

1. Execute for all defined keys (sparse arrays will skip elements)
2. Fail over context execution to an empty object if not defined. i.e. something like `helper.call(context || {})`

It's not ideal but seems to provide the best middle ground for handling undefined in non-strict mode.

**Comment by Marsup** [comment]
You should probably explicitly check for null and undefined, other falsy values should work.

**Comment by kpdecker** [comment]
Good call, took that into account.

**Comment by kpdecker** [comment]
Released in 4.0.3

**Comment by florianpilz** [comment]
Thanks, works like a charm!
