### ISSUE TITLE
Move cli outside

### ISSUE THREAD

**Issue by TrySound** [wycats/handlebars.js#1094]
It depends on uglify which is too big. And it has big dependency tree. Problem is there are many versions of handlebars used as dependencies. It would be cool for the future versions be as small as it possible.

You can see like @sindresorhus makes [cli](https://github.com/sindresorhus/detect-indent-cli) for his projects separatly.

**Comment by sindresorhus** [comment]
:+1:

**Comment by kpdecker** [comment]
Thanks for the suggestion but not looking to increase the overhead of this project and people will complain if the CLI is removed. If using `node_modules` on a small file system then you're in for trouble regardless. Outside of that, I'm not really sure what the file size concern is.

**Comment by ben-eb** [comment]
:+1:
