### ISSUE TITLE
Why does Handlebars wait for first use to compile a template with Handlebars.compile?

### ISSUE THREAD

**Issue by afram** [wycats/handlebars.js#1095]
Just wondering why calling Handlebars.compile doesn't compile the template immediately.
It waits for the first invocation of template(context) to compile the template.

https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/compiler/compiler.js#L507

**Comment by kpdecker** [comment]
This is for performance reasons. This could delay startup if many templates
are declared on startup time. Generally they don't need to be compiled
until they are used.

**Comment by afram** [comment]
Thanks for your reply.

I was asking because - unless I've missed something - it seems that there isn't a method to precompile templates at runtime for server side rendering. 

compile waits for first use, and precompile returns a string for outputting to a file or to client side HTML into a script tag.

Would I be correct in saying that the only way is to use the parser/compiler api and precompile 'asObject'?

**Comment by kpdecker** [comment]
I'm not sure how this relates to execution on the server. What negative behavior are you seeing under the current implementation?

**Comment by afram** [comment]
My server side templates are dynamically updated at run time, and I didn't want to spend time on the initial request for a new template render to compile templates.

For now I will use the standard `compile` method and see what kind of a performance hit we get on initial render, otherwise I'll roll my own precompile function.

**Comment by kpdecker** [comment]
You're probably safer calling the method once with empty data after it is recreated vs. writing a custom compile method using non-public APIs.

**Comment by afram** [comment]
Yeah good idea. Will do that. Thanks.
