### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by rkgrep** [wycats/handlebars.js#1097]
Why isn't the package available via bower?

**Comment by jakkor** [comment]
Bower is for client side libraries without dependencies or with only small amount of them. For everything else npm is better.

**Comment by nknapp** [comment]
Actually, the instructions on http://handlebarsjs.com/installation.html say that you can install handlebars via `bower install --save handlebars` and I just tried it and it is working for me.

**Comment by kpdecker** [comment]
Yep as @nknapp notes the install instructions are on the website. Please feel free to ping if there are issues in there!
