### ISSUE TITLE
Icov.info kills vagrant machine

### ISSUE THREAD

**Issue by Trevald** [wycats/handlebars.js#1101]
Have a virtual machine setup via the Drupal VDD project. Short after adding svgstore to grunt the Drupal admin couldn't be reached. Just returned an empty response. Couldn't find any errors in any log-files so I started removing files to see what crashed it and when I removed svgstore it started to work again.

So I started removing files within the grunt-svgstore directory and find two files that where causing problem:

grunt-svgstore/node_modules/cheerio/coverage/Icov.info
grunt-svgstore/node_modules/handlebars/coverage/Icov.info
So these two files killed the Drupal admin by their sheer prescence. I wasn't even running Grunt on neither my host (OS X) or the virtual machine. Hell, the theme contaning grunt-svgstore wasn't even active.

Now the fun part: All I had to do to make the admin work again was to change the extensions to .txt and then back to .info again.

I'm very new at using vagrant as a development tool. But my guess is that the problem lies with the environment rather than Drupal, PHP or Apache. So I'm not sure this is the right place to post the issue, I will probably post it at VDD aswell. But svg-store was the only grunt-plugin causing problem, the others I have installed work fine.

**Comment by kpdecker** [comment]
I know nothing about Drupal or how this could be at all related but it sounds like some sort of bug in the drupal admin. I would raise this issue either with that team or the grunt-svgstore team.

As an aside, the grunt-svgstore team is using a very old version of handlebars that included in the coverage files in the output. Newer versions do not include this file in the npm package so you should probably ask them to upgrade.
