### ISSUE TITLE
Source map from rendered string to original handlebars template

### ISSUE THREAD

**Issue by jacqt** [wycats/handlebars.js#1103]
Feature: Have some way of mapping a rendered string back to its template

For example: 
 template:  "Hi! I'm {{ name }}" 
 compiled & rendered: "Hi I'm jacqt"
 some aux datastructure that says that "jacqt" was rendered from "{{ name }}"

How hard would it be to implement something like this?

**Comment by stevenvachon** [comment]
https://github.com/wycats/handlebars.js/pull/902?

**Comment by kpdecker** [comment]
#902 handles the compiler stages, I took this as runtime tracking, so you have location data with the rendered content. @jacqt can you help me understand the use case?

**Comment by jacqt** [comment]
Yeah, I'm interested in the runtime tracking - in particular, I don't actually care about what part of the template string maps to which part of the rendered content. Instead, I'm interested in knowing which substrings are generated by the handlebars expression, and which ones aren't. 

In my use case, I have an instance of text editor that users can write handlebars template in, and then they can render it in a preview. Right now, it's hard to see what substitutions were done to the template.

Ideally it would be possible to highlight the substitutions in the rendered string. 

This is more an exploratory question than anything else - so if you have any ideas how I might go about implementing something like this I'd love to hear!

**Comment by kpdecker** [comment]
You might be able to do something like this by overriding `JavascriptCompiler.appendToBuffer` and potentially `initializeBuffer`.

**Comment by kpdecker** [comment]
@jacqt going to close this out as I don't think we want to support this directly in the language due to potential execution overhead but feel free to email me if you want to run potential solutions along the override front past me.
