### ISSUE TITLE
dynamic partials

### ISSUE THREAD

**Issue by mmclau14** [wycats/handlebars.js#1105]
hi there, have not contributed to this group, so i'm not sure if this issue has been decided on already, but according to http://handlebarsjs.com/partials.html, handlebars should be able to support dynamic partials either using a lookup keyword, or by surrounding the key in parenthesis to be executed before the >partial. However, I have not been able to make this work, with my backbone models. Is there a version number that this feature is available after? or perhaps I'm just doing something wrong. neither one of these work :/

    {{> (keyOnObject)}}
    {{> (lookup . "keyOnObject")}}

**Comment by kpdecker** [comment]
Could you post a jsfiddle showing the failure? I'm really not sure who they are failing from your description.

**Comment by mmclau14** [comment]
so it looks like the version that i have (3.0.3) does not have dynamic partials, so i have to figure out if marionette is not automatically using the upgrade or what.
http://jsfiddle.net/mmclau/zvy3t1c9/

**Comment by kpdecker** [comment]
Dynamic partials have been supported since 3.0.0.
https://github.com/wycats/handlebars.js/commit/cb51b82b8e8114aaa3e1b19c41e5c4eebf0539d5

Not sure why it might be failing in your environment but can't really help out too much without having access to an environment that this reproduces under.
