### ISSUE TITLE
window.onerror ReferenceError: "log" is not defined.

### ISSUE THREAD

**Issue by ashish-kataria** [wycats/handlebars.js#1106]
I am using bugsnag and it keeps on giving "log" is not defined near line 2272 i.e. 

```javascript
HandlebarsEnvironment.prototype = {
	constructor: HandlebarsEnvironment,

	logger: logger,
	log: log,
```

**Comment by kpdecker** [comment]
Not much to work on here. Can you create a reproducible case in jsfiddle?

**Comment by kpdecker** [comment]
Close as there's not enough details for anything actionable here. Glad to reopen if we get some more details that we can work with.
