### ISSUE TITLE
Square Notation access in Handlebars

### ISSUE THREAD

**Issue by akshayjha28** [wycats/handlebars.js#1107]
Hi

I want to access a JSON using square notation. 

I have a variable with which I need to access JSON keys.

Is it possible to use the same. For eg.

var x = 'good';

access JSON - json.something[x]

**Comment by kpdecker** [comment]
The lookup helper allows for this: http://handlebarsjs.com/builtin_helpers.html#lookup

**Comment by akshayjha28** [comment]
Please can you check that lookup is used correctly or not.

{{#each sites}}
                                <div id="js-orderStage-{{stage}}" class="item js-modalStage">
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <div class="row para-title css-modal-content-color">{{lookup ../stageTypeLabels stage}}
                                                    <span class="para-text">{{locationName}}<i>{{#if locationName}}, {{/if}}</i>{{countryName}}</span>
                                                </div>
                                                <div class="row para-text css-modal-content-color">
                                                    {{{locationDescription}}}
                                                </div>
                                            </div>
                                            
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <ul class="rslides">
                                                    {{#each images}}
                                                        <li><img src="{{url}}" class="img-responsive"></li>
                                                    {{/each}}
