### ISSUE TITLE
Handlebars not working on IOS

### ISSUE THREAD

**Issue by bskimball** [wycats/handlebars.js#1108]
Pre-compiled templates using node. Everything works great on Windows desktop (all browsers except safari) also works on Droid phone. On iPad and iPhone none of the templates load. It looks like any time Handlebars is called, the browser stops rendering the rest of the javascript. I'm using 4.0.3 but I have tried 4.0.2 and 3.0.3

**Comment by kpdecker** [comment]
Can you provide an example reproduction case?

**Comment by bskimball** [comment]
If you really need I can give you access to the site. Basically as soon as I call Handlebars in my code (ex. Handlebars.templates.mytemplate(context)). All javascript after that stops working. It works on desktop. I ran a console log on Handlebars.templates and it does return the templates as the object in safari. I also tried compiling at run-time with the same results.

**Comment by bskimball** [comment]
compiled using the handlebars command line

task.handlbars:
<tr class="task task-{{ task.id }} {{#if_eq task.status 'Active'}} warning {{/if_eq}} {{#if_eq task.status 'Complete'}} success {{/if_eq}}">
	<td class="task-id">{{ task.id }}{{ page.archive }}</td>
	<td class="task-assembly">{{ task.assembly_number }}</td>
	<td class="task-employee">{{ task.employee.cardnumber }} - {{ task.employee.firstname }} {{ task.employee.lastname }}</td>
	<td class="task-area">{{ task.area.name }}</td>
	<td class="task-type">{{ task.type.name }}</td>
	<td class="task-start">{{ task.start }}</td>
	<td class="task-stop">{{ task.stop }}</td>
	{{#is_archive}}
	<td class="task-supervisor">{{ task.employee.supervisor.firstname }} {{ task.employee.supervisor.lastname }}</td>
	<td class="task-job">{{ task.job.number }}</td>
	<td class="task-status">{{ task.status }}</td>
	{{/is_archive}}
	<td class="task-buttons">
		<div class="btn-inline pull-right">
			<button class="btn btn-default btn-edit-task" data-task-id="{{ task.id }}">
				<i class="fa fa-fw fa-edit"></i>
			</button>
			{{#is_single}}
			<form class="stop-time" action="/api/tasks/{{ task.id }}" method="POST">
				<input type="hidden" name="id" value="{{ task.id }}">
				<input type="hidden" name="_method" value="PUT">
				<input class="task-stop" type="hidden" name="stop" value="">
				<button class="btn btn-danger" data-saving-text="<i class='fa fa-spinner fa-spin'></i>" {{#if_eq task.status 'Complete'}} disabled="disabled" {{/if_eq}}><i class="fa fa-fw fa-clock-o"></i></button>
			</form>
			{{/is_single}}
			{{#is_archive}}
				<button type="button" class="btn btn-danger btn-task-delete" data-task-id="{{ task.id }}">
					<i class="fa fa-fw fa-times"></i>
				</button>
			{{/is_archive}}				
		</div>
	</td>
</tr>

taskList.handlebars
{{#each tasks as |task| }}
	{{>task task=task}}
{{/each }}

app.js
var loadTaskList = function() {
	return getTasks(jobId)
			.done(function(data, textStatus, jqXHR) {
				$('#progress-bar').hide();
				var taskList = Handlebars.templates.taskList(data);
				taskHolder.html(taskList);
				$('#task-table').trigger('update');
			})
			.fail(function(jqXHR, textStatus, errorThrown) {
				$('.alert-top').append(errorThrown);
			})
};

tasks.html
<script type="text/javascript">
jQuery(document).ready(function($) {
	loadTaskList();
});
</script>

**Comment by kpdecker** [comment]
If you create a simplified repo case on jsfiddle was can try to help.
Otherwise there's not a lot that we can do to help you out.

**Comment by bskimball** [comment]
Thank you for your help. I fixed the issue. I removed all of my helpers then put them back in one at a time. The problem was with the ```{{#if_eq task.status 'Complete'}} success {{/if_eq}}``` helper. For some reason safari didn't like it but the other browsers don't mind it.
