### ISSUE TITLE
Got a problem when using @first

### ISSUE THREAD

**Issue by seajean** [wycats/handlebars.js#1109]
I have an  object array  like 
```
 {
code: 111,
list:  {
  a:1,
  b:2
}}
```
and my template 

```
{{#each list}}
{{#if @first}}
{{../code}}
{{/if}}
{{/each}}
```
the code output nothing 

but if I delete
```
 {{#if  @first}}
{{/if}}
```
 , it works fine.

**Comment by kpdecker** [comment]
What version of handlebars are you using? Can you create a fiddle demonstrating the failure?

**Comment by seajean** [comment]
I am using 3.0.0, fiddle demo is here :  http://jsfiddle.net/seajean/63dmruL6/

**Comment by kpdecker** [comment]
You need to either use an additional `../` or update to Handlebars 4.0.
http://jsfiddle.net/63dmruL6/7/

The discussion is sort of lengthy, but we changed how `../` works under 4.0 to better match what your expectations are here #1028. That's the primary [breaking change](https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v400---september-1st-2015) so you're likely safe to update.
