### ISSUE TITLE
How to use Helpers?

### ISSUE THREAD

**Issue by basickarl** [wycats/handlebars.js#1112]
It's very nice that the documentation explains the relation between the helpers and the actual templates. But it states nowhere how the helpers are initialized and in which files?

If I'm running node with koa for example.

```
var handlebars = require("koa-handlebars");
handlebars.registerHelper('sessionDate', function (date) { // get minutes between date and now
    var difference = (new Date()).getTime() - date.getTime(); // millisecond difference
    return Math.round(difference / 60000);
});
```
I get a `TypeError: undefined is not a function` at registerHelper(...

**Comment by kpdecker** [comment]
No idea what koa-handlebars is doing. I'd raise with that project.
