### ISSUE TITLE
Passing or utilizing multiple arguments into {{#each}}

### ISSUE THREAD

**Issue by basickarl** [wycats/handlebars.js#1113]
```
var arr = [1, 2, 3];
var obj = {"herro":"why hello"};
```
Is it possible to do the following:
```
{{#each arr}}
    {{obj.herro}}
{{/each}}
```
It does not wish to display the "why hello"!

**Comment by rogertheshrubber** [comment]
No. When you're in the for each,  "this" will be the current item in the array. Your array doesn't contain the "obj" data.

**Comment by basickarl** [comment]
My obj in my case is a language file containing all the words of a specific language. So I must inject this file x times over into each array element object? :S

**Comment by rogertheshrubber** [comment]
You can move up the object with "../"

Example: "../myVar"

**Comment by basickarl** [comment]
Perfect! Thank you, works now. Would be nice if this was in the documentation!

**Comment by rogertheshrubber** [comment]
By the way, I'm not sure what your data looks like, but if you have the key to the legend you want to show in your array, you could load your language data in a helper function, and have that helper function get the right text instead of moving up and down your data.

**Comment by kpdecker** [comment]
@basickarl the documentation on this is here: http://handlebarsjs.com/#paths
@rogertheshrubber thanks for the response
