### ISSUE TITLE
Maybe the APIs could be a little more friendly

### ISSUE THREAD

**Issue by seajean** [wycats/handlebars.js#1115]
I use handlebars a lot in my RIA coding,and finally in order to save my time,
I add  a few APIs  to my handlebars lib,
and these really help a lot,
I am wondering if these kind of usage would be supported by native handlebars lib.
thanks, here is the code.
```
//compatible with pre-compiled handlebars‘ template

Handlebars.xcompile = function (tpl) {
    if (tpl && typeof tpl !== 'function') {
        return Handlebars.compile(tpl);
    }
    else {
        return tpl;
    }
};

//get html with data 
Handlebars.xhtml = function (tpl, data) {
    var xtpl = Handlebars.xcompile(tpl);
    var html = xtpl(data || {});
    return html;
};
//  compatible with pre-compiled template
 
Handlebars.addPartial = function (tpl, id) {
    var tpl2 = Handlebars.xcompile(tpl);
    Handlebars.registerPartial(id, tpl2);
};
//============================
// we never  remove  Partial
//============================
// get html
Handlebars.getPartial = function (id, data) {
    var tpl = Handlebars.partials[id];
    if (typeof (tpl) == 'function') {
        return tpl(data || {});
    }
    else {
        return tpl;
    }
};
```

**Comment by kpdecker** [comment]
I'm not clear what the goal is here. You want to use a string or a compiled template without making a different call?

**Comment by seajean** [comment]
yes,it's exactly what I want.and I think these kind of change could help others if they use raw template in developing and use compiled template in release.

**Comment by kpdecker** [comment]
This is a very confusing API and also outright doesn't work with the runtime library. I don't think we should include them in the library proper. If you are using string templates in development (which I wouldn't recommend if using precompiled in production), I would recommend that you have these helpers setup in your own code.
