### ISSUE TITLE
Precompile handlebars partials only

### ISSUE THREAD

**Issue by kirkstrobeck** [wycats/handlebars.js#1116]
http://stackoverflow.com/questions/33110865/precompile-handlebars-partials-only

**Comment by kpdecker** [comment]
No idea what you are asking here.

**Comment by kirkstrobeck** [comment]
Please clarify. Which do you mean?

1. You clicked the link, read the question, and it’s confusing
2. A GitHub issue shouldn’t be a link off to another site

**Comment by agladysh** [comment]
I didn't understand the question text either, it doesn't parse.

**Comment by kirkstrobeck** [comment]
@agladysh I want to know if there is a way to combine handlebars partials together as a compile step. In other words, only process `{{>header}}`, don’t process `{{name}}`

**Comment by kirkstrobeck** [comment]
**Solved**

```js
var Handlebars = require('handlebars');
Handlebars.registerPartial('header', 'im the header, hi \\{{name}}');
Handlebars.registerPartial('footer', 'im the footer, hi \\{{name}}');
console.log(Handlebars.compile('{{>header}}im the body, hi \\{{name}}{{>footer}}')({}));
// outputs: im the header, hi {{name}}im the body, hi {{name}}im the footer, hi {{name}}
```

http://stackoverflow.com/questions/33110865/precompile-handlebars-partials-only/33136820#33136820
