### ISSUE TITLE
Accessing parent context from custom helper?

### ISSUE THREAD

**Issue by grofit** [wycats/handlebars.js#1117]
I am new to handlebars and could not find any information on this, but lets say I wanted to make a helper method like:

```
handlebars.registerHelper("doSomething", function() {
     if(parentContext.something) {
        return this + parentContext.something;
     }
     else {
      return this;
    }
});
```

And assume a context passed in of something like:

```
{
    something: "woop",
    children: [ "amaze", "blah" ]    
}
```

and the template usage would be something like:

```
{{#each children}}
    {{doSomething}}
{{/each}}
```

This is a completely made up scenario but basically I have some child elements and the template markup is getting a bit convoluted looking out for parent context settings which would effect the child outputs. So I wanted to try and move it into a helper so I could at least try to minimize some of the output and logic in the template, as the template is re-used with multiple input contexts which will often have different parent vars.

Anyway hopefully the problem is clear, currently `doSomething` would only have access to the current context, and I was hoping there would be a way to access the parent scopes in the helper method without having to resort to using paths or anything else in the template.

**Comment by kpdecker** [comment]
Unfortunately we do our best to not track this for performance reasons and don't pass anything to the helpers. Your best option is `{{doSomething ..}}` which isn't ideal but will get the job done and not require language changes that are potentially brittle or with performance concerns.
