### ISSUE TITLE
partial with properties on multiple lines?

### ISSUE THREAD

**Issue by essmahr** [wycats/handlebars.js#1123]
When dealing with partials with a lot of properties I've been breaking each property onto its own line, like so:

``` hbs
{{> path/to/partial
   property_one="value one"
   property_two="value two"
   property_three="value three"
}}
```

This works, but sporadically: I'm sometimes getting an `Uncaught error: The partial path/to/partial could not be found`. I can't consistently reproduce the error in a way that matches a pattern of what might be the cause.

are newlines like this officially supported? Should I be looking elsewhere for the cause of this? :grimacing:

**Comment by kpdecker** [comment]
Newlines are supported within any `{{}}` construct. That error means that the partial you are trying to call has not been loaded. I would check to see if you have either a race condition loading that dependency or an error is occurring while loading that.

**Comment by kpdecker** [comment]
If you can confirm that is not the issue, please ping back here linking to something that we can help debug.
