### ISSUE TITLE
Load partial context dynamically

### ISSUE THREAD

**Issue by cauburtin** [wycats/handlebars.js#1124]
i was trying to turn that fiddle http://jsfiddle.net/crl/5yt6M/104/ in this one http://jsfiddle.net/crl/5yt6M/106/ where the tree is flattened, and next nodes are accessed by a global helper, problem: I don't think the current syntax supports this

**Comment by Pisi-Deff** [comment]
The problem is that you've tried to use the global helper as an array.
Slight changes to the helper and to how you call the helper, and we get a working solution:
http://jsfiddle.net/5yt6M/107/

**Comment by cauburtin** [comment]
yes good point, thanks, nice, (I'll post on SO with the right tag next time)

where can I read on what are the possible expression inside `()`?
