### ISSUE TITLE
Improper AST parsing

### ISSUE THREAD

**Issue by aigokul15** [wycats/handlebars.js#1126]
Dear Team,

We are currently developing a static tool for handlebars. we are extracting necessary contents using HANDLEBARS AST. The AST generated(using Handlebars.parse method) is not up to the mark.
The Handlebars Template with {{if}}{{else}}{{/if}} is not parsed correctly. 

We are using Handlebars 2.0.0 version.

Example:
```
  <div class="entry">
  {{#if author}}
    <h1>{{firstName}} {{lastName}}</h1>
  {{else}}
    <h1>{{Unknown Author}}</h1>
  {{/if}}
</div>
```

Here, no object is rendered for {{else}} block. It is getting skipped. Is there any other way to parse it correctly. Please update Us as soon as possible. Very Urgent.

Regards
Gokul

**Comment by kpdecker** [comment]
Please provide an example of the AST and explain how that differs from your expectations.
