### ISSUE TITLE
What is no-conflict.js and what's going on with it?

### ISSUE THREAD

**Issue by ianbytchek** [wycats/handlebars.js#1134]
Have been having the strangest issue for ages, now it's getting out of control and turns out to be related to handlebars. When my js fails from time to time, chrome often reports an error with the following stack trace. Now I need to debug something online, so I've put `debugger` statement, to find out chrome stopping at the exact same place.

```
Uncaught Error
OopUtility.mixin.onMount @ no-conflict.js:12
OopUtility.mixin.mount @ no-conflict.js:12
Mountable @ no-conflict.js:12
Network @ no-conflict.js:12
jQuery.fn.(anonymous function) @ no-conflict.js:12
JQueryUtility.bindPlugin @ no-conflict.js:12
(anonymous function) @ no-conflict.js:12
__webpack_require__ @ no-conflict.js:12
(anonymous function) @ no-conflict.js:12
(anonymous function) @ no-conflict.js:12
__webpack_require__ @ no-conflict.js:12
(anonymous function) @ no-conflict.js:12
(anonymous function) @ no-conflict.js:12
```

`no-conflic.js` is a tiny script, that looks like this:

```js
/* global window */
export default function(Handlebars) {
  /* istanbul ignore next */
  let root = typeof global !== 'undefined' ? global : window,
      $Handlebars = root.Handlebars;
  /* istanbul ignore next */
  Handlebars.noConflict = function() {
    if (root.Handlebars === Handlebars) {
      root.Handlebars = $Handlebars;
    }
  };
}
```

I package everything with webpack into `main.js` and it's the only script that I have executing. Where chrome gets this file? It's not even loaded into the browser nor available on the server. I know this might be anything, but since this is part of handlebars I thought to ask here first.

Did anybody see anything like this before? What might this be?

**Comment by kpdecker** [comment]
Since the function (I.e. `OopUtility.mixin.onMount`, etc) is changing but the line and the file stay the same for all of them and don't match to anything in the no-conflict file, I suspect that somehow your sourcemaps are corrupted or you found a bug in Chrome.

Closing this as it's most likely not related to handlebars. I think that you webpack issue you also filed is better targeted to help resolve this.

**Comment by ianbytchek** [comment]
@kpdecker, thanks, great point regarding sourcemaps. Will follow that up.

**Comment by duncanfinney** [comment]
Same thing happening for me with Webpack / Handlebars-loader. Gonna be a pain to fix.

**Comment by ianbytchek** [comment]
@duncanfinney That was totally sourcemap-related. It was included with one of the minified libraries I was bundling, which was spoiling everything for months. Just make sure to strip them when creating the final bundle.

**Comment by duncanfinney** [comment]
@ianbytchek: Wish I had seen your post earlier! I managed to figure it out after a lot of fiddling. One of the builds doesn't have inline sourcemaps. I just changed my webpack config to this:

From my webpack config: 
```
      {
        test: /\.hbs$/,
        loader: nodeModDir + 'handlebars-loader/index.js',
        query: {
          runtime: nodeModDir + 'handlebars/dist/handlebars.runtime.js',
        }
      },
```
