### ISSUE TITLE
How do we port ember compat handlebars?

### ISSUE THREAD

**Issue by SamSaffron** [wycats/handlebars.js#1136]
Not really a bug but I am not sure how to get advice on this... 

At Discourse we use Handlebars version 2.0 with this file https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/lib/ember_compat_handlebars.js to compile handlebars templates. 

Our extension of the 2.0 compiler allows handlebars to "understand" computed properties by wrapping all mustaches in ``Em.get`. That way `{{test.computed}}` ends up becoming `Em.get(this, 'test.computed')` in the compiled template. 

This all works fine in 2.0 but with 4.0 I am noticing it no longer works: 

```

  RawHandlebars.Compiler.prototype.mustache = function(mustache) {
    if ( !(mustache.params.length || mustache.hash)) {

      var id = new Handlebars.AST.IdNode([{ part: 'get' }]);
      mustache = new Handlebars.AST.MustacheNode([id].concat([mustache.id]), mustache.hash, mustache.escaped);
    }

    return Handlebars.Compiler.prototype.mustache.call(this, mustache);
  };
```

Never gets called ... 

How do I go about overriding the behavior of mustaches in 4.0?

**Comment by kpdecker** [comment]
3.0 changed the names of these functions to match the formally defined API made in that version.
https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v300---february-10th-2015

**Comment by kpdecker** [comment]
https://github.com/wycats/handlebars.js/compare/v2.0.0...v3.0.0#diff-658a031b39cc411e6b745ec37b411607L192
