### ISSUE TITLE
Need CLI Documentation

### ISSUE THREAD

**Issue by michaelalhilly** [wycats/handlebars.js#1137]
I'm using Handlebars with Node and I'd like to run it as a package script. I can't find any documentation on the CLI commands and options. Are they already available somewhere?

**Comment by kpdecker** [comment]
`handlebars --help` and http://handlebarsjs.com/precompilation.html#usage

**Comment by michaelalhilly** [comment]
Thank you! Sorry I wasn't more thorough.
