### ISSUE TITLE
Question about partial context (v3.0.0 ~ v4.0.5)

### ISSUE THREAD

**Issue by zordius** [wycats/handlebars.js#1139]
**Question 1**: Can we use partial block inside a partial block?

**Question 2**: When the outer partial block pushed 1 context stack (need to use ../ to refer to original context) , why the inner partial block did not change the context stack? Please refer to this jsfiddle: http://jsfiddle.net/z3fwhmwL/

Template:
```
~{{#> dude}}={{../foo}}={{#> ya}}@{{../foo}},{{../../foo}}{{/ya}}={{/dude}}~
```

Data:
```
{foo: 'bar'}
```

Output:
```
~=bar=@bar,=~
```

My Expectation:
```
~=bar=@,bar=~
```

**Question 3:** When a partial provided for the outer partial block, the context is gone. Why? Please refer to this jsfiddle: http://jsfiddle.net/z3fwhmwL/1/

Provided partial:
```javascript
Handlebars.registerPartial('dude', '!{{foo}}${{../foo}}%{{../../foo}}');
```

Output:
```
~!$%~
```

**Question 4:** When a partial provided for the inner partial block, the context is gone. Why? Please refer to this jsfiddle: http://jsfiddle.net/z3fwhmwL/2/

Provided partial:
```javascript
Handlebars.registerPartial('ya', '!{{foo}}${{../foo}}%{{../../foo}}');
```

Output:
```
~=bar=!$%=~
```

**Comment by kpdecker** [comment]
1. Yes
2. Partials follow the same rules as helper calls, which changed in version 4 to avoid creating new depth values if the context has not changed. Discussion of this in #1028.
3. Global partials do not allow for depthed references, you'll need to pass in as a custom context.
4. Same as above.

So basically this is all working as expected.

**Comment by zordius** [comment]
Thank you for your answers.

But for 2. , if partials should prevent context change, then the outer partial block should not change the context, right? (the inner partial block should follow the same rule with outer partial block, now their behaviors are different)

**Comment by kpdecker** [comment]
Partials CAN change the context, but if they don't, then a new depth is not created. This matches the behavior you see with `if` under 4.

**Comment by zordius** [comment]
After some tests I found more issues.

Refer to this jsfiddle: http://jsfiddle.net/ymd1dg7o/

A. compare 1. with 3. , their behaviors are different.
B. check 4. and 5. , partials behavior changed? no any context be passed into partial.

Something strange in v3.0.0 ~ v4.0.5 (maybe it is a designed change?) ; here is another test with v2.0.0, http://jsfiddle.net/20sz0jbf/ . We can pass original context into partial by `{{>foo}}` or `{{>foo .}}` . But, now we only get empty context either by `{{>foo}}` or by `{{>foo .}}`

The issue title will be changed from `Questions about partial block inside partial block (v4.0.5)` to `Question about partial context (v3.0.0 ~ v4.0.5)`

**Comment by kpdecker** [comment]
It looks like these issues spawn from the use of stringParams, which we did not account for when we were making the changes to depth handling. If you remove the stringParams option or run against the latest in master the results are all as expected
http://jsfiddle.net/qrdurwpn/

Closing this since stringParams will be desupported in 5, see #1145

**Comment by zordius** [comment]
Thank you for the clarify!
