### ISSUE TITLE
how use Handlebars.js on server and client  at the same time

### ISSUE THREAD

**Issue by jonahzheng** [wycats/handlebars.js#1140]
I have an app in Node.js using Hapi and Handlebars as the template engine.
the client also use Handlebars，but it doesn't work on client。
my program like it， http://stackoverflow.com/questions/10037936/node-js-with-handlebars-js-on-server-and-client
I want only use Handlebars。

thank you

**Comment by kpdecker** [comment]
Not sure what you might be seeing, but we can't really help out without pointing us to an example of this failing. CONTRIBUTING.md has a link to a jsfiddle that might help and I recommend standard debugging practices of trying to create a reduced test case. Often times this helps you find the issue without needing to ask the community for help.

Closing this issue but if you post some form of live reduced test case, preferably a fiddle, then we can try to help you out.

**Comment by jonahzheng** [comment]
thank you
1、my html souce like this
=========================================
                    <h3 class="page-title"> {{title}} </h3> 
                    <div class="row" id="sysinfo"></div>
                    <script id="sysinfo-template" type="text/x-handlebars">
                    <div class="row" id="sysinfo">{{client_val}}</div>
                    </script>
<script type="text/javascript">
                    var myTemplate = Handlebars.compile($("#sysinfo-template").html());        
                    var data_info = {"client_val":"Abc"};
                     $('#sysinfo').html(myTemplate(data_info));
</script>
==========================================
result:  title is 'Mypage', but client_val isn't 'ABC', it's null character;
