### ISSUE TITLE
Decorator documentation/implementation out of sync

### ISSUE THREAD

**Issue by ryanmurakami** [wycats/handlebars.js#1141]
The [Decorator API documentation](https://github.com/wycats/handlebars.js/blob/master/docs/decorators-api.md) lists "program, props, container, context, data, blockParams, depths" as arguments for a Decorator handler, but it looks like the actual handler is called with "fn, props, container, options", as seen in the inline partial implementation. 

In testing those additional arguments in 4.0.5, they are all currently undefined. 

Would be great to have them, or at the least update the documentation or mark it as upcoming/design.

I can make a PR for the documentation update if needed.

**Comment by ryanmurakami** [comment]
Scratch that, I see in runtime.js where executeDecorator is being called with the correct arguments.

I do see something odd with the container argument, however. What should I expect from this argument? The documentation states the current runtime container, so I would expect the decorator/helpers hashes to contain the current decorator, but it is empty. For reference, here's what I'm looking at:
```javascript
Handlebars.registerDecorator('debug', function(fn, props, container, options) {
	console.log('Debug: ' + JSON.stringify(container));
});
var templ = `<div>
{{* debug}}
	{{#if pet.isDog}}
		<h1>Dog: {{pet.name}}</h1>
		<p>{{pet.desc}}</p>
	{{/if}}
`;
var template = Handlebars.compile(templ);
template({pet: { name: 'Garfunkel', desc: 'Best dog', isDog: true}});
```
And here's the output:
```
Debug: {"programs":[],"compilerInfo":[7,">= 4.0.0"],"helpers":{},"decorators":{}}
```

**Comment by kpdecker** [comment]
Json.stringify omits functions from its output so they won't be displayed
with your code as is.

**Comment by ryanmurakami** [comment]
That's it. Thanks for the response!
