### ISSUE TITLE
how do you use programatically precompiled templates with helpers in them?

### ISSUE THREAD

**Issue by davis** [wycats/handlebars.js#1143]
i'm precompiling using the handlebars/handlebars.runtime's Handlebars.precompile()
and helpers aren't being called

**Comment by kpdecker** [comment]
Closing this out as there is nothing actionable here. Glad to reopen if you post a fiddle (see CONTRIBUTING.md for link to template) or other reduced test case that demonstrates the issue that you're having.

**Comment by davis** [comment]
ah yeah, i figured it out. thanks!

**Comment by kpdecker** [comment]
Generally it's best to include specific details when making open source issue request and updating if you found the solution. This prevents the maintainers from wasting their time.

**Comment by davis** [comment]
Gotcha, thanks for the tips
