### ISSUE TITLE
Error “Cannot read property 'partial-block' of undefined”

### ISSUE THREAD

**Issue by kapooostin** [wycats/handlebars.js#1144]
I modified Assemble.js to depend on Handlebars 4.0.5 so I could use partials blocks. And I get this error when I try to build my project.

Maybe it is a wrong place to ask because it is assemble task that failed, but I hope you could give me a direction for my attempts to fix it. What could cause it?

**Comment by kapooostin** [comment]
If I use ```{{{ @partial-block }}}``` instead of ```{{> @partial-block }}```in a partial, it works.

**Comment by kpdecker** [comment]
Can you provide more details on what is failing?

**Comment by kapooostin** [comment]
I use [grunt-assemble](https://github.com/assemble/grunt-assemble) with modified [assemble-handlebars](https://github.com/assemble/assemble-handlebars) plugin (with Handlebars 4.0.5).

```handlebars
(main.hbs)
{{#> module-row }}
    <p>Some text</p>
{{/ module-row }}

(module-row.hbs)
<div class="row>
    {{> @partial-block }}
</div>
```

And I get the error **Cannot read property 'partial-block' of undefined**.

**Comment by kpdecker** [comment]
It sounds like you're not registering a partial, but the partial's rendered output is being assigned to a local variable. I'd raise this with the assemble community to get their feedback. If that doesn't resolve the issue, then please post a jsfiddle with a reduced test case and I'd be glad to try to help out.
