### ISSUE TITLE
Time to kill stringParams mode?

### ISSUE THREAD

**Issue by machty** [wycats/handlebars.js#1145]
`stringParams` mode was originally implemented to support the legacy pre-Glimmer/HTMLbars view layer in Ember.js, but since moving to Glimmer, there's no longer any need to support `stringParams` mode, so we should probably remove it from Handlebars proper...

...unless somewhere out there another prominent library that extends Handlebars also makes use of `stringParams`? Does anything come to mind? Any good reason to keep it around? It certainly is a pain to maintain.

**Comment by kpdecker** [comment]
It's not a feature that I've every pushed people to use and I suspect that Ember is the only consumer of `stringParams` and Thorax SSJS the only consumer of `trackIds`. Using download numbers from https://www.npmjs.com/package/fruit-loops as a proxy, I'm guessing that very few people if anyone are still using this.
