### ISSUE TITLE
Short 'or' in expression

### ISSUE THREAD

**Issue by ValeryIvanov** [wycats/handlebars.js#1146]
Is there a way to write something like that `<h1>{{title || body}}</h1>` with context 
`
{ 
  title: "", 
  body: "This is my first post!"
}
` and it would output `body` value since in javascript `!!title === false`

I know about `{{#if title}}{{title}}{{else}}{{body}}{{/if}}` but is there a shorter way or should be a shorter way some time added? Going further would be even more awesome like `{{value1 || value2 || value3}}` etc.

**Comment by kpdecker** [comment]
Not in the language itself, but you can easily achieve this with a helper:
```
{{coalesce title body}}
```
```
Handlebars.registerHelper('coalesce', function(a, b) { return a || b; });
```

**Comment by ValeryIvanov** [comment]
So this takes only to arguments? What about if I want indefinite arguments. like so `{{value1 || value2 || value3}}`

**Comment by Pisi-Deff** [comment]
Untested:
```
Handlebars.registerHelper('coalesce', function() {
  for (var i = 0; i < arguments.length - 1; i++) { // - 1 because last should be handlebars options var
    if (arguments[i]) {
      return arguments[i];
    }
  }
  return null;
});
```

**Comment by alexanderbird** [comment]
You could also use `Array.find()`

`Handlebars.registerHelper('coalesce', (...args) => args.find(i => !!i));`

`{{coalesce a b c d e f g}}`
