### ISSUE TITLE
Handlebars auto-escaping hash parameters?

### ISSUE THREAD

**Issue by dmcknight26** [wycats/handlebars.js#1147]
It seems like Handlebars is auto-escaping hash parameters passed into helpers.  Is there to disable this behavior?

I would prefer to handle all escaping inside of my helper directly, as not all of my hash parameters need to be escaped.

Example:

{{myHelper title="Hugh & Carmella"}}

In my helper if I try and access the title attribute in options.hash it's already been converted to `Hugh &amp; Carmella`.  Is there a way around this?

**Comment by kpdecker** [comment]
Handlebars does not do this. I'm guessing that you're defining the template in the HTML and the browser's parser is introducing this behavior but am not certain. My general recommendation is that you use precompiled templates, but if you are defining them in html, please make sure that they are defined in `<script>` tag as this has the least amount of parsing done by the browser.

Closing this out but if you can create a fiddle demonstrating that it's not a browser parsing issue, see CONTRIBUTING.md, then I'll be glad to reopen.

**Comment by dmcknight26** [comment]
Yes, that was exactly my problem (templates directly in HTML).  I've moved them to script tags for now (they will eventually be separate files completely).

Thanks!
