### ISSUE TITLE
Images w/ src="{{image_url}}" requests root url.

### ISSUE THREAD

**Issue by plukevdh** [wycats/handlebars.js#115]
I have a template that includes an image tag that looks like so:

`<img src="{{avatar_url}}" alt="user-avatar" />`

When handlebars compiles this, it causes the browser to request the root url (assumedly due to the following issue: http://stackoverflow.com/questions/1386312/resource-interpreted-as-other-but-transferred-with-mime-type-text-javascript)

For this particular request, we allow the server to request html or json. The html request fires off a lot of actions we don't want to fire after it is requested the first time, but this re-request of the root url causes that action to be called again, causing Chrome to throw a warning: `Resource interpreted as text/htm but transferred with MIME type text/javascript`

This seems to happen mainly when using Chrome. Fx6 has not displayed the same behavior. Have not tested elsewhere. Let me know if it is thought to be a browser issue and I'll retract.

**Comment by JuanjoRamirez262** [comment]
How do you fix it? I'm having this problem 10 years later.
