### ISSUE TITLE
Creating a helper with path string parameter 

### ISSUE THREAD

**Issue by MuyBien** [wycats/handlebars.js#1154]
Hi!
I want to create a helper to make translations. In my application, messages key are dotted. For example generic.message.success. So I made the translation helper 
```
 {{translation generic.message.success}}
```
But generic.message.success is not in the passed JSON. It's a general string. How can I tell the helper to not try to get this string as a JSON member?

```
Handlebars.registerHelper('translation', function(key) {
	var translation = translate(key);
	return new Handlebars.SafeString( translation );
});
```

Thanks!

**Comment by kpdecker** [comment]
You'll have to pass this in as a string `{{translation 'generic.message.success`}}`

**Comment by MuyBien** [comment]
OK simple...
Thanks!
