### ISSUE TITLE
Passing a variable to a partial then use it in a #each

### ISSUE THREAD

**Issue by mudlee** [wycats/handlebars.js#1155]
Hi!

I have data available in templates with this structure for eg.:
```
{{data.strings}} <- it's an array containing strings
```

If I pass a variable to a partial like
```
{{> xy iterate=strings}}
```

And I want to use that in the partial "xy" this to iterate, can I somehow? 
I would use in a way like this:
```
{{#each data[iterate]}}
...
{{/each}}
```

**Comment by kpdecker** [comment]
This can be achieved with the lookup helper and subexpressions.
http://handlebarsjs.com/builtin_helpers.html#lookup

```
{{#each (lookup data iterate)}}
```

**Comment by mudlee** [comment]
Thank you, it does the job!
