### ISSUE TITLE
Handlebars crash when use helpers inside tag

### ISSUE THREAD

**Issue by vgorobec** [wycats/handlebars.js#1157]
I don't understand the reason of issue when I write something like
<pre>
&lt;a href="{{model.TargetUrl}}" {{#if model.IsTargetBlank}} target="_blank" {{/if}}&gt;click here&lt;/a&gt;
</pre>
I get an issue, and error in console is:
<pre>
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'EQUALS'
throw new Error(str); 
</pre>

Seems the issue occures when I try to use helpers inside <> of tag.

When I remove "if" from the tag it works fine.

Can you check this?

**Comment by kpdecker** [comment]
Looks valid from the snippet that you've posted. Please post an example of the failure on jsfiddle or other service and we can take a look. CONTIBUTING.md has a link to a template that will help you create an example.

**Comment by vgorobec** [comment]
I've created example here https://jsfiddle.net/9m6zk3wq/3/

**Comment by kpdecker** [comment]
This is a HTML parser issue. You need to place the template in a `<script type="text/handlebars">` tag if you are going to put them in the html but the recommended solution it to precompile them to javascript.

There is a code example at the top showing the `script` tag: http://handlebarsjs.com/
