### ISSUE TITLE
if statement doesn't work correct

### ISSUE THREAD

**Issue by i8b00ff** [wycats/handlebars.js#1158]
You can use the if helper to conditionally render a block. If its argument returns false, undefined, null, "", 0, or [], Handlebars will not render the block.

JSON 
{"A":[{"a":"1","f":"0"}]}
HB
{{#if a}}{{a}}{{/if} // output: 1
{{#if f}}{{f}}{{/if}  // output: 0 WHY?

**Comment by nknapp** [comment]
`"0"` is not a falsy value, contrary to `0`. 
Try the following in your javascript-console: `if ("0") { console.log("0") }`. It will output 0 as well and so does Handlebars.

I expect that `{"A":[{"a":1,"f":0}]}` will give you the expected result (but I haven't tried)

**Comment by kpdecker** [comment]
thanks @nknapp
