### ISSUE TITLE
JAWR bundling / minifying results in error: SyntaxError: invalid increment operand

### ISSUE THREAD

**Issue by nickgr6** [wycats/handlebars.js#1162]
JAWR changes the line (line: 3542) `varDeclarations += ', alias' + ++aliasCount + '=' + alias;`
into: `alias'+++aliasCount+'= etc.` which results in the following error: 
`SyntaxError: invalid increment operand
...larations+=', alias'+++aliasCount+'='+alias;node.children[0]='alias'+aliasCount
`

Now I know, this is mainly a JAWR issue, except it can be easily fixed in handlebars by changing the code to: `varDeclarations += ', alias' + (++aliasCount) + '=' + alias;` 

This change also makes the code, imo, more readable.
Can this be fixed in the handlebars library?

**Comment by kpdecker** [comment]
This is written this way in the code but transpiler or something else in the process strips this.
https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/compiler/javascript-compiler.js#L214

Not something that we can fix directly in our project. I'd advise raising the issue with JAWR or switching to Uglify.
