### ISSUE TITLE
how to execute javascript inside template without helpers ?

### ISSUE THREAD

**Issue by alsemany** [wycats/handlebars.js#1164]
Hello,
is there a way to execute javascript inside the template ?
I'm used EJS before and I'm new to HBS , in EJS I can easily use 

<% var foo = 'bar'; %>
then inserting it easily 
<%= foo %>

is there any feature to do this with Handlebars something like that
{{code}}
var foo = 'bar';
{{/code}}
then 
{{foo}}

**Comment by kpdecker** [comment]
The language was explicitly designed to avoid this. If you need anything with side effects then you'll need to design your own system with helpers.
