### ISSUE TITLE
customizing syntax

### ISSUE THREAD

**Issue by lorvent** [wycats/handlebars.js#1167]
Hello,

is it possible to customize handlebars syntax

for exm: ````{{var}}```` with ````{{$var}}````

OR

````
{{#if userActive}}​
Welcome, {{firstName}}
{{/if}}
````
with
````
@if(userActive)
Welcome, {{$firstName}}
@endif
```

Any advice is appreciated
Thanks.

**Comment by kpdecker** [comment]
The syntax is defined [here](https://github.com/wycats/handlebars.js/blob/master/src/handlebars.l), so you could produce a fork of your own if you desire, but the syntax of the canonical project is pretty set at this point.
