### ISSUE TITLE
@partial-block unclear or render bug

### ISSUE THREAD

**Issue by morgondag** [wycats/handlebars.js#1168]
``Template.hbs``

```hbs
<div>
	{{> @partial-block }}
</div>

```
``Then Compile:``

```js
Handlebars.compile(fs.readFileSync("./template.hbs", "utf8"))({});
```

``Èrror``

```js
/handlebars/runtime.js:266
    throw new _exception2['default']('The partial ' + options.name + ' could not be found');
    ^
Error: The partial @partial-block could not be found
    at Object.invokePartial (/handlebars/runtime.js:266:11)
    at Object.invokePartialWrapper [as invokePartial] (/handlebars/runtime.js:68:39)
    at Object.eval (eval at createFunctionContext (/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:6:28)
```

#1144

**Comment by kpdecker** [comment]
You aren't going to have a partial-block if you are rendering the template directly. Partial blocks are only available when a template is rendered as a partial, i.e. `{{#> template}}this block{{/template}}`

**Comment by morgondag** [comment]
@kpdecker so there is no way to use the handelbars api to compile a template with a partial-block???

**Comment by loominade** [comment]
Shouldn't ``@partial-block``s behave like variables? If they aren't defined, they aren't printed. 

[jade](http://jade-lang.com/reference/mixins/#blocks) handles it the same way.

**Comment by frederfred** [comment]
@morgondag I had a similar issue and solved it by using an if statement:

```handlebars
{{#if @partial-block}}
  {{> @partial-block }}
{{/if}}
```

Hope you solved it already though :)
