### ISSUE TITLE
Behavior of {{#if x} when x is a function?

### ISSUE THREAD

**Issue by ChrisRus** [wycats/handlebars.js#1169]
I have a template that I'm using to generate GitHub-flavor markdown documentation. In my template (failing fragment excerpted below), I execute a conditional to test if `filterDescriptor.bodyFunction` is defined or not.

```
| 2. Operation | Developer-defined custom data transformation function. | {{#if filterDescriptor.bodyFunction}}**enabled**{{else}}disabled{{/if}} |
```

In my scenario, context.filterDescriptor.bodyFunction is either of type [object Undefined] or [object Function].

What is odd and totally unexpected is that {{#if}} appears to actually **call** the function. And, this is super problematic because (a) nobody can just call this function - it's part of a visitor pattern and there's no way on earth that Handlebars can correctly dispatch it with expected parameters and closure contexts (b) the function may have side effects.

This is easy enough to work around but actually figuring out that the source of the odd errors was not in my document generator, and not in Handlebars required exhaustive greps of Handlebars and my code under test to not find any of the variable names reported in thrown exception).

Do all context variables that happen to be of type [object Function] get called? Where is that documented? Is this specific to {{#if}}? Why on earth call the function? Makes no sense in the general case. Perhaps, the intent is that context variables that happen to be functions are to be called to obtain the value to use? If so, I've seen no discussion of this nuance in the docs.

Any clarification would be appreciated.

**Comment by jbboehr** [comment]
You can provide your own `if` implementation via `Handlebars.registerHelper('if', function() {})`. I believe
> The optional Mustache-style lambdas are not supported. Instead Handlebars provides its own lambda resolution that follows the behaviors of helpers.

in the readme refers to this feature.

It applies at least to these helpers:
https://github.com/wycats/handlebars.js/blob/v4.0.5/lib/handlebars/helpers/if.js#L5
https://github.com/wycats/handlebars.js/blob/v4.0.5/lib/handlebars/helpers/each.js#L21
https://github.com/wycats/handlebars.js/blob/v4.0.5/lib/handlebars/helpers/with.js#L5

**Comment by ChrisRus** [comment]
tx @jbboehr - this works acceptably well for me & am closing the issue. appreciate the help.
