### ISSUE TITLE
About include template

### ISSUE THREAD

**Issue by EasonWang01** [wycats/handlebars.js#1170]
How to do this like ejs template do? <% include ../partials/header  %>   
thanks

**Comment by Pisi-Deff** [comment]
It's described in detail in the documentation: http://handlebarsjs.com/partials.html

**Comment by EasonWang01** [comment]
Can I using Partials from other files?

**Comment by Pisi-Deff** [comment]
I assume you're precompiling all your template files.
If so, you can, for simplicity's sake, register all your templates as partials. And then use what you need with the partial syntax.
```
for (var t in Handlebars.templates) {
  Handlebars.registerPartial(t, Handlebars.templates[t]);
}
```
or maybe even this might work to have all your templates be partials, I'm not entirely sure:
```
Handlebars.partials = Handlebars.templates;
```

If you are not precompiling your templates, you'll have to read the partial template files at page load and register them as partials via Handlebars.registerPartial before rendering your templates.

**Comment by EasonWang01** [comment]
I find a great article here  http://www.adamwadeharris.com/how-to-precompile-handlebars-templates/
