### ISSUE TITLE
Each helper not accepting any other template variables except 'this'

### ISSUE THREAD

**Issue by cyang** [wycats/handlebars.js#1172]
Here's an example:

```
<div class="comments">
  {{#each comments}}
    <div class="comment">
      <h2>{{user}}</h2>
      <p>{{this}}</p>
      {{email}}
    </div>
  {{/each}}
</div>
```

I am able to access {{this}}, but any other variables (ie. {{user}}, {{email}}) will return an empty string.

**Comment by nknapp** [comment]
A jsfiddle would have helped you posting complete information (like the input object). @kpdecker  always nodes that there is a jsfiddle-template linked in the [contributing-guide](https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md). But I think I can guess the information that you are not posting. 

Your template will work it the input is:

```json
{
    "comments": [
        {
            "user": "Nils",
            "email": "npm@knappi.org"
        }
    ]
}
```

But it is probably different. I believe your input is:

```json
{
    "user": "Nils",
    "email": "npm@knappi.org",
    "comments": [
        "comment1","comment2"
    ]
}
```
Then you are trying to access variables from a parent scope inside the `{{if}}`-statement. You have to use `{{../user}}` and `{{../email}}` to access them, so try 

```hbs
<div class="comments">
  {{#each comments}}
    <div class="comment">
      <h2>{{../user}}</h2>
      <p>{{this}}</p>
      {{../email}}
    </div>
  {{/each}}
</div>
```

**Comment by cyang** [comment]
Thank you for the great response. It works now!

**Comment by kpdecker** [comment]
Thank you @nknapp! @cyang glad you found a fix.

**Comment by nknapp** [comment]
no problem. I just occasionally look for issues I can answer...
