### ISSUE TITLE
if block won't fire

### ISSUE THREAD

**Issue by chrleon** [wycats/handlebars.js#1178]
I use sheetsu.com to get data from google sheets, I get the data as JSON. I parse it and use it to fill in data in a template.

Since this data is input via a form I have human readable column names, and I do an each to populate the template. I escape the human-readable column names with quotes, like so {{'Faglig kompetanse'}}.

Given this code 
>   {{#if 'Faglige kompetanser / kunnskap'}}
    {{'Faglige kompetanser / kunnskap'}}
  {{/if}}

the template shouldn't be filled when the key in question = "", but it still does.
Here is the offending key, logged to the console in chrome
![image](https://cloud.githubusercontent.com/assets/347919/12972966/b92f84c2-d0a9-11e5-9430-80a8a55f1e60.png)

Is there something wrong with using quotes around column names, like I do, or am I totally missing something here?

**Comment by zordius** [comment]
Try this: https://jsfiddle.net/9D88g/48/ . use `[` and `]` to protect special chars, check document here: http://handlebarsjs.com/expressions.html

**Comment by chrleon** [comment]
Great, thanks!
