### ISSUE TITLE
unescaped whitespace control error

### ISSUE THREAD

**Issue by stevenvachon** [wycats/handlebars.js#1181]
```handlebars
{{path~}} content {{{~path}}}
```
```
...{path~}} content {{{~path}}}
-----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
```

**Comment by zordius** [comment]
Try this: https://jsfiddle.net/9D88g/49/ , valid syntax are `{{~foo}}` , `{{~{foo}}}` , `{{~{foo}~}}` or `{{{foo}~}}` .

**Comment by stevenvachon** [comment]
Thanks. Is that valid syntax or is that a workaround?

**Comment by thumphries** [comment]
`{{~{foo}~}}` is the valid syntax for what you're trying to do. Check out [the lexer](https://github.com/wycats/handlebars.js/blob/master/src/handlebars.l) to get a better understanding

**Comment by stevenvachon** [comment]
Ok, thank you. I still think that it's a bit weird, but if it's an old standard then I'm wrong.
