### ISSUE TITLE
change delimiters

### ISSUE THREAD

**Issue by fithwith** [wycats/handlebars.js#1184]
I'm using handlebars with nodejs and I would like to change the delimiters {{ }}.

is it possible ? 
if yes how ? 

Thank you :)

**Comment by Pisi-Deff** [comment]
A question about syntax customization has been answered before: 
https://github.com/wycats/handlebars.js/issues/1167

**Comment by fithwith** [comment]
ok thank you, but this is a too much, fork the project and playing with the whole syntax just to be able to change delimiters from {{ }} to [[ ]] 
there is no other simple solution ? 
I guess no, look like the parser was auto generated.

**Comment by kpdecker** [comment]
The reason that it's not supported within the project itself is that there is not a simple solution given our parser infrastructure.

**Comment by kpdecker** [comment]
That is to say there is no simple solution that doesn't break all existing use cases or introduce significant overhead.

**Comment by fithwith** [comment]
ok, any way thank you for your reply :+1:
