### ISSUE TITLE
Leaner/Clearer compiled templates

### ISSUE THREAD

**Issue by stevenvachon** [wycats/handlebars.js#1189]
Currently, this:
```handlebars
<tag1>{{path0 (path1 "string") hash="value"}}</tag1>
<tag2>{{@path2}}</tag2>
```
compiles to:
```js
(function()
{
	var template  = Handlebars.template;
	var templates = Handlebars.templates = Handlebars.templates || {};
	
	templates['compiled-template.hbs'] = template(
	{
		"compiler": [7, ">= 4.0.0"],
		
		"main": function(container, depth0, helpers, partials, data)
		{
			var helper;
			var alias1 = depth0 != null ? depth0 : {};
			var alias2 = helpers.helperMissing;
			var alias3 = container.escapeExpression;
			
			return "<tag1>"
				+
				alias3
				(
					(helpers.path || (depth0 && depth0.path) || alias2).call
					(
						alias1,
						(helpers.path || (depth0 && depth0.path) || alias2).call
						(
							alias1,
							"string",
							{
								"name": "path1",
								"hash": {},
								"data": data
							}
						),
						{
							"name": "path0",
							"hash": { "hash":"value" },
							"data": data
						}
					)
				)
				+
				"</tag1>\n<tag2>"
				+
				alias3
				(
					(
						(helper = (helper = helpers.path || (data && data.path)) != null ? helper : alias2),
						(
							typeof helper === "function" ? helper.call
							(
								alias1,
								{
									"name": "path2",
									"hash": {},
									"data": data
								}
							) : helper
						)
					)
				)
				+
				"</tag2>"
			;
		},
		
		"useData": true
	});
})();
```

There is some, in my opinion, unnecessary redundancies in there. Could they not be moved to more descriptive functions such as `maybeCallHelper()`?

**Comment by kpdecker** [comment]
I looked into a number of these changes and this route was chosen in most cases over the use of helper functions as this is significantly faster for rendering and the overhead over the wire is minimal with gzip as this is procedurally generate code so it compresses very well.

That being said, if someone were to create a pull request that adds a compiler option for this use case if they feel the gzip compression is not sufficient, I'd be open to landing that.

**Comment by stevenvachon** [comment]
File size is only one benefit of optimizing this. The main one is complexity -- I'm finding it difficult to figure out exactly what's going on in order for me to complete compilers that will depend on [handlebars-html-parser](https://github.com/stevenvachon/handlebars-html-parser).

**Comment by kpdecker** [comment]
This is true, but the compiled output of the templates was never intended for human consumption. We are optimizing for the runtime in this case since this is procedurally generated code.

If you are writing your own compile to infrastructure, you may want to consider implementing your own version of JavascriptCompiler (you'd need to do the same to implement the helper-based implementation you are proposing) and modify this to fit whatever output you find easiest for you to follow.

**Comment by stevenvachon** [comment]
I'd prefer to use the handlebars runtime, but not use `handlebars.compile`.

**Comment by kpdecker** [comment]
Then that implies that you'll need to work in the format that the runtime currently uses now. You might be boxing yourself into a particular pattern unnecessarily as the handlebars runtime is highly focus on generating strings as fast as possible and does little to support other object types. HTMLbars as an example only uses the parse, to my knowledge.

**Comment by stevenvachon** [comment]
The compiled Handlebars templates appear to use callbacks that return the block-level contents. They wouldn't have to return strings, but could return vDOM/similar objects. But all of the conditions to run functions could be hidden away, making my job more humanly possible.

**Comment by kpdecker** [comment]
If you want to submit pull requests to help support your use case, we would be glad to consider them, but there is a bit of a bar to be passed as we don't want to degrade performance and additions to the client runtime require breaking changes, so we may be limited in when we can land them.

**Comment by stevenvachon** [comment]
How are `else if` and `else` helpers handled in the Handlebars source? I can't seem to find definitions for them. Also, based on the test suite, such appear to be used with `with` and `unless` as well -- are there others? What does the compiled output look like?

**Comment by kpdecker** [comment]
`else if` is chaining two `if` helpers together. Any helper can be chained.

```
{{if foo}}
{{else if bar}}
{{else if baz}}
{{/if}}
```

Is effectively syntactic sugar for this:

```
{{if foo}}
{{else}}
  {{if bar}}
  {{else}}
    {{if baz}}
    {{/if}}
  {{/if}}
{{/if}}
```

Re: what the output looks like, `print-script` is a utility in this repo that will output the generated code to the console. I generally use this when trying to determine the structured Ex:
```
./print-script '{{foo}}`
```

**Comment by stevenvachon** [comment]
These appears to be possible, then:
```handlebars
{{#unless foo}}
{{else if bar}}
{{else}}
{{/unless}}
```
```handlebars
{{#helper foo}}
{{else if bar}}
{{else}}
{{/helper}}
```
Correct?

**Comment by kpdecker** [comment]
Yes.

**Comment by stevenvachon** [comment]
Wouldn't this conflict with a view model `else` property?:
```js
console.log( require("handlebars").compile("{{#if var}} foo {{else}} baz {{/if}}")({else:"bar",var:true}) )
```

**Comment by stevenvachon** [comment]
Is `else` considered a "standalone" tag? I've seen mentions of this in comments and documentation but it wasn't clear enough for me.

**Comment by kpdecker** [comment]
Users can reference the variable else with [else]. Both of these behaviors
have been like this since the early days of the project.

**Comment by stevenvachon** [comment]
Back in the early days I wasn't writing a custom handlebars compiler ;)

Is there a name to describe the special function of `{{else}},{{else if}},{{^}}`?

**Comment by stevenvachon** [comment]
Particularly something that differentiates themselves from `{{^else}}` (inverted standalone block).

**Comment by stevenvachon** [comment]
Well, I'm going with "chained, inverted standalone block".

**Comment by stevenvachon** [comment]
@kpdecker regarding PRs that might degrade performance; is it really a concern when the tradeoff is new uses for Handlebars? I think the degrade would be marginal.
