### ISSUE TITLE
mustacheOnly option?

### ISSUE THREAD

**Issue by stevenvachon** [wycats/handlebars.js#1190]
...that disables helpers, expressions and whitespace control and throws errors if they're found.

This can be useful when compiling templates that should be as simple as possible, such as for emails, and would prefer not to add another dependency.

**Comment by kpdecker** [comment]
Why not just use mustache?

**Comment by kpdecker** [comment]
I don't see a lot of value to adding this because that's basically requesting the implementation of the original library.

**Comment by stevenvachon** [comment]
Why not mustache? "would prefer not to add another dependency"

**Comment by kpdecker** [comment]
Can't justify the maintenance cost nor the potential for the behaviors to skew and cause technical debt over a 116K download.
