### ISSUE TITLE
Enable debugging

### ISSUE THREAD

**Issue by SzaboMate90** [wycats/handlebars.js#1196]
Hello guys!
I have a really big problem with debugging since I'm using handlebars, because it has a module: printer.js(PrintVisitor) that devours every outgoing console information, that I must see in my console for the appropriate debugging. Here is a screen-shot about what I'm talking about:
![printer](https://cloud.githubusercontent.com/assets/17760932/13664942/4336cd86-e6aa-11e5-87f9-f121e32e27cf.png)
Is there any way to disable that printer.js, and let every information show that come from my website?

**Comment by kpdecker** [comment]
Your source maps are incorrectly generated. Turn those off in the browser and it will point you to the actual location of the error.
