### ISSUE TITLE
Custom interpolation syntax

### ISSUE THREAD

**Issue by BeatC** [wycats/handlebars.js#1200]
My colleagues stumbled with an issue when they are using HBS with other template engines (in their case with Twig). Different parts of HBS templates are rendered via PHP and Twig. As I know there is solution with using __endverbatim__ syntax but the result looks so weird. What if we add custom interpolation syntax for such cases (for example as we have in Angular templates, they use __{{__ syntax too, but customization of interpolation is also supported)?

**Comment by kpdecker** [comment]
Short answer is no, but #350 has some discussion on options here.
