### ISSUE TITLE
Add ES6 Module style to CLI

### ISSUE THREAD

**Issue by msmith-techempower** [wycats/handlebars.js#1205]
It would be great of the CLI supported the up-and-coming ES6 standard and utilize modules as another option to sit alongside both AMD and CommonJS output.

Here is the current vanilla output using just `<div>{{test}}</div>` as the example:

``` JavaScript
(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['test.html'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper;

  return "<div>"
    + container.escapeExpression(((helper = (helper = helpers.test || (depth0 != null ? depth0.test : depth0)) != null ? helper : helpers.helperMissing),(typeof helper === "function" ? helper.call(depth0 != null ? depth0 : {},{"name":"test","hash":{},"data":data}) : helper)))
    + "</div>";
},"useData":true});
})();
```

This could very easily be turned into the following to be a valid ES6 module:

``` JavaScript
import 'handlebars.js'; // This is the only tricky part

class Template() {
  constructor() {
    let template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
  templates['test.html'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
      let helper;

    return "<div>"
      + container.escapeExpression(((helper = (helper = helpers.test || (depth0 != null ? depth0.test : depth0)) != null ? helper : helpers.helperMissing),(typeof helper === "function" ? helper.call(depth0 != null ? depth0 : {},{"name":"test","hash":{},"data":data}) : helper)))
      + "</div>";
  },"useData":true});
    // Important bit; you could move this up to the same line as the assignment of the templates['test.html'] variable, but I wanted to make this sand out.
    this.template = templates['test.html'];
   }
}

export const template = new Template().template;
```

The only tricky thing about this type of output is that the CLI must require a path to `handlebars.js` so the `import` works "out of box". Something like:
`$ handlebars test.html -f test.js -e` or `$ handlebars test.html -f test.js --es6`

This implement would allow development in ES6 modules and having templates defined as imports:

``` JavaScript
import template from 'test.js';

export default class TestModule {
  constructor() {
    this.render = template;
  }
}

// Example usage
let context = {};
document.body.innerHTML = new TestModule().render(context);
```

**Comment by methodbox** [comment]
Shouldn't ES6 already work for this? Maybe not natively within the module as you suggest, but at least if you're precompiling?

**Comment by kirlat** [comment]
I second to what @msmith-techempower suggests. Would be really cool to have this feature, especially now, when all modern browsers are starting to support ES6 modules.

**Comment by b1lly** [comment]
bump, was there any support for this?

**Comment by nknapp** [comment]
Currently, we are still supporting Internet Explorer 6. I would hesitate to implement different output flavours, because of the complexity this creates and I don't see the benefit right now.

If this is important to anybody, please open a new issue.
