### ISSUE TITLE
Node security error

### ISSUE THREAD

**Issue by awebdeveloper** [wycats/handlebars.js#1206]
1 vulnerabilities found
┌───────────────┬────────────────────────────┐
│               │ Regular Expression Denial of Service                                                      │
├───────────────┼─────────────────────────────┤
│ Name          │ uglify-js                                                                                 │
├───────────────┼─────────────────────────────┤
│ Installed     │ 2.4.24                                                                                    │
├───────────────┼────────────────────────────-┤
│ Vulnerable    │ <2.6.0                                                                                    │
├───────────────┼─────────────────────────────┤
│ Patched       │ >=2.6.0                                                                                   │
├───────────────┼─────────────────────────────┤
│ Path          │ api@0.0.0 > hbs@4.0.0 > handlebars@4.0.3 > uglify-js@2.4.24                           │
├───────────────┼─────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/48                                                     │
└───────────────┴────────────────────────────┘

**Comment by stevenvachon** [comment]
I'm pretty sure that it's only used locally to build the distribution file. It's even within `optionalDependencies`.

**Comment by ErisDS** [comment]
This was resolved in 4.0.5. Upgrading, or getting your dependent project to upgrade should remove hte warning.
