### ISSUE TITLE
CLI Compiling Question

### ISSUE THREAD

**Issue by lostthetrail** [wycats/handlebars.js#1208]
When using the CLI it appears you have to create an output file per specific template or templates in a folder. It doesn't appear that there is a way to have the CLI process the whole tree of dependencies in a template.

Is it the intention to need to run the CLI at least one time for partials? If not once per partial?

Furthermore, partials once registered seem to be aliased to their filename, any suggestions on namespacing?

Thank you so much for your time.

**File structure**
```
<< root >>
↳ templates/
↳ main.hbs
↳ partials/
┋ ↳ item.hbs
```

**main.hbs**
```
<h1>My page</h1>
{{> item}}
```

**item.hbs**
```
<p>An item</p>
```

**Comment by jbboehr** [comment]
If you're using requirejs, [this library](https://github.com/SlexAxton/require-handlebars-plugin) can load partials. The precompilation step is done through the requirejs optimizer, so you don't have to precompile manually.

**Comment by methodbox** [comment]
A lot of people have examples out there for gulp/grunt to recompile on change when watching specific files or contents of a given folder(s).

Takes about a minute to setup and will both compile all or specific items on any save.
