### ISSUE TITLE
Handlebars wraps / escapes <!DOCTYPE html> (in metalsmith)

### ISSUE THREAD

**Issue by diroru** [wycats/handlebars.js#1209]
Hello,

i am sorry but i don't know if it is a `handlebars` or `metalsmith` specific bug. I just simply can't get a doctype declaration into my final html. Have been trying direct declaration in the template file and with the `SafeString()` function. The latter yielded following results:

a) a _conventional_ element (e.g. `<div>`) inside the `<html>` block gets rendered, as expected, without changes.

b) a _conventional_ element before the `<html>` block gets rendered ok, but is placed inside a `<p>` tag.

c) a _doctype_ element inside the `<html>` block gets rendered as pure text, like this: `&lt;!DOCTYPE html&gt;`

d) a _doctype_ element before the `<html>` block will be rendered in the same manner but wrapped in a `<p>` element.

This is the helper function in question: 

```
handlebars.registerHelper('doctype', function() {
  return new handlebars.SafeString("<!DOCTYPE html>");
});
```

I would like to know if this bug is reproducible in other systems. I personally use `handlebars`  `^4.0.5` with `metalsmith` `^2.1.0`. Please somebody tell me that an evil virus is hijacking my build script :)

Any help would be appreciated.

Cheers,
dimitar

**Comment by diroru** [comment]
Seems to be a `metalsmith` transformation- / plugin-related issue.

**Comment by maticrivo** [comment]
@diroru did you find a solution for this?

**Comment by diroru** [comment]
Just tested with a minimal setup using `handlebars ^4.0.6`, the helper works as expected. Everything’s fine, thank you.
