### ISSUE TITLE
handlebars.registerPartial can't work with html template element

### ISSUE THREAD

**Issue by objectisundefined** [wycats/handlebars.js#1212]
{{> description}} expression in script tag, the code works,
but when I put it in template tag, it fails.
handlebars throw an error '{{\&\g\t\; ...'  , '>' can't be compiled correctly.
Is there any method I can use with template element in html?

**Comment by ErisDS** [comment]
Hi @objectisundefined! There's not enough info here for someone to understand or reproduce your issue to see what is happening. Please see the information [here](https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md#reporting-issues) on reporting issues and put together an example showing what it is you're doing that's not working as you would expect.

**Comment by objectisundefined** [comment]
If i use a script tag to contain the {{> expression of handlebars, the code works well.
When I use html5 template tag to contain the expression, the > sign was transformed to safe string.

**Comment by kpdecker** [comment]
This is a behavior of the browser attempting to "fix" what it deems to be invalid input. You need to use the `script` element to properly parse templates if you are choosing to embed them directly in html, but generally it's better to compile the scripts into you javascript bundles.
