### ISSUE TITLE
\n's passed in context to a partial are replaced with \n\t\s\s

### ISSUE THREAD

**Issue by jbsouvestre** [wycats/handlebars.js#1216]
Hello, 

I have put together a jsbin to better reproduce my issue : https://jsbin.com/yodoyu/edit?html,js,output.

Basically the string `value` displays fine if I only pass it to a template, but all `\n` are replaced with `\n\t\s\s` if it is passed through a partial. 

Thank you

**Comment by stevenvachon** [comment]
Your partial expression is indented within your template element.

**Comment by jbsouvestre** [comment]
Ah thank you. It seems unlikely that my issue is caused by that in my setup so I'll reopen if I'm able to reproduce it

**Comment by stevenvachon** [comment]
Np. You could keep your indenting (for code quality) and try using whitespace control to remove the injected indenting:
```handlebars
{{~> partial}}
```
