### ISSUE TITLE
Nested partials not working

### ISSUE THREAD

**Issue by mendlik** [wycats/handlebars.js#1218]
Nested partials cause RangeError.
Example: https://jsfiddle.net/mendlik/bp7jsbd8/3/

This problem is probably a root cause for another issue https://github.com/wycats/handlebars.js/issues/1185

**Comment by damncabbage** [comment]
Confirmed; c.f. https://github.com/wycats/handlebars.js/issues/1185#issuecomment-227059887

**Comment by lawnsea** [comment]
I am investigating this rn. What I've found thus far is that this line is the source of the infinite recursion: https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/runtime.js#L48.

**Comment by lawnsea** [comment]
Ok, I did a lot of stepping through this code this weekend and root-caused the bug to this line: https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/runtime.js#L218. I'm not sure what *should* happen, but what *does* happen is that the `options.fn` value for the outer partial is overwritten by the `options.fn` value for the nested partial.

I tried to figure out what's going on, but was unable to do so. I think we're going to need @kpdecker's help on this one.

<details>
<summary>Minimal repro script runnable from the root of repo</summary>

```javascript
'use strict';

const Handlebars = require('./dist/handlebars.js');

const nested = `
nested
{{>@partial-block}}
nested-end
`;

const outer = `
outer
{{#>nested}}
  {{>@partial-block}}
{{/nested}}
outer-end
`;

const template = `
{{#>outer}}
content
{{/outer}}
`;

Handlebars.registerPartial('outer', outer);
Handlebars.registerPartial('nested', nested);

var compiledTemplate = Handlebars.compile(template);
console.log('result:\n', compiledTemplate());
```
</details>

In the course of

**Comment by slimelabs** [comment]
@kpdecker 👋 sup

**Comment by kpdecker** [comment]
I have not really been active in Handlebars for a while and just started a new job that is JSX focused rather than Handlebars, so I don't expect to have much time to work on this in the near future. @wycats may be able to tap someone in the Ember community to help out in my absence.
