### ISSUE TITLE
How to keep unspecified variables in handlebars?

### ISSUE THREAD

**Issue by TheInvoker** [wycats/handlebars.js#1220]
In handlebars, I have this code

```
<p>
    {{A}}
    {{B}}
</p>
```

and then I compile with 

```
{"A" : "test"}
```

However the end result is

```
<p>
    test
</p>
```

But what I really want is:

```
<p>
    test
    {{B}}
</p>
```

Since `B` was not defined in the object, I want the variable text to remain. Is there a flag I can pass to the compile or some function to specify this behavior?

Thanks

**Comment by nknapp** [comment]
You specific case can be solved with the `helperMissing` helper.

https://jsfiddle.net/vva7musq/18/

It does not work anymore though, if you use `{{a.x}}` with dots in it, because that cannot be interpreted as helper call. I'd say there is no other way of doing that.
