### ISSUE TITLE
Documentation is sorely lacking

### ISSUE THREAD

**Issue by methodbox** [wycats/handlebars.js#1222]
I am new to HB and continually find myself looking to outside sources (as in, not your docs) to learn how to use HB properly.

The documentation on Partials, Precompiling and even basic usage is terrible and missing a lot of information.

For example:

1) Usage of "context" is hardly explained, yet critical to how HB actually works.

2) Usage of Partials, if following directly from your own website, will NOT result in rendering a Partial. I would go so far as to say the docs are technically incorrect as the incomplete example given will not actually work.

3) Usage with require(); in node is not properly explained. At the moment, using require(); will not throw an error, but it won't make the package available in the browser, either, so templates don't render.

4) The additional JS needed to properly display a rendered template (assigning it to a div with the proper id) is not explained at all in the docs. It's obvious that it will have to be done, only if you already develop in JS. But for someone coming to your page new, it isn't clear that HB doesn't handle this on it's own.

5) HB is obviously meant to reduce the need to repeat yourself, particularly when using dynamic data, such as from Mongo, yet not a single example or even mention appears in the docs as to how this would be done. That's find, I can figure it out with Mongo, but it's simply undocumented.

**Comment by rafde** [comment]
You might want to take this to https://github.com/wycats/handlebars-site/issues considering that site being the place where all the lack of documentation is being hosted.

**Comment by methodbox** [comment]
Will do.

**Comment by nknapp** [comment]
Interested in helping creating a new site? #1345

**Comment by methodbox** [comment]
Not really. I stopped using handlebars a long time ago in favor of modern view management using Vue or React, looking at Angular 2 a bit, but Vue or React does the trick most if the time.

It's no longer HBS's documentation alone which is lacking, but also the value of the library itself.

Creating templates in Vue is trivial and more flexible, components and stateless components in React are just as effective. IMO handlebars is now irrelevant.

**Comment by nknapp** [comment]
I guess you are right, as long as browser javascript is concerned.

I've found it very useful for static-site- or documentation-generators. And the nice thing about Handlebars is, that there are implementations in other languages and other implementations like Glimmer that use the same syntax. 
All the more reason to have a proper documentation and a language-specification with an official test-suite that other implementations can be validated against.

But I can see your point and I agree that it does not make sense for you to help out here, if you are not using Handlebars anymore. You have created a nice list of issues though, that we will hopefully all incoroporate into the new site.

**Comment by methodbox** [comment]
You said it well. I wouldn't make much sense for me to spend time contributing to something I won't be using.

If and when handlebars becomes relevant to me again, I may consider.

However, I certainly see value in what you are doing in terms of the need for those who actually use HBS to have proper documentation.
