### ISSUE TITLE
Scope changes when calling a Partial Block-using Partial with a provided object scope. 

### ISSUE THREAD

**Issue by damncabbage** [wycats/handlebars.js#1226]
The following works (producing `<h1 class="abc">Hello!</h1>` twice), but is perhaps unexpected:

test.json:

``` json
{ "donut": { "internal": "abc", "title": "Hello!" } }
```

test.hbs:

``` handlebars
{{#*inline "donut"}}
  <h1 class="{{ internal }}">{{> @partial-block }}</h1>
{{/inline}}

{{!-- Working as expected: --}}
{{#>donut internal=donut.internal}}
  {{~ donut.title ~}}
{{/donut}}

{{!-- Passing the "donut" object here as the scope: --}}
{{#>donut donut}}
  {{!-- Means we have to change this here to get this to work: --}}
  {{~ title ~}}
{{/donut}}
```

I found this to be… unexpected. Is this a bug?
(Tested with both the version from tryhandlebars.com and locally with Handlebars v4.0.5.)

**Comment by lawnsea** [comment]
To me, this is expected behavior, so I'm closing this. Please reopen if you feel strong that it's unexpected.
