### ISSUE TITLE
blocker "each" raise an exception in the android webview

### ISSUE THREAD

**Issue by kuangpeng** [wycats/handlebars.js#1228]
android 5.x webview raise an exception when compile "each" blocker, that show the javascript code like

`function push(expr) { if (!(expr instanceof Literal)) { expr = this.source.wrap(expr); } this.inlineStack.push(expr); return expr; }`

**Comment by heke2929** [comment]
i met the same.

**Comment by kuangpeng** [comment]
i change the method to handle tpl , use the regexp in a simple function wriiten by myself.

**Comment by heke2929** [comment]
@kuangpeng 能说下详细吗？

**Comment by kuangpeng** [comment]
@heke2929  自己写个简易的函数，使用正则匹配参数并用值替换
`var exp = new RegExp("{{" +da + "}}","gi");
tpl_html = tpl_html.replace(exp, data[da]);`

这只是简单的处理，没有什么条件判断等表达式，能否适用还得看具体需求。
如果不满足需求可以选择换个模版框架。

**Comment by heke2929** [comment]
@kuangpeng 首先感谢您的答复。我先按照您的方式尝试一下。

**Comment by lawnsea** [comment]
This bug doesn't provide enough information to reproduce it locally. I'm going to close it. Please reopen if you can provide a template that reproduces the failure you saw.

**Comment by migomhmi** [comment]
@lawnsea I faced this issue a minute ago. I can't see a concrete pattern to this behavior. However I have noticed that it might be occurring while I am compiling multiple handlebar templates with large json arrays simultaneously. It occurs frequently, but not always. Hope this helps.
