### ISSUE TITLE
Helper cannot return Array or Object

### ISSUE THREAD

**Issue by toksea** [wycats/handlebars.js#1229]
Hi! It seems that return value of custom helpers will force cast to string.

e.g.
```
Handlebars.registerHelper('testArray',function(object) {
    return [1,2,3];
});

{{#testArray}}loop{{/testArray}}

// will output
1,2,3
```

Can I return Array or Object from helpers?

**Comment by nknapp** [comment]
You can use your helper as argument to the {{#each}}-helper in order to iterate the array. Try this template:

```hbs
{{#each (testArray)}}
	{{.}}.loop
{{/each}}
```

**Comment by toksea** [comment]
@nknapp Thank you! It works!
