### ISSUE TITLE
customHelper language specific characters

### ISSUE THREAD

**Issue by rares-p** [wycats/handlebars.js#1231]
Hello,
I made a project with handlebars. It works great and does what it has to do.
The only problem I have is that with a custom helper I do not get the language specific characters thru.
For the sake of simplicity this is what I have:
```
Handlebars.registerHelper('html10n', function (str) {
    return "ß ăî ومض";
});
```
I call it with:
`{{html10n "blablabla"}}`

Unfortunately I get this output: � ?� ???

Even worse than this is that on http://tryhandlebarsjs.com/ my helper works flawlessly and the ouput is _ß ăî ومض_
Do you have any pointers on this?
Thanks.

**Comment by rares-p** [comment]
It was my bad.
I have placed the registerHelper() in a file that was ANSI encoded.
It works as expected.

**Comment by stevenvachon** [comment]
Please close, then.
