### ISSUE TITLE
Expressions are lost on precompile

### ISSUE THREAD

**Issue by methodbox** [wycats/handlebars.js#1232]
I have a contact form, for example, that I can directly render expressions like this:
```
app.get('/contact', function(req, res) {
	res.render('contact', {test: "Test Works!"});
});
```

And on contact.handlebars:
```
<div id="contact"></div>
{{test}}
```

The div id="contact" is actually a precompiled template. This comes from my source, which is bundled and pulled in on the main layout html page using a simple ```<script src="bundle.min.js">```.

Everything renders, EXCEPT any expressions defined in the precompiled template. For example:

```
<h1>Contact</h1>

{{> exampleForm}}

{{test}}
```

Test is defined in my route as described at the top. This is just for testing; eventually this data will be pulled from a database. In this example the ```{{> exampleForm}}``` is a partial that is also precompiled - just a html form - and it renders just fine, CRUD is all wired up, works fine.

Just expressions do not display unless I add them to the destination, non-precompiled template. This basically makes precompiling worthless. I want to be able to output the results of the form using a template which will display four fields, ideally populated by using something like this:

```
{{#if contactResults}}
  <p>{{name}}</p>
{{/if}}
```
But if the expression isn't preserved into the final rendered template, then the whole purpose of precompiling is worthless.

I'm sure there's a way to preserve the location of the expression without destroying it when it's precompiled. Note that NO errors are thrown in terminal or web console.

**Comment by methodbox** [comment]
This appears to be an issue I've narrowed to gulp-handlebars and will likely close this issue later today.

It appears gulp-handlebars precompile either isn't compatible with handlebars 4.x or loses expressions during the compile due to evaluating them and returning an empty value (because it can't evaluate them yet).

**Comment by kpdecker** [comment]
Can this be closed?

**Comment by methodbox** [comment]
Yes this can be closed. This is an issue with gulp-handlebars and effectively an issue with order of operations.

Writing a precompile method using "vanilla" handlebars doesn't produce the same issue.

Sorry for the late response.
