### ISSUE TITLE
Inconsistency between api doc and implementation

### ISSUE THREAD

**Issue by blikblum** [wycats/handlebars.js#1237]
I'm using the [compiler API](https://github.com/wycats/handlebars.js/blob/master/docs/compiler-api.md) and the specs as references to port handlebars to pascal

The API  states that BlockStatement path must be a PathExpression but the parser accepts string,number and even boolean literals in path. 

The examples below works:

```
{{#1}}ss{{else}}xx{{/1}} 
{{#true}}ss{{else}}xx{{/true}}
```

The current implementation gives the expected behavior and the doc is misleading?

**Comment by stevenvachon** [comment]
I'm pretty sure that it's due to backwards-compatibility with Mustache

**Comment by nknapp** [comment]
#1277

**Comment by nknapp** [comment]
The documentation has actually been updated in 8088a466cdc204bd97f. Closing
