### ISSUE TITLE
Request: Add express-handlebars to documentation

### ISSUE THREAD

**Issue by bugs181** [wycats/handlebars.js#1241]
It might be worthwhile to add the express-handlebars repo to the documentation. I wouldn't of come across handlebars had it not been for that project which exposes handlebars to the Express engine in nodejs. 

Repo: https://github.com/ericf/express-handlebars

**Comment by rafde** [comment]
You could submit a PR that adds it to https://github.com/wycats/handlebars.js/blob/master/README.markdown#handlebars-in-the-wild
section. 
Good luck getting it merged though. This project seems inactive since the primary focus of @wycats is to improve EmberJS.

**Comment by lawnsea** [comment]
We are back in business, definitely. Please submit a PR if you want this.
