### ISSUE TITLE
Can't reference JSON data using a variable

### ISSUE THREAD

**Issue by williamwisesiteminder** [wycats/handlebars.js#1248]
Hi, I've been pulling my head apart trying to find a way to access JSON data within a helper, such {{#each}} by using a variable as a reference. 

Example: 
**JSON**
`{
  "lang" : "en",
  "story": {
    "en" : {
        "intro": "Before the jump",
        "body": "After the jump"
    },
    "fr" : {
        "intro": "Before le jump",
        "body": "After le jump"
    }
  }
}`

**TEMPLATE**
`{{#each story[lang]}} ... {{/each}}`

I'm working on a multi-lingual site, and we're experimenting being able to have a single JSON and Handlebars template for each of our pages, then when compiled – output an HTML file for each language. 

Pretty much, we would itterate over each of our supported languages when compiling and pass the "lang" variable accordingly for each one (lang: fr, lang: de, and so on...) 

I've played around with different syntax but it seems like this method of referencing isn't supported... Am I wrong? 

Just let me know if you need more info!

Cheers,
Will

**Comment by zordius** [comment]
Use `lookup` to handle this. Example:

Template:
```
{{#each (lookup . foo)}}{{.}}!{{/each}}
```
Data:
```
{ 
  foo: 'a',
  a: [1, 3, 5],
  b: [2, 4, 6],
  c: [1, 2, 3]
}
```
Output:
```
1!3!5!
```

Other reference: <a href="https://zordius.github.io/HandlebarsCookbook/0020-lookup.html">Handlebars: Built-in helper - lookup</a>

**Comment by lawnsea** [comment]
Thanks for the great answer, @zordius. Closing this. Please reopen if the suggested solution doesn't meet your needs.
