### ISSUE TITLE
Passing a moment as data with key `date` results in error

### ISSUE THREAD

**Issue by adamreisnz** [wycats/handlebars.js#1249]
I get the following error when I try to compile a template with the following data:

``` js
{
  date: moment(),
}
```

```
TypeError: mom.isValid is not a function
    at get_set__get (node_modules/moment/moment.js:512:20)
    at Object.<anonymous> (node_modules/moment/moment.js:506:24)
    at lambda (node_modules/handlebars/dist/cjs/handlebars/runtime.js:109:54)
    at Object.eval (eval at createFunctionContext (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:15:14)
    at main (node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
```

Using instead:

``` js
{
  now: moment(),
}
```

Doesn't create any problems. Is `date` some kind of reserved key for data?

**Comment by nknapp** [comment]
Could you post a complete example, including template or even better, create a fiddle? There is a [template](https://jsfiddle.net/9D88g/47/) to start with.

**Comment by adambuczynski** [comment]
Sorry, I don't have the time to do that right now unfortunately. But I think the error can be pretty easily deduced from the stack trace. I have specified the steps required to reproduce, it's really just the name of the data that is `date` and is a `moment()`.

**Comment by nknapp** [comment]
I tried to reproduce this issue with 4.0.8 (https://jsfiddle.net/9D88g/99/) and couldn't. Could you verify that you still have the problem?

**Comment by adamreisnz** [comment]
@nknapp I can confirm that this problem does not happen anymore in **4.0.6**, but 4.0.8 now breaks registering helpers, so I can't really test it with that version:

```
Error: Missing helper: "moment"
    at Object.<anonymous> (node_modules/meanie-mail-composer/node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
```

Reverting back to 4.0.6 and the missing helper error disappears. Not sure what is going wrong there, but a patch release shouldn't introduce breaking changes to the API of loading helpers I presume.

My code to load them is straightforward:

```js
'use strict';

/**
 * Dependencies
 */
const fs = require('fs');
const path = require('path');
const handlebars = require('handlebars');

/**
 * Settings
 */
const PATH_HELPERS = path.resolve('./app/helpers/transform/');

/**
 * Register handlebars helpers
 */
fs.readdirSync(PATH_HELPERS)
  .forEach(file => {
    const ext = path.extname(file);
    const name = path.basename(file, ext);
    const helperPath = path.join(PATH_HELPERS, file);
    const helper = require(helperPath);
    handlebars.registerHelper(name, helper);
  });
```

With 4.0.6 and previous this works like a charm, but with 4.0.8 it breaks and throws the above error. Good I found it now, or all of our emails would have been broken...
