### ISSUE TITLE
Document [else] as in `{{#if}}...{{[else]}}..{{/if}}` 

### ISSUE THREAD

**Issue by nknapp** [wycats/handlebars.js#1251]
The syntax `{{#if}}...{{[else]}}..{{/if}}` that is described in [this comment](https://github.com/wycats/handlebars.js/issues/1189#issuecomment-211569918) is not documented (at least I found it nowhere). This is a reminder to do that some time.

**Comment by rafde** [comment]
Might want to take this to https://github.com/wycats/handlebars-site/issues

**Comment by nknapp** [comment]
Good point. Thanks

**Comment by nknapp** [comment]
wycats/handlebars-site#162
