### ISSUE TITLE
Precompiled templates cannot be imported

### ISSUE THREAD

**Issue by lukgreen** [wycats/handlebars.js#1254]
I precompile templates with the command:
`handlebars -m -e html ./templates/ > ./templates/templates.js`
Then I try to import the resulting file in my javascript:
`import './templates/templates.js';`
Which throws an error:
`Uncaught ReferenceError: Handlebars is not defined`
This error appears with either full or run-time only Handlebars included. I use Handlebars 4.0.5 and bundle a project with Webpack.
Can you help with this please?

**Comment by nknapp** [comment]
The precompiler does not create any module-code. If you are using webpack, you should probably consider using the [handlebars-loader](https://github.com/pcardune/handlebars-loader) or something similar.

(I have not tried the loader yet).
