### ISSUE TITLE
custom expression indicator

### ISSUE THREAD

**Issue by osher** [wycats/handlebars.js#1257]
Hi

The expression indicators are `{{` - `}}` and `{{{` - `}}}`.

mustache allows me to switch the indicators like so:

```
{{=<% %>=}}

now the tags are swapped
<% title %>

and I'm going to put them back
<%={{ }}=%>
```

Trying to do the same with handlebars did not work:

```
$ node
> var hb = require('handlebars');
undefined
> hb.compile('I didn\'t changed the {{ title }}')( { title: 'tags' } )
'I didn\'t changed the tags'
> hb.compile('{{=<% %>=}} I changed the  <% title %>')( { title: 'tags' } )
Error: Parse error on line 1:
{{=<% %>=}} I got a  <
--^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'EQUALS'
    at Object.parseError (C:\ws\nodejs\cwt-oapi-util\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:19)
    at Object.parse (C:\ws\nodejs\cwt-oapi-util\node_mo.....
```

Any plans to support it?

I'm asking because I consider handlebars for code generator, and the myriad of `{` and `}` gets to be a pain...

**Comment by stevenvachon** [comment]
This is a very old topic, but the project creators may have a new take on it. It'd be interesting to be able to change the indicators to `${` `}` to be ES6-like.

**Comment by nknapp** [comment]
see #350 for details

**Comment by lawnsea** [comment]
Thanks, @nknapp. Looks like the answer is "no". @osher, if you have ideas for working around the issues laid out in #350, please reopen this issue.
