### ISSUE TITLE
Cannot read property 'JST' of undefined

### ISSUE THREAD

**Issue by Tiendq** [wycats/handlebars.js#1258]
I got this error at the beginning of compiled template file after add babelify (to support ES6) into my grunt-browserify configuration.

this["JST"] = this["JST"] || {}; // <-- exception raised here

Below is my grunt-browserify configuration, comment out options will solve issue (and no more ES6):

`
options: {
    transform: [
      ["babelify", { "presets": ["es2015"] }]
    ]
  }
`

**Comment by lawnsea** [comment]
This is not enough information to reproduce the failure you observed. If you can provide a full minimal reproduction, please reopen this issue.
