### ISSUE TITLE
Handlebars using Assemble partials

### ISSUE THREAD

**Issue by mturnwall** [wycats/handlebars.js#1259]
I have a site where static pages are generated using Assemble. I want to make part of the site dynamic where certain blocks are rendered after page load using Handlebars. I'm precompiling the templates. Is there a way to reuse the partials I have for Assemble in my handlebars precompiled templates? When compiling my handlebars template the partials from Assemble are pulled in correctly. I get errors saying the partial isn't found.

Is it possible to do use Assemble partials in handlebars precompiled templates?

**Comment by lawnsea** [comment]
The information you provided is not enough to locally reproduce the failure you saw. If you can provide a full example that reproduces the failure, please reopen.
