### ISSUE TITLE
Long time evaluate EACH helper

### ISSUE THREAD

**Issue by capfsb** [wycats/handlebars.js#1260]
This is example.

console.time('aaa')
bbb={}; //This string is optimal
bbb[100000000]=1
Handlebars.compile("{{#each products as |p pid|}}111{{/each}}")({products:bbb})
console.timeEnd('aaa');

console.time('aaa')
bbb=[];  //This string is NOT optimal
bbb[100000000]=1
Handlebars.compile("{{#each products as |p pid|}}111{{/each}}")({products:bbb})
console.timeEnd('aaa');

**Comment by nknapp** [comment]
If have created a [jsfiddle](http://jsfiddle.net/nq1ymb2s/24/) for your second example.
As you can see, Handlebars iterates the whole array, also displaying the "undefined" elements.
With `bbb[100000000]`, these are a lot of elements and a long runtime can be expected.

The behavior of [Array.prototype.forEach()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Printing_the_contents_of_an_array) on arrays is different.
The Handlebars-behavior is what I would have expected, and I don't think this will be changed without a good reason. (Although I'm not a collaborator of the project, so it would not be my decision).

**Comment by lawnsea** [comment]
@nknapp is right. This is expected, given JavaScript.
