### ISSUE TITLE
Uncaught Error: if doesn't match each - 78:122

### ISSUE THREAD

**Issue by letoss** [wycats/handlebars.js#1263]
Hello mates.

I'm dealing with the error described in the tittle. I found a similar one in the closed issues, but unfortunately nobody answer about what was going on there and the Issue has been closed.

I'll try to put all the info that I have to see what is going on here.

1. This is only happening in Production Environment. I'm running this locally and I don't get that error, everything is working.
2. I have the same version (oldie one 1.3.0) in Production and Locally.
3. I'm running the same code, it's not minified on Prod.

Code:
```
{{#each active_accounts}}
  <li class="account-item {{#unless this/user_has_roles}}disabled{{/unless}}">
    <a href="" data-bypass class="account-name{{#currentAccount this/account_id}} active{{/currentAccount}} {{#if this/is_default}}default{{/if}}" {{#unless this/user_has_roles}}title="No roles in this account"{{/unless}}>
      <span>{{this/account_name}}</span>
      <input type="radio" value="{{this/account_id}}" name="default_account" {{#unless this/user_has_roles}}disabled{{/unless}}
             {{#if this/is_default}}checked="checked"{{/if}} title="Set as Default" />
    </a>
  </li>
{{/each}}
```
I tried removing the `if` sentence, but the error still there. When I removed one of the `unless` sentence, the error changed the column number. After removing all the `unless` occurrences the error disappeared, but after that, it appears in another template.

I also tried upgrading to the latest Handlebars version but I didn't get better results.

Anyone knows what is going on here?

**Comment by letoss** [comment]
I found the problem!

It  wasn't Handlebars. The problem was a nginx plugin installed in production called pagespeed. This plugin for some reason had been breaking the HTML removing `/`, for example in `{{/unless}} => {{ unless}}`. For this reason handlebars was raising that error.

**Comment by wycats** [comment]
@letoss thanks for the issue and the resolution 😄 

Hopefully it will be useful for some future traveller!
