### ISSUE TITLE
async: return new Handlebars.SafeString not working inside function

### ISSUE THREAD

**Issue by ubergeekzone** [wycats/handlebars.js#1266]
The SafeString function does not like to be used inside a function. I am trying to write some async ajax calls for loading input form template files along with a json config data file. Once i have my promises all set up the function won't fire. I can get this to work using async: false, but not with async:true.

Any input on why the Handlebars.SafeString will not work inside a callback function? I am assuming it's got to do with loading data into the dom after it's already been loaded by the main handlebar function i have that loads the pages.

I have tried a setTimeout() work around with no success. Any help would be awesome sauce!

# This way does not work. (My Preferred Way)
```javascript
var promise = $.ajax({url: 'input.jst'}); // loads an input textfield.

promise.done(function(html){
    data = {};
    template = Handlebars.compile(html);
    callback(template(data));
});

function callback(html) {
    return new Handlebars.SafeString(html);
}
```

# This way work's. (My Fallback Way)

```javascript
function do_html() {
    var html;
    var data = {};
    $.ajax({
    url: 'helpers/forms/input.jst',
    async: false,
    success: function (template_data){
        template = Handlebars.compile(template_data);
        html =  template(data);
    }
});
    return html;
}

return new Handlebars.SafeString(do_html());
```

**Comment by nknapp** [comment]
I'm not sure what you want to achieve. In your first example, you are returning the `new Handlebars.SafeString(html);` from the callback, but you are not doing anything with the result of the callback in  `done`-function.

The intended use of the Handlebars.SafeString class is within [helpers](http://handlebarsjs.com/#helpers). 
If you want to prevent Handlebars from escaping the return value of a helper. Are you using `do_html()`-function as Handlebars-helper? Then the problem may be, that async helpers are not supported by Handlebars. I have written a node library [promised-handlebars](https://www.npmjs.com/package/promised-handlebars) that wraps Handlebars to allow helpers returning Promises. I have nevery tried it in the browser though. Might work with a CommonJS loader.

**Comment by lawnsea** [comment]
@ubergeekzone As @nknapp points out, your preferred code snippet will not work for reasons unrelated to `SafeString`. Specifically, your callback's return value is not used by your `done` handler.

I'm going to close this for now. Please reopen if you can provide a code snippet that demonstrates that `SafeString` doesn't work in a function.

**Comment by ubergeekzone** [comment]
i ended fixing this by loading all my form templates using a deferred request, storing them into an object and then calling the helper as normal from within my templates, works perfectly how it should now. The way before would be making an ajax request for each form template more than once, My new method seems to work better and allows the helper to have a structure that is more to guidelines of a use case. I was over engineering the whole thing, late nights... Thanks for all the help though!
