### ISSUE TITLE
Context change with block helpers in 4.0.6

### ISSUE THREAD

**Issue by Florian-R** [wycats/handlebars.js#1278]
I'm not sure if it's the effect of a bugfix, or if it's a regression. See this two fiddles : 

[4.0.5](https://jsfiddle.net/vva7musq/1/), [4.0.6](https://jsfiddle.net/vva7musq/2/).

I'll try to reduce this more, but any confirmation of the correct behaviour will be greatly appreciated.

Thanks!

**Comment by nknapp** [comment]
Can this be related to #1300 ?

**Comment by nknapp** [comment]
Still present in 4.0.8
