### ISSUE TITLE
Why is the license printed 3 times in the runtime ... ?

### ISSUE THREAD

**Issue by blaasvaer** [wycats/handlebars.js#1287]
I can see that the license is printed three times in a row in the runtime version. And I've spent the whole day trying to get the right runtime version up and running, and still have no »luck«, as guessing is all I seem to be able to do just now.

And this just made me wonder (as I saw the license three times), is this project going down somehow? Can it still be trusted in a production pipeline?

**Comment by nknapp** [comment]
The license being printed 3 times might be related to #1288. Apart from that, what are the problems you are facing?

There has just been a patch release (4.0.6) in November 2016. The project is active and can be used in production (in fact, it is used by many projects).
