### ISSUE TITLE
nested iteration with ability to access parent

### ISSUE THREAD

**Issue by snimavat** [wycats/handlebars.js#129]
Please see the issue here http://stackoverflow.com/questions/552934/what-javascript-templating-engine-do-you-recommend/7812081#7812081

**Comment by bjmercado** [comment]
hello guys i am learning node/express right now, the code above wont work for me i am using express-handlebars, can you help me? Is this possible with express-handlebars? here's my code. the **gpareaData** is iterating but the **branch is not**

```
{{#each gpareaData}}
  <tr>
    <td>
       <select class="form-control" name="gp_branch[]">
           <option value="{{id}}">{{desc}}</option>
             {{#each branch}}
           <option value="{{id}}">{{branch_desc}}</option>
             {{/each}}
       </select>		
     </td>
    <td><button type="button" class="btn btn-primary btn-sm" id="addRws3"><i class="fa fa-plus"></i></button></td>
</tr>
{{/each}}
```

**Comment by Farrukh-Sarmad** [comment]
{{#allData}}
            all<br>
                {{#assignedData}}
                assigned<br>
                    <div class="col-md-2">
                        {{#ifEqual id course_id }}
                            <h6><input type="checkbox" name="course[]" value="{{id}}" checked> {{title}}</h6>
                        {{else}}
                            <h6><input type="checkbox" name="course[]" value="{{id}}"> {{title}}</h6>
                        {{/ifEqual}}
                    </div>
                {{/assignedData}}
            {{/allData}}
My app control is nor even entering the inner loop . Just printing 
all
all
all
Can you tell me why?
