### ISSUE TITLE
Making expressions case insensitive

### ISSUE THREAD

**Issue by priedthirdeye** [wycats/handlebars.js#1302]
I'd like to make it so expressions are not case sensitive.

For example, the following data:

```js
var context = {title: "My New Post"};
var html    = template(context);
```

would support both:

```html

{{title}} 

and 

{{Title}}

```

I looked through the source code and can't see where I would make such a change. I understand there may be some performance impact, but this would really help for my use case.

**Comment by priedthirdeye** [comment]
To be more clear....

I just want to get an idea of where in the source code I would make such a change.

**Comment by rafde** [comment]
This doesn't sound ideal. It'll probably be easier for you to handle it from your object instead of have a breaking change like this request handle it.

**Comment by nknapp** [comment]
I wouldn't accept this as change to the library either, but I found [this function in the compiler api](https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/compiler/javascript-compiler.js#L15-L20), which indicates that it is possible to change this behaviour without changing Handlebars itself.

**Comment by nknapp** [comment]
I have updated [the compiler-api example](https://github.com/wycats/handlebars.js/blob/master/docs/compiler-api.md#example-for-the-compiler-api).

It does not solve your exact issue (it only performs lookups in lower-case, not case-insensitive), but it is a starting point. I believe you can find out the remaining parts by yourself.

However, looking at [this Stackoverflow post](http://stackoverflow.com/questions/12484386/access-javascript-property-case-insensitively), I believe implementing case-insensitive lookups will be a rather large performance impact (not just *some*).
