### ISSUE TITLE
Extending the parser error object with error details

### ISSUE THREAD

**Issue by t-sauer** [wycats/handlebars.js#1305]
Right now when the parser encounters a problem it throws an error containing the error message and the stack trace.

Would it be possible for the error object to also include properties describing the parse error  (e.g. line number, column, error text)? This would solve https://github.com/emberwatch/ember-language-server/issues/31 and would enable editors and IDEs in general to visualise parser errors directly.

**Comment by nknapp** [comment]
I did a short test: The latest commit of the current 4.x branch does not have this problem:

The test

```js
    it.only('should include the location as enumerable property in parse errors', function() {
      try {
        Handlebars.compile(' \n  {{abc}}}\n')();
        equal(true, false, 'Statement must throw exception. This line should not be executed.');
      } catch (err) {
        console.log(err);
      }
    });
```
shows a "hash"-field with location information, and it does not do that when I check out the 4.0.6 tag.
I don't exactly know why this is the case though.

Another reason to publish 4.0.7 soon.

**Comment by twokul** [comment]
@nknapp I looked into it a little. It definitely does not have `hash` with error information in `4.0.6` but it does have it on `master` branch. Somehow, parser is generated differently between those two. Any idea why?

`4.0.6`:

```js
 parseError: function parseError(str, hash) {
  throw new Error(str);
}
```

`master`:

```js
 parseError: function parseError(str, hash) {
   if (hash.recoverable) {
     this.trace(str);
   } else {
     function _parseError(msg, hash) {
       this.message = msg;
       this.hash = hash;
     }
     _parseError.prototype = new Error();

     throw new _parseError(str, hash);
   }
 }
```

Also, I'm not sure what the release cadence is. Are you planning to release `4.0.7` any time soon?
