### ISSUE TITLE
Invalid certificate for https://handlebarsjs.com/

### ISSUE THREAD

**Issue by jonas-schievink** [wycats/handlebars.js#1307]
I clicked a link to the HTTPS version of the Handlebars website, and Firefox refused to connect because the certificate is only valid for a few GitHub subdomains. Just letting you know, since this does seem like a scary error at first :)

**Comment by nknapp** [comment]
I've moved it to wycats/handlebars-site#171, since it is an issue with the site. Thanks for reporting.
