### ISSUE TITLE
How to precompile several templates at once ?

### ISSUE THREAD

**Issue by mdcarter** [wycats/handlebars.js#131]
I wish I could precompile a lot of templates all at once (stored in an hml file, in script tag like "the usual").
Is there a way to do this ?
It's a real hassle to have each template in a separate file and to have to compile each of them ,then copy & paste the result into one single js template file :/

**Comment by caiowilson** [comment]
I know it's kinda old "issue" but why not a catch script with precompiles every .whatever into templates, that's what i'm doing, since then i can make adjustments on dev side and deploy precompiled to the server.

**Comment by nickasd** [comment]
I have started using Handlebars and I have the same problem. My main html file is a large template which contains some small child templates and it would be annoying having to move them to separate files. I would be happy to propose a solution if nobody's working on it yet.
