### ISSUE TITLE
PreCompiler dont respect name argument

### ISSUE THREAD

**Issue by falahati** [wycats/handlebars.js#1311]
Hi,

I am writing my build script to precompile all handlebars templates. But I have a problem with precompiler, following is my command:

`>handlebars "_PartialTemplate.hbs"  --partial --name "PartialTemplate" --extension "hbs"`

Output is:
`... Handlebars.partials['_PartialTemplate'] = ....`

How can I change the name of the template from '_PartialTemplate' to 'PartialTemplate' without renaming my file?

Version:
`>handlebars -v`
`4.0.5`

Thanks

**Comment by nknapp** [comment]
The "--name" argument is only used if the template is passed via the "-i" option, so this should work for you: 

```bash
handlebars  --partial --name "PartialTemplate" -i - <_PartialTemplate.hbs
```
Can you try that?

**Comment by nknapp** [comment]
I'm closing this issue. Please feel free to add comments if you have more questionss.

**Comment by falahati** [comment]
Hi @nknapp,

I see, but why file name has priority? It would be great if you could make this argument more useful by allowing it to overwrite the file path.

Thanks

**Comment by nknapp** [comment]
I think the option was never intended to override filenames. It was a necessary option, because there is no other way to provide a partial-name when using the -i option. 

Am 26. Februar 2017 09:44:03 MEZ schrieb Soroush <notifications@github.com>:
>Hi @nknapp,
>
>I see, but why file name has priority? It would be great if you could
>make this argument more useful by allowing it to overwrite the file
>path.
>
>Thanks
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/wycats/handlebars.js/issues/1311#issuecomment-282541735

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
