### ISSUE TITLE
[Question] Access context of another template

### ISSUE THREAD

**Issue by MFlyer** [wycats/handlebars.js#1316]
Hi all,
after googling about this didn't find a solution/docu so, asking here:

I have one page loading 2 different templates, each template with its own context, let's call them 

```javascript
A = template ( {'some_varA' : 'some_valA'} );
B = template ( {'some_varB' : 'some_valB'} );
```

From B template I can get `{{some_varB}}`, but I'd like to know if i can get some_varA too without using ad hoc Helpers or Partials?

Thanks
Mirko

**Comment by nknapp** [comment]
If you want to access `some_varA`, you have to pass it to the template-function (i.e. mix it into the other object like 

```js
B = template ({
    'some_varB' : 'some_valB',
    'some_varA' : 'some_valA' 
} );
```

Is this not possible in your case?

**Comment by MFlyer** [comment]
Hi @nknapp ,
I know I can do this passing it to B template, but it was a dict with dynamic fields (some fields can be undefined too) so I was looking for the most elegant way to do this.
At the end I had it with hacking `Handlebars.registerPartial`, used to define some globas instead of subtemplating :)
Mirko
