### ISSUE TITLE
Lookup helper won't work with block parameters

### ISSUE THREAD

**Issue by kelvinss** [wycats/handlebars.js#1317]
```
{{#each names as |name id|}}
  {{name}} <br>
  {{lookup . 'name'}} <br>
{{/each}}
```
works for `{{name}}` but not for `{{lookup . 'name'}}`

[jsfiddle](https://jsfiddle.net/9D88g/91/)

I intend to use this with dinamic partials:
`{{> (lookup . 'name') }}`

**Comment by nknapp** [comment]
I can't say if this is supposed to work, since the block parameters are not part of this model. 
I think this needs to be specified (#1277, "We need a spec")

**Comment by nknapp** [comment]
Do you have to use "lookup" to solve your problem. I think you could just use `{{> (name)}}` like in https://jsfiddle.net/vva7musq/9/
