### ISSUE TITLE
Decorator arguments don't work with properties or helpers

### ISSUE THREAD

**Issue by kelvinss** [wycats/handlebars.js#1320]
Decorators seem to only accept literal arguments. If trying to pass property or sub expression they receive `undefined` or just fail, respectively.

```
{{myHelper myVar}}  // works
{{*myDec myVar}} // gives undefined
{{*myDec (lookup . myVar) }}  // crashes
```

[jsfiddle](https://jsfiddle.net/kelvinss/9D88g/94/) (better if developer console is open)

**Comment by mdelbuono** [comment]
I have the same problem.
With me it works as expected if the block contain only one inline decorator. With two it fails.
Did you find a solution?

**Comment by mdelbuono** [comment]
I found the problem: the decorator function is executed after `var fn = compile(template, options)` but before `var output = fn(context)`, therefore the context is not known when the decorator function runs.  
The decorator argument `options.args` refers to the parent block, therefore if you place your decorator inside a child block, it will work. See also [this question](http://stackoverflow.com/questions/38149025/handlebars-decorator-in-loop) on StackOverflow.  
Hope this helps.

**Comment by nknapp** [comment]
@kelvinss Please add a comment if this didn't work out.
