### ISSUE TITLE
Why not support "data['key']" or "array[0]" , bug only "data.key"？

### ISSUE THREAD

**Issue by win7killer** [wycats/handlebars.js#1322]
I have a case:
"var arr = [1,2,3]"

And I need use it like this:
{{arr[0]}}, but not need to loop it now.

then, I get an error in webpack.

------------------------
but "{{arr.0}}",  this can be worked, 
and how about this “arr['key-xx']” or “ key = 'k1',   data[key]”?

**Comment by nknapp** [comment]
If you want to loop over an array, you should use the {{#each}}-helper 
I have made a short example: https://jsfiddle.net/vva7musq/10/

**Comment by nknapp** [comment]
Sorry, didn't read well.

**Comment by nknapp** [comment]
Have a look here: http://handlebarsjs.com/expressions.html
The correct notation is `{{arr.[0]}}`. if you need to access `arr[i]` where i is also stored in your data,
you have to use a helper. 

I have setup an example at: https://jsfiddle.net/vva7musq/11/

**Comment by milahu** [comment]
> The correct notation is `{{arr.[0]}}`

ugly ...

`{{arr[0]}}` is supported by https://underscorejs.org/#template

```js
import Underscore from 'underscore'

Underscore.templateSettings = {
  interpolate: /\{\{(.+?)\}\}/g
};
const render = Underscore.template("Hello {{name[0]}}!");
const res = render({name: ["Mustache"]});
console.dir({res})
// { res: 'Hello Mustache!' }
```
