### ISSUE TITLE
[Question] Error handling in helpers/compilation

### ISSUE THREAD

**Issue by jarodsmk** [wycats/handlebars.js#1326]
Hey there,

I created a custom helper which uses an external library. 
It's a very simple helper, accepting a single (string) input, manipulates it with the external library and returns it. 

I encapsulate this in some error preventative code (similar to what's used in regular/non-block helpers in handlebars), checking if:
 the parameter is defined, and;
 typeof param === 'string', 
but only after previously having code to return a string, where if an error had been encountered, this default string is returned.

I'd output a log that the error had occurred, and then navigate through the templates that were generated to find my default string, and work around like that. 

**Questions**
- Is there any specific way that helper/compilation errors should be handled?
- What is the philosophy behind catching errors and reporting them with some more detailed information, such as template source file & line number?

Any feedback would be greatly appreciated! 😄

**Comment by jarodsmk** [comment]
The solution I have is to use the log helpers prior using my custom helpers and analyse the output of the template generation to identify the possible area of an issue.

**Comment by nknapp** [comment]
Since nobody else answered to this topic, I could add some ideas. I don't know of any best-practice or philosophy to handle such errors, and I'm not sure if you want to use this as a debugging tool or to handle errors in production, but:

* I think that the generated source-maps should allow you to trace the error back through the templates and to the helper, as long as a stack trace exist.
* I would try to catch known errors in the helper and handle them there
* You can also try to create a block helper like

```js
Handlebars.registerHelper('handleErrors', function (options) {
    try {
         return options.fn(this)
    } catch(e) {
        return 'something that handles the error'
    }
})

Handlebars.registerHelper('oops', function() {
  throw new Error('oops')
})
```

and than use it in your template in order to replace a larger part of the output if an error occurs.

```hbs
{{#handleErrors}}
Oops {{oops}}
{{/handleErrors}}
```

**Comment by nknapp** [comment]
Let me know if this helps you and please also add a comment if it didn't.

**Comment by jarodsmk** [comment]
Thanks for responding eventually @nknapp!

So what I ended up doing was something similar (using your example code):
```
Handlebars.registerHelper('doSomethingTemplatey', function (options) {
    try {
         return options.fn(this)
    } catch(e) {
        return 'HandlebarsError[doSomethingTemplatey]';
    }
});
```

**For templates that manage to render successfully:**
I then iterate through the generated/rendered template afterwards and **(a)** count how many issues there were, **(b)** list which specific helpers gave errors, and **(c)** on what specific lines of the newly rendered template they were thrown.

**For templates that don't render at all:**
I haven't got a solid solution yet to handle those errors since one of the primary functions of the system are to modify templates, but maybe I'll investigate this further with the code you provided above. Seems like a possible way to handle this instance.

Thanks again for your help!

**Comment by Mohsen-Bazmi** [comment]
> ```js
> Handlebars.registerHelper('handleErrors', function (options) {
>     try {
>          return options.fn(this)
>     } catch(e) {
>         return 'something that handles the error'
>     }
> })
> ```

It doesn't work for me.

**Comment by Mohsen-Bazmi** [comment]
Is there any way to intercept all errors?
