### ISSUE TITLE
access object property in handlebar contains '.'

### ISSUE THREAD

**Issue by isahuja** [wycats/handlebars.js#1329]
Before filing issues, please check the following points first:

- [ ] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [ ] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [ ] Use the jsfiddle-template at https://jsfiddle.net/9D88g/47/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

**Comment by isahuja** [comment]
up vote
0
down vote
favorite
I am getting data from service in which array of objects are coming like below:-

    [{
        title : 'Tilte 1',
        s.no : 1
     },
     {
        title : 'Tilte 2',
        s.no : 2   
     }
    ]
I have used handlebars templating to parse this data like below:-

{{#each this}}
   <div>
      <span>{{this.s.no}}</span>
      <h2>{{this.title}}</h2>
   </div>
{{/each}}
In the above I am not able to access the property('s.no'). In vanila javascript we can access it like this['s.no'] but in handlebars it's not working.

Thanks in advance

**Comment by nknapp** [comment]
`{{this.[s.no]}}` should work. Have a look a the http://handlebarsjs.com/expressions.html for the details.

https://jsfiddle.net/vva7musq/14/ for an example

**Comment by isahuja** [comment]
@nknapp Thanks, it's working.
