### ISSUE TITLE
Build fails, Running "test:cov" task failed: SyntaxError: missing ) after argument list in node_modules\.bin\istanbul:2 

### ISSUE THREAD

**Issue by m-ahmadi** [wycats/handlebars.js#1331]
I'm on windows.
I followed instructions in `CONTRIBUTING.md`.
I did both of the following, separately and both have failed. 
First I did:
```
git clone https://github.com/wycats/handlebars.js.git
git submodule update --init
npm install
grunt
```
then I did
```
git clone https://github.com/wycats/handlebars.js.git --recursive
npm install
grunt
```

After both of the above this happened:

```
E:\xampp\htdocs\handlebars.js\node_modules\.bin\istanbul:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
```

![hb](https://cloud.githubusercontent.com/assets/16363767/24839527/744d1f3e-1d71-11e7-9082-13518b0b5ff7.png)

It's weird because there is no `test:cov` in the `Gruntfile.js`

**Comment by nknapp** [comment]
Looks like Grunt is calling a bash-script for. In my checkout (on Linux) `node_modules/.bin/istanbul` is not a bash script, but a JavaScript file.

**Comment by nknapp** [comment]
Could you remove all your deps and re-run "npm install"?

**Comment by nknapp** [comment]
Please add a comment if this problem is not solved for you. I'd like to cleanup a little and close requests that are probably answered.

**Comment by m-ahmadi** [comment]
"remove the node_modules directory and re-run npm install"
I just did that and nothing changed, still the same error.

**Comment by nknapp** [comment]
Could you apply the change I have commited in 611d6d5 and then run "grunt" again? 

On Linux, all scripts in the "bin"-property of package.json are copied into the "node_modules"-directory. 
On Windows, a ".cmd"-file and as bash-script is created instead. "grunt" runs istanbul with the "child_process.fork()"-command, which does not work with bash-scripts. 
The commit directly uses the node-script instead.

**Comment by m-ahmadi** [comment]
"apply the change in commit: 611d6d5 and then run grunt"

```
Running "test:bin" task

Running "test:cov" task
Running env: ./runtime

460 passing (2s)
  26 pending
  2 failing
```

![untitled](https://cloud.githubusercontent.com/assets/16363767/26027376/4706d012-3822-11e7-834e-af581c253570.png)

**Comment by nknapp** [comment]
I think that the file `spec/artifacts/example_1.handlebars` contains CRLF line-endings in your checkout
I have updated the branch `issue-1331` to fix this with a .gitattributes-file. 
I could only make this workd, by removing the files (i.e. the files in `spec/artifacts`) and then do  `git reset --hard` to recreate the files.
 
The gitattributes-entry `*.handlebars text eol=lf` makes sure that the handlebars-files always have LF line-endings after checkout.

**Comment by m-ahmadi** [comment]
"remove the files in spec/artifacts and then do git reset --hard"

![image](https://cloud.githubusercontent.com/assets/16363767/26036315/9bd794f4-38f0-11e7-9f1d-ce2ab285c86f.png)

(I recloned and renpminstalled too, but still above err)

**Comment by nknapp** [comment]
This might be the last one... "*.hbs" files are also used as fixtures in the test and must have LF line-endings

**Comment by nknapp** [comment]
I have only commited to the 4.x-branch now. Please try that one

**Comment by m-ahmadi** [comment]
![1](https://cloud.githubusercontent.com/assets/16363767/26060292/d1c9cac4-3999-11e7-939e-7b23f8902ad4.png)

(same err in master and 4.x )

**Comment by nknapp** [comment]
mhm

**Comment by nknapp** [comment]
I'll continue this in a separate branch. It doesn't make sense to merge to 4.x and master all the time without being sure that it works.

**Comment by nknapp** [comment]
There is now an appveyor-build (which runs on Windows machines) and successfully running all tests. I assume this issue can be closed. If you think that's not the case, please add a comment and I'll reopen.
