### ISSUE TITLE
How to pass values from handlebars view to Javascript function

### ISSUE THREAD

**Issue by GaikwadPratik** [wycats/handlebars.js#1333]
Hi,

I am loading a view. During page load of that view, I am trying to pass variable to a javascript function as below 

```
<div id="personal_info" 
     name="PersonalInfo" 
     class="personal_info_form step_1 hide" 
     next="contact_info" 
     prev=""
     data-load-function="PersonalProfile.LoadInit({{UserDetails}},{{BirthAddressDetails}});"
>
```

The html generated is 

```
<div id="personal_info" 
     name="PersonalInfo" 
     class="personal_info_form step_1 show current_step" 
     next="contact_info" 
     prev="" 
     data-load-function="PersonalProfile.LoadInit([object Object],[object Object]);"
>
```

And in `LoadInit` function I am getting as `[object Object],[object Object]` in the `UserDetails` while `BirthAddressDetails` is undefined.

On the same page however, I am extracting first name from `UserDetails` as `<label>{{UserDetails.FirstName}}</label>` where the value of  `FirstName` is correctly bound to label.

How do I pass values of `UserDetails` and `BirthAddressDetails` to javascript?

**Comment by nknapp** [comment]
Hi, I have reformatted you comment a little, so that I could better read it.
You could try a `json`-helper as in #1337.

**Comment by acmoune** [comment]
What if the object you want to pass is created with `new User(...) `? `JSON.stringify()` will lost all code from the User class/prototype, and leave you with a plain object. How to pass an Object as is ?
