### ISSUE TITLE
Should the AMD module have a name?

### ISSUE THREAD

**Issue by jcoyne** [wycats/handlebars.js#1335]
When I use Almond.js (AMD module loader) I'm unable to load handlebars because the module does not have a name. I get this error: `Error: See almond README: incorrect module build, no module name`

This error is caused by line 31 of http://builds.handlebarsjs.com.s3.amazonaws.com/handlebars-v4.0.5.js

```javascript
		define([], factory);
```

Almond.js says modules ought to have a name:
https://github.com/requirejs/almond#incorrect-module-build-no-module-name

Is there a change to be made to handlebars or is using almond.js with handlebars hopeless?

When I change line 31 to this then it works fine:

```javascript
		define('handlebars', [], factory);
```

**Comment by nknapp** [comment]
Would this be a breaking change? What is the exact difference in the behavior of RequireJS, between a module with and without name?
Or in other words: If someone uses Handlebars with RequireJS now, would she have to change anything if handlebars suddenly has a module-name?

I am not sure about that. If this is no problem and everything is fully backwards-compatible, I would accept a merge-request for the 4.x-branch and add it to 4.0.7.

But I don't know how long it will take to get it published (see #1312 for details)

**Comment by jcoyne** [comment]
@nknapp I consider myself a n00b when it comes to the various module systems.  I don't *think* it would affect anything, but I certainly defer to someone with expertise.

**Comment by nknapp** [comment]
I found [this post as StackOverflow](http://stackoverflow.com/questions/19720646/named-module-vs-unnamed-module-in-requirejs), which points to [this part of the RequireJS-documentation](http://requirejs.org/docs/api.html#modulename): 

>  It is normally best to avoid coding in a name for the module and just let the optimization tool burn in the module names.

And I just saw that Almond is described (on its GitHub-page) as 'A minimal AMD API implementation for use after optimized builds'. So you should probably run an optimizer let it create the module name and then use Almond to load the module.

**Comment by jcoyne** [comment]
Isn't the distributed version (on s3) already an optimized build?

**Comment by nknapp** [comment]
I think by "optimized version" they means that you bundle all your dependencies into a single (or few) minimized files. It means that multiple libraries are in one file that can then be loaded with almond.

**Comment by jcoyne** [comment]
But there's no way to get to that using the s3 build.  So as I understand it our s3 build is completely useless for AMD.  You have to pull the source and build yourself?
