### ISSUE TITLE
Access handlebars passed argument from Javascript

### ISSUE THREAD

**Issue by vlos** [wycats/handlebars.js#1337]
I have a handlebars template, which when I call request.render('hbrspage', {...}) I pass in an object which hbrs uses to render it's variables.

What I would like to do is access that object inside javascript within a function in the browser.

now I can declare a variable within script tags and then access that variable, but wondering if unitList is available in the browser somehow?
`
var unitList [
        {{#each  unitList}}
        "{{this}}",
        {{/each}}
];`

So do I have to declare the local script variable like above or is there a way to access the passed object?
`
function checkObject() {
   for (var cnt=0; cnt < unitList.length; cnt++) {
       --access unitList[0]---
   }
}
`

I'm assuming no, but figured I would check.

**Comment by nknapp** [comment]
I don't think this question is directly related to Handlebars, but to the framework you are using. 
You might be able to solve your problem by creating a helper

```js
Handlebars.registerHelper('json',function(obj) {
   return new Handlebars.SafeString(JSON.stringify(obj))
})

and than call the helper in your template

```handlebars
<script>
   window.json = {{json unitlist}}
</script>
```

But I cannot say if this is already done by your framework. You should ask the question to the maintainers of that project.
