### ISSUE TITLE
User's return null on option tag

### ISSUE THREAD

**Issue by berat703** [wycats/handlebars.js#1338]
I'm trying list my data to select's options.I'm using handlebars backbone jquery requireJS.

userselectlist.js

```js
var users = new UserCollection();
var SelectUserList = Backbone.View.extend({
    model: User,
    el:'.page',
    render:function(users)  {
        var template = Handlebars.compile(SelectUserListTemplate);
        var html = template({users:users.toJSON()});
        console.log(users);//This line
       $("#userSelect").html(html);
    }
});

return {
    users:users,
    SelectUserList:SelectUserList
};
```

my select-user-list.html

```handlebars
 <option value="">Kullanıcı Seçiniz</option>
{{#each users}}
<option value='{{userID}}'>{{firstName}}</option>
{{/each}}
```

index.html

```html
<div class="page">
            <div class="form-group">
                <select class="form-control" id="userSelect"></select>
            </div>
```

router.js

```js
user:function(){
  $('body').after(spinner.spin().el);
        var users = new Users();
        var userSelect = new UserSelectList.SelectUserList();
        users.fetch({

            contentType: "application/json",
            cache: false,
            success: function (m_users) {
                m_users.each(function (m_model) {
                    spinner.stop();
                    var userList = new UserSelectList.SelectUserList();
                    UserSelectList.users = new Users();
                    userList.render(m_model);
                });
            }
```

My problem is user's printing with console.log .But select tag has a null option line.If you don't understand(sorry of my english) , you can look this ScreenShot

[http://pasteboard.co/6knbWGzMi.png](ScreenShot)

**Comment by Crowes** [comment]
What is ``{users:users.toJSON()}``? Shouldn't it be ``users.users.toJSON()`` or ``JSON.parse(users.users)``?

**Comment by nknapp** [comment]
@berat703 Please add a comment if you issue is still open. It seems to me that it is answered, so I'm closing it now.

**Comment by nknapp** [comment]
Thanks for anwering @Crowes, It's nice to see that I am not alone here...

**Comment by nknapp** [comment]
Thanks for answering @Crowes. I have decided to act as a Collaborator here, because there seems to be a lack of them and I like the project. But it is nice to see that there are other people helping out as well.
