### ISSUE TITLE
4.0.8 breaks registering helpers

### ISSUE THREAD

**Issue by adamreisnz** [wycats/handlebars.js#1347]
As mentioned in the other issue (#1249), after updating from 4.0.6 to 4.0.8, my registered helpers can no longer be found:

```
Error: Missing helper: "moment"
    at Object.<anonymous> (node_modules/handlebars/dist/cjs/handlebars/helpers/helper-missing.js:19:13)
    at Object.eval [as main] (eval at createFunctionContext (node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:254:23), <anonymous>:12:70)
    at main (node_modules/handlebars/dist/cjs/handlebars/runtime.js:173:32)
    at ret (node_modules/handlebars/dist/cjs/handlebars/runtime.js:176:12)
    at ret (node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:525:21)
```

Reverting back to 4.0.6 fixes the problem. Not sure what is going wrong there, but I presume that a patch release shouldn't introduce breaking changes to the API of loading helpers.

My code to load them is straightforward:

```js
'use strict';

/**
 * Dependencies
 */
const fs = require('fs');
const path = require('path');
const handlebars = require('handlebars');

/**
 * Settings
 */
const PATH_HELPERS = path.resolve('./app/helpers/transform/');

/**
 * Register handlebars helpers
 */
fs.readdirSync(PATH_HELPERS)
  .forEach(file => {
    const ext = path.extname(file);
    const name = path.basename(file, ext);
    const helperPath = path.join(PATH_HELPERS, file);
    const helper = require(helperPath);
    handlebars.registerHelper(name, helper);
  });
```

And the files in the helpers path just export functions.
With 4.0.6 and previous this works like a charm, but with 4.0.8 it breaks and throws the above error. 

It's good I found it while testing the other issue, so I can fix the handlebars version in place, or all of our emails would have been inexplicably broken... :(

**Comment by nknapp** [comment]
Well, all the old tests are still passing and there are a lot of tests the load helpers... There should not be any breaking changes in the API. I'll try to reproduce this.

**Comment by nknapp** [comment]
I've created this repo https://github.com/nknapp/handlebars-issue-1347 and it seems to work. Could you try to break it?

**Comment by adamreisnz** [comment]
I'll give it a try

**Comment by adamreisnz** [comment]
@nknapp Ok it must have been a fluke with Yarn messing up some dependencies. 

I played around with it on two different machines, and managed to reproduce the issue in my own code base, but after removing the yarn lock file and recreating it, the problem went away as it changed the entry for handlebars. For some reason it was also including handlebars 4.0.3 as a separate entry in the lock file, and after removing and remaking, it was combined in a single entry.

Not sure how that would cause the missing helper error, but it did. The problem did not expect in the example repo with either 4.0.3 or 4.0.8.

Will close this now, but I'll keep an eye on it in case it pops up again.

**Comment by nknapp** [comment]
Ok, I'm glad to hear that. I wouldn't have liked to introduce a severe problem like that.
