### ISSUE TITLE
Can I access object with a variable as key?

### ISSUE THREAD

**Issue by aleen42** [wycats/handlebars.js#1350]
I have a object named `obj`:

```js
var obj = {
   case: 'test' 
};
```

And also with a variable named `name` with a value `case`.

And can I access this object with `#with` statement like the following snippet?

```html
{{#with obj}}
    {{this.[{{../name}}]}}
{{/with}}
```

Or

```html
{{#with obj}}
    {{this.[../name]}}
{{/with}}
```

I just want to use variables as keys in the bracket.

**Comment by atomictag** [comment]
perhaps `{{lookup obj name}}` ? Check out [the lookup helper](http://handlebarsjs.com/builtin_helpers.html) as it might be what you're after.

**Comment by aleen42** [comment]
@atomictag okay, because I have used an old version of Handlebars, I just register another similar method named `get`. Thanks a lot.
