### ISSUE TITLE
Packaging Handlebars with Webpack.

### ISSUE THREAD

**Issue by iiison** [wycats/handlebars.js#1351]
Hi, I am using Handlebars as template engine in my application and using Webpack to bundle stuff. I am loading templates dynamically(by using `system.import`) and the issue is the template as small as `<div>hello world</div>` is sizing around 13kb with Webpack optimization flag on(in dev build it sizes around 30kb). I am sure there is a way to fix this. Here is few links:

[Webpack configurations](https://github.com/iiison/Flash/blob/master/webpack.config.babel.js)
[Package.json file](https://github.com/iiison/Flash/blob/master/package.json)
[Link to repo](https://github.com/iiison/Flash)

Please let me know if you need anything else.

**Comment by nknapp** [comment]
When I call just ` bin/handlebars -m -f test.js test.hbs` with `test.hbs` being your template, I get 199 bytes of output. 

```
!function(){var e=Handlebars.template;(Handlebars.templates=Handlebars.templates||{})["test.hbs"]=e({compiler:[7,">= 4.0.0"],main:function(e,a,t,l,n){return"div>hello world</div>\n"},useData:!0})}();
```

I wonder what Webpack adds to it so that you have 13kb. Maybe the Handlebars-runtime is included in that size as well.

I'm pretty sure this is more an issue for the `handlebars-loader` than for `handlebars` itself.

**Comment by iiison** [comment]
Yes, I figured out that Handlebars-runtime is being included in every template. Is there any solution to this issue..

**Comment by nknapp** [comment]
Then it is an issue with handlebars-loader. You're likelihood of getting an answer is higher if you ask there. Personally, I have never used the handlebars-loader. I would have to do the same research that you did already.

Would be great though if you could post or link here if you have an answer, for other people with the same problem.

Am 21. Mai 2017 10:24:02 MESZ schrieb Bharat Soni <notifications@github.com>:
>Yes, I figured out that Handlebars-runtime is being included in every
>template. Is there any solution to this issue..

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
