### ISSUE TITLE
Is there anyway to check condition with a variable?

### ISSUE THREAD

**Issue by ocvninfo** [wycats/handlebars.js#1352]
I have a categories array:
```
"categories": [
    {
      "id": "22",
      "name": "Brands",
      "url": "/brand/"
    },
    {
      "id": "1",
      "name": "Women",
      "url": "/women/"
      }
}
```
And i have a setting variable:
`"category_id": "1"`

**in HTML:**
```
{{#each categories}}
     {{#if id '==' '1'}}
          <a href="{{url}}">{{name}}</a>
     {{/if}}
{{/each}}
```
**OUTPUT:**
`<a href="/women/">Women</a>`
**==> This is correctly output.**

**BUT WHEN I USING category_id VARIABLE:**
```
{{#each categories}}
     {{#if id '==' category_id}}
          <a href="{{url}}">{{name}}</a>
     {{/if}}
{{/each}}
```
==> It's not working. :((

So my question is: **Is there anyway to check condition with a variable?**

**Comment by nknapp** [comment]
The `{{#if}}`-helper only checks for truthy values and it takes only one argument. If you want to compare things, you need to register your own helper: Have a look at #206 for examples on how to achieve this.
