### ISSUE TITLE
Problem with passport-steam and handlebars

### ISSUE THREAD

**Issue by vladgal** [wycats/handlebars.js#1358]
This is the error I trying to display user name
`Error: Parse error on line 36: ... <img src='{{user.photos[2].value}}' a -----------------------^ Expecting 'ID', got 'INVALID' at Parser.parseError (C:\Users\VladG\Desktop\Tutorials\Express Web\CSGOGamble\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:267:1 9) at Parser.parse (C:\Users\VladG\Desktop\Tutorials\Express Web\CSGOGamble\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:336:30) at HandlebarsEnvironment.parse (C:\Users\VladG\Desktop\Tutorials\Express Web\CSGOGamble\node_modules\handlebars\dist\cjs\handlebars\compiler\base. js:46:43) at compileInput (C:\Users\VladG\Desktop\Tutorials\Express Web\CSGOGamble\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:514:19) at ret (C:\Users\VladG\Desktop\Tutorials\Express Web\CSGOGamble\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:523:18) at ExpressHandlebars._renderTemplate (C:\Users\VladG\Desktop\Tutorials\Express Web\CSGOGamble\node_modules\express-handlebars\lib\express-handleba rs.js:247:12) at ExpressHandlebars.<anonymous> (C:\Users\VladG\Desktop\Tutorials\Express Web\CSGOGamble\node_modules\express-handlebars\lib\express-handlebars.j s:173:21)`

Code:

`<img src='{{user.photos[2].value}}' alt="Avatar Image" /> <span>{{user.displayName}}</span>`

**Comment by nknapp** [comment]
Try with a dot after "photos".

```hbs
<img src='{{user.photos.[2].value}}' alt="Avatar Image" /> <span>{{user.displayName}}</span>
```

**Comment by vladgal** [comment]
Thanks its works but weird that at ejs they didnt put a . dot  :D
