### ISSUE TITLE
Does not supporting XMl handlebar

### ISSUE THREAD

**Issue by gauravbhusare** [wycats/handlebars.js#1359]
I am trying to compile XML handlebars. My code is as follows,

           fs.readFile(appRoot+'/src/services/templates/'+tallyTemplate+'.handlebars',function(error,source){
                if(error){
                  console.log(error)
                }
                else{
                  if(source){
                    var template = OriginalHandlebars.compile(source);
                    var tallyPayload = template(msg);
                    postDataToTally(msg,tallyPayload);
                  }else {
                    console.log('Template missing ' + tallyTemplate );
                  }
                }
              });
My handlebar is,
     
[receipt_add.txt](https://github.com/wycats/handlebars.js/files/1077336/receipt_add.txt)

in this case i am getting xml template but handlebar compiler is throwing following error,
`D:\Project Work\ASAP Node-6\Tally_Manager_Feathers\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:501
    throw new _exception2['default']('You must pass a string or Handlebars AST to Handlebars.compile. You passed ' + input);
    ^
Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed **My Template get printed here**`

**Comment by nknapp** [comment]
When you call `fs.readFile` without options, "source" will be a Buffer and not a string. Try

```js
fs.readFile(file, 'utf-8', function (err, source) {...})
```

That should work fine

**Comment by gauravbhusare** [comment]
@nknapp yes you catch it. It is the issue of buffer.
