### ISSUE TITLE
Nested {{each}} loops: @key is displaying the key index rather than the key name

### ISSUE THREAD

**Issue by petersobczak** [wycats/handlebars.js#1364]
In nested {{each}} loops the @key is displaying the key index but should be displaying the key name instead.  See http://jsfiddle.net/petersobczak/p9m3be3j/ for reference.  This works correctly in versions 2.0.0 and lower but appears to be broken in version 3.0.0 and higher.

**Comment by nknapp** [comment]
The `@key` always refers to the current (innermost) loop and when you iterate over an array, the `@key` is the index. The behavior is correct as it is, but you could use the following syntax: 

```hbs
{{#each users as |user userId|}}
  {{#each user.book as |book bookId|}}
    User Id: {{userId}} Book Id: {{bookId}}
  {{/each}}
{{/each}}
```
(see http://handlebarsjs.com/block_helpers.html)

**Comment by petersobczak** [comment]
Thanks for the reply and clarifying the functionality. I was using the "#each this"  syntax as I don't know the name of each of the data items (as in the sample below). Can I still use the syntax you mentioned above to iterate the sample data set and get outermost value in the inner loop? (I tried but was unsuccessful).  Thanks again!

```
var data =  {
      'Bourbons': ['Bulleit', 'Four Roses', 'Woodford Reserve'],
      'Ryes': ['WhistlePig', 'High West']
    };
```

**Comment by nknapp** [comment]
http://jsfiddle.net/p9m3be3j/1/

**Comment by petersobczak** [comment]
Awesome!!! Thank you!
