### ISSUE TITLE
Unwanted newline char

### ISSUE THREAD

**Issue by claudepanam** [wycats/handlebars.js#1365]
Hi,

Not sure what option I've missed... Can't figure out how to get rid of the extra char added in between "1" & "2"

TY

fiddle = https://jsfiddle.net/d3mzL0x1/

![hb1](https://user-images.githubusercontent.com/30242652/28283371-de976b74-6b2d-11e7-8f32-7da715ec146d.PNG)
![hd2](https://user-images.githubusercontent.com/30242652/28283372-de97dc4e-6b2d-11e7-8a7e-ca70052cad17.PNG)
![hb3](https://user-images.githubusercontent.com/30242652/28283373-deaa1c60-6b2d-11e7-81bd-30bebc03a777.PNG)

Edit: I have a workaround = I replace tabs and newline before compiliing... replace(/[\t\n\r]/gm,'') But would rather use the right option

**Comment by nknapp** [comment]
You might want to have a look at [whitespace-control](http://handlebarsjs.com/expressions.html#whitespace-control). 

You could do [this](https://jsfiddle.net/d3mzL0x1/2/). But personally I think this is counter-intuitive, so this is **not** a suggestion to do it.

I you probably put it into the same line or use CSS to remove the gap.

**Comment by claudepanam** [comment]
TY for your answer.

Already checked whitesapce-control which helps me fixing extra chars in loops...

I was wondering if I was doing things the right way which seems to be the case.

Won't use your unassigned property trick nor the css (not even sure I can remove a character using css)...
Same line is fine with 2 items... But I have more ;)

Will keep my workaround: removing tabs & newlines before compilation and/or use a {{~#each _Object~}}{{~/each~}} with a little context for my "static links"

**Comment by nknapp** [comment]
I thought there was a good way, but there seems not to be. I found this: https://davidwalsh.name/remove-whitespace-inline-block which may include some helpful hacks, but there does not seem to be a pretty solution...
