### ISSUE TITLE
How to get list item in Handlebars each ?

### ISSUE THREAD

**Issue by liuyuqiang** [wycats/handlebars.js#1367]
{{#each channels}}
<a href="{{func_name "1"  ___this object item___ "" "2"}}">link</a>
{{/each}}

**Comment by stevenvachon** [comment]
```handlebars
{{#each channels as |channel|}}
  {{func_name "1" channel "" "2"}}
{{/each}}
```

http://handlebarsjs.com/block_helpers.html#block-params

**Comment by liuyuqiang** [comment]
It's work . thanks
