### ISSUE TITLE
Parse error when you accidentally use commas to delimit helper arguments is confusing

### ISSUE THREAD

**Issue by barbeque** [wycats/handlebars.js#1373]
Example code: https://jsfiddle.net/9D88g/157/

In the example code, if you write `{{reverse toReverse, otherToReverse}}` instead of `{{reverse toReverse otherToReverse}}` the resulting parser error is not clear what the problem is.

![image](https://user-images.githubusercontent.com/423811/29387264-744376ba-829c-11e7-95fd-374a38216b8d.png)

The arrow points to the head of the parse block (probably because that's where the parser fails to recognize the top-level helper-call rule) but the parse actually failed because it cannot identify `toReverse,` with the comma as an identifier.

Since the parser appears to be generated from a lex-like tool it might take a bit of effort to identify this specific error and return something like "`toReverse,` is not a valid identifier."

The comma could also be made optional (and just ignored), though I don't know what that else that might affect.

I would imagine this is a pretty common mistake to make even after you know about Handlebars, because most people are probably still in the mental mode of programming JavaScript.

I'm not sure if your mention of "alternative delimiters" in the readme describes this case, but it would be nice to have a more obvious error about it if possible.

**Comment by nknapp** [comment]
I was a bit confused with this, but I just noticed that the arrow actually points to the `toReverse` and not to `reverse`. There is a tab-character at the beginning of the template. It takes up more space, than the corrsponding "minus"-character of the arrow. 

It looks like the arrow points to the first keyword, but it's not.
