### ISSUE TITLE
[QUESTION] How to have multiple partials with same defining name.

### ISSUE THREAD

**Issue by gkumar77** [wycats/handlebars.js#1383]
Hello, First i would like to appreciate for creating such a elegant and efficient templating engine. Thank you.

Well, 
my question is for using partial in handlebar because according to my requirement i need a function or some sort of solution for having same defining partial name i.e (Header or Footer) and it might change its address.
i.e 
```
Handlebars.registerPartial('Header', fs.readFileSync('/home/software/workspace/Headers/header1.html').toString());
Handlebars.registerPartial('Footer', fs.readFileSync('/home/software/workspace/Footers/footer1.html').toString());
Handlebars.registerPartial('Footer', fs.readFileSync('/home/software/workspace/Footers/footer2.html').toString());
Handlebars.registerPartial('Header', fs.readFileSync('/home/software/workspace/Headers/header2.html').toString());

```
whereas my layout file will be as such:
```
{{> Header}}

{{{ contents }}}

{{> Footer}}
```

I have a UI for header and footer selection according to user need.
But the scenario will get stuck  if for same layout different requirement of header and footer is needed.
Also, i cant create every possible combination of header and footer with a single layout and feed it according . That would be waste of studying CSE in Bachelors. 

P.S 
i am using handlebar with [metalsmith](http://www.metalsmith.io/) which is a static site generator.
This would be my metalsmith.js file executed with ```node metalsmith.js```

```
var Metalsmith=require('metalsmith');
var markdown=require('metalsmith-markdown');
var layouts=require('metalsmith-layouts');
var permalinks=require('metalsmith-permalinks');
var fs=require('fs');
var Handlebars=require('handlebars');
Handlebars.registerPartial('Header', fs.readFileSync('/home/software/workspace/Headers/header1.html').toString());
Handlebars.registerPartial('Footer', fs.readFileSync('/home/software/workspace/Footers/footer1.html').toString());
Handlebars.registerPartial('Footer', fs.readFileSync('/home/software/workspace/Footers/footer2.html').toString());
Handlebars.registerPartial('Header', fs.readFileSync('/home/software/workspace/Headers/header2.html').toString());
 Metalsmith(__dirname)
.metadata({title:'',description:''})
.source('/home/software/workspace/FlowzServiceApi/websites/newDemo/Pages')
.destination('/home/software/workspace/FlowzServiceApi/websites/newDemo/MetalsmithOutput')
.clean(false)
.use(markdown())
.use(permalinks())
.use(layouts({engine:'handlebars',directory:'/home/software/workspace/FlowzServiceApi/websites/newDemo/Layouts'}))
.build(function(err,files)
{if(err){
console.log(err)
}});
```

**Comment by nknapp** [comment]
I don't understand the requirements. At some point before rendering the page, you'll have to decide whether to use header1 or header2. Then you call registerPartial.

I don't understand what Handlebars should do with multiple partials of the same name.

**Comment by gkumar77** [comment]
@nknapp yeah you are right that at some point i will decide the header1 or header2 but my prob. is what if he decide header1 for page1 and header2 for page2.
Then, i get fucked because as you can see that its Just 'Header' in layout for all pages. 
Hence metalsmith wont know and will set the later chosen header and set it in all the pages and i loose the dynamic header selection component.

I just request to have a function which will help.
I am thinking that in my layout file i.e a if else kinda a scenario.  

P.S 
i know its a chaos understanding this situation and i respect your effort to even try to understand it.

**Comment by nknapp** [comment]
Maybe you can use inline partials to replace the Header- and Footer-Partials within the context of your page:

https://jsfiddle.net/9D88g/177/
