### ISSUE TITLE
Is it possible to output processed and unprocessed blocks with a helper?

### ISSUE THREAD

**Issue by CGTS** [wycats/handlebars.js#1385]
I'm trying to create a helper that renders the html for a partial block and generates a code example of that partial. 

for example this:

    <div class="wrapper">
      {{> first}}
      {{> second}}
    </div>

would produce this:

    html:
    ----------
    <div class="wrapper">
      <div>first</div>
      <div>second</div>
    </div>
    ----------
    example:
    ----------
    <div class="wrapper">
      {{> first}}
      {{> second}}
    </div>

I can use a `{{{{raw}}}}` block helper or `\{{{escape}}}}`, this works for the example but not the html. Is there a way to output both without needing to repeat myself in the code like:

    <div class="wrapper">
      {{> first}}
      {{> second}}
    </div>

    {{{{raw-helper}}}}
      <div class="wrapper">
        {{> first}}
        {{> second}}
      </div>
    {{{{/raw-helper}}}}

Is this possible?

**Comment by nknapp** [comment]
You could try to use a raw-helper and call `var block = Handlebars.compile(options.fn()); block(this);` within the helper. The Handlebars instance somehow (because of the registered partials).

Does this help?

**Comment by CGTS** [comment]
I tried the solution and it returned ` Error: The partial this could not be found`. 

I removee `block(this);` and it ran, but it printed `function ret(context, execOptions) { if (!compiled) { compiled = compileInput(); } return compiled.call(this, context, execOptions); }` on the page instead. 

I'm pretty new to this so I'm sure it's something on my end. Any ideas about what's going on?

**Comment by CGTS** [comment]
This appears to be a conflict with Panini. I'll close this for now.

**Comment by nknapp** [comment]
Here is a more complete example: https://jsfiddle.net/9D88g/164/

**Comment by CGTS** [comment]
Thanks for the example, this did it! I had been handling all the conversions in in variables. As soon as I moved it directly to the return it worked.
