### ISSUE TITLE
Q: why differentiating partials from templates?

### ISSUE THREAD

**Issue by dwelle** [wycats/handlebars.js#1389]
We've been using handlebars for quite some time and this question comes to mind from time to time.

What's the benefit of having to define a template as a partial when you need it to be "nestable" in other templates? Why not every template be a partial?

I imagine there's some small perf benefit, but is it worth the added complexity?

In our codebase, around 2/3 of hbs templates are partials.. and it only adds to cognitive fatigue having to register a template to make it a partial when one wants to nest it (mind you, we have a build process so one only needs to change `name="template"` to `name="partial"`, but this requirement really feels arbitrary).

**Comment by doowb** [comment]
I don't think there is a technical difference. Partials are named templates that can be accessed inside other templates using the partial syntax: `{{> partial }}`.

You can just as easily, register all of your templates as partials and get one of them to render later:

```js
handlebars.registerPartial('partial', '{{title}}');
handlebars.registerPartial('home', 'home page: {{> partial }}');

var home = handlebars.partials.home;
if (typeof home !== 'function') {
  home = handlebars.compile(home);
}
console.log(home({title: 'Home'}));
```

**Comment by dwelle** [comment]
That's my point. I assume there must be some non-trivial perf difference in using partials vs templates, else I see no reason why handlebars differentiates between partials/templates at all.

**Comment by nknapp** [comment]
Are you using plain Handlebars or some wrapper like express-hbs or a static site generator like metalsmith or assemble?

In plain Handlebars, there is no (plural) "templates". There is only one template, the contents of which you pass to the "compile" function and for which a function will be returned.

The template is the entry point. You can also register the template as partial and use the template"{{> mytemplate}}"

**Comment by dwelle** [comment]
Yes. My question was why is there a differentiation between a template and partial.

**Comment by nknapp** [comment]
How else could it be? What would you expect?

**Comment by dwelle** [comment]
Every template being a partial by default, which can be done even now. Just register all your templates as partials. Boom. Nothing happens, but you can use any template as a partial as a side effect.

**Comment by nknapp** [comment]
I mean. You *cannot* register a template. You can only compile it.

**Comment by dwelle** [comment]
I'm sorry, maybe my nomenclature is wrong and I'm not aware of it.

If you want to use a template inside another template, you first need to register it as a partial (via `Handlebars.registerPartial()`).

What am I missing?

**Comment by nknapp** [comment]
Yes. And if you don't want to use it as partial, you don't. Sure, you can register all your templates as partials if you like. But "every template being a partial by default" is not possible, because a partial needs a name and a template does not have one.

I believe there is a misunderstanding because many frameworks that use Handlebars have the notion of a template directory, a directory for layouts and a directory for partials. When you use such a framework, your template will have a filename and it could make sense to register it as partial by default.

The Handlebars library itself does not have that notion. It does not work with files at all. A template is a string like `{{#each person}}{{name}}...{{/person}}` that you pass to the `.compile`-function. How would you register that as a partial by default?

**Comment by dwelle** [comment]
Man... you're right. I was talking nonsense from the beginning. Years of working with hbs templates as files have completely warped my mental model of how handlebars works. Thanks for bearing with me and (re)opening my eyes to the light!

**Comment by dwelle** [comment]
Further, actually checking source code of `registerPartial` (which I should have done ITFP) reveals there is indeed no magic going on, so registering all (named) templates as partials seems fine (perf-wise).
