### ISSUE TITLE
`uglify-js` is unconditionally imported, but only listed as optional dependency

### ISSUE THREAD

**Issue by Turbo87** [wycats/handlebars.js#1391]
This is causing https://github.com/ember-cli/ember-cli/issues/7371, where people are using `npm` to install `handlebars` as a transitive dependency but apparently `npm` is not installing the optional `uglify-js` dependency (anymore?) which makes the import fail.

**Comment by kellyselden** [comment]
This would need to be a 4.x fix right?

**Comment by Turbo87** [comment]
either that or we update the dependency in https://github.com/ember-cli/broccoli-middleware/blob/master/package.json#L22. not sure if that's possible though 🤔

**Comment by nknapp** [comment]
I can do the release if anyone creates a PR. And yes, it should be a PR for the 4.x branch. I'll merge into master afterwards.

What about 3.x?

**Comment by nknapp** [comment]
Released in 4.0.11

**Comment by Turbo87** [comment]
awesome, thanks :)

**Comment by Turbo87** [comment]
> What about 3.x?

I think our issue was only with 4.x. Since 5.x seems to be the current release I think we're probably fine without another 3.x release.

**Comment by nknapp** [comment]
The current release is 4.x. There has not been any 5.x release yet
If nobody needs a new 3.x release, I'll save my time for other stuff.

**Comment by Turbo87** [comment]
🤔 

thought I had seen 5.x somewhere... nevermind, sorry about the noise :D

**Comment by nknapp** [comment]
I bumped the master branch to 5.0-alpha. But there is no release at the moment and I'm only doing bugfixes
