### ISSUE TITLE
Can't load template from sibling folder

### ISSUE THREAD

**Issue by lukasoppermann** [wycats/handlebars.js#1397]
Hey,

I have the following folder setup

- templates
  - partials
  - portfolio

I would now like to include a handlebars template from **portfolio** into a template from **partials**, however it does not work.

I tried many variations of:

    {{>"../portfolio/item"}}

Is there a way to do this and if so, how? Thank you.

**Comment by nknapp** [comment]
The handlebars-library does not have the notion of directories and files. If you want to use a partial, you have to call `Handlebars.registerPartila('partialName', 'Contents of the partial')`. Then you can use

```hbs
{{> partialName}}
```
in your template. Or, if you are using a framework like Assemble, Metalsmith or Bootprint, you have to see how they map filenames to partial-names.

**Comment by lukasoppermann** [comment]
Thank you, I will look into it. 👍
