### ISSUE TITLE
Can't escape curly brackets

### ISSUE THREAD

**Issue by danbopes** [wycats/handlebars.js#1404]
I'm trying to get the following output (`bar` will be replaced with a variable via handlebars.):

```${bartest}``` 

See code sandbox [here](https://codesandbox.io/s/jp5q4pyjx5).

Compiling the template with `template({foo: 'bar'})`, I have tried the following:

```$\\{{{foo}}test}``` results in `${{{foo}}test}`
```${{{foo}}test}``` results in compile error (Expecting 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'CLOSE')

How does one replace `foo` with `bar`?

**Comment by nknapp** [comment]
You can use whitespace control: `${ {{~foo~}} test}`

**Comment by FDiskas** [comment]
```
$\{{{foo}}test}
```
will result:
```
{{{foo}}test}
```

**Comment by piranna** [comment]
> You can use whitespace control: `${ {{~foo~}} test}` (http://handlebarsjs.com/expressions.html#whitespace-control)

404 error, new link is https://handlebarsjs.com/guide/expressions.html#whitespace-control

**Comment by rauschma** [comment]
I just had a similar issue and fixed it like this (as suggested here):

```tex
\setmainfont{ {{~mainfont~}} }[]
```

I wonder if it would make sense to change the backslash so that it only escapes one following brace – then this would work:

```tex
\setmainfont\{{{mainfont}}}[]
```

Currently, the output is:

```tex
\setmainfont{{{mainfont}}}[]
```

That is: No substitution takes place – the backslash escapes three braces.

**Comment by rauschma** [comment]
Good point. Backward compatibility is crucial and trumps many things.
