### ISSUE TITLE
Html not shown as html, is plain text

### ISSUE THREAD

**Issue by ningacoding** [wycats/handlebars.js#1405]
```
const htmlTemplate = Handlebars.compile("some template {{body}}");
const htmlBody = Handlebars.compile("<a href=\"{{url}}\">a link</a>");

const output = htmlTemplate({
body: htmlBody({
url: "some url"
})
});
```

this outputs is a plain text:

`some template <a href="some url">a link</a>`

(link is not a link, is just text with html visible, )

**Comment by nknapp** [comment]
I guess it depends on what you do with the output. If you use `element.innerText=output` to display the text, then the browser will escape it. Same thing happens, if you use it with nodejs to generate an HTML-page and set the response content-type to `text/plain`.
 
Have a look at the [jsfiddle](https://jsfiddle.net/9D88g/180/). Can you reproduce the issue there?

**Comment by Ninja-Coding-Git** [comment]
i don't use this for a JavaScript View, i use this to generate HTML mails. if this helps.

**Comment by Ninja-Coding-Git** [comment]
this the reproduction at [jsfiddle](https://jsfiddle.net/9D88g/180/)

**Comment by Ninja-Coding-Git** [comment]
basically, i want a general template and then insert a "body" in the general template or parent template:


```
<div>
<div>Hello</div>

<!-- dynamic body start -->
<div>please click link below: <a href="some_place">click here</a></div>
<!-- dynamic body end -->

<div>
```

**Comment by nknapp** [comment]
If you want to insert the contents of a variable without html-escaping it, you can use triple mustaches like `{{{body}}}` with `{ body: '<a href="">link</a>' }` as input.

You may also want to look at the partials page of the http://handlebarsjs.com website. Dynamic partials might be useful in your case and more secure than passing unescaped HTML directly from the input.

**Comment by ningacoding** [comment]
that part is not documented, but works.

**Comment by nknapp** [comment]
Triple mustaches are documented in the "expressions" page of handlebarsjs.com
