### ISSUE TITLE
Potential security vulnerability!

### ISSUE THREAD

**Issue by MurhafSousli** [wycats/handlebars.js#1406]
GitHub says: 
> We found a potential security vulnerability in one of your dependencies.
The handlebars dependency defined in package-lock.json has a known moderate severity security vulnerability in version range < 4.0.0 and should be updated.

![image](https://user-images.githubusercontent.com/8130692/32983159-a500fd00-cca1-11e7-92cd-eed7004ffe76.png)

![image](https://user-images.githubusercontent.com/8130692/32983157-9524e7b6-cca1-11e7-82c5-adadb1afc2ac.png)

**Comment by nknapp** [comment]
Yes, there is a potential security issue with using `handlebars` before version 4. You should use version 4.x instead

**Comment by nknapp** [comment]
See https://nodesecurity.io/check/handlebars/3.0.3 for details.

**Comment by MurhafSousli** [comment]
@nknapp Thanks for the prompt response
