### ISSUE TITLE
How to get value inside for loop custom helper?

### ISSUE THREAD

**Issue by emjea** [wycats/handlebars.js#1411]
I have a problem how to get value inside custom helper for loop. This my code 
app.js

```js
hbs.registerHelper('fors', function(from, to, incr, block) {
  var accum = '';
  for(var i = from; i <= to; i += incr)
      accum += block.fn(i);
  return accum;
});


file.js
router.get('/page=:count', function (req, res) {
  knex(table_name)
    .select()
    .limit(per_page)
    .offset((req.params.count-1) * per_page)
    .then(todos => {
      res.render('name_list', {
        todos: todos,
        total_page: 10,
        current_page: req.params.count
      });
    })
});
```

name_list.hbs
```
 {{#for 1 total_page 1}}
            <h1>{{current_page}}</h1>
  {{/for}}
```

if {{current_page}} i put outside #for , i get the value of current_page, but when i put inside for the value is blank. How to get value inside for custom helper?
thanks before

**Comment by nknapp** [comment]
There is an example at http://handlebarsjs.com/block_helpers.html, far down. The text is starting with

> Block helpers can also inject private variables into their child templates. 
> This can be useful to add extra information that is not in the original context

**Comment by chandrahaswtw** [comment]
Guess you can try it as below:

```
{{#for 1 total_page 1}}
            <h1>{{../current_page}}</h1>
  {{/for}}
```
adding `../`  helps in referencing to the parent scope.
