### ISSUE TITLE
Getting blank table rows on #each statement while looping JSON file

### ISSUE THREAD

**Issue by miki996** [wycats/handlebars.js#1413]
I am getting blank table rows when i run my code. 
Please check the link to my code on jsfiddle: https://jsfiddle.net/qrvfor4h/#run&togetherjs=ka1qPgPMlK

The blank rows are equal to the users i have in my db.json file. But i am not getting any data just blank rows equal to the number of users in the JSON file. This happens on both GetAllUsers() and FindUsers() functions.

I am using lowdb to get the data from the JSON file.

This is what i get in the browser:
![image](https://user-images.githubusercontent.com/23620141/33853442-410b2634-debe-11e7-87a4-98ac5266471c.png)

**Comment by nknapp** [comment]
Did you put your template inside a script-block? The fiddle does not contain one...

**Comment by nknapp** [comment]
If you don't put your template inside a script-block, the HTML-parser will modify the template and there is nothing Handlebars can do about it.

**Comment by miki996** [comment]
Thanks for the answer. Actually i just fixed it. I have no idea how i was just replacing emails in the JSON file and suddenly it worked. 

I didn't put my template inside script tags. It stays like that as a block in my Handlebars views file. 

Anyways thanks a lot for the answer. Works fine now.
