### ISSUE TITLE
Feature idea: capability to extract a list of data in compiled template

### ISSUE THREAD

**Issue by jasonterando** [wycats/handlebars.js#1421]
I'm running into a bit of a "religious" conundrum using Node with Handlebars.  My use case is grabbing a payload from Atlassian, which includes some URLs to images.  I would like to add that payload to a model, and render that model in multiple templates.  The URLs do not render by inserting them as img.src or even style.background.url, because they require redirects and authentication.  There are multiple resolutions in the payload, and do not want to spend the time to grab all available resolutions and include their base64 data in the model I'm returning.  I would rather just do it for the resolutions (if any) used by the template.

I'm running up against what a lot others have, based upon searching online:

- Handlebars is a synchronous library
- Node is a very asynchronous framework (you can force it to behave synchronously, but it's not a good idea)
- Handlebars is pretty much MVC, models and views should know next to nothing about each other

In Handlebars, we compile a template.  What if we added a capability extract out a list of the data elements used in the compiled template (and yeah, it would have be hierarchical).  I could then retrieve the data (i.e. get data from the image URLs I need), and add it to my model, before calling the compiled template function to render the template with the model.  It would also allow for things like optimized RESTful data retrieval.  We would not have to retrieve *everything* we would *possibly* need, just the things required by the template.  Handlebars remains synchronous, Node remains asynchronous, and the model and view are not tightly bound.

Is this a decent or horrible idea?  Does this already exist?  If not, I don't mind doing the work and submitting it if there is a chance it would get added to the project.

**Comment by nknapp** [comment]
There has been some discussion about support for asynchronous operations. It's not trivial to implement, especially in a way that doesn't brake lots of existing helper-libraries.

The best I can give you for asynchronous helpers is the 'promised-handlebars' library. It's still very hacky in its nature though. And I haven't made any performance measurements. But it allows you to write helpers that return promises.

**Comment by nknapp** [comment]
I'm not sure if I understood everything correctly, but I have the feeling that this is your actual problem: The ability to execute an asynchronous helper.

Support for Restful APIs should definitely not be in the core or Handlebars. Such a kind of logic is better put into a helper. It will make you templates unreadable for sure, not to mention platform dependent code and dependencies to other node libraries that would have to be included simply for this feature.

**Comment by atomictag** [comment]
If I understood correctly your use case you basically would like to know what context data a template is really going to use, so you can pre-fetch it before feeding it to the template. 
How about using a custom [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) as your DRY_RUN context as your custom "collector" to gather that information? With that you can trap getters, method invocations etc. 

I guess your templates would have to be very much logic-less as cases like 
`{{#if something}} {{ this_thing }} {{else}} {{ that_thing }} {{/if}}`
would be difficult to handle. But I suppose you'd have the same issue with any implementation of that DRY_RUN collector idea down the lines.

**Comment by doowb** [comment]
@jasonterando I think you can use the [AST + compiler api](https://github.com/wycats/handlebars.js/blob/master/docs/compiler-api.md) to find what context the templates will expect to use. You may have to combine this with some of your own application logic since I think resolving ambiguous helper or data expressions is done at render time.

**Comment by jasonterando** [comment]
@doowb  - yeah, that looks interesting. I'll check it out and thanks!
