### ISSUE TITLE
Readonly doesnt work

### ISSUE THREAD

**Issue by ridhogillang** [wycats/handlebars.js#1429]
so i try to make input element on .hbs 

this is my code 
` <input id="ProductTypeDropdown" type="text" name='productType' class="inputNohp padding-0 mid-align txt-bluewite txt-ubuntu" placeholder="Produk" readonly />`

when i try to load it in chrome. chrome remove readonly attribute. 

ive try several option such as 
`readonly = "true"`
`readonly = "readonly"`
`readonly = ""`
`readonly = "ReAdOnLy"`

but none of them is work..

thank you so much :)

ive attached the screen shot between my code and inspect element 

<img width="927" alt="screen shot 2018-03-06 at 9 44 15 pm" src="https://user-images.githubusercontent.com/15265259/37038539-ad4a6d6c-2187-11e8-8d06-e519d9033b54.png">
<img width="1144" alt="screen shot 2018-03-06 at 9 44 30 pm" src="https://user-images.githubusercontent.com/15265259/37038541-ad89a040-2187-11e8-95d7-895016268def.png">

**Comment by nknapp** [comment]
Have you put your template inside a `<script>`-tag? I don't think this is a Handlebars issue, but if you like you can set up a jsfiddle (see the CONTRIBUTING.md) for a link, and I'll have a look.

**Comment by ridhogillang** [comment]
i think ists my fault i was mistype the Doctype with doctype thank you so much
