### ISSUE TITLE
Repalce `async` on `neo-async`

### ISSUE THREAD

**Issue by evilebottnawi** [wycats/handlebars.js#1431]
Before filing issues, please check the following points first:

- [x] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [x] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [x] Use the jsfiddle-template at https://jsfiddle.net/9D88g/47/ to reproduce problems or bugs

It is will improve perf. I can do PR :+1:

**Comment by nknapp** [comment]
I know you opened this issue a long while ago. I somehow had the impression that neo-async was working with newer NodeJS version only, so it would be a breaking change to include it.

But it seems like I was wrong. At least I wasn't able to find a "const" keyword in the source.

Thank you for this issue, I have made a branch now.
