### ISSUE TITLE
New Handlebars Expression Linter

### ISSUE THREAD

**Issue by dhollenbeck** [wycats/handlebars.js#1437]
Before filing issues, please check the following points first:

- [x ] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [ x] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [ x] Use the jsfiddle-template at https://jsfiddle.net/9D88g/47/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

Just published a Handlebars Expression Linter and would like feedback on how it can be improved.

- **Code**: https://www.npmjs.com/package/provejs-handlebars
- **CodeMirror Demo**: https://dhollenbeck.github.io/codemirror-examples/

The demo is linting both the HTML and Handlebars Expressions. If there are HTML errors I don't lint the Handlebars Expressions. The Linter works on both the browser and the server (Node.js).

One area that I would like advice on is how to get better reporting on parser exceptions messages. Currently, I am parsing the expression message and it is a hack. Is there a way to override some parser functionality to improve the returned parser exception data?

Pull requests are welcome.

**Comment by nknapp** [comment]
The demo looks very nice... If you think you have reached an appropriate level of stability and completeness, you could file a PR for adding it to the [Handlebars-in-the-wild](https://github.com/wycats/handlebars.js#handlebars-in-the-wild) list.

About exceptions: There [should be a `column` and  a `lineNumber` property](http
(https://github.com/wycats/handlebars.js/blob/fb26f69485d37673192d59098c654aad3fc56979/spec/compiler.js#L41) for compiler exceptions, although I remember issues where people were missing them.

Other than that, there is no additional data. What exactly would you like to have?

**Comment by dhollenbeck** [comment]
Thank you for the feedback! Handlebars throws two types of exceptions messages. One type does not include a column number, but instead includes an `line pointer indicator`.

**Type 1:** `{{foo}}{{/foo}}` which does **not** provide the column number, but shows the indicator.
```bash
Parse error on line 1:
{{foo}}{{/foo}}
-------^
```
**Type 2:** `{{#foo}}{{/bar}}` includes the column number.
```
foo doesn't match bar - 1:3
```
**I wish I had that column number in the Type 1 exception messages.**

I have [written code](https://github.com/provejs/provejs-handlebars/blob/master/src/exceptions.js#L7) to parse the type 1 exception message trying to guess the column number. My Linter frequently points to the wrong template code column because I can't reliably compute the column number from the type 1 exception message.

Related Issue: https://github.com/wycats/handlebars.js/issues/1173

**Comment by nknapp** [comment]
Closing in favour of #1173
