### ISSUE TITLE
What does handlebars expression {{!< default}} mean?

### ISSUE THREAD

**Issue by Megidd** [wycats/handlebars.js#1438]
This is not an issue, I just have a question:

I wonder what is the meaning of `{{!< default}}` expression at the very first line of some `*.hbs` files. 

The [KeystoneJS](https://github.com/keystonejs/) top directory generated by yeoman generator, contains a file at the address `templates/views/index.hbs` having the expression `{{!< default}}` at the very first line.

**Comment by atomictag** [comment]
`{{! ... }}` is a comment, as in ` {{! This comment will not be in the output }}`.
So in standard Handlebars `{{!< default}}` should produce no output.

**Comment by LittleBiggler** [comment]
I understand that there will be no output from {{!< default}}, but what does it do in the code?
