### ISSUE TITLE
Dynamic td width while creating table

### ISSUE THREAD

**Issue by amirzandi** [wycats/handlebars.js#1439]
I am creating a table which includes two rows with dynamic numbers of td.
The important part is to set the width for each td and the width has been calculated and passed to view.
tdWidth: 100/numberOfChars => which gives a percentage for width
I am using following code but it is not working:
```
<table>
<tbody>
<tr>
{{#each array}}
<td style='width: {{tdWidth}}%;'>{{this}}</td>
{{/each}}
</tr>
</tbody>
</table>
```
any helps appreciated.

**Comment by amirzandi** [comment]
@nknapp please help!

**Comment by magikstm** [comment]
@amirzandi could you please share more of your code?

Especially the part that creates the "tdWidth" value as well as how you link it to that part of your page.

**Comment by amirzandi** [comment]
this is the server side: 
res.render('./game/phrase_box', {
                            layout: false,
                            incorrects: result.incorrects,
                            corrects: result.corrects,
                            numberOfChars: result.numberOfChars,
                            tdWidth: 100 / numberOfChars
                        });


this is the client side: 
{{#if incorrects}}
    {{#if corrects}}
        <table class="phrasebox-table">
            <tbody>
                
                <tr>
                    {{#each corrects}}
                        <td style="width:{{tdWidth}}%">{{this}}</td>
                    {{/each}}
                </tr>
            </tbody>
        </table>
    {{/if}}
{{else}}

{{/if}}

**Comment by magikstm** [comment]
You're iterating in "corrects" in your "each" statement, but that object doesn't hold the "tdWidth" object.

I think you may need to change this:
`{{tdWidth}}`

To this:
`{{../tdWidth}}`

Ref: http://handlebarsjs.com/ (under "Handlebars Paths")

**Comment by amirzandi** [comment]
@magikstm ohhhhh you saved my day.... thank you very much... thanks a lot.
