### ISSUE TITLE
safe-string.js

### ISSUE THREAD

**Issue by GZWZC** [wycats/handlebars.js#1441]
when i build by webpack will generate the js for safe-string.js
Why is it so??
this make me debugger the code is so difficultly.

![image](https://user-images.githubusercontent.com/16217142/39682803-9fb0b728-51e4-11e8-931e-adc2c681fff8.png)

`safe-string.js`
> // Build out our basic SafeString type
function SafeString(string) {
  this.string = string;
}
SafeString.prototype.toString = SafeString.prototype.toHTML = function() {
  return '' + this.string;
};
export default SafeString;

**Comment by nknapp** [comment]
This is the implementation of the SafeString-class. If you return a `SafeString` from a helper, the [escapeExpression](https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/utils.js#L67) method will notice the `toHTML`-method and call it. The result will be passed to the output without escaping.

**Comment by GZWZC** [comment]
@nknapp  I want to solve this problem, how should i do?

**Comment by nknapp** [comment]
What exactly is the problem?

**Comment by nknapp** [comment]
Maybe there is something wrong with your source map config. I don't think it is related to handlebars
