### ISSUE TITLE
Templates read {{if}} as helper without '#'

### ISSUE THREAD

**Issue by s7726** [wycats/handlebars.js#1447]
https://jsfiddle.net/tb58kjmx/2/

My data contains the key 'if', When attempting to expand the template I'm getting:
`Uncaught TypeError: Cannot read property 'hash' of undefined handlebars.js:817`
It appears handlebars is attempting to treat my template `{{if}}` like a helper.
From the way I read the documentation, to invoke the 'if' helper it should have the `{{#if condition}}` syntax.

This is unexpected behavior. Is there a suggested work around? Obviously I could mangle my data ahead of time, is there a way to escape the name in the template to get past the helper check?

**Comment by nknapp** [comment]
If might work with `{{[if]}}` (https://github.com/wycats/handlebars.js/issues/1251)
