### ISSUE TITLE
Add/Improve `.npmignore`

### ISSUE THREAD

**Issue by SimonSchick** [wycats/handlebars.js#1448]
You are missing various files in your `.npmignore`:

```
.gitattributes
.gitmodules
.idea/
.istanbul.yml
appveyor.yml 
CONTRIBUTING.md
docs/
FAQ.md
package-lock.json
print-script
release-notes.md
```

Please consider using a whitelist instead of a blacklist for files instead.

You can do so by using an inverted glob.
```
/*
!/allowed
```

**Comment by nknapp** [comment]
I would prefer the "files" section in package.json 

Would you like to make a PR to the 4.x branch?

**Comment by SimonSchick** [comment]
Same difference, I can look into that, no promises tho.

**Comment by SimonSchick** [comment]
The `files` property is already there...

https://github.com/wycats/handlebars.js/blob/master/package.json#L76

Is it possible that someone used a bad npm version to publish this package?

**Comment by SimonSchick** [comment]
I think we can mark this as resolved with the latest release, the package is still big but it's all code so that's cool.
