### ISSUE TITLE
Why is Handlebars so fast? How does it work?

### ISSUE THREAD

**Issue by nebrelbug** [wycats/handlebars.js#1451]
Since I can't find any documentation online for the inner workings of Handlebars, I'm curious--why is Handlebars so much faster than Mustache?

Does it parse the strings character by character (like a C compiler?) I saw that there's what looks like a Yacc file? Is that what it is? If so, how does it work with JS?

Or does Handlebars just use Regular Expressions, like Mustache?

Usually, I'd just look through the code, but since it's really large, I have no idea why the Yacc file is there, and I can't find any documentation as to how it's organized, I'm just asking here.

**Comment by nknapp** [comment]
It compiles the template into a JavaScript function, that you can call with the input data.
The JavaScript function more or less consists of string concatenation using the + operator.
Now... There's more to it, and the runtime library is needed as well for helpers and context handling, but the main reason for it being fast is: you only parse and compile the first time. After that you just call the compiled function.

**Comment by nebrelbug** [comment]
@nkapp does it use RegExp to parse, or does it parse character by character like a C compiler?

**Comment by nknapp** [comment]
I uses [jison](https://github.com/zaach/jison), but I think jison uses RegExp internally.
The parser rules can be found in the [src](https://github.com/wycats/handlebars.js/tree/master/src) directory.

**Comment by nebrelbug** [comment]
@nknapp Cool, thanks!
