### ISSUE TITLE
Can't use `null` in object path expression

### ISSUE THREAD

**Issue by tsing** [wycats/handlebars.js#1456]
Before filing issues, please check the following points first:

- [x] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [x] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [x] Use the jsfiddle-template at https://jsfiddle.net/9D88g/47/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

```
Handlebars.compile('{{payload.null}}')({payload: {null: 'foo'}});
```

will cause error: 
```
Error: Parse error on line 1:
{{payload.null}}
----------^
Expecting 'ID', got 'NULL'
```
https://jsfiddle.net/9D88g/623/

**Comment by nknapp** [comment]
Use ` {{payload.[null]}}`. https://jsfiddle.net/9D88g/625/
