### ISSUE TITLE
Dynamic partial gives: jQuery.Deferred exception: (intermediate value).call is not a function ...

### ISSUE THREAD

**Issue by sabsaxo** [wycats/handlebars.js#1457]
When I try to load a partial dynamically using this syntax:
```
{{#each data.fields}}
	{{>(this.type)}}
{{/each}}
```
Where this.type is a string ('text', 'image' etc.), I get this error:
```
jQuery.Deferred exception: (intermediate value).call is not a function ... yadda yadda.
```
Partials are registered during a Gulp build ...

What is it that I'm missing?

**Comment by nknapp** [comment]
The answer is in the docs (hooray), but I was confused as well until I read it the second time and the docs could be better (so don't worry). The important sentence on http://handlebarsjs.com/partials.html is:

> Subexpressions do not resolve variables so whichPartial must be a function. If a simple variable has the partial name, it's possible to resolve it via the lookup helper.

This should work:

```
{{> (lookup . 'type') }}
```
