### ISSUE TITLE
Ability to escape delimiters

### ISSUE THREAD

**Issue by scottgonzalez** [wycats/handlebars.js#146]
There's no way to escape delimiters, so creating a template that generates another template is a bit painful.

I'm currently using custom helpers to do:

```
{{ldelim}}foo{{rdelim}}
```

It'd be much nicer to be able to just escape the delimiters:

```
\{{foo}}
```

**Comment by brantwedel** [comment]
Using Handlebars to generate JavaScript code so it makes sense to use <> as delimiters, and + for partials <+partial>, would be nice to change delimiters, currently just passing the template through a translation step:
```
tempSrc = tempSrc
          .replace(/( =?)<(=? )/,'$1__preserve_lt__$2')
          .replace(/( =?)>(=? )/,'$1__preserve_gt__$2')
          .replace(/\{\{/g,"\{{") // escape delimiters
          .replace(/<\+/g,"{{>") // use + for include
          .replace(/</g,"{{").replace(/>/g,"}}") // replace delimiters
          .replace(/__preserve_lt__/,'<')
          .replace(/__preserve_gt__/,'>');
```

**Comment by stevenvachon** [comment]
Implementing this feature would basically replace Mustache with Handlebars. At the very least, it would fully support it.
