### ISSUE TITLE
Unclosed section error when using any helper

### ISSUE THREAD

**Issue by DominicTobias** [wycats/handlebars.js#1461]
Hi, any time I write anything other than `{{something}}`, `{{#something}}{{/something}}`, or `{{^something}}{{/something}}` I get "Unclosed section".

I've tried `#each`, `#unless`, and `#if`:

<img width="518" alt="screen shot 2018-08-21 at 23 13 05" src="https://user-images.githubusercontent.com/760314/44432013-3bb30480-a598-11e8-9841-0ad7fcb5a41d.png">

Even if I reduce it down to nothing much at all:

<img width="510" alt="screen shot 2018-08-21 at 23 19 12" src="https://user-images.githubusercontent.com/760314/44432135-b2500200-a598-11e8-906e-328d772dd3b1.png">

In the examples above you can clearly see I'm closing the sections, but any time I write something similar it tells me that it's unclosed. Why is that? Thanks.

**Comment by DominicTobias** [comment]
Nevermind I forgot I had switched to Mustache to test something 😅

**Comment by ColinEberhardt** [comment]
Oh for gods sake - I've fallen into the same trap, using Handlebars syntax within Mustache!

**Comment by tejaszambre** [comment]
@ColinEberhardt - Thank you for saving my day :)

For those who are still looking for an answer, Refer [Inverted section in Mustache](http://mustache.github.io/mustache.5.html#Inverted-Sections)

It will show you how to use if-else in Mustache.

**Comment by dancodehq** [comment]
I also just fell into this trap. Doh!
