### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jirutka** [wycats/handlebars.js#1463]
Could you please release a new version? It's almost a year since the last release. I have problem with outdated `source-map` dependency that does't work well with Rollup, so I have to hack it somehow.

**Comment by nknapp** [comment]
Sorry for the delay. When I wanted to release in the weekend, I noticed several security warnings when running "npm install". I'll try to do the release today.

**Comment by nknapp** [comment]
Tonight, that is. In about 7 hours

**Comment by jirutka** [comment]
Thanks!
