### ISSUE TITLE
Template not working as expected

### ISSUE THREAD

**Issue by adriancast** [wycats/handlebars.js#1466]
I spent a few hours trying to understand this test case. Would be cool if this example is added in the documentation. 

In this test case that the template system is not working as expected:
### Template
```
{{#each data.items}}
  {{id}} - {{value}} - {{../current}}<br>
{{/each}}
```
### Test Data
```
{
"data": {
  "items":  [
      {"value": "New", "id": 1},
      {"value": "Open", "id": 2},
      {"value": "Close", "id": 3}
    ],
  "current": 2
  }
}
```

in order to render the node 'current' I need to use {{../data.current}} insteod of {{../current}}

I created a JS fiddle to reproduce the 'issue'. http://jsfiddle.net/7wz0gmpv/

Thanks for the support, have a nice day

**Comment by collinoswaltpsd** [comment]
If you want to do `../current` right now, use the `{{with}}` block:

```js
{{#with data}}
  {{#each items}}
    {{id}} - {{value}} = {{../current}}<br>
  {{/each}}
{{/with}}
```

**Comment by nknapp** [comment]
Example could be added to the docs at https://handlebarsjs.com/guide/expressions.html#changing-the-context

**Comment by adriancast** [comment]
thanks @nknapp !
