### ISSUE TITLE
Handlebars.compile returning function

### ISSUE THREAD

**Issue by jagmitg** [wycats/handlebars.js#1472]
I currently have a for loop, which feeds in an object containing handlebar partials. However, for some odd reason, out of the 20 to 30 handlebar components, the ones that are actually present in other handlebars partials as includes, are returning a `function` and not a `string`.

```
if (typeof handlebar[hbp] == 'string') {
    const compiled = Handlebars.compile(handlebar[hbp]);
    html = compiled(this.data);
}
```

If i comment out this code, it all returns back a string. However, when its there, anything that is used as an include somewhere else fails.

Would anyone know if this is a bug or an issue?

**Comment by nknapp** [comment]
Partials are replaced by compiled versions in the internal "partials"-object when they are executed for the first time.
