### ISSUE TITLE
Sanitize {{{untrusted-html}}} to avoid XSS attacks

### ISSUE THREAD

**Issue by ToreOlavKristiansen** [wycats/handlebars.js#1473]
What is a good way to sanitize {{{untrusted-html}}} to avoid XSS attacks? I need to display as html, but strip dangerous content.

Would it be a good idea to use [https://github.com/google/caja/wiki/JsHtmlSanitizer](https://github.com/google/caja/wiki/JsHtmlSanitizer)? Where would I plug that in?

**Comment by nknapp** [comment]
You could register a [helper function](http://handlebarsjs.com/#helpers)

**Comment by ToreOlavKristiansen** [comment]
Thanks for this Nils with skills.
