### ISSUE TITLE
Copy html block to helper? (help needed)

### ISSUE THREAD

**Issue by cgpro** [wycats/handlebars.js#1475]
In my file is a documentation and a markup part. For syntax highlighting I want the same code (pink rectangle) in my markdown block. Is there an easy way to simply "copy" the markup? 

<img width="775" alt="styleguide" src="https://user-images.githubusercontent.com/1557147/48098612-9a922c80-e21d-11e8-8766-80ea1b2bd579.png">

I can't access the content of the parent file context with options.fn(this) in my markdown helper. I searched for about 3 hours for now (github issues, stackoverflow, handelbars documentation) and didn't find any solution :-(. I dont want to copy&paste the html markup each time in my markdown block... 😕

**Comment by nknapp** [comment]
You could use an [inline partial](http://handlebarsjs.com/partials.html#inline-partials) 

Example: https://jsfiddle.net/9D88g/855/

**Comment by cgpro** [comment]
Works like a charm! Thanks! :-)
