### ISSUE TITLE
Is options parameter in parse method part of Public API ?

### ISSUE THREAD

**Issue by Toilal** [wycats/handlebars.js#1480]
Before filing issues, please check the following points first:

- [x] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [x] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [x] Use the jsfiddle-template at https://jsfiddle.net/9D88g/47/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

I'm currently writing some enhancements to typescript definition files available at DefinitelyType for this package, be we are not sure if [options argument on parse method](https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/compiler/base.js#L11) is available in the public API, as it doesn't seems to be documented anywhere.

Could you confirm the options is part of the Public API ? Does it make sense to pass options to the parse method as a end user ? I could enhance the docs directory to describe possible values then.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30619#discussion_r235859859

**Comment by nknapp** [comment]
Closing to inactivity. Typings are now part of this repo.
