### ISSUE TITLE
Tag 4.0.12 as latest on npmjs

### ISSUE THREAD

**Issue by danielkesselberg** [wycats/handlebars.js#1486]
Could you please tag `4.0.12` as latest again?

![image](https://user-images.githubusercontent.com/3902676/50043722-a9b89580-0079-11e9-9dc9-c3b933d880bb.png)

https://www.npmjs.com/package/handlebars

**Comment by nknapp** [comment]
I've re-tagged it as soon as I realized what had happened. Sorry for the inconvience.

**Comment by danielkesselberg** [comment]
Thank you!

**Comment by nknapp** [comment]
Released in 3.0.6
