### ISSUE TITLE
Conflicting TypeScript definitions between @types/handlebars and latest handlebars

### ISSUE THREAD

**Issue by lupestro** [wycats/handlebars.js#1499]
Before filing issues, please check the following points first:

- [X] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [X] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md

Since the 4.0.13 and 4.1.0 releases, there are now two "sources of truth" for types - `@types/handlebars` and `handlebars`, as the project has taken `handlebars.d.ts` back into its lib area with this release. A module can end up picking up both packages through dependencies. TypeScript is presented with two places claiming to define the handlebars types, which leads to a spate of messages during the build. 

I am told there is some kind of deprecation process over at StronglyTyped that may help with this confusion, but I do not know the details or whether it offers a practical solution. For the time being, I'm using the `resolutions` section of my `package.json` to freeze the version of `handlebars` used within my project at 4.0.12. This quells the confusion, but this cannot continue forever.

I'm not sure if a more cleanly orchestrated solution can be found, but the parsed contents of the version delivered in 4.0.13 / 4.1.0 is byte-for-byte identical to the version in `@types/handlebars`. Only the comments differ. This suggests that, if it would help, little might be lost by backing out the current behavior before introducing the transition in a more coordinated way.

**Comment by nknapp** [comment]
You are right, handlebars@4.1.0 now has type definitions included (4.0.13 doesn't). In yesterdays release, I was more concerned with patching the security vulnerability, so I  forgot to notify DefinitelyTyped.  I'm sorry if that caused you trouble.

I will get on it now.

**Comment by nknapp** [comment]
I have submitted a request for removal at DefinitelyTyped (see DefinitelyTyped/DefinitelyTyped#32897).

**Comment by Sparticuz** [comment]
Will that also fix handlebars/runtime?
````
Could not find a declaration file for module 'handlebars/runtime'. '/node_modules/handlebars/runtime.js' implicitly has an 'any' type.
  Try `npm install @types/handlebars` if it exists or add a new declaration (.d.ts) file containing `declare module 'handlebars/runtime';`ts(7016)
````

**Comment by nknapp** [comment]
The typings in 4.1 do declare a module `handlebars/runtime`. Could you verify that in your `node_modules`?

**Comment by nknapp** [comment]
After all the problems this has caused so far, I'm thinking about removing the typings from the package and instead put a note into the contributing guide that types should be updated in @types/handlebars on every release.

**Comment by nknapp** [comment]
After all the problems this has caused so far, I'm thinking about removing the typings from the package and instead put a note into the contributing guide that types should be updated in @types/handlebars on every release.

**Comment by nknapp** [comment]
I think the most graceful way out of this is adding the types a dependency and removing them from the package.

That way, the change is backwards compatible to 4.1.0 for people that rely on types being there. At the same time, the problems with Ember's typings and others, will disappear

**Comment by Sparticuz** [comment]
I do see line 354 in handlebars.d.ts says declare module "handlebars/runtime".

I'm relatively new to typescript, so I don't know the ins and outs of .d.ts files, nor do I understand the problem, it looks right to me.

Personally, I would prefer them to be included in the package itself, but I understand having them in DefinitelyTyped's repo

**Comment by Sparticuz** [comment]
It's odd because I get the intellisense option for handlebars/runtime
![image](https://user-images.githubusercontent.com/161913/53190232-19498480-35d7-11e9-96f7-8e7ffc8c7182.png)
but when I select it, it shows the error
![image](https://user-images.githubusercontent.com/161913/53190264-2d8d8180-35d7-11e9-832b-dd913a4602c4.png)
(I do NOT have @types/handlebars installed either)

**Comment by Sparticuz** [comment]
Here is the --traceResolution output for handlebars

```
======== Resolving module 'handlebars/runtime' from '/mnt/d/dev/dazser-send-invoices/typescript/merge.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
Loading module 'handlebars/runtime' from 'node_modules' folder, target file type 'TypeScript'.
Directory '/mnt/d/dev/dazser-send-invoices/typescript/node_modules' does not exist, skipping all lookups in it.
'package.json' does not have a 'typesVersions' field.
Found 'package.json' at '/mnt/d/dev/dazser-send-invoices/node_modules/handlebars/package.json'. Package ID is 'handlebars/runtime/index.d.ts@4.1.0'.
File '/mnt/d/dev/dazser-send-invoices/node_modules/handlebars/runtime.ts' does not exist.
File '/mnt/d/dev/dazser-send-invoices/node_modules/handlebars/runtime.tsx' does not exist.
File '/mnt/d/dev/dazser-send-invoices/node_modules/handlebars/runtime.d.ts' does not exist.
Directory '/mnt/d/dev/node_modules' does not exist, skipping all lookups in it.
Directory '/mnt/d/node_modules' does not exist, skipping all lookups in it.
Directory '/mnt/node_modules' does not exist, skipping all lookups in it.
Directory '/node_modules' does not exist, skipping all lookups in it.
Loading module 'handlebars/runtime' from 'node_modules' folder, target file type 'JavaScript'.
Directory '/mnt/d/dev/dazser-send-invoices/typescript/node_modules' does not exist, skipping all lookups in it.
'package.json' does not have a 'typesVersions' field.
Found 'package.json' at '/mnt/d/dev/dazser-send-invoices/node_modules/handlebars/package.json'. Package ID is 'handlebars/runtime/index.d.ts@4.1.0'.
File '/mnt/d/dev/dazser-send-invoices/node_modules/handlebars/runtime.js' exist - use it as a name resolution result.
Resolving real path for '/mnt/d/dev/dazser-send-invoices/node_modules/handlebars/runtime.js', result '/mnt/d/dev/dazser-send-invoices/node_modules/handlebars/runtime.js'.
======== Module name 'handlebars/runtime' was successfully resolved to '/mnt/d/dev/dazser-send-invoices/node_modules/handlebars/runtime.js'. ========
```

**Comment by nknapp** [comment]
@Sparticuz Please try if the changed `.d.ts`-files from 5cedd62 fix your problem.

**Comment by Sparticuz** [comment]
I think that fixed it.

**Comment by nknapp** [comment]
I think that the problem with conflicting TypeScript-definitions should be resolved now. Can anybody confirm that? 

If that is the case, I will try to get a new version out as soon as possible containing the 5cedd62 fix.
