### ISSUE TITLE
Is it possible ignore a specific "tag"?

### ISSUE THREAD

**Issue by rnhurt** [wycats/handlebars.js#1502]
I am using Handlebars to create AWS CloudFormation (CFN) templates and am having a problem with its [Dynamic References](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html).  Dynamic References use double brackets {{}} to specify special abilities in CFN and my templates are getting all confused.  

For a number of reasons I am processing my templates multiple times; sometimes once sometimes twice.  I tried escaping the value but that didn't work.  I also tried using a raw handler [below] but that only works for a single use case and it gets pretty ugly and unwieldy.
```
"MasterUserPassword": "{{{{raw}}}}{{{{raw}}}}{{resolve:ssm-secure:MyPassword:5}}{{{{/raw}}}}{{{{/raw}}}}"
```

My question is, can I set something in Handlebars so that it will completely ignore an element that begins with `resolve:`?  I was thinking that I might be able to create a partial to handle this but the element name would always be different.  One time it would be `{{{resolve:ssm-secure:MyPassword}}}` and another it might be `{{{resolve:ssm:SomeString}}}`.  I looked through the compile() options but didn't see anything that might be useful.

**Comment by wycats** [comment]
Have you tried escaping the curlies? https://handlebarsjs.com/expressions.html#escaping

**Comment by rnhurt** [comment]
Yes, I tried escaping the curlies and that works in a limited fashion, but it still fails if you process the template multiple times.  I was thinking it might be handy to have a general purpose way to ignore non-handlebars tags, or even specific tags (ie. ones that start with a certain string).

NOTE: I solved my original problem by not processing my templates multiple times.
