### ISSUE TITLE
Why dont you have logical operators like and or in {#if} statements?

### ISSUE THREAD

**Issue by AlextheGrace** [wycats/handlebars.js#1505]
Before filing issues, please check the following points first:

- [ ] Please don't open issues for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [ ] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [ ] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [ ] Use the jsfiddle-template at https://jsfiddle.net/9D88g/47/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

**Comment by nknapp** [comment]
I think the main point is that templates should not contain a lot of logic and having such operators would encourage you to write templates with complicated logic. The "logicless templates"-claim has been debated a lot of times in different issues. With an "if"- and an "each"-helper, Handlebars certainly is not logicless, but templates still should has "less logic".

In the same way that you should avoid writing inline JavaScript or CSS in HTML files, you should avoid using complicated boolean-expressions in a Handlebars-template.

In cases where you would need such operators you should probably write a helper that performs the logic part for you. You can give the helper a descriptive name so a person reading the template will know what it should do. Like:

```hbs
{{#if (personIsSingleMaleAdult .)}}
  {{name}} is a single male adult person
{{/#if}}
```

```js
Handlebars.registerHelper('personIsSingleMaleAdult', function (person) {
   return person.gender === 'male' && person.partner != null && person.age >= 18
})
```
