### ISSUE TITLE
How to disable HTML safe characters?

### ISSUE THREAD

**Issue by acceleratxr** [wycats/handlebars.js#1510]
I am using Handlebars to generate source code. However, any time I attempt to generate output for characters like '<' or the " it converts it to an HTML safe sequence which I don't want. How can I disable this feature so that it outputs exactly the string I give it?

**Comment by liqiang372** [comment]
@acceleratxr please read the doc https://handlebarsjs.com/ , HTML ESCAPING is listed on the very first page.

**Comment by acceleratxr** [comment]
Applogies for the bogus post. I apparently skipped past that section while reading previously. :)
