### ISSUE TITLE
Run {{#each }} iterate on array inside a array

### ISSUE THREAD

**Issue by Rubioli** [wycats/handlebars.js#1522]
Is it possible to run  {{#each }} iterate for `array` inside a `array`.

By that I mean, currently, If I have:
```
profiles: [
     {firstname: 'foo'},
     {firstname: 'bar'},
]
```
I can do:
```
{{#each profiles}}
   {{firstname}}
{{/each}}
```

But how am I able to achieve something like this:
```
profiles: [
     males: [
           {firstname: 'foo Male'},
           {firstname: 'bar Male'},
     ],
     females: [
           {firstname: 'foo Female'},
           {firstname: 'bar Female'},
     ]
]

// OR

profiles: [
    {
        males: [
            {firstname: 'foo Male'},
            {firstname: 'bar Male'},
        ]
    },
    
    {
        females: [
            {firstname: 'foo Female'},
            {firstname: 'bar Female'},
        ]
    }
]

{{#each profiles males}}
   {{firstname}}
{{/each}}
```

Any tips is appreciated and thanks in advance!

**Comment by lorefnon** [comment]
[hbs-jsonpath-helpers](https://www.npmjs.com/package/hbs-jsonpath-helper) enables you to use [jsonpath](https://goessner.net/articles/JsonPath/) to traverse and retrieve data in your handlebars templates. 

With that installed, you can do something like: 

```
{{#each (jp-get "profiles[*].males[*]")}}
   {{firstname}}
{{/each}}
```

**Comment by nknapp** [comment]
Use 

{{#each profiles}}
{{#each males}}
{{firstName}}
{{/each}}
{{/each}}
