### ISSUE TITLE
Empty arrays treated as falsy

### ISSUE THREAD

**Issue by mcandre** [wycats/handlebars.js#1531]
Before filing issues, please check the following points first:

- [x] Please don't open issues for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [x] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [x] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [x] Use the jsfiddle-template at https://jsfiddle.net/9D88g/47/ to reproduce problems or bugs

This will probably help you to get a solution faster. 
For bugs, it would be great to have a PR with a failing test-case.

To begin with, I want to parameterize some HTML content based on whether a binding exists or not. So I tried `{{#if <binding>}} ... {{/if}}`. However, this treats empty arrays as falsy, which goes against JavaScript standards:

https://developer.mozilla.org/en-US/docs/Glossary/Falsy

I realize that Handlebars its in fact its own language, which may or may not be used with JavaScript. But JavaScript being its primary application, it would stand to reason to match JavaScript's behavior more closely here.

Perhaps someone could recommend a safer way to check for the existence of variable bindings? Does Handlebars support `!= undefined`, or similar semantic? I don't expect updates to alter the behavior of existing Handlebars built-ins, as that would break backwards compatibility. But some kind of syntax is often needed in order to support testing for potentially falsy bindings, even `null` bindings.

**Comment by nknapp** [comment]
This is a bit hidden in the docs and should certainly been updated.

The [Utils.isEmpty](http://handlebarsjs.com/reference.html#utils-isEmpty) function that decides for `if` and `with` helpers. It simulates the mustache behavior.

You can always write your own block helper. Something like this:

https://handlebars-draft.knappi.org/playground.html#format=1&currentExample=%7B%22template%22%3A%22nullValue%3A%20%7B%7B%23ifdefined%20nullValue%7D%7Dtrue%7B%7Belse%7D%7Dfalse%7B%7B%2Fifdefined%7D%7D%5CnnonexistingProperty%3A%20%7B%7B%23ifdefined%20nonexistingProperty%7D%7Dtrue%7B%7Belse%7D%7Dfalse%7B%7B%2Fifdefined%7D%7D%5Cnzero%3A%20%7B%7B%23ifdefined%20zero%7D%7Dtrue%7B%7Belse%7D%7Dfalse%7B%7B%2Fifdefined%7D%7D%5CnemptyString%3A%20%7B%7B%23ifdefined%20emptyString%7D%7Dtrue%7B%7Belse%7D%7Dfalse%7B%7B%2Fifdefined%7D%7D%5CnemptyArray%3A%20%7B%7B%23ifdefined%20emptyArray%7D%7Dtrue%7B%7Belse%7D%7Dfalse%7B%7B%2Fifdefined%7D%7D%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20nullValue%3A%20null%2C%5Cn%20%20zero%3A%200%2C%5Cn%20%20emptyString%3A%20''%2C%5Cn%20%20emptyArray%3A%20%5B%5D%5Cn%7D%5Cn%22%2C%22output%22%3A%22nullValue%3A%20false%5CnnonexistingProperty%3A%20false%5Cnzero%3A%20true%5CnemptyString%3A%20true%5CnemptyArray%3A%20true%5Cn%22%2C%22preparationScript%22%3A%22Handlebars.registerHelper('ifdefined'%2C%20function(value%2C%20options)%20%7B%5Cn%20%20%20%20if%20(value%20!%3D%20null)%20%7B%5Cn%20%20%20%20%20%20return%20options.fn(this)%5Cn%20%20%20%20%7D%20else%20%7B%5Cn%20%20%20%20%20%20return%20options.inverse(this)%5Cn%20%20%20%20%7D%5Cn%7D)%3B%5Cn%22%2C%22handlebarsVersion%22%3A%224.2.0%22%7D

**Comment by nknapp** [comment]
alternatively: write a helper that checks for "undefined" and use it in a sub-expression:

```
{{#if (isdefined value)}}true{{else}}false{{/if}}
```

**Comment by nknapp** [comment]
Helpers are the proposed way to add custom logic to templates.

**Comment by nknapp** [comment]
I'm keeping this issue open, because this should be documented along with block helpers and not just in an API function

**Comment by papasmile** [comment]
Took a stab at doc in block helpers section: https://github.com/handlebars-lang/docs/pull/40

**Comment by papasmile** [comment]
mark as closed?
