### ISSUE TITLE
How to pass dynamic value into partials params?

### ISSUE THREAD

**Issue by etterwin** [wycats/handlebars.js#1533]
I need to pass some dynamic value into handlebars partials via params, but a phpstorm's linter highlights my code in red.

Use Handlebars, Symphony. I tried to transform a value to a string, but it doesn't work.

```
{{> ../partials/card/mobile/warranty_lazy_load.hbs
    image = item.image
    <!-- see code below -->
    src = '/imgtmb/89x130/res/content/sanepidem/' + item.id + '/' + item.name + '.jpg'
}}
```
I want to pass a value consist of static and dynamic elements. How to do it?

**Comment by roberkules** [comment]
maybe add a `concat` helper that ... concatenates all params into one string
```hbs
{{> warranty_lazy_load src=(concat '/img/89x130/foo/' item.id '/' item.name '.jpg) }}
```

**Comment by nknapp** [comment]
I would even create a custom helper for this use-case. Something like

```handlebars
{{> warranty_lazy_load src=(itemImageUrl item.id item.name) }}

or

{{> warranty_lazy_load src=(itemImageUrl item item) }}
```

and compute the URL in the `itemImageUrl` helper
