### ISSUE TITLE
Nested partial uses param from parent if not set

### ISSUE THREAD

**Issue by roberkules** [wycats/handlebars.js#1535]
if I nest partials that both use the same param name, but the param is not set on the inner partial, then it will take the param from the "parent" partial. is this intended? I think this is not ideal.

```hbs
{{! partial-a.hbs }}
<section class="{{css}}">
  {{> @partial-block}}
</section>
```

```hbs
{{! partial-b.hbs }}
<article class="{{css}}">
  {{> @partial-block}}
</article>
```

```hbs
{{! index.hbs }}
{{#> partial_a css="foo" }}
  {{#> partial_b}}
    bar
  {{/partial_b}}
{{/partial_a}}
```

will result in:

```html
<section class="foo">
  <article class="foo">  <!-- SHOULD NOT BE "foo", SHOULD BE "" -->
    bar
  </article>
</section>
```

is the only solution to always set `class=""`?

**Comment by nknapp** [comment]
This is essentiall the same as #1550

**Comment by nknapp** [comment]
@roberkules  There is a runtime-option "explicitPartialContext" (see https://handlebars-draft.knappi.org/guide/api-reference.html) that seems to do what you need. I haven't seen it myself and I haven't tested it, but the description looks like what you need.
