### ISSUE TITLE
Why difference raw data and compiled data?

### ISSUE THREAD

**Issue by winverse** [wycats/handlebars.js#1536]
I want use handleBar(v4.1.2) to html template in node(v8.15)

but i have a little problem,

example, my data is array likes

`const myData = [{ isWork: '재직중',
    hireType: '정규직',
    position: '연구원',
    entryDate: '2018-12-31T15:00:00.000Z',
    leaveDate: '',
    description: '-something',
    corporateName: 'open',
    departmentName: '온라인사업부' },
  { isWork: '퇴사',
    hireType: '계약직',
    position: '주임',
    entryDate: '2019-05-05T15:00:00.000Z',
    leaveDate: '2019-05-22T15:00:00.000Z',
    description: '-something',
    corporateName: 'open',
    departmentName: '기획팀' }]`

myData length 2

but after compile, myData length 1

my code

`
const html = fs.readFileSync(`${dir}/template.hbs`, 'utf-8');
const context = {
  resume: myData,
}

const html = Handlerbars.compile(html)(context)

// after, add {{log resume}} in template.hbs
// log resume result => [ { isWork: '재직중',
//  hireType: '정규직',
// position: '연구원',
// entryDate: '2018-12-31T15:00:00.000Z',
// leaveDate: '',
// description: '-something',
// corporateName: 'open',
// departmentName: '온라인사업부' } ]

// why remove index 1 ???
`

**Comment by foundy** [comment]
Korean is included, so I will reply in Korean for convenience.

@winverse 
컴파일에 데이터가 포함되는 내용은 아니라서 컴파일 대상의 템플릿 내용을 확인해야 할 것 같습니다.
위 내용으로는 템플릿이 컴파일 된 후에 context를 바인딩 하는 부분이라 raw 데이터에 대한 핸들링은 전적으로 템플릿에서 제어를 합니다.
built-in helper인 log를 활용하면 데이터 확인 가능합니다.
https://handlebarsjs.com/builtin_helpers.html

**Comment by winverse** [comment]
@foundy 
앞서 말했듯이 이미  built-in helper log를 활용해서 템플릿에서 데이터가 어떻게 핸들링 되는지 보았습니다.
compile되기전엔 존재했던 데이터가 template안에서는 사라지는 현상이 일어났는데 이걸 어떻게하면 좋을까요?

**Comment by foundy** [comment]
@winverse 
context로 전달된 myData를 핸들링하면서 참조에 의해 데이터 제거가 발생한 것 같은데요.
템플릿 소스를 살펴봐야 알 수 있을듯 합니다.

**Comment by winverse** [comment]
@foundy

**Comment by foundy** [comment]
@winverse 
foundy@foundy.io 입니다. :)

**Comment by winverse** [comment]
@foundy 
이메일 보내드렸습니다~ 감사합니다 :)

**Comment by nknapp** [comment]
@winverse @foundy for those of us, who don't speak Korean, could you give a short summary on what the problem and the solution was?

It may help other people who have the same problem.

**Comment by foundy** [comment]
@nknapp 
The cause was not related to compilation.
The reason is that the raw data transformation is caused by the portion of the helper in the template that controls the length during array processing.
Below is an example code for the cause.

```javascript
function field(a, b, options) {
   if (b[a].length = 1) { // This is a problem
     return options.fn(this);
   } else {
     return options.inverse(this);
   }
}
```

**Comment by nknapp** [comment]
thanks
