### ISSUE TITLE
bug: if block helper doesn't return the proper value if the field value is an integer

### ISSUE THREAD

**Issue by aimyth** [wycats/handlebars.js#1537]
Object

{
  name : {
     minLength : 2
  }
}

{{#if name.minLength}} always return false

while 
{
  name : {
     minLength : "2"
  }
}
{{#if name.minLength}} always return true

**Comment by Denny966** [comment]
What makes you think this is a bug? Because `2` in an if-statement is imo `true`

**Comment by nknapp** [comment]
Are you sure? This example

https://handlebars-draft.knappi.org/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B%23if%20name.minLength%7D%7D%20%5Cn%5Ctreturns%20true%5Cn%7B%7Belse%7D%7D%5Cn%5Ctreturns%20false%5Cn%7B%7B%2Fif%7D%7D%5Cn%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20name%3A%20%7B%5Cn%20%20%20%20minLength%3A%202%5Cn%20%20%7D%5Cn%7D%5Cn%5Cn%22%2C%22output%22%3A%22%5Ctreturns%20true%5Cn%22%2C%22preparationScript%22%3A%22%2F%2F%20Handlebars.registerHelper('loud'%2C%20function(string)%20%7B%5Cn%2F%2F%20%20%20%20return%20string.toUpperCase()%5Cn%2F%2F%20%7D)%3B%5Cn%22%2C%22handlebarsVersion%22%3A%224.1.2%22%7D

I've tried this and I cannot reproduce this: In the linked example, the helper returns true in both cases.
