### ISSUE TITLE
Variable not updated on res.render(variable)

### ISSUE THREAD

**Issue by goldern** [wycats/handlebars.js#1538]
I have the following code, where 'message: data' variable should be updated each second:
```
// What happens when a message is received:
    socket.on("message", (data) => {
        console.info(`Received message`);

        app.get('/', function (req, res) {
            testBuff = new Buffer.from(data, 'iso-8859-1').toString('base64');
            var result = "data:image/jpg;base64," + testBuff;
            //console.log(result);
            res.render('index', {message: result} );
        });
    });
```
and the following Handlebars template:
```
<!DOCTYPE html>
<html>
	<head>
		<title>Handlebars load template</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
		<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
		<script src="handlebars_dynamic_loader.js"></script>
		<script>
			document.getElementById("ItemPreview").src = '"'+{{message}}+'"';
		</script>
	</head>

	<body>
		<img id= "ItemPreview" src= {{message}}>
	</body>
	
</html>
```
But even when the socket receives a new value, it doesn't update handlebars value to reflect that, even on page refresh.
Is this a bug or do I need to use another logic to implement dynamic values in variables?

**Comment by goldern** [comment]
Fiddle: https://jsfiddle.net/w1spbm2t/

**Comment by goldern** [comment]
Related: https://stackoverflow.com/questions/33069113/node-js-res-render-wont-update-view-on-browser

**Comment by nknapp** [comment]
Like in the stack-overflow answer: `res.render` renders the result to the HTTP response. It does not do anything client side on the browser. You need your own mechanism to update the page.

To be honest, if that is a requirement, I would use another SPA framework like Ember, Vue, React, Angular or Ractive.
