### ISSUE TITLE
Use helpers inside <script> template

### ISSUE THREAD

**Issue by vladislav-vasilyev** [wycats/handlebars.js#1542]
I use handlebars with keystone.js. So to embed values inside my `<script>` templates I add `/` before handlebars expressions. Like this:
`<script id="main-post-card-template" type="text/x-handlebars-template">`
&nbsp;&nbsp;&nbsp;`<img src="/{{mainImage}}">`
`</script>`
The problem is embedding of helper value. I tried to use default cloudinaryUrl helper but it doesn't work:
`<script id="main-post-card-template" type="text/x-handlebars-template">`
&nbsp;&nbsp;&nbsp;`<img src="\{{{cloudinaryUrl mainImage quality='auto' format='jpg'}}}"`
`</script>`
 I see `Missing helper: "cloudinaryUrl"` message in my console.
How can I fix it?

**Comment by nknapp** [comment]
This seems to be a question for keystone.js rather than for Handlebars.
