### ISSUE TITLE
add handlebars in script tag

### ISSUE THREAD

**Issue by Monkeyyy11** [wycats/handlebars.js#1543]
Hello I have a website with a script tag here:
```
<script>
    // Administration ajax script
    (function ($) {
        function processForm(e) {
            var name = this.name;
            $(`#${name}`).attr('disabled', 'disabled');
            $.ajax({
                url: `/dashboard/${guildid}/administration/${name}`,
                dataType: 'text',
                type: 'post',
                contentType: 'application/x-www-form-urlencoded',
                data: $(this).serialize(),
                success: function (data, textStatus, jQxhr) {
                    notifySuccess();
                    $(`#${name}`).removeAttr("disabled");
                },
                error: function (jqXhr, textStatus, errorThrown) {
                    console.log(errorThrown);
                    notifyError();
                    $(`#${name}`).removeAttr("disabled");
                }
            });
            e.preventDefault();
        }
</script>
```
Now what I want to add is {{test}} which is a simple string, how can I do that? I couldn't find an issue which had this problem. I checked also the documentation but without success.

Thanks!

**Comment by nknapp** [comment]
I don't understand what you are trying to do with Handlebars here. Does this example help you?

https://jsfiddle.net/L3ynz8ow/2/

**Comment by Monkeyyy11** [comment]
Oh yea I think this will help me! Thanks! @nknapp

**Comment by Monkeyyy11** [comment]
Normally the disable and enable should be a string but it is only an empty string: https://i.imgur.com/aaBlm4E.png

In another file I have the same but it's placed on top of the html code and there it works fine. How is this possible?

**Comment by nknapp** [comment]
I'm sorry, but I still don't understand how your question is related to Handlebars. I don't see any use of Handlebars in your example. If you think, you can explain better in German, that would be OK too.

**Comment by nknapp** [comment]
Closing, because I don't understand the issue, and it's been 10 days
