### ISSUE TITLE
If helper can generate several syntax errors that aren't very useful

### ISSUE THREAD

**Issue by ErisDS** [wycats/handlebars.js#1548]
If you write a malformed `{{#if}}` helper with too many arguments, you get weird syntax errors that are different depending on just how you malformed the helper:

`{{#if anything_goes_here "string"}}`

>cannot read property 'includeZero' of undefined

`{{#if anything_goes_here undefined}}`

> Cannot read property 'hash' of undefined

`{{#if anything_goes_here null}}`

> Cannot read property 'hash' of null

Here's a JS Fiddle demonstrating these errors
https://jsfiddle.net/m5a9q3b0/3/

Obviously, the if statement examples are incorrect, but the varied weird errors that get generated are the problem. In Ghost themes we regularly see all 3 of these errors, and it's clear noone understands what they mean or how to fix them.

We just added an ugly workaround to Ghost you can [see here](https://github.com/TryGhost/Ghost/commit/708927335be96d850e4a97e4d883e0848031e681#diff-4a0ce8c3ce27b90a1098e0509a2a6a2cR42)

**Comment by nknapp** [comment]
related to #1549

**Comment by nknapp** [comment]
Released in 4.5.0
