### ISSUE TITLE
ASK: "#" symbol make the rest of handlebars code goes white blank

### ISSUE THREAD

**Issue by user14045** [wycats/handlebars.js#1554]
Hello, I am sorry if I ask a very simple thing, but I couldn't find the solution. I tried to use handlebars for the template of generating PDF along with Puppeteer. Everythings went fine until I have to display some special characters in my template. If I directly use this code in my template.hbs:

```
<body>
   <div>
      My Special Characters: #`~!@$%^&*()_-+={}[]\|;:'",<.>?/
   </div>
   {{!-- other codes --}}
<body>
```

everythings after ```#``` not rendered. Only white blank. But, if I remove the ```#```, everythings displayed. Thats the case if the ```#``` is static.

Another case is if ```#``` symbol presents in a string variable. If I have a variable:

```const myString = '#`~!@$%^&*()_-+={}[]\|;:'",<.>?/';```

and passed to template.hbs and displayed like this:

```<div>{{{myString}}}</div>``` -- using triple-stash to avoid ```myString``` being escaped if I use only double-stash. It will also display blank spash after the ```#``` symbol. But everythings fine if I remove the ```#```.

I've read [https://handlebarsjs.com/expressions.html](https://handlebarsjs.com/expressions.html) which mention that ```#``` is whitespace. Then, any work around for my problem, please? I need to display this ```#``` symbol.

Thank you in advance.

**Comment by nknapp** [comment]
If you refer to the section

> Identifiers may be any unicode character except for the following: Whitespace ! " # % & ' ( ) * + , . / ; < = > @ [ \ ] ^ ` { | } ~

Then this should not be your problem: If means that "whitespace"  and the other mentioned characters (including `#`) are not allowed as part of an expression (i.e. `{{prop#ertry}}` is not allowed).

The code 

```js
const myString = '#`~!@$%^&*()_-+={}[]\|;:'",<.>?/';
```
does not work, because you have to escape the `'` character in your string.

```js
const myString = '#`~!@$%^&*()_-+={}[]\|;:\'",<.>?/';
```

in any case, I could not reproduce this behavior: Please create a jsfiddle using the following template: 

https://jsfiddle.net/0L92ufpv/

**Comment by user14045** [comment]
I've open and try the snippet based on your template. Everythings fine on the jsfiddle. So, I want to try to share some of my code of the template and how I pass the parameter.

```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <style>
    {{!-- css goes here --}}
  </style>
</head>

<body>
  <div>
    <div>
      <h1>TITLE</h1>
    </div>

    <div>
      <div>
        <table>
          <thead>
            <th>
              header1
            </th>
            <th>
              header2
            </th>
            <th>
              header3
            </th>
          </thead>
          <tbody>
            {{#each sampleData as |dataVariable|}}
            <tr>
              <td>
                {{dataVariable.value1}}
              </td>
              <td>
                {{dataVariable.value2}}
              </td>
              <td>
                {{dataVariable.value3}}
              </td>
            </tr>
            {{/each}}
          </tbody>
        </table>
      </div>
    </div>

  </div>
</body>
</html>
```

Above code, is lies in a file named myTemplate.hbs (in .hbs format, not in .html. One of my reason is to get the for loop feature). And here, is how I pass the parameter:

```
export const pdfMaker = async (): Promise<any> => {
  try {
    const browser = await puppeteer.launch({
      headless: true,
      // another config
    });

    const compile = async (data: any) => {
      const filePath = path.resolve(`${process.cwd()}/path/to/template/myTemplate.hbs`);
      const html = fs.readFileSync(filePath, 'utf8');
      return handlebars.compile(html)(data);
    };

    const page = await browser.newPage();

    const sampleData = [{
      value1: '1-1',
      value2: '1-2',
      value3: '1-3',
    }, {
      value1: '2-1',
      value2: '#2-2',
      value3: '2-3',
    }, {
      value1: '3-1',
      value2: '3-2',
      value3: '3-3',
    }];

    const data = {
      sampleData,
    };

    const content = await compile(data);

    await page.goto(`data:text/html;charset=UTF-8,${content}`, {
      waitUntil: ['domcontentloaded', 'networkidle0', 'load', 'networkidle2'],
    });

    await page.emulateMedia('print');

    const pdf = await page.pdf({
      format: 'A4',
    });

    await browser.close();

    // code
  } catch (e) {
    // code
  }
};
```

above code, with ```#``` presence in ```#2-2``` will produce:

![image](https://user-images.githubusercontent.com/53927863/65198155-beb0d200-daac-11e9-9ba6-d4241faf54ca.png)

if I remove the ```#```, or even change it to other special character, like this:

```
const sampleData = [{
      value1: '1-1',
      value2: '1-2',
      value3: '1-3',
    }, {
      value1: '2-1',
      value2: `~!@$%^&*()_-+={}[]|\:;"'<,>.?/2-2`,
      value3: '2-3',
    }, {
      value1: '3-1',
      value2: '3-2',
      value3: '3-3',
    }];
```
it will produce:

![image](https://user-images.githubusercontent.com/53927863/65198437-4f87ad80-daad-11e9-8511-29e89d11a40d.png)

or, if I change:

```
<div>
      <h1>TITLE</h1>
</div>
```

into 

```
<div>
      <h1>#TITLE</h1>
 </div>
```

the result is only a blank page. Is this problem with handlebars file that I create? or, whats wrong here? Btw, thank you for your fast response.

**Comment by nknapp** [comment]
I think your problem is with this part 

```js
await page.goto(`data:text/html;charset=UTF-8,${content}`, {
      waitUntil: ['domcontentloaded', 'networkidle0', 'load', 'networkidle2'],
    });
```

You should use `encodeURIComponent` to encode you content into a data-url

```js
await page.goto(`data:text/html;charset=UTF-8,${encodeURIComponent(content)}`, {
      waitUntil: ['domcontentloaded', 'networkidle0', 'load', 'networkidle2'],
    });
```

**Comment by ahmdichsan** [comment]
Ah, thank you so much!

**Comment by user14045** [comment]
thank you!!
