### ISSUE TITLE
Nested #each not working

### ISSUE THREAD

**Issue by JordiOfRivia** [wycats/handlebars.js#1556]
Hi i have the following code:

`{{#each id}}{{#each ./title}} <a href="/post/{{this}}/{{./this}}">{{./this}}{{/each}}{{/each}}</a>`

but when i run this i dont see anything in my browser.

Can somebody help me with my problem?

**Comment by paulfalgout** [comment]
It looks to me like `id`s are objects containing a title.. but then you're also printing out `this` and `./this`?  It makes little sense to me what you're attempting to accomplish with this.  

What does your data look like, and what html are you trying to produce with it?

**Comment by JordiOfRivia** [comment]
So i have a title that looks like this:
This is my test post

the user can click on title
Than you come to the following page:
/post/1/This is my test post

So {{this}} is id
And {{./this}} is the title

**Comment by paulfalgout** [comment]
no, I mean that in order to understand the situation, I need from you:
data:
```json
{
   "title": "My data looks like this"
}
```
and html:
```html
<div>
  I want to produce this html
</div>
```

**Comment by nknapp** [comment]
Ideally, you would create a fiddle here: https://jsfiddle.net/0L92ufpv/

But looking at your template and formatting it like this...

```hbs
{{#each id}}
  {{#each ./title}} 
    <a href="/post/{{this}}/{{./this}}">{{./this}}
  {{/each}}
{{/each}}
</a>
```

I can see that you create an opening `<a>`-tag for each id and title, but you are only closing it once in the end. Maybe this is already the problem.
