### ISSUE TITLE
Feature Request: Flattening sources/partials for future compilation

### ISSUE THREAD

**Issue by CodyEakins** [wycats/handlebars.js#1567]
Third party email sending services (such as SendGrid and AWS SES) support Handlebars syntax in the HTML parts of their email sending APIs.

In other words, a developer can upload email templates with Handlebars syntax to their servers to be used in email sending requests.

However, this makes maintaining email templates more difficult because these 3rd party services don't always support core Handlebars features such as partials.

**I think a good addition to the Handlebars API would be some sort of method for flattening sources/a group of partials into a single HTML/Handlebars file**.

It would behave similar to compilation, except it would leave all Handlebars tags untouched except those that require external sources/files/partials.

That way, a developer can upload the result to a 3rd party email sending service, and expect them to handle the rest of the required compilations.

---

**Note:** Relying on 3rd party services for rendering helps avoid some of the overhead in rolling your own message queue and email rendering/sending server.

**Comment by nknapp** [comment]
Have you had a look at inline partials? You can define partials within your handlebars template...

**Comment by CodyEakins** [comment]
> Have you had a look at inline partials? You can define partials within your handlebars template...

I have. It doesn't really help in this use case...
Imagine having 3 different email templates with common elements (header, footer, etc.). The partials help locally with this, but are not available in the cloud environments.

What I am describing is essentially multi-stage rendering/compilation, which has a lot of benefits.

**Comment by nknapp** [comment]
That I fear that I don't fully understand your use-case. I mean: What exactly can the handlebars-library do to support your case? What is your input, what should be the output?

**Comment by jzahka** [comment]
AWS does support inline partials. It would be helpful to be able to convert references to partial templates into inline partials.

For example, extract the template from `header.hbs` and `footer.hbs` and inline them
``` handlebars
{{#*inline "header"}}
<h1>Example Header</h1>
{{/inline}}


{{#*inline "footer"}}
<div>Unsubscribe: {{ unsub_link }}</div>
{{/inline}}


// main.hbs:
{{> header }}

<div>
  Fancy, dynamic body content with variables: {{ foo }}
</div>

{{> footer }}
```

**Comment by nknapp** [comment]
So you have a bunch of handlebars template files  and partial-files in your project directory and you want a tool to generate a template with inline-partials for each template file in order to store them in your AWS mail templates?

**Comment by nknapp** [comment]
I can see the value of such a tool. But I think it should not be part of the core Handlebars project.

At the moment, Handlebars has no logic for locating partial files in the filesystem. The single purpose of the CLI tool is to precompile templates to JavaScript. What you describe could be an external tool, like the webpack handlebars-loader.

I am not even sure if you need a dependency to the handlebars project to implement that. Maybe to identify partial calls in the templates.
