### ISSUE TITLE
Exception fields are missing in the typings

### ISSUE THREAD

**Issue by nknapp** [wycats/handlebars.js#1576]
The file `lib/handlebars/exception.js` defines a couple of properties for exceptions.

There is also a `function Exception(...)` in `types/index.d.ts`, but it does not contain any properties.

The goal of this issue is be to define the appropriate properties on the `Exception` prototype in the typings.

**Comment by kabirbaidhya** [comment]
@nknapp I am working on this one.

**Comment by nknapp** [comment]
This is fixed
