### ISSUE TITLE
Is it possible to use an inline partial as a partial block?

### ISSUE THREAD

**Issue by migmuni** [wycats/handlebars.js#1581]
Hello, I've run into an issue using Handlebars where I have an inline partial that I would like to use as a block. When I call it as a block, the inline partial's contents do not get inserted at `{{@partial-block}}`, instead just replacing the entire block.
I set up a simple fiddle set up showing my issue here: https://jsfiddle.net/3se4q26d/8/

This Handlebars:
```hbs
{{#*inline 'paragraph'}}Text{{/inline}}

{{#> paragraph}}
<p style="color: red;">{{> @partial-block}}</p>
{{/paragraph}}
```
Renders this:
```html
Text
```
When I expected this:
```html
<p style="color: red;">Text</p>
```
Is this some sort of bug or an intentional decision? I have some workarounds for this, like creating an extra partial or using a conditional statement and a parameter, but I was wondering if this would work.

**Comment by nknapp** [comment]
I find this example difficult to understand. Could you edit the issue description and strip down the example? It should contain only the minimal data to reproduce the issue, with all the surplus div tags and attributes

**Comment by nknapp** [comment]
I think it is a misunderstanding.This is what you probably want to really do: https://jsfiddle.net/se4aox9p/

```hbs
{{#*inline 'paragraph'}}<p style="color: red;">{{> @partial-block}}</p>{{/inline}}

{{#> paragraph}}
Text
{{/paragraph}}
```

The `@partial-block` must be defined inside the partial and it is the place where the contents of the partial-call is inserted.
