### ISSUE TITLE
Helper "this" is empty

### ISSUE THREAD

**Issue by tjblackheart** [wycats/handlebars.js#1582]
Hi,

I have a build a helper like this:

```
import showdown from 'showdown'
import Handlebars from 'handlebars'

const md = new showdown.Converter({ simpleLineBreaks: true })

Handlebars.registerHelper('markdown', options => {
  console.log(options.fn(this))
  return md.makeHtml(options.fn(this))
});

export default class SomeClass { ... }
```

If I use this helper in the template via `<div class="content">  {{#markdown}} {{ content }} {{/markdown} </div>`, it does nothing, because `this` is empty.

Am I missing something here?

Btw: The content is availabe in `options.data.root[options.data.index].content`, but that defies the whole helper idea.

**Comment by nknapp** [comment]
I you want use "this", you need to declare a full function 

```
Handlebars.registerHelper('markdown', function () {
});
```
see https://hackernoon.com/javascript-es6-arrow-functions-and-lexical-this-f2a3e2a5e8c4

**Comment by tjblackheart** [comment]
oh damn ... you are completely right. :) thank you and sorry.

**Comment by nknapp** [comment]
don't worry about it.
