### ISSUE TITLE
Ability to re-render the partial without rendering the parent along with the partials template

### ISSUE THREAD

**Issue by aimyth** [wycats/handlebars.js#1612]
When using partials, the structure of the view or page would be as follows

View1
    &nbsp;&nbsp;partial1
    &nbsp;&nbsp;partial2
    &nbsp;&nbsp;partial3
After rendering the view1 if due to a selection one needs to re-render the partial1, there should be an ability to render only this section instead of re-rendering the entire View1.

**Comment by nknapp** [comment]
Partial rendering is not a use-case for Handlebars. In your case, you can do it yourself using multiple templates instead of partials. But I would strongly suggest to use Ember (if you want to use Handlebars-syntax), Vue.js, React or Angular for in-browser rendering.

**Comment by aimyth** [comment]
I don't agree with this view. One of the reason handlebar is not able to render partials is due to the assumption that all data including the partials should be provided to the parent template.

If one has to use multiple templates which is the current workaround, namely have these template present separately. The parent can't include these partials, we need to know the Ids where the rendered content of the template should go.
Parent
       content Id 1 for Template 1 content
       content Id 2 for Template 2 content

Handlebar
      Template1
      Template2

Pass template 1 data and render Template 1. Then using Jquery or other framework this needs to be substituted into parent content id 1. Basically we now need to do this outside nullifying the enhanced use cases for partials for dynamic content.

I am closing this as the current direction for partials is to keep it simple. If enhanced we could relook at this use case.

**Comment by nknapp** [comment]
I have never used it myself, but maybe 'glimmer-vm' is more appropriate to your case.

**Comment by nknapp** [comment]
Its use case is to render and incrementally update a handlebars template in a website. It is used by ember.js
