### ISSUE TITLE
Can't show value of property with name contain square brackets

### ISSUE THREAD

**Issue by trieu-hphuc96** [wycats/handlebars.js#1613]
Please, help me! How can I show value of property 'last-name[]', this is just an example
![image](https://user-images.githubusercontent.com/22952175/49028705-98484000-f1d5-11e8-8012-6fa3342abd49.png)

**Comment by nknapp** [comment]
If you still have that question, please add a complete example including the input and the expected output.

Maybe you need to use the "lookup"-helper: https://handlebarsjs.com/guide/builtin-helpers.html#lookup
