### ISSUE TITLE
helperMissing misinformation

### ISSUE THREAD

**Issue by sgbeal** [wycats/handlebars.js#1614]
According to:

http://handlebarsjs.com/builtin_helpers.html

The `helperMissing` helper says:

> Internal helper that is called when a potential helper expression was not found in either the environment helpers or the current context.

That's not entirely true: it's also (very unfortunately) triggering (with 379172e) for fields which exists but have a value of `null`. This is forcing me to loop over all my input data beforehand and replace nulls with empty strings :(. Interestingly, this only appears to affect `{{blah}}` references, not `{{foo.blah}}` references.

**Comment by nknapp** [comment]
The commit you have referenced is a merge commit from 4.x to the master. It cannot be responsible for this problem. Can you identify the correct commit?

Please also provide a working example in the fiddle.

**Comment by sgbeal** [comment]
It's been far too long for me to remember what this was even about - i'm no longer using Handlebars, so can't add any relevant info about it and will close this ticket.

**Comment by nknapp** [comment]
OK. Thanks. I didn't want to close it without trying to make sense of it.
