### ISSUE TITLE
Documentation for escape sequence

### ISSUE THREAD

**Issue by andychlee** [wycats/handlebars.js#1615]
There doesn't seem to be any documentation on the escape sequence `\{{ }}` for handlebars. As shown in this  [stackoverflow answer](http://stackoverflow.com/a/18602782), it is really useful when using handlebars on both the client and the server.

**Comment by nknapp** [comment]
Can someone check if those docs are there on the new site, and add a small example in the right place if they aren't.

**Comment by ole-martin** [comment]
https://handlebarsjs.com/guide/expressions.html#escaping-handlebars-expressions
That one should cover it, right?

**Comment by nknapp** [comment]
right, thanks
