### ISSUE TITLE
Precompiling Templates dead link

### ISSUE THREAD

**Issue by DanielOberlechnerBrandnamic** [wycats/handlebars.js#1616]
Hi,
I tried to click on the link in the main description but it is a dead link.
Someone should change it.

Thank you. :)

"Precompiling Templates
Handlebars allows templates to be precompiled and included as javascript code rather than the handlebars template allowing for faster startup time. Full details are located here."

**Comment by nknapp** [comment]
Can you try this again? I have deployed the new documentation-page on Sunday. Maybe the old page is still cached in your browser.

**Comment by DanielOberlechnerBrandnamic** [comment]
I tried it again even in different browsers but it is still there. (cleared the cache in Chrome but no changes) ... 
There must be something wrong ...

Greets

**Comment by nknapp** [comment]
Could you post a screenshot of the page that contains the link?

**Comment by DanielOberlechnerBrandnamic** [comment]
![error github handlebars](https://user-images.githubusercontent.com/57362803/69937825-05bf3880-14dc-11ea-9f68-5d6dcb6f906c.PNG)

Here you can see the defect link ...

Greets,
Daniel

**Comment by nknapp** [comment]
Ah, I thought you where on the homepage, not on in a file on GitHub. You are right, that's indeed not fixed, but the linke PR will do it.

**Comment by nknapp** [comment]
should be corrected by now
