### ISSUE TITLE
Whitespace

### ISSUE THREAD

**Issue by ghost** [wycats/handlebars.js#162]
There appears to be some additional newlines added to template partials, and I think Handlebars would benefit from removing them. Consider the following template code:

``` html
<ul>
{{#people}}
  {{> person}}
{{/people}}
</ul>
```

And the following template partial:

``` html
<li>{{name}} is cool!</li>\n
```

Below is the generated code from Handlebars. In the partial there's only one line feed at the end:

```
<ul>

  <li>Troy Phelan is cool!</li>


  <li>Rachel Lane is cool!</li>


  <li>Josh Stafford is cool!</li>


</ul>
```

The following code is compiled from a mustache compiler provided by Twitter, using the exact same template & partial:

```
<ul>
  <li>Troy Phelan is cool!</li>
  <li>Rachel Lane is cool!</li>
  <li>Josh Stafford is cool!</li>
</ul>
```

I believe, the latter is the proper way of rendering the mustache code in the template & partial. Here's [the script](http://paste.pocoo.org/show/533149/), in case you guys are interested on testing.

I tried forking and submitting a pull request, but I wasn't able to figure out where the extra line feeds are being added. 

Hope this helps!

**Comment by gabrielaldana87** [comment]
Has the whitespace issue been resolved? I'm trying to use the helper ~ as in {{ position ~ }} as indicated in the handlebars documentation, yet it still appends a whitespace after my locals are passed. Is there a way to resolve it using a helper? .trim() or another combination of RegEx .replace isn't working either.

  ``{{position ~}}

returns..

"position "

**Comment by kpdecker** [comment]
@gabrielaldana87 if you are seeing bugs, please post a new issue with a jsfiddle demonstrating the issue (See CONTRIBUTING.md)
