### ISSUE TITLE
Pass @partial-block via context?

### ISSUE THREAD

**Issue by asharron** [wycats/handlebars.js#1621]
# Pass @partial-block via context?

When creating a container component, you can have it wrap partials like this:

```
//container.hbs

<div>
    {{> @partial-block }}
</div>
```

And then use it like so:

```
//container.test.hbs

{{#> container }}
    {{> anotherPartial }}
{{/container}}
```

My questions is: *Is it possible to pass the @partial-block via context?*

As in, could I do something like this:

```
context = {
    "@partial-block": "anotherPartial"
}

containerTemplate.render(context)
```

Any help or guidance would be appreciated!

**Comment by nknapp** [comment]
I don't think it will work and it's certainly not meant to work. I'm not sure what you expect the outcome to be. If you want to call the partial "anotherPartial" dynamically, you can use

```hbs
{{#> container}}
   {{> (dynamicPartial) }}
{{/container}}
```

with 

```js
context = {
  "dynamicPartial": "anotherPartial"
}
```

**Comment by asharron** [comment]
Thanks!!! I'll close this issue!
