### ISSUE TITLE
Passing 3+ params to helper?

### ISSUE THREAD

**Issue by arthabus** [wycats/handlebars.js#1632]
Hi, is it possible to pass 3+ parameters to a helper? It seems like it only sees the first two:

```
Handlebars.registerHelper('myHelper', function (param1, param2, param3) {
   return param1 + param2 + param3;
}
```

in template:
`{{myHelper '1' '2' '3'}}` //removed commas as per the comment below since it was a misspell here

`param3` is always `undefined`.

Am I doing it wrong?

**Comment by dhollenbeck** [comment]
Remove the commas:
```html
{{myHelper '1' '2' '3'}}
```

**Comment by arthabus** [comment]
Oh, yeah, thanks @dhollenbeck - it was a misspell in the question, I don't have the commas in my app actually, updated the question to fix that.

Though I seem to find the problem - I was passing a variable as a parameter which was not present in the current context. Once added, the problem was fixed and all three params were populated.

I was just googling for this and all the examples were presented with up to 2 variables, so it started to look like that's the limit.
