### ISSUE TITLE
Help - Erro com o handlebars JS - 

### ISSUE THREAD

**Issue by rafaelmrd** [wycats/handlebars.js#1643]

**Comment by rafaelmrd** [comment]
Handlebars: Access has been denied to resolve the property "..." because it is not an "own property" of its parent

Alguém sabe me informar como eu conserto esse erro quando vou usar o handlebars ?
Erro:
Pt-Br: handlebars: acesso negado para resolver a propriedade "nome" porque não é uma "propriedade própria" de seu pai.
Você pode adicionar uma opção de tempo de execução para desativar a verificação ou este aviso:


Does anyone know how to report this error when you use the handlebars?
Mistake:
En: handlebars: access denied to resolve the "name" property because it is not your father's "own property".

You can add a runtime option to disable verification or this warning:

**Comment by nknapp** [comment]
Please read the description of #1642 and then add a comment there.

**Comment by nknapp** [comment]
ah, you already did. I'll close this as a duplicate of #1642
