### ISSUE TITLE
Download links to aws broken on handlebarsjs.com - access denied

### ISSUE THREAD

**Issue by Tea56** [wycats/handlebars.js#1644]
Hi, 

the links to your aws hosting are broken for current and older releases, with an error of access denied or no such key

`<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>handlebars-v4.7.2.js</Key>
<RequestId>8DCB30AE44FAFD96</RequestId>
<HostId>
1wCpZQl+9nRfy3qB75XqmHssl1nKPA8jQinZ6Gi4KpbkvLjrtEATKexCer3NEfusZg+rBERbwsQ=
</HostId>
</Error>`

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>9D3E4113CAD50B45</RequestId>
<HostId>
hPeYQjkmtZ0H2dxAYsmoxfiYXUAmbu/yqXWgM3GWnDXh3sZ5zyIHfxBVTICNweZnrgaBdunlRPQ=
</HostId>
</Error>`

https://handlebarsjs.com/installation/#npm-or-yarn-recommended

build page
https://com.s3.amazonaws.com/builds.handlebarsjs/bucket-listing.html?sort=lastmod&sortdir=desc

Figured you should know!

Thanks,

t.

**Comment by nknapp** [comment]
There was an error in the deployment code that I had refactored a month ago. I uploaded all missing versions (4.6.0, 4.7.0, 4.7.1, 4.7.2) after fixing the code. Thanks for the notice.

**Comment by nknapp** [comment]
Released in 4.7.3

**Comment by tchaton** [comment]
Got the error in 4.7.6.
