### ISSUE TITLE
Create helpers inline?

### ISSUE THREAD

**Issue by leosdad** [wycats/handlebars.js#1645]
Hi,

I need to convert colors for an HTML template, so I'm declaring this partial:

`{{#*inline "color"}}{{ lookup app.colors value }}{{/inline}}`

and calling it like this:

`class="{{> color value=app.content.color }}"`

It works nicely, but I find the syntax a bit overwhelming. It would be much nicer to write:

`class="{{ color app.content.color }}"`

I know I can use **registerHelper()** for that, but I'd like to handlebars itself to declare the helper as I'm doing the partial above. Is there a way to do this?

Sorry if this was asked before, and many thanks in advance. Keep up the nice work!

**Comment by nknapp** [comment]
You can do 

```hbs
{{#*inline "color"}}{{ lookup app.colors . }}{{/inline}}
```
or 
```hbs
{{#*inline "color"}}{{ lookup app.colors this }}{{/inline}}
```
and then call is using

```hbs
class="{{> color app.content.color }}"
```
but I always prefer the `value=`-syntax, because it allows you to clearly state what kind of parameter
your partial is expecting.

You won't get rid of the `>` when calling the partial. A helper is just something different.

**Comment by leosdad** [comment]
Thanks for the clarification! I didn't know about the shorthand, it's almost exactly the same I've asked for.
