### ISSUE TITLE
Property 'VERSION' does not exist on type 'typeof Handlebars'

### ISSUE THREAD

**Issue by leosdad** [wycats/handlebars.js#1647]
Hi,

Just a simple request. When calling `handlebars.VERSION`, the error message **Property 'VERSION' does not exist on type 'typeof Handlebars'** appears when using Typescript. I believe this is just a simple fix in the index.d.ts file. Thanks.

**Comment by nknapp** [comment]
Can you open a PR for that? Please also include a test. It would also be nice to have the documentation updated (the API reference on handlebarsjs.com) to include this feature.

**Comment by papasmile** [comment]
Hi, sorry, how do you run tests in `test.ts` anyway?

**Comment by nknapp** [comment]
`npm run check-before-pull-request` should include the tests. Otherwise, run `npm run dtslint`

**Comment by nknapp** [comment]
published in 4.7.3

**Comment by leosdad** [comment]
> published in 4.7.3

Thanks!!
