### ISSUE TITLE
Access has been denied to resolve the property "img" because it is not an "own  property" of its parent.

### ISSUE THREAD

**Issue by xreider** [wycats/handlebars.js#1648]
Hello! I am a new in Node.js

Please, help me to rewrite my code

I have this problem with express-handlebars and mongoose

### I tried to solve this problem with [this webpage](https://www.npmjs.com/package/@handlebars/allow-prototype-access#usage--express-handlebars-and-mongoose-)
 But I got "Cannot find module '@handlebars/allow-prototype-access'" warning 
  I am a new to rewrite it now, just help me, please!

**index.js file**
```

const express = require("express");
const path = require('path');
const mongoose = require('mongoose');
const exphbs =  require('express-handlebars');
const homeRouts = require('./routes/home');
const cartRoutes = require('./routes/cart');
const addRoutes = require('./routes/add');
const coursesRoutes = require('./routes/courses');

const app = express();
const hbs = exphbs.create({
  defaultLayout: 'main', 
  extname: 'hbs',
});
app.engine('hbs', hbs.engine); 
app.set('view engine', 'hbs');
app.set('views', 'views');

app.use(express.static(path.join(__dirname, 'public')));
app.use(express.urlencoded({extended: true}));
app.use('/', homeRouts);
app.use('/add', addRoutes);
app.use('/courses', coursesRoutes);
app.use('/cart', cartRoutes);

const PORT = process.env.PORT || 3000;

async function start() {
  try {
    const url = `****`;
    await mongoose.connect(url, {useUnifiedTopology: true, useNewUrlParser: true, useCreateIndex: true});
    app.listen(PORT, () => {
      console.log(`Listen to ${PORT}`);
    });
  } catch(e) {
    console.log(e)
  } 
};

start();

```
**package.json file**
```
{
...
  "dependencies": {
    "express": "^4.17.1",
    "express-handlebars": "^3.1.0",
    "handlebars": "^4.7.2",
    "mongoose": "^5.8.11",
    "uuid": "^3.4.0"
  },
  "devDependencies": {
    "nodemon": "^2.0.2"
  }
}

```

**Comment by craj1031tx** [comment]
When I try to use the allow-prototype-access extension for handlebars in my express-handlebars application, I get a "Error: Module "handlebars" does not provide a view engine."

```
var express = require('express')
var Handlebars = require('handlebars')
var expressHandlebars = require('express-handlebars')
var {allowInsecurePrototypeAccess} = require('@handlebars/allow-prototype-access')

const app = express()
app.engine('hbs', expressHandlebars({
    //defaultLayout: 'main',
    handlebars: allowInsecurePrototypeAccess(Handlebars)
}));
app.set('view engine', 'handlebars')
```

**Comment by nknapp** [comment]
You are using

```js
app.engine('hbs', ...
``` 
in one place and 

```js
app.set('view engine', 'handlebars')
```
in the other. Try using either `handlebars` or `hbs`, but do not mix them.

**Comment by nknapp** [comment]
I'll update the readme of the package.

**Comment by xreider** [comment]
> I'll update the readme of the package.

You mean I need to delete `app.set('view engine', 'hbs');` ?
I deleted it, but it doesn't work.
Let's rewrite my code to make it work, please

**Comment by nknapp** [comment]
@xreider can you show me how you tried to make it work? Your code doesn't contain the `@handlebars/allow-prototype-access`-package at all. Your error message suggests that you haven't run `npm install @handlebars/allow-prototype-access` at all.

**Comment by nknapp** [comment]
The rest of your code looks good, as long as your files have the extension `.hbs`. Try the following: 

1) Run 

    ```bash
    npm install @handlebars/allow-prototype-access
    ```

2) add the following to the beginning of of your file.

    ```js
    const Handlebars = require('handlebars')
    const expressHandlebars = require('express-handlebars'); 
    ```

3) change the line 

    ```js
    const hbs = exphbs.create({
      defaultLayout: 'main',  
      extname: 'hbs',
    });
    ```
    to
    ```js
    const hbs = exphbs.create({
      defaultLayout: 'main', 
      extname: 'hbs',
      handlebars: allowInsecurePrototypeAccess(Handlebars)
    });
    ```

**Comment by xreider** [comment]
You helped me a lot! Thank you very much! You made me believe in miracles.

**Comment by craj1031tx** [comment]
Nils, that fix worked for me, I appreciate the help. I am indeed using .handlebars as my extension type for my templates. Providing 'hbs' as an argument even when using .handelbars as your extension name when using just the express-handlebars was working (and is actually what the express-handlebars documentation states) but I guess when using this updated package the `app.set('view engine', ARG2)` must be paired with the exact extension name. I appreciate your help on this, thank you.

**Comment by BigUhoTape** [comment]
Thank for ur advice:)

**Comment by Edgar-hub-bit** [comment]
You helped me a lot! Thank you very much!

**Comment by sindri55** [comment]
Thanks a lot nknapp. Tell me, have we then prevent to possible create these security holes? 
ref. https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access

**Comment by nknapp** [comment]
If you allow your users to create templates and execute those templates in your Node.js server, then your users may be able to crash your machine, or possiblty inject code (if there is a new way of doing so, the publicly known ways should still be impossible with this setting).

**Comment by pankkap** [comment]
Its working. Thanks brother

**Comment by DilushkumarVasu** [comment]
Thank you very much, bro. You are the only person giving me the correct solution

**Comment by washedupdino** [comment]
@nknapp thank you so much!! been stuck on this for longer than I would like to admit

**Comment by renato462** [comment]
Thank you so much, I needed help !!!!!!! after 10 hour It was solved. Thank a lot.

**Comment by andreolllem** [comment]
Show de bola! Valeu!

**Comment by Bohda-P** [comment]
It helped me so much, you gave useful infirmation. Thank you!!!

**Comment by Tarekmohammed109** [comment]
Hi,
It still give me the same error any help please!

**Comment by mgorodokin** [comment]
> You are using
> 
> ```js
> app.engine('hbs', ...
> ```
> 
> in one place and
> 
> ```js
> app.set('view engine', 'handlebars')
> ```
> 
> in the other. Try using either `handlebars` or `hbs`, but do not mix
> 
> Update: Sorry, no, this is not the problem. I have used this code in the same way. I have to test it.
> 
> Update 2: I wasn't that wrong... The solution is to use `app.engine('handlebars', ...)`. You need to do this if you use `.handlebars` as extension of your views, and not `.hbs`. 

Hi, I'm also new to JS and handlebars and having trouble implementing the @handlebars/allow-prototype-access' package. Could you please help? This is my current code, I'm not sure how to implement the allow-prototype-access package into my existing app.engine.

```
const express = require('express');
const mongoose = require('mongoose');
const path = require('path');
const hbs = require('express-handlebars');
const {mongoDbUrl, PORT} = require('./config/configuration');
const flash = require('connect-flash');
const session = require('express-session');
const {selectOption} = require('./config/customFunctions');
const fileUpload = require('express-fileUpload');
const methodOverride = require('method-override');
const {allowInsecurePrototypeAccess} = require('@handlebars/allow-prototype-access');

const app = express();

/* Configure Mongoose to Connect MongoDB */
mongoose.connect(mongoDbUrl, { useNewUrlParser: true })
    .then(response => {
        console.log("MongoDB Connected Successfully.", { useNewUrlParser: true });
    }) .catch(err => {
        console.log("Database connection failed", err)
    });



/* Configure express*/
app.use(express.json());
app.use(express.urlencoded({extended: true}))
app.use(express.static(path.join(__dirname, 'public')));

/*flash and session*/
app.use(session({
    secret: 'anysecret',
    saveUninitialized: true,
    resave: true
}))

app.use(flash());

app.use(globalVariables);

app.use(fileUpload({
    limits: { fileSize: 50 * 1024 * 1024 },
  }));

/* Setup View Engine To Use Handlebars */
app.engine('handlebars', hbs({defaultLayout: 'default', helpers: {select: selectOption}}));
app.set('view engine', 'handlebars');
```

**Comment by rhythm98** [comment]
When I visit http://localhost:2323/dishes data doesn't get populated
![Web Preview on visiting http://localhost:2323/dishes](https://user-images.githubusercontent.com/68167456/118397692-e33ec200-b672-11eb-895f-66be735bcb45.png)  

Console Error
![Screenshot from 2021-05-16 18-17-41](https://user-images.githubusercontent.com/68167456/118397728-15502400-b673-11eb-8200-5f4b3b63cdb3.png)


> ### package.json
```
"dependencies": {
  "dotenv": "^9.0.2",
  "express": "^4.17.1",
  "express-hbs": "^2.3.4",
  "express-session": "^1.17.1",
  "mysql2": "^2.2.5",
  "passport": "^0.4.1",
  "passport-local": "^1.0.0",
  "sequelize": "^6.5.0",
  "uuid": "^8.3.2"
},
"devDependencies": {
  "chai": "^4.3.4",
  "debug": "^2.6.9",
  "eslint": "^7.18.0",
  "eslint-config-standard": "^16.0.2",
  "eslint-plugin-import": "^2.23.1",
  "eslint-plugin-node": "^11.1.0",
  "eslint-plugin-promise": "^4.2.1",
  "eslint-plugin-react": "^7.22.0",
  "eslint-plugin-standard": "^5.0.0",
  "mocha": "^8.4.0",
  "nodemon": "^2.0.7",
  "nyc": "^15.1.0",
  "request": "^2.88.2"
}
```
> ### Project Structure
- src (Backend)
	- controllers (functions to execute sql queries)
		- dishes.js (fetchDishes, fetchDishById, createDish)
		- users.js (fetchUsers, fetchUserById, createUser)
	- models
		- db.js (creating table users, dishes)
	- routes
		- api
			- dishes.js
			- users.js
			- index.js
		- pages
			- dishes.js
			- index.js
	- run.js
	- server.js
- views
	- layouts
		- main.hbs
	- pages
		- dishes
			- id.hbs	
		- dishes.hbs


> ### server.js
```
const { static } = require('express')
const express=require('express')
const app = express()
const path=require('path')
const hbs = require('express-hbs')

const session=require('express-session')
const passport=require('./auth/passport')
const { pass } = require('./auth/strategies/passport-local-strategy')
app.use(passport.initialize())
app.use(passport.session())

app.use('/',express.static(path.join(__dirname,'../public')))

app.engine(
  'hbs',
  hbs.express4({
    partialsDir: path.join(__dirname, '../views/partials'),
    layoutsDir: path.join(__dirname, '../views/layouts'),
    defaultLayout: path.join(__dirname, '../views/layouts/main.hbs'),
  })
)
  
app.set('view engine','hbs')
app.set('views',path.join(__dirname,'../views'))

app.use(session({
  secret:process.env.SECRET,
  resave:false,
  saveUninitialized:false 
}))

//to make POST request
app.use(express.json())
app.use(express.urlencoded({extended:true}))

app.use('/',require('./routes/pages'))
app.use('/api',require('./routes/api'))

module.exports={
    app
}
```
> ### run.js
```
require('dotenv').config()

const { app } = require('./server')
const { db } = require('./models/db')
const log = require('debug')('app:run')
const PORT = process.env.PORT || 2323
async function run() {
  await db.sync()
  log('Database is ready')
  app.listen(PORT, () => {
    log('Server started on http://localhost:2323')
  })
}

run()

```
> ### src/models/db.js
```
const Sequelize = require('sequelize')

const db = new Sequelize('dishdb', process.env.DB_USER, process.env.DB_PASS, {
  dialect: 'mysql',
  host: process.env.DB_HOST,
  pool: {
    min: 0,
    max: 5,
  },

})

const Dish = db.define('dishes', {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: true,
    primaryKey: true,
  },
  name: {
    type: Sequelize.STRING(150),
    allowNull: false,
  },
  chef: Sequelize.STRING,
  price: {
    type: Sequelize.FLOAT,
    allowNull: false,
    defaultValue: 0.0,
  },
})

const User = db.define('users', {
  firstName: Sequelize.STRING,
  lastName: Sequelize.STRING,
  username: {
    type: Sequelize.STRING(30),
    allowNull: false,
    unique: true,
  },
  password: {
    type: Sequelize.STRING,
    allowNull: true,
  },
})
db.sync()
  .then(() => console.log('Database has been synced'))
  .catch((err) => console.error(`Error creating database: ${err}`))

exports = module.exports = {
  db,
  Dish,
  User,
}

```

> ### src/controllers/dishes.js
```
const { Dish } = require('../models/db')

async function createDish(name, chef, price) {
  if (typeof name !== 'string' || name.length < 1) {
    throw new Error('Dish name empty or undefined')
  }
  if (typeof chef !== 'string' || chef.length < 1) {
    throw new Error('Chef name empty or undefined')
  }

  if (typeof parseFloat(price) !== 'number') {
    throw new Error('Price of dish not defined')
  }
  try {
    return await Dish.create({
      name,
      chef,
      price,
    })
  } catch (e) {
    throw e
  }
}

async function fetchDishes() {
  try {
    return await Dish.findAll({
      attributes: ['name', 'chef', 'price'],
    })
  } catch (e) {
    throw e
  }
}

async function fetchDishById(dishId) {
  try {
    return await Dish.findByPk(dishId)
  } catch (e) {
    throw e
  }
}

module.exports = {
  createDish,
  fetchDishes,
  fetchDishById,
}

```
> ### src/routes/pages/dishes.js
```
const route = require('express').Router()
const { fetchDishes } = require('../../controllers/dishes')

route.get('/', async (req, res) => {
  try {
    const dishes = await fetchDishes()
    res.render('pages/dishes', { dishes })
  } catch (e) {
    res.redirect('/')
  }
})

module.exports = route
```
> ### views/pages/dishes.hbs
```
{{#each dishes as |dish|}}
  <section>
    <h1>{{dish.name}}</h1>
    <small> - by {{dish.chef}}</small>
    <div>
      {{dish.price}}
    </div>
  </section>
{{/each}}

```

**Comment by Folexy13** [comment]
> The rest of your code looks good, as long as your files have the extension `.hbs`. Try the following:
> 
> 1. Run
>    ```shell
>    npm install @handlebars/allow-prototype-access
>    ```
> 2. add the following to the beginning of of your file.
>    ```js
>    const Handlebars = require('handlebars')
>    const {allowInsecurePrototypeAccess} = require('@handlebars/allow-prototype-access')
>    ```
> 3. change the line
>    ```js
>    const hbs = exphbs.create({
>      defaultLayout: 'main',  
>      extname: 'hbs',
>    });
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    to
>    ```js
>    const hbs = exphbs.create({
>      defaultLayout: 'main', 
>      extname: 'hbs',
>      handlebars: allowInsecurePrototypeAccess(Handlebars)
>    });
>    ```

**Comment by Folexy13** [comment]
Thanks @nknapp .... you just saved from a lot of headache

**Comment by ejas404** [comment]
thankyou it worked
