### ISSUE TITLE
Inline onclick xss

### ISSUE THREAD

**Issue by jnayak1** [wycats/handlebars.js#1653]
https://stackoverflow.com/questions/60110995/handlebars-inline-onclick-safe
> I have a handlebars template running client-side that renders variables inside an inline onclick like so:
```
<script id="my-handlebars-template" type="text/x-handlebars-template">
    <button onclick="console.log('{{name}}');">Click Me!</button>
</script>
```
> The context for this handlebars template is coming from an ajax call. name was user input on the sign in screen. My question is could someone launch an xss attack by changing their name to some malicious sequence of characters? For instance if name was );alert('hello would the handlebars template run the alert? From my testing, it does. This just seems wildly easy to write insecure code.

> Here is a jsfiddle with a test. Notice how the alert is run when you click on the link );alert('hello. http://jsfiddle.net/68tme0hr/1/

I was surprised to learn that handlebars does not escape javascript. I feel like this should be highlighted somewhere in the documentation. I think there should be a warning about this somewhere. I wouldn't be surprised if there are thousands of people doing this in the wild. It's just too easy of a thing to do. I thought as long as I stayed away from using triple curly braces I was safe from xss. Turns out that is not the case. Would you consider adding a warning in the documentation about this?

**Comment by nknapp** [comment]
If you think that this is a security issue, you should not open an issue but report it to npm-security.

**Comment by nknapp** [comment]
Handlebars is not aware of JavaScript, no. Neither is it aware of HTML, actually. For example, it does not know if a mustache-expression is inside a script-tag.

Now, my two cents, in short:

1. I think mixing using Handlebars to generate client-side JavaScript-code is not a good ideas as far as code-readability is concerned.
2. I think Handlebars should not be used in the browser.
3. Please have a look at https://handlebarsjs.com/installation/when-to-use-handlebars.html for pros and contras and a list of alternative frameworks.
4. I understand that there are some cases where you do not have a choice (legacy code, for instance). But give it a thought, please.

**Now, your request:**

The documentation describes that Handlebars escapes special HTML-characters. I would have said that the docs are very clear on what is escaped, and how. But I would accept a PR that adds a *warning box* stating the JavaScript strings are not escaped. You can add that to this section: https://handlebarsjs.com/guide/#html-escaping

The other place is https://handlebarsjs.com/guide/expressions.html#html-escaping. I would accept a PR containing an exact list of escaped characters.

**Comment by jnayak1** [comment]
Hi @nknapp. I made a [PR](https://github.com/handlebars-lang/docs/pull/38) on the handlebars documentation repo for the warning box stating javascript strings are not escaped.
