### ISSUE TITLE
Escaping simple string

### ISSUE THREAD

**Issue by PitPik** [wycats/handlebars.js#1659]
Before filing issues, please check the following points first:

- [x] Please don't open issues for security issues. Instead, file a report at https://www.npmjs.com/advisories/report?package=handlebars
- [x] Have a look at https://github.com/wycats/handlebars.js/blob/master/CONTRIBUTING.md
- [x] Read the FAQ at https://github.com/wycats/handlebars.js/blob/master/FAQ.md
- [x] Use the jsfiddle-template at https://jsfiddle.net/4nbwjaqz/4/ to reproduce problems or bugs

Would it be against the standard or too much hassle to implement the following:
`{{"some <strong>text</strong>"}}` renders to `some &lt;strong&gt;text&lt;/strong&gt;` for a quick escaping of a simple string without the need of a helper.
Right now, Handlebars just ignores simple tags which only contain a string (unless it equals to an existing variable in the scope, which is in my opinion a bug).

This would be a "nice to have" but not necessary if it involves too much code to realise.

See demo: https://jsfiddle.net/p1y05m6f/

**Comment by nknapp** [comment]
Actually, it doesn't ignore the string. Using quotes is one of the ways to use invalid characters in mustache-expressions. It will look for a property named `some <strong>string</strong>` in the current context.

https://jsfiddle.net/xb1c6z2d/1/

**Comment by PitPik** [comment]
Ahhh, yes. Thanks for pointing this out. I always forget about this feature.
