### ISSUE TITLE
Use of `white-space: pre` makes for uncomfortable Handlebars-ing

### ISSUE THREAD

**Issue by lukwallace** [wycats/handlebars.js#1663]
###  Please feel free to close as necessary, I've found the solution for my issue, but it's somewhat non-ideal, and discovering made for some interesting thinking.

Issue (?): Handlebars `{{` always handles new lines in strings with preceding partials in mind. 

B/c `pre` tags use `white-space: pre` the white space inside the tag is treated differently in the browser, so when rendering content within a Handlebars content like the following:
```
<pre>{{codeExample}}</pre>
```
Any newlines in `codeExample` factors in additional whitespace from their parent partial invocations. See example here:

https://jsfiddle.net/e2kmzn56/

My workaround was to use the white space control operator on all partials leading up to the `pre` tag. I.e., in reference the example, using `{{~> example }}` instead of `{{> example }}` and `{{~> article }}` instead of `{{> article }}`.

While this solves the issue, it makes it somewhat harder to understand authorial intent for the templates. The compiled HTML here makes it look very obvious:
```
<body>
  <article>
    <div class="example">
      <pre><code>var abc = {
  a: 1,
  b: 2,
  c: 3
}</code></pre>
    </div>
  </article>
</body>
```
but the template itself looks absolutely benign...
```
	<div class="example">
		<pre><code>{{text}}</code></pre>
	</div>
```

So I'm curious if there's any interest in providing a method to bypass & trim the additional whitespace from parent partials for new lines?

E.g. with `{ text: "My text with\n  new\n  lines\n" }`,
```
        {{!-- within a partial --}}
        </div>
	<div class="example">
		<pre>
                     <code>
                         {{~~ text }}
                    </code>
                 </pre>
	</div>
```
would translate to

```
        ...
        </div>
	<div class="example">
		<pre>
                     <code>
My text with
  new
  lines
                    </code>
                 </pre>
	</div>
```

**Comment by nknapp** [comment]
There is a compile-option "preventIndent" that should turn of auto-indenting with partials.
