### ISSUE TITLE
I've got a vulnerability in my project due to optimist -> minimist dependency  

### ISSUE THREAD

**Issue by serhiyzablotskiy** [wycats/handlebars.js#1665]
I have an optimist in dependencies of handlebars@4.7.3. And now it has vulnerability with minimist.
<img width="574" alt="Screen Shot 2020-03-27 at 4 39 16 PM" src="https://user-images.githubusercontent.com/7163430/77767689-1a56ac00-704a-11ea-92fe-9a3df532a20e.png">

**Comment by createthis** [comment]
dupe of #1661

**Comment by nknapp** [comment]
See #1661
