### ISSUE TITLE
Functions support

### ISSUE THREAD

**Issue by evil-shrike** [wycats/handlebars.js#168]
Let's consider the example:

```
var source = "<ul><li>Title: {{title}}</li></ul>";
var tmpl = Handlebars.compile(source);
var vm = { title: "xyz"};
var markup = tmpl(vm);
```

This works. But instead of passing json-object I need to supply an object which has functions instead of fields:

```
var vm = {
    title: function() {
        if (arguments.length > 0) {
            this._title = arguments[0];
        } else {
            return this._title;
        }
    }
}
```

So in template I'm trying to use a function call:

```
var source = "<ul><li>Title: {{title()}}</li></ul>";
```

But this doesn't work. It throws:

```
Parse error on line 1:
<ul><li>Title: {{title()}}</li><li>Te
-----------------^
Expecting 'ID', got 'undefined'
```

What are my options?

**Comment by markomanninen** [comment]
Small change to the last one to add support for any function call on template, without argument(s) however:

[code]
Handlebars.JavaScriptCompiler.prototype.nameLookup = function(parent, name, type) {
    if (/^[0-9]+$/.test(name)) {
        return parent + "[" + name + "]";
    } else if (Handlebars.JavaScriptCompiler.isValidJavaScriptVariableName(name)) {
        return "(typeof " + parent + "." + name + " == 'function' ? " + parent + "." + name + "() : " + parent + "." + name + ")";
    } else {
        return parent + "['" + name + "']";
    }
};
[/code]

Works with a models like this:

[code]
form.feedback = {
    type: "warning"
    warning: function() {return this.type == "warning"},
    error: function() {return this.type == "error"},
    success: function() {return this.type == "success"},
    has: function() {return ["error", "warning", "success"].contains(this.type)},
}
[/code]

Note contains is not a core javascript list prototype function. Anyway in the template now you can use simple functions:

[code]
{{#if form.feedback.has}}
	{{form.feedback.type}}: 
	{{#if form.feedback.success}}ok{{/if}}
	{{#if form.feedback.warning}}stay calm{{/if}}
	{{#if form.feedback.error}}remove{{/if}}
{{/if}}
[/code]

Keeps template logic simple.
