### ISSUE TITLE
Can handlebars run in Java/Rhino? 

### ISSUE THREAD

**Issue by jeremychone** [wycats/handlebars.js#188]
I saw this commit on one of the fork: https://github.com/mmoulton/handlebars.js/commit/8909d08dfb0d0dfe15f0435c01552cbbbb9a739b

But I am not sure if that was added or not. For our application, we would like to compile our handlebars templates in the server to JS. It would be great if it could work.

**Comment by tyaginitin28** [comment]
Hey,

Can you please share the code snippet if its working fine.

Thanks
Nitin
