### ISSUE TITLE
block helper adds extra level to parent context (../..)

### ISSUE THREAD

**Issue by trask** [wycats/handlebars.js#196]
It seems you have to use ../.. to get to the parent context from inside of a block helper.  I'm not sure if this is correct or not.  It feels like the parent context should stay the same (..), similar to how the context stays the same (e.g. "block helper staying in the same context" in qunit_spec.js).  Here's a runnable html example in case I'm using the wrong terminologies and not making sense:

```
<html>
<head>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script type="text/javascript" src="http://cloud.github.com/downloads/wycats/handlebars.js/handlebars-1.0.0.beta.6.js"></script>
<script id="t" type="text/x-handlebars-template">
{{#subitems}}
  name: {{name}}<br>
  parent id: {{../id}}<br>
  {{#h}}
    (works) name: {{name}}<br>
    (doesn't work) parent id: {{../id}}<br>
    (works) parent parent id: {{../../id}}<br>
  {{/h}}
{{/subitems}}
</script>
</head>
<body>
<div id="d"></div>
<script type="text/javascript">
  var f = Handlebars.compile($('#t').html())
  Handlebars.registerHelper('h', function(options) {
    return options.fn(this)
  })
  var items = { 'id': 123, 'subitems': [{'name': 'abc'}]}
  $('#d').html(f(items))
</script>
</body>
</html>
```

Thanks,
Trask

**Comment by jt000** [comment]
@sharans - I'm confused about this as well. I have an [SO question](http://stackoverflow.com/questions/29377019/does-if-affect-the-context) related to it, but haven't gotten any response.  Seems ```{{#if}}``` *doesn't* preserve the parent context in some situations, but not sure why or when to expect it...

**Comment by kpdecker** [comment]
@jt000 There is no preserving of the parent context. `../` means use the context of the block above me. When calling `if` you create a new block, thus need another `../`, even if the execution context is not changed. I can't speak to the docs for other projects but you might want to speak with them if they are confusing.

**Comment by jt000** [comment]
@kpdecker - Thanks. That helps a lot. I just gave this a [try in jsFiddle](http://jsfiddle.net/jaytre/e4c1dkhm/) using the latest handlebars & it works as I originally expected (*#if block context is same as parent block context*). I'm not sure why it is not behaving the same in my code using assemble.io. I'll have to look into that further. Thanks again.

**Comment by mgenev** [comment]
wait what you need a helper to access the scope? That's super annoying and makes me regret choosing to use handlebars

**Comment by jebrial** [comment]
You can just do `@root.<id or other ctx item>` for anyone that stumbles on this.

**Comment by wolthers** [comment]
Correct me if I'm wrong, but I'm pretty sure that instead of calling options.fn or options.inverse with `this`, you can just call it with the root of the data that is passed to the template, so you "avoid" creating a new context.

    Handlebars.registerHelper("is",   (value, test, options) => value === test ? options.fn(options.data.root) : options.inverse(options.data.root));
    Handlebars.registerHelper("isnt", (value, test, options) => value !=  test ? options.fn(options.data.root) : options.inverse(options.data.root));
    Handlebars.registerHelper("gt",   (value, test, options) => value  >  test ? options.fn(options.data.root) : options.inverse(options.data.root));
    Handlebars.registerHelper("gte",  (value, test, options) => value >=  test ? options.fn(options.data.root) : options.inverse(options.data.root));
    Handlebars.registerHelper("lt",   (value, test, options) => value  <  test ? options.fn(options.data.root) : options.inverse(options.data.root));
    Handlebars.registerHelper("lte",  (value, test, options) => value  <= test ? options.fn(options.data.root) : options.inverse(options.data.root));
    Handlebars.registerHelper("or",   (a, b, options)        =>     a ||  b    ? options.fn(options.data.root) : options.inverse(options.data.root));
    Handlebars.registerHelper("isNull",   (value, options)   => value === null ? options.fn(options.data.root) : options.inverse(options.data.root));
