### ISSUE TITLE
if-block needs value to compare

### ISSUE THREAD

**Issue by thany** [wycats/handlebars.js#206]
I want to be able to write a resultcount like this:

{{#if count == 0}}No results{{/if}}
{{#if count == 1}}1 result{{/if}}
{{#if count > 1}}{{count}} results{{/if}}

This doesn't seems possible. Can this be made?

**Comment by jeremiahlee** [comment]
I, too, wish for basic comparisons in Handlebars. I understand the logicless philosophy. I also believe basic comparison support would be more intuitable and allow users to work more efficiently. If users in mass are moving basic comparison logic to a helper, this philosophy isn't doing them a favor or dissuading a perceived suboptimal behavior—it's just creating more work.

**Comment by thany** [comment]
@jeremiahlee Not sure if you're agreeing or disagreeing with me there, I can read your comment either way :)

Either way, I've worked with Handlebars in the past, and I've requested for them to implement a proper if-block. This resulted in an avalanche of comments about a faux philosophy that logic should remain in the model. No Handlebars developer wished to think so much as a millimeter outside of their own tiny world (there is a rude word for that, but I'll skip it).

This forced me to write a helper called "when" that does comparisons. Still no proper if-block construction, but close enough for me at the time. It did create a lot of unneccesary work for me though.

**Comment by jeremiahlee** [comment]
@thany: I agree that Handlebars should have basic comparison of two values built in. Logicless templates should not also be empathy-less.

**Comment by codeofsumit** [comment]
I'll also vote for @thany's and the other arguments. The `if` `else` statements are way too basic.
Conditional classes and `select` boxes with pre-selected `option`s should be doable with the default package of handlebars.

**Comment by mmun** [comment]
With subexpressions this is no longer an issue, e.g.

```hbs
{{#if (greater-than array.length 3)}}
  ...
{{/if}}
```

**Comment by zordius** [comment]
good example @mmun :+1:

**Comment by thany** [comment]
A bit odd, and I don't see any boolean combinators... But most of all, it doesn't change the overall standpoint of the maintainers of this project, which seems to be an unbreakable "NO LOGIC!!11!!1!1" kind of view.
