### ISSUE TITLE
[Not-quite-pull-request contribution] Template inheritance

### ISSUE THREAD

**Issue by thejohnfreeman** [wycats/handlebars.js#208]
I wrote a couple helpers that let me use template inheritance, a la Django. Since they're just helpers, they don't need to go into Handlebars proper, but I wanted to share them. Perhaps if they are deemed useful enough, someone can put in the effort to integrate them.

### Usage

The first helper is named [`block`](https://github.com/thejohnfreeman/jfdoc/blob/master/lib/utility/handlebars.js). It lets you specify default content.

The second helper is named [`partial`](https://github.com/thejohnfreeman/jfdoc/blob/master/lib/utility/handlebars.js). (I don't know why I chose these names.) It lets you specify overriding content.

In your [base template](https://github.com/thejohnfreeman/jfdoc/blob/master/templates/main.hbs), you declare sections of content that may be replaced by deriving templates. For these sections, you can either use `{{#block}}`s or normal partial inclusion (`{{>}}`). The second option serves as a shorthand for when you have no default content.

```html
<!-- base.hbs -->
<title>{{#block "title"}}Untitled{{/block}}</title>
{{> content}}
```

Then in your [deriving templates](https://github.com/thejohnfreeman/jfdoc/blob/master/templates/files.hbs), you specify any overrides with `{{#partial}}`s *before* declaring the inherited template with normal partial inclusion.

```html
<!-- derived.hbs -->
{{#partial "title"}}Title{{/partial}}
{{#partial "content"}}Hello, World!{{/partial}}
{{> base}}
```

Example output:

```html
<title>Title</title>
Hello, World!
```

**Comment by kpdecker** [comment]
Closing in favor of #1018
