### ISSUE TITLE
Can Handlebars do client side templating?

### ISSUE THREAD

**Issue by DaFrik** [wycats/handlebars.js#221]
thanks for creating handlebar. While reading your page I know how to use handlebar, but I was looking for an client side template engine, could handlebars  handle it? I saw from http://handlebarsjs.com/precompilation.html there is a <script src="/libs/handlebars.runtime.js"></script>  , what if i didn't precompile the template , could I still use that js, or there is another js i need to include to make handlebars works in a client side only mannar ? It would be great if there is a page in http://handlebarsjs.com giving out simple html structure to setup the use of handlerbars in the client side.

Thanks.

**Comment by maxkoryukov** [comment]
Hello!

Strange, but I didn't find the solution on the first page of googling result.

But there is enough information on handlebars site:

1. http://handlebarsjs.com/#getting-started
2. http://handlebarsjs.com/block_helpers.html#raw-blocks

The second link would be very useful, if you want to put one HBS template (for client-side compiling) to another (server side). Sample - [below](#strange-case)

And here working solution:

```html

<body> ....
    <!-- I will add results of templating to this section -->
    <section class="hbs-container"></section>

	<script src="/js/jquery.min.js"></script> <!-- jquery - optional, it will help us to change DOM dynamically -->

    <!-- Required for templating -->
    <script src="/js/handlebars.min.js" type="text/javascript"></script>

<!-- actual client side template -->
<script id="template-hbs" type="text/x-handlebars-template">
	<article class="entry">
		<h1>{{title}}</h1>
		<div class="body">
			{{body}}
		</div>
	</article>
</script>

<!-- RUN CLIENT SIDE TEMPLATING -->
<script type="text/javascript">
    // get the template
    var source   = $("#template-hbs").html();

    // compile template:
    var template = Handlebars.compile(source);

    // apply template:
    var html = template({
        title: 'Info',
        body: "CLient side templating with HBS",
    });

    // add result to the page:
    $('.hbs-container').append(html);
</script>

</body>

```

<a id="strange-case"/>
### 'Client' template inside 'server' template:

1. wrap client-side template with `{{{{raw-helper}}}}`:

    ```handlebars
    {{{{raw-helper}}}}
    <script id="template-hbs" type="text/x-handlebars-template">
    	<article class="entry">
    		<h1>{{title}}</h1>
    		<div class="body">
    			{{body}}
    		</div>
    	</article>
    </script>
    {{{{/raw-helper}}}}
    
    ```

2. Register **server-side** helper ([proof](http://handlebarsjs.com/block_helpers.html#raw-blocks)):

    ```js
    // Here is solution for hbs+express, but it works for any handlebars engine:
    var hbs  = require('hbs');
    
    hbs.registerHelper('raw-helper', function(options) {
      return options.fn();
    });
    ```

3. PROFIT

**Comment by maxkoryukov** [comment]
Sorry, april 2012...

**Comment by brikka-quotient** [comment]
> Hello!
> 
> Strange, but I didn't find the solution on the first page of googling result.
> 
> But there is enough information on handlebars site:
> 
> 1. http://handlebarsjs.com/#getting-started
> 2. http://handlebarsjs.com/block_helpers.html#raw-blocks
> 
> The second link would be very useful, if you want to put one HBS template (for client-side compiling) to another (server side). Sample - [below](#strange-case)
> 
> And here working solution:
> 
> ```
> <body> ....
>     
>     <section class="hbs-container"></section>
> 
>     <script src="/js/jquery.min.js"></script> 
> 
>     
>     <script src="/js/handlebars.min.js" type="text/javascript"></script>
> 
> 
> <script id="template-hbs" type="text/x-handlebars-template">
>     <article class="entry">
>         <h1>{{title}}</h1>
>         <div class="body">
>             {{body}}
>         </div>
>     </article>
> </script>
> 
> 
> <script type="text/javascript">
>     // get the template
>     var source   = $("#template-hbs").html();
> 
>     // compile template:
>     var template = Handlebars.compile(source);
> 
>     // apply template:
>     var html = template({
>         title: 'Info',
>         body: "CLient side templating with HBS",
>     });
> 
>     // add result to the page:
>     $('.hbs-container').append(html);
> </script>
> 
> </body>
> ```
> 
> ### 'Client' template inside 'server' template:
> * wrap client-side template with `{{{{raw-helper}}}}`: ``` {{{{raw-helper}}}} <script id="template-hbs" type="text/x-handlebars-template"> <article class="entry"> <h1>{{title}}</h1> <div class="body"> {{body}} </div> </article> </script> {{{{/raw-helper}}}} ```
> 2. Register **server-side** helper ([proof](http://handlebarsjs.com/block_helpers.html#raw-blocks)):
>    ```js
>    // Here is solution for hbs+express, but it works for any handlebars engine:
>    var hbs  = require('hbs');
>    
>    hbs.registerHelper('raw-helper', function(options) {
>      return options.fn();
>    });
>    ```
> 3. PROFIT

This really helped, thanks! Any idea how to use custom helpers in client side?

**Comment by nknapp** [comment]
@brikka-quotient don't do that. Don't compile templates client-side. Do not wrap client-side templates inside server-side templates. Unless there is a good reason for it...

And do not use Handlebars to build your single-page-app in 2020. There are better frameworks that support this kind of combination from scratch.

**Comment by brikka-quotient** [comment]
@nknapp I'm doing this client side for only one section which will be loaded from AJAX based on user input

**Comment by nknapp** [comment]
What I mean is that frameworks like Vue, React, Angular or frameworks based on them like nuxt, next, vuepress and many others, support isomorphic rendering, which is probably what you want to do. If you are just building a new app, you are probably trying to build something that already exists in an easier way.
