### ISSUE TITLE
How do you handle pluralisation in Handlebars?

### ISSUE THREAD

**Issue by orientalperil** [wycats/handlebars.js#249]
Is it possible to write a helper for pluralizing words that can be used like this?

```
{{dog_count}} {{pluralize dog_count "dog" "dogs"}} {{pluralize dog_count "has" "have"}} gone for a walk.
```

**Comment by drmercer** [comment]
I made my own Handlebars helper for this. It's pretty versatile. For example, all of these compile to "bagel" when `numVar === 1` and to "bagels" for everything else:

```
{{plural numVar 'bagel'}}
{{plural numVar 'bagel(s)'}}
{{plural numVar 'bagel/bagels'}}
bagel{{plural numVar}}
```
It can also be used for switching between singular and plural grammar as appropriate:
```
{{numVar}} bagel{{plural numVar ' was/s were'}} eaten.
```

Here's the source: https://gist.github.com/drmercer/c3e0b2e174718787dac5a181b2be83f6

**Comment by jokesterfr** [comment]
Also consider using [grunt-locales](https://github.com/blueimp/grunt-locales) to manage your translations.
