### ISSUE TITLE
Include index in each block helper, aka each_with_index

### ISSUE THREAD

**Issue by rbu** [wycats/handlebars.js#250]
It would be really nice to have access to the index of an each iteration.
There are ready-to-use block helpers out there, but having this upstream would be nice.

I can provide a pull request if that helps.
## See also

https://gist.github.com/1048968
https://gist.github.com/1966803
http://stackoverflow.com/questions/5021495/in-mustache-how-to-get-the-index-of-the-current-section

**Comment by aaronharding** [comment]
If it helps, this was my solution. I edited the execIteration function within the each helper.

handlebars-3.0.3, line 2375
```javascript
...
data.index = index;
data.humanIndex = index + 1; // added
data.first = index === 0;
...
```

This could very easily be added in with a pull request.

**Comment by jblotus** [comment]
+1 for one based index

**Comment by kpdecker** [comment]
Locking this thread as we are set on the implementation here. Zero-based index will continue to be exposed from the native implementation. Those that need a 1-based index should write a simple helper to add this value. With subexpressions that helper can be used as arguments to other helpers too so this provides the option to have one-based anywhere without the overhead of tracking another field in the iteration logic that may or may not be used or breaking existing templates.

```
Handlebars.registerHelper('addOne', function(value) {
  return value + 1;
});
```
```
Like This: {{addOne @index}} or {{helper (addOne @index)}}
```
