### ISSUE TITLE
Handlebars.js is causing a memory leak in IE9

### ISSUE THREAD

**Issue by yxh10** [wycats/handlebars.js#271]
Hi there, 

I am wondering if any one else experience memory leak from compile function.

I am working on a single page app which polls data periodically from server via Ajax call. Every time when I get new data, I re-render the view. (I am using Backbone.js in conjunction. I understand that I need to manually free view objects when I close the view and switch to other view, but that is not the case here. At least, I think it is not. Regarding to this topic please see this link:  http://lostechies.com/derickbailey/2011/09/15/zombies-run-managing-page-transitions-in-backbone-apps/ ) 

Here is my code:

```
compileTemplate: function (view, data, templateSelector, ratio) {
        var templateSource = $(templateSelector).html(),
        template = Handlebars.compile(templateSource);

        var el = view.html(templateResult);
}
```

If I comment out  "var el = view.html(templateResult);" I won't have memory leak issue. As soon as I enable this line, the IE 9 memory consumption just start to raise. (I am forcing the view to re-compile the template every 0.5 seconds for testing purpose.)

I would like to know if there is a known memory leak issue in Handlbar.js or it is something I am doing wrong.

Thank you very much in advance.

Cheers

**Comment by AnirudhaGohokar** [comment]
Although its quite an old issue, we have huge memory leaks happening when compiling templates of size > 32kb. For now we have switched to [mustache.js](https://github.com/janl/mustache.js/) which has resolved the memory leak.

I think the root cause of the issue should be fixed.
