### ISSUE TITLE
Helper alias feature?

### ISSUE THREAD

**Issue by estliberitas** [wycats/handlebars.js#348]
Hello to everyone. I thought to offer helper alias feature. I really do not know if it  useful, so want to discuss.

For example in Ember we have `unbound` helper:

``` handlebars
{{unbound x.y.z}} 
```

Maybe it would be better to create a _helper alias_ \* (indirection operator from world of C)

``` javascript
Ember.Handlebars.helperAlias('unbound', '*');
```

``` handlebars
{{* x.y.z}}
```

Another way - using regexp replacement, so short transcription:

``` handlebars
{{div."class1 class2 class3" MyView}}
```

is translated to:

``` handlebars
{{view App.MyView tagName="div" class="class1 class2 class3"}}
```

The purpose of such feature is decreasing size of resulting template. From the other side, right now I do such job now in my web app before calling `Handlebars.compile()` and have no problems. :smile:

**Comment by nknapp** [comment]
Closing, because it is probably outdated, or solved.
