### ISSUE TITLE
Changing Delimiter

### ISSUE THREAD

**Issue by danielmahon** [wycats/handlebars.js#350]
I dont seem to be able to change the delimiter as defined in mustache:

`{{=<% %>=}}` and then back to `<%={{ }}=%>`

Im trying to let a 3rd party WYSIWYG generate tags which is possible if I am able to customize the opening and closing tags. Is there another way to do this? Im using handlebars with node.js and express 3.0.

**Comment by little-big-h** [comment]
@jonschlinkert this is a very fragile workaround (it cannot reliably deal with curly braces in the template code). This modified version of your example:
```
var Handlebars = require('handlebars');
var useDelims = require('handlebars-delimiters');
useDelims(Handlebars, ['<%=', '%>']);
var b = Handlebars.compile('{{ name }}<%= name %>}')({name: 'Jon'});
```
throws at template compile time.

**Comment by jonschlinkert** [comment]
Who knew a hack could be fragile ;P any time you have a workaround that is only useful in specific scenarios it will necessarily be fragile in every other scenario. That, and who wants to spend the time to do much more than that? IMO if you need different delimiters for something important, it just makes more sense to use a different engine. Do you have suggestions for a better alternative?

**Comment by little-big-h** [comment]
So, I guess you effectively demonstrated that it is not that easy to create a clean, robust solution to this problem. While I don't quite agree with you that it makes more sense to use a different engine (they all make tradeoffs) I ended up using swig instead.
