### ISSUE TITLE
Strange behavior on Safari IOS

### ISSUE THREAD

**Issue by Furizaa** [wycats/handlebars.js#373]
I found this issue that is absolutely imposible to debug for me. It happens like every other time so it's not clearly repeatable. As soon as I hook my iPad into remote debugging the issue disappears completely.

It seems to happen after a certain point of template complexity and nesting level. This can cause that the `name` attribute in `invokeAmbiguous` is `"undefined"`. This of course crashes at the next call `setupHelpers`. Any idea what circumstances have to occur to have an outcome like that? I've already checked that the context and the template is fine.

One of the possible templates where this can happen is:

```
<ul>
  {{#each filters}}
    <li>{{this}}</li>
  {{/each}}
</ul>
```

Where the context is

```
{
  filters: [
    "Transfer Inklusive"
  ]
}
```

There seems to be a Problem with `{{this}}` and it happens on the template call.

First we thought that splitting the heavy nested stuff in Partials would fix the problem. But after a few hours it started again. We do not precompile our templates in node.js.

As I said - it's almost impossible to reproduce and to debug because it only happens in IOS Safari when it's not hooked to a debugging device like every other reload. Could it possible be a race condition or some memory issues?

EDIT: Stack Trace:

```
'undefined' is not an object

quotedString@handlebars.js0:1727
setupHelper@handlebars.js?0:1735
invokeAmbiguous@handlebars.js?0:1569
compile@handlebars.js?0:1190
compile@handlebars.js?0:1842
@handlebars.js?0:1850
```

**Comment by atondelier** [comment]
> This issue is the only one we found on the internet about the issue we just solved in our case, so we put our conclusions here.

FYI, we encountered a very close rendering bug on Safari on iOS 9.2.1. We receive a JSON object with a string in it. This string is copied by models contructors and then copied again the this model constructor is called as a cloner. The same string is bound to multiple objects and Safari does an optimization. This string is then breaking the renderer after multiple usages (more than 7).

We detected the issue JavaScript side when reading the type of this string with `typeof`. In the buggy case, it said "object".

We succeed in fixing the rendering issue by forcing the engine to de-optimize this string. We are going to find the less consuming way of forcing de-optimization but what works for now is:
```JS
myObject.myString.split('').join('');
```

**Comment by shreymahendru** [comment]
Hey, @atondelier thanks for that comment. I encountered the same issue with Safari 11 (macOS). The string value in an object was being changed by safari into a garbage value everywhere and your solution fixed it. Would this be a Safari bug?
