### ISSUE TITLE
Passing null argument to helper causes error in IE

### ISSUE THREAD

**Issue by benjamin-smith** [wycats/handlebars.js#403]
For helpers with optional arguments, when passing null, like so:

Helper:

``` javascript
Handlebars.registerHelper("someHelper", function(arg1,arg2,options) {
    ....
}
```

Template:

`{{#someHelper 'foo' null}}`

the compiler creates code such as:

`stack1 = depth0.null`

Which, in IE8, throws a `Expected identifier` error. The `obj.null` is no good in IE, unfortunately. I have not checked IE7 or 9.

I am using handlebars 1.0.7

**Comment by ricardograca** [comment]
So in the case of an inline helper (or whatever they're called):

```javascript
Handlebars.registerHelper("someHelper", function(arg1, arg2, options) {
    ....
}

// In template:
{{someHelper 'stuff' null anOption=true}}
```

How would you go about omitting an argument while still providing the last one (`options` in this case)? Considering that `arg2` can also be an object, so it isn't possible to check for its type. Apparently this doesn't work:

```
 {{#someHelper 'foo' null anOption=true}}
```

**Comment by ricardograca** [comment]
To answer my own question, it sort of works after all. Since it tries to lookup `null` in the current context and can't find it, that argument will simply be `undefined` which isn't exactly `null`, but close enough for my needs.

I suppose that if anyone really needs the value of that argument to be `null` in this case it is possible to create a helper called null that returns `null` :laughing:

**Comment by kpdecker** [comment]
Neither null nor undefined are explicit primitives. I think your best option is to use a helper or define a context value as those options don't add additional complexity (and performance hit) to the compiler infrastructure.

**Comment by ricardograca** [comment]
The context value option isn't very feasible if you're calling the helper inside an `{{#each}}` block, which is how I'm using it in my case. That only leaves the helper option, which seems a bit silly but should work as intended:

```javascript
Handlebars.registerHelper('null', function() {
  return null
})
```
