### ISSUE TITLE
Assign variables in template

### ISSUE THREAD

**Issue by rottmann** [wycats/handlebars.js#476]
Is it possible to assign a variable within a template and use it like variables from outside?

Example:
I want output a table, but 1 column is optional, depend on data (fields[].field2) exists or not.

In each row it is no problem to check, but how to check it for the header ?

``` html
<table>
  <thead>
    <tr>
      <th>Head 1</th>
      <th>Head 2 (optional)</th>
      <th>Head 3</th>
    </tr>
  </thead>
{{#each fields}}
  <tr>
    <td>{{{field1}}}</td>
    {{#if field2}}<td>{{{filed2}}}</td>{{/if}}
    <td>{{{field3}}}</td>
  </tr>
{{/each}}
</table>
```

At the moment i use a unsteady helper function "assign" which creates helpers.

``` html
{{#each fields}}
  {{#if field2}}
    {{assign "helperVar" "<th>Head 2 (optional)</th>"}}
  {{/if}}
{{/each}}

Output with: {{{helperVar}}}
```

But thats not a good solution and i cant use it in #if.

**Comment by efuquen** [comment]
:+1:

@kpdecker We can have loops, if statements, and a number of other logic constructs in templates.  But apparently assigning a variable is *too* much logic in templates?   I really don't get the reasoning behind that decision when the other default helpers contain way more logic than simply having the ability to assign a variable.

**Comment by luisdaniel** [comment]
+1

**Comment by gudoy** [comment]
+1

**Comment by booleangate** [comment]
+1

**Comment by miquelescolar** [comment]
+1

**Comment by kpdecker** [comment]
Something along these lines can be implemented using block parameters and is documented here:
http://handlebarsjs.com/block_helpers.html#block-params

Since this is done in a separate namespace outside of the current context, it provides more consistent behavior over context assignment.

**Comment by swport** [comment]
lord knows why some people think it's a good idea to use hbs at the server with node.

**Comment by sasichkamega** [comment]
> only the lord knows why some people think it's a good idea to use hbs at the server with node.

why?
