### ISSUE TITLE
Browser Support?

### ISSUE THREAD

**Issue by bmccune** [wycats/handlebars.js#477]
I'm looking to use handlebars on a project I have coming up that needs to support back to IE7. I know the evil that I'm looking at, if I could avoid supporting them I would. 

Does handlebars support IE7 & 8 and does it make a difference if I pre-compile? So if handlebars.js doesn't support IE7 & 8 if I pre-compile does it solve the support issues.

**Comment by softmarshmallow** [comment]
`TypeError: Cannot read property 'Handlebars' of undefined
    at Object.../node_modules/handlebars/dist/cjs/handlebars/no-conflict.js.exports.default
`

Is it sure that still browser is supported? I'm getting above error
