### ISSUE TITLE
Handling localized context data (prior to precompilation)

### ISSUE THREAD

**Issue by webpro** [wycats/handlebars.js#575]
I'm thinking about a solution for i18n. Considering two types of context: localized labels and "regular" context data for the (precompiled) template to render.

One fairly simple approach is to "mix in" the localized labels to the context data (client-side), and have Handlebars render. This would also work for pre-compilation.

However, from a client-side performance perspective, I think it's efficient if the localized labels were rendered into the template prior to pre-compilation during the build phase. So the precompiled function would already contain localized content once consumed by the client. In other words:

1. Create a regular HB template with expressions for localized labels and anything else (e.g. `<label>{{label.surname}}: <input type="text" value="{{context.surname}}"></label>`.
1. Render only labels (e.g. `<label>Achternaam: <input type="text" value="{{context.surname}}">`.
1. Precompile this into a function.

The problem here is that this first render phase would strip out the remaining Handlebars expressions (`{{ }}`) from the template.

I can think of some solutions:

1. Use a different template engine (with different syntax/delimiters) for the label rendering. Then pass the result to HB.
1. Set up some custom str-replace solution for this.
1. Somehow change delimiter syntax for HB, only for the first render phase.

I was wondering if someone had any thoughts about this? Would be nice if I could use the existing tooling/libs (i.e. HB), but I'm open to any solution.

(Btw, I also happen to use a require.js plugin to load/write templates.)

Edit: Something I completely forgot to mention: the idea is to precompile into as many locales as needed (three locales means three precompiled templates).

**Comment by webpro** [comment]
Closing, old and inactive ticket :-)

**Comment by kpdecker** [comment]
For anyone interested, the formalized AST APIs in 3.x will hopefully allow for this in a much easier manner. My hope is to implement support for this and other "build time helpers" in https://github.com/walmartlabs/circus-handlebars, but the full implementation will depend very much on the build tools and environments that each project is using.
