### ISSUE TITLE
Handlebars doesn't work in tables

### ISSUE THREAD

**Issue by matrym** [wycats/handlebars.js#604]
http://jsfiddle.net/cwYhN/3/

Notice that the same handlebars #each succeeds when outside tables.  My jsfiddle includes two bordered outputs demonstrating this.

**Comment by profullstack** [comment]
This bug wasted two hours of my life and now it is 10:30pm at Saturday, I am working in my office just to solve this bug until I found this issue and [Official Block Doc]
(http://handlebarsjs.com/builtin_helpers.html) says nothing about that.

**Comment by stevenvachon** [comment]
In case it wasn't clear, this is not the fault of handlebars, but *yours* for now knowing how HTML works: https://html.spec.whatwg.org/multipage/syntax.html#an-introduction-to-error-handling-and-strange-cases-in-the-parser

**Comment by profullstack** [comment]
So, you assume everyone who tries to use Handlebarsjs should have a good understanding of how HTML parser works? And if not, then it is _the user's fault_, not the fault of the clearness of documentation? This assumption does not make sense. Another heavy and complex template engine, Angularjs, use Html compatible syntax as their template syntax, for example, if I need to loop  table, I can use
```
<tr ng-repeat="dto in tableData">
```
And Angularjs keeps the internal status of loop by using Html comments:
```
<!-- ngRepeat: column in row -->
<tr ng-repeat="dto in tableData">
```
Angualrjs tries to respect and follow the syntax of Html as much as possible and avoid the assumption successfully. But Handlebarsjs's template syntax does not so it exposes the Html parser problem to users. 
If you developer can't solve the problem at your side and then you have the _duty_   to tell your users to be aware of the problem if you really care about your project and your users from all over the world.
Anyway, I will open a document issue because _**I believe I am not the first one who came across this headache issue and I will not be the last one.**_

**Comment by stevenvachon** [comment]
Angular runs in the DOM, so it is DOM aware. Handlebars works with strings only and has no concept of the DOM.

**Comment by nknapp** [comment]
@profullstack: As @stevenvachon said, Handlebars does not work with HTML, but only with text. But this may not be obvious from the docs, since all examples are HTML. It personally use it also to generate markdown...

If you could tell me, what kind of text you would have needed in the docs, I would be happy to add it. However, the general usage instructions (including the part with the `<script>`-tag are already there on the main page of http://handlebarsjs.com/. That's why I'm not sure what your need is here.

**Comment by ErisDS** [comment]
@profullstack I get that you're frustrated about having "wasted time", but in my opinion, you've got this entirely backwards. 

No open source project nor contributor has any duty to you. Tools like handlebars are created and maintained for free and with almost no thanks, to try to making other developers lives easier. If you were not able to use any open source projects what-so-ever, how long would your work have taken? 

I can tell you, first hand, that coming along and writing comments with a tone such as this will have the [opposite to the desired effect](https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/). Simple carrot vs stick, if you want someone to do something for you, ask nicely or even better raise a PR and do it yourself.

**Comment by profullstack** [comment]
@ErisDS Thank you for your advice. Maybe my first comment was too strong, but I totally agree with your say about:
```
to try to making other developers lives easier
```
And why I drop Angularjs to use Handlebarsjs? _Because I believe Handlebarsjs will my life easier than Angularjs._
So, just kindly add some notice words in the documentation to help your thousands of open source users to avoid the potential problem is against your will of "making other developers lives easier"? I guess it's no.
For:
```
No open source project nor contributor has any duty to you.
```
Yes, it's true. You can start an open source project and then drop it, it's totally OK. But when your project grows, you spend more time and heart on your project, you are loving more about your project and you also want to share it with the world. At this time you will start to _care about your users_ and _care about your documentation_. Handlebarsjs is at this stage, this is not a small project, it's a popular project and used by programmers all over the world, even in South Korea, in China and so on. 
As far as I know, most open source programmers on Github are proud of their project and their README.md file, and wish more and more people to use their tools and codes.
So if:

- You don't want to care about your open source users
- I am the last one who will come across this issue
You can totally ignore my technical analysis in the first comment and user-kindly discussion in this comment.
Besides, open source project is not something like _charity_ you give the world, it's the _communication bridge_ between you and other programmers.

**Comment by profullstack** [comment]
@nknapp Thanks for your reply. 
**Maybe my first comment is too strong and I apologize for that and to people who read my comment.** 
From the first sight,  Handlebars works simply like _a text replacement tool_ and it's really easy to understand. So when I write something like this:
```
{{#each myListData}}
                        <tr>{{name}}</tr>
{{/each}}
```
If it is just simply replacement, I would expect something like this:
```
<tr>nameA</tr>
<tr>nameB</tr>
```
But when came across HTML, it behaves something different, and it is because of the natual of HTML parser just as @stevenvachon kindly noted. 
So I guess just one sentence will be enough below the "The each block helper" section:
```
WARNING: please use script block when you try to use #each block inside table, due to the know issue of [How HTML parse works(thanks for @stevenvachon's reference](https://html.spec.whatwg.org/multipage/syntax.html#an-introduction-to-error-handling-and-strange-cases-in-the-parser)
```
I really appreciate it if you will share your opinion. Thanks.

**Comment by nknapp** [comment]
The thing is, that this has nothing to do with the `#each`-helper. You should just **never** write a template directly into HTML. An statement like this should be on the main page, but the question is: Would you have read it there? 

Maybe we could a a warning like yours below the example on the landing-page...

In fact, I even would not use the script-blocks method in production. Instead I would use Webpack or another tool to precompile the templates.

**Comment by profullstack** [comment]
@nknapp Yes, I guess your opinion is right: we should never write a template directly into HTML. So I guess on the landing-page, the first "Getting Started" section should use script as example and in the below gray  block, we can change
```
You **_can_** deliver a template to the browser by including it in a <script> tag.
```
to
```
You **_should always_** deliver a template to the browser by including it in a <script> tag.
```
I guess your suggestion:
```
**_never_** write a template directly into HTML
```
is totally right, and should be put at the landing-page to let everyone follow this and it can avoid many problems. I guess it's a good idea, do you think so?

**Comment by stevenvachon** [comment]
That explanation doesn't work, though, because they might interpret that as:
```html
<script type="text/x-handlebars">
{{#each list as |item|}}
  <td>{{item}}</td>
{{/each}}
</script>
```

**Comment by profullstack** [comment]
@stevenvachon Yes, just putting templates inside the script is not enough in your example, maybe we need to add more notes about the right way to use a template, we would like to hear your suggestions about this.

**Comment by stevenvachon** [comment]
Perhaps:
> For most production applications, you will not want to use the parser and string templates. Look into precompilation.

**Comment by profullstack** [comment]
And I guess it will be better if we put your HTML parser link together with your comments:
```
For most production applications, you will not want to use the parser and string templates. Look into precompilation. There are some known issues if you use a template directly into HTML, for example, the #each template won't work inside tables due to how [HTML parser works.](https://html.spec.whatwg.org/multipage/syntax.html#an-introduction-to-error-handling-and-strange-cases-in-the-parser)
```

**Comment by nknapp** [comment]
It should probably be split into

1. Directly below the `<script>`-tag example

> It is important that you put the template inside a `<script>`-tag. Do not put it into the HTML directly or the HTML-parser might modify it (for example,  [if it contains a table](https://html.spec.whatwg.org/multipage/parsing.html#unexpected-markup-in-tables))

2. Change the bullet point about precompilation to.

> Please note that this approach is not recommended for production applications. It is also possible to precompile your templates. [...]

**Comment by nknapp** [comment]
Actually, I personally would not use Handlebars in the browser anymore: There are many other frameworks out there (not only Angular and React, but also Vue and Ractive). [This video](https://youtu.be/o12-90Dm-Qs?t=47m24s) is pretty cool and shows the problem...

I use Handlebars on the server and as static-page generator, but for browser-rendering, I think there are better ways.

**Comment by stevenvachon** [comment]
@nknapp I started writing [handlebars-html-parser](https://github.com/stevenvachon/handlebars-html-parser) for use in bringing it to the browser through VDOMs, but it [met resistance](https://github.com/wycats/handlebars.js/issues/1189).

**Comment by profullstack** [comment]
@nknapp Thanks for your reply. Your comments include:

1. The importance of putting template inside a <script>-tag.
2. The table issue and HTML parser reference from @stevenvachon .
3. The importance of precompilation.

It contains all the important details and it will be fine if we put your comments on the site. 
@stevenvachon, do you think it is ok if we make it final changes and do we miss something important? Thanks.

**Comment by stevenvachon** [comment]
@profullstack I'm not a maintainer this project.

**Comment by nknapp** [comment]
I have made the changes.

**Comment by profullstack** [comment]
@nknapp Thank you, I believe a lot of people will benefit from your changes.

**Comment by gurpreetatwal** [comment]
I know this issue is quite old, but I ran into this recently due to Sendgrid's email template editor not following these best practices. If anyone else ends up on this issue from Google for that reason, a workaround is to place the handlebars code in a HTML comment.

```html
<table >
  <tbody>
    <!-- {{#each items}} -->
    <tr>
      <td>{{this.key}}</td>
      <td>{{this.value}}</td>
    </tr>
    <!-- {{/each}} -->
  </tbody>
</table>
```

that produces the following output
```html
<table>
  <tbody>
    <!--  -->
    <tr>
      <td>my key</td>
      <td>my value</td>
    </tr>
    <!--  -->
    <!--  -->
    <tr>
      <td>my key 2</td>
      <td>my value 2</td>
    </tr>
    <!--  -->
  </tbody>
<table>
```

**Comment by DanaEpp** [comment]
Thanks for that tip @gurpreetatwal . You saved me hours of debugging this evening with that tidbit for SendGrid!

**Comment by Lazarencjusz** [comment]
@gurpreetatwal but why?

**Comment by gurpreetatwal** [comment]
@Lazarencjusz why in regards to why the fix works or why is SendGrid email template editor doesn't work correctly?

**Comment by leventefarkas** [comment]
Hi! When you use div elements instead of a table, will be work.
Also rewrite all table elements to div.

**Comment by mattdrewitt** [comment]
@gurpreetatwal 's Solution works for me on Mailchimp/Mandrills templating for handlebars.  Thanks for saving me a ton of trouble!

**Comment by zezix** [comment]
> I know this issue is quite old, but I ran into this recently due to Sendgrid's email template editor not following these best practices. If anyone else ends up on this issue from Google for that reason, a workaround is to place the handlebars code in a HTML comment.
> 
> ```
> <table >
>   <tbody>
>     
>     <tr>
>       <td>{{this.key}}</td>
>       <td>{{this.value}}</td>
>     </tr>
>     
>   </tbody>
> </table>
> ```
> 
> that produces the following output
> 
> ```
> <table>
>   <tbody>
>     
>     <tr>
>       <td>my key</td>
>       <td>my value</td>
>     </tr>
>     
>     
>     <tr>
>       <td>my key 2</td>
>       <td>my value 2</td>
>     </tr>
>     
>   </tbody>
> <table>
> ```
> 
> (NOTE: I have not verified this with Handlebars directly, just on Sendgrid's template editor)

Thanks man!! This really helps a lot! Kudos!!

**Comment by cgangalRELPRO** [comment]
@gurpreetatwal Your hack worked on Mailchimp+Mandrill. Thanks for saving me hours !
