### ISSUE TITLE
There should be a configuration option to throw if a tag finds no match in the source

### ISSUE THREAD

**Issue by christothes** [wycats/handlebars.js#651]
Given data with a missing property represented in the source, it should be configurable to have this throw.

```
var source = 'Some text {{foo}} with {{missing}} tag';
var template = Handlebars.compile(source);
var data = { foo : 'bar'};

//should optionally throw
var result = template(data); 

```

**Comment by ajs139** [comment]
Converted @showell's gist to TypeScript, in case it helps anyone: https://gist.github.com/ajs139/f84ccbe5678ef1497a53965cc326b452
