### ISSUE TITLE
Handlebars uses "default" with the AMD option

### ISSUE THREAD

**Issue by arobinson** [wycats/handlebars.js#667]
With handlebars.js version 1.1.2 the "handlebars --amd" option now creates invalid templates.

The code has this:

```
output.push('define([\'' + argv.handlebarPath + 'handlebars.runtime\'], function(Handlebars) {\n  Handlebars = Handlebars["default"];');
```

I'm not seeing any "default" property of handlebars. The code would be fine if the assigning to Handlebars["default"] was not used.

Here is how I'm loading handlebars 1.1.2 so that it is correctly exported:

```
requirejs.config(
{
  "baseUrl": "/js",
  "shim":
  {
    "handlebars.runtime":
    {
      "exports": "Handlebars"
    }
  }
});
```

Is there something different that must be done with v1.1.2?

**Comment by tribe84** [comment]
Having the same issues when trying to include Handlebars in karma tests.

**Comment by nasangam** [comment]
Use grunt-replace task to fix this issue:

match: /function\(Handlebars\) \{/g,
replacement: 'function(Handlebars) { Handlebars=Handlebars.default || Handlebars;'
                    
src: ['*/**/hbs.js'], 
dest: './'

https://www.npmjs.com/package/grunt-replace
