### ISSUE TITLE
feature request: inline partial definitions

### ISSUE THREAD

**Issue by ashanbrown** [wycats/handlebars.js#792]
There was some discussion on inline partial definitions and https://github.com/mustache/spec/issues/63 but it looks like it went off the rails a bit.

I'm addicted to 'capture' in the erb/haml world.  It seems to me that combined with subexpressions, you could use inline partial definition to pass the outputs of multiple blocks to a view or helper.  Using one of the proposed partial definitions from @spudly, you'd be able to write code like this:

```
{{>> bold-name}}
  <strong>{{name}}</strong>
{{/>>}}
{{#tooltip title:(bold-name)}}
  My name is bold.
{{/tooltip}}
```

Maybe partials could even accept arguments.  Sorry if I've got to wrong forum for this and if there is some better existing solution that I haven't stumbled across.  I think that the general push on the mustache site discussion was to define such helpers outside the template. I didn't quite follow all the reasons given to oppose this idea, but given how convenient I find 'capture' in rails, I'd love for handlebars to offer the same convenience.

Thanks for your consideration.  If there's interest in this, I might investigate a pull request for this.

**Comment by kpdecker** [comment]
The proposal in #1018 will allow for this:

```
{{*bold-name}}
  <strong>{{$default}}</strong>
{{/bold-name}}

{{#bold-name}}
  My name is bold.
{{/bold-name}}
{{#bold-name}}
  So is mine.
{{/bold-name}}
```

Closing this in favor of #1018 and requesting comments there.
