### ISSUE TITLE
Is there any way to render handlebars template from an external file?

### ISSUE THREAD

**Issue by amrnt** [wycats/handlebars.js#82]
I mean not from inline code.

**Comment by reykjavikingur** [comment]
I also wrote an entire extra module to solve this problem (on the server-side anyway): [handlebars-generator](https://www.npmjs.com/package/handlebars-generator)

**Comment by davidyell** [comment]
I found this issue whilst Googling, and despite using the technique at the top of this issue, and the return being a string, Handlebars is still complaining that I'm passing an object, when it's actually a string.

Although it's outside of the scope, to me it's a critical part of using a templating engine. As nearly everyone will keep different templates in different files.
