### ISSUE TITLE
Cross-site scripting on 'Getting Started'?

### ISSUE THREAD

**Issue by iagox86** [wycats/handlebars.js#826]
Hey,

So, I work in web security, and I'm trying to learn some frameworks better. Handlebars is nice and simple, but I'm having trouble figuring out the best way to escape user-controlled data that's passed into a helper. One of your first examples in your 'Getting Started' is making a link out of user input:

```
Handlebars.registerHelper('link', function(text, url) {
  return new Handlebars.SafeString(
    "<a href='" + url + "'>" + text + "</a>"
  );
});
```

But because you're putting what is most likely user-controlled input (text) into a Handlebars.SafeString(), any HTML in it will get rendered. As a result, your example is basically teaching people how to be vulnerable to XSS - not a great idea, IMO!

That being said, and this could be because I don't know much about Handlebars at this point, but I couldn't figure out a better way! I couldn't find an "explicitly escape this string" function to fix 'text' or 'url' if they contained user-controlled text.

So, in addition to not liking to see XSS in an example, I'm wondering what the best practice IS for passing user-controlled input into a helper?

Thanks!

**Comment by KevinHock** [comment]
👍  Ron
