### ISSUE TITLE
Handlebars not print {{this}} in each helper after few attempts in Chrome

### ISSUE THREAD

**Issue by samithaf** [wycats/handlebars.js#832]
I iterate an object and try to print value of object and sometimes it works and sometimes it does not. 
This mainly happen in Chrome, Firefox and IE9 is working as it should be. Somehow the generated function from handlebars get different when it works and when it does not. 

Data is the same for both time. When i use log helper to print {{this}}, i can see correct value print in console.

Recreation of the issue (tested in Chrome version 36) but I could not reproduce in in Firefox or IE9. But in my application issue causes in Firefox as well.
http://jsfiddle.net/samitha/UDVag/

Please see further details about this issue
http://stackoverflow.com/questions/24987854/handlebars-sometimes-not-print-this-in-each-helper

**Comment by udvarib** [comment]
@samithaf, I had the same problem, but with ./this also doesn't work as with simple this :( Any tips for me?
