### ISSUE TITLE
How to pass variables to handlebars helpers

### ISSUE THREAD

**Issue by zion03** [wycats/handlebars.js#840]
I'm create handlebars helper:

```
 export default Ember.Handlebars.registerHelper('if-eq', function(v1, v2, options) {
 if (this.get(v1) === this.get(v2)) {
   return options.fn(this);
   }
  return options.inverse(this);
   });
```

And execute like this:

```
 {{#each item in model.cons }}
{{#if-eq model.currentUser.id item.record_poster_id}}
 <div class="td author current">{{model.currentUser.name}}</div>
 {{else}}
 <div class="td author remote">{{model.remoteUser.name}}</div>
{{/if-eq}}
{{/each}}
```

I recieved variables like text "model.currentUser.id", using this.get(v1) I can get value. But this.get working only for model.currentUser.id and don't work for item.record_poster_id (maybe because it's variable from the loop)

QUESION: how i can pass variable by value?

**Comment by Kostanos** [comment]
Did you found the solution?
