### ISSUE TITLE
Support for If statements with logic expressions in templates by default without helpers

### ISSUE THREAD

**Issue by ghost** [wycats/handlebars.js#844]
It would be really neat if Handlebars.js would support If statements with logic expressions in templates by default, without helpers. Then I could do amazing things, like this:

```
{{#if unicorns == ponies }}
That's amazing, unicorns are actually undercover ponies
{{/if}}
```

Also see this [blog post](http://doginthehat.com.au/2012/02/comparison-block-helper-for-handlebars-templates/) on the issue.

**Comment by jeremiahlee** [comment]
I, too, wish for basic comparisons in Handlebars. I understand the logicless philosophy. I also believe basic comparison support would be more intuitable and allow users to work more efficiently. If users in mass are moving basic comparison logic to a helper, this philosophy isn't doing them a favor or dissuading a perceived suboptimal behavior—it's just creating more work.
