### ISSUE TITLE
Disable new default auto-indent at included partials

### ISSUE THREAD

**Issue by majodev** [wycats/handlebars.js#858]
Handlebars >v2.0.0-alpha.4 introduced a new default indentation handling at partials, namely "_Partials that are standalone will now indent their rendered content_" ([source](https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v200-beta1---august-26th-2014)). This might cause unexpected behavior when upgrading from previous versions, is there a `flag` to restore the old handling?

[Detailed explanation / self reproduce](https://github.com/majodev/handlebars-2-0-default-indentation-handling)

Thanks in advance! :)

**Comment by lzilioli** [comment]
This same behavior appears to exist when calling partials, or outputting content with the `{{{ }}}` syntax. Is there a way to prevent this behavior in these cases as well?

**Comment by kpdecker** [comment]
@lzilioli please open a new issue with supporting fiddle or other repo case if you're running into issues. I'm not sure what you mean by the same behavior as there are a few things discussed here, quite awhile ago, and it's probably better to start a new standalone conversation if you have concerns.

**Comment by erik-landvall** [comment]
Is there still no fix for this implemented? This renders the complete library useless for a lot of users, just to have a bit pettier output..? Until a working fix for the prettier output can be produced, the feature should be reversed, as it is broken.
