### ISSUE TITLE
Error: call to Function() blocked by CSP

### ISSUE THREAD

**Issue by loucyx** [wycats/handlebars.js#861]
CSP (content-security-policy) blocks Handlebars v2.0.0 rendering @ handlebars.js:2236

```
return Function.apply(this, params);
```

Allow 'unsafe-eval' is not an option. Is there a safe implementation of handlebars for the client side?

**Comment by mmerezhko-hv** [comment]
Hello guys, this is not resolved. Still seeing this line in the latest version:

https://cdn.jsdelivr.net/npm/handlebars@latest/dist/handlebars.js

```
if (asObject) {
	      params.push(source);

	      return Function.apply(this, params);
	    } else {
	      return this.source.wrap(['function(', params.join(','), ') {\n  ', source, '}']);
	    }
```
