### ISSUE TITLE
Extract the parser to a separate module

### ISSUE THREAD

**Issue by mmun** [wycats/handlebars.js#862]
Is this something realistically achievable?

The HTMLBars precompiler (both the Node version and the browser version) would benefit from this extraction. Currently we are embedding the entirety of Handlebars in order to access its parser, which is particularly painful in the browser case.

**Comment by kpdecker** [comment]
@mmun, we're now using babel+webpack to generate the various build components and running the latest es6 spec for module imports so it's no longer super painful to split out into separate npm modules if helpful. What were you thinking for this?

**Comment by kpdecker** [comment]
Closing but glad to reopen if the desire is still there.
