### ISSUE TITLE
Handlebars.noConflict() option?

### ISSUE THREAD

**Issue by bradvogel** [wycats/handlebars.js#887]
It would be useful to have a noConflict() method to pull Handlebars out of the global namespace, similar to jQuery's http://api.jquery.com/jquery.noconflict/. It would be used like:

```
(function(){
    var hb = Handlebars.noConflict(); // Removes window.Handlebars from the global namespace.
})();
```

Use cases for this:
1. You're writing a gmail chrome extension that shares global namespace with gmail. You want to use Handlebars but don't want window.Handlebars.
2. You're using Handlebars inside of an environment that already declares it (such as Meteor does for backwards compatibility).

**Comment by kpdecker** [comment]
Released in 3.0.0

**Comment by bernland** [comment]
Can you please give an example?

    var hb = Handlebars.noConflict();
    hb.compile(...);

results in the following error: *TypeError: hb is undefined*.

**Comment by kpdecker** [comment]
It does not return the instance as currently implemented, so you would need to do something like

```
var hb = Handlebars;
Handlebars.noConflict();
```

Glad to accept a pull request for the return value though, it's minimal overhead.
