### ISSUE TITLE
How to get handlebars's usage in power shell ? [OS: Windows 7]

### ISSUE THREAD

**Issue by javagtcpp** [wycats/handlebars.js#895]
I saw the usage in page "https://github.com/wycats/handlebars.js". And the web site "http://handlebarsjs.com/precompilation.html", open and scroll to end "Optimizations", here only show the " -k if "...
I wonder how to browse handlebars's usage in windows 7 power shell ?
I try "handlebars -h",  "handlebars -help", "handlebars --help", no one works, why and how ?

**Comment by kpdecker** [comment]
Released in 3.0.0
