### ISSUE TITLE
Still escapes with noEscape enabled on isolated Handlebars environment

### ISSUE THREAD

**Issue by reaperdtme** [wycats/handlebars.js#901]
Using isolated Handlebars environments with compat true and noEscape true still escapes mustaches

I logged the options object in Compiler.compile and Compiler.mustache and somewhere options is losing the noEscape:true value, but it retains the compat:true value

Running node v0.11

The breakdown occurs when Compiler.compile is called and options only contains:

```
compiler compile options:
{ data: true, compat: true, useDepths: true }
```

The usual Compiler.compile call has:

```
{ compat: true,
  noEscape: true,
  data: true,
 useDepths: true,
 knownHelpers: 
    { helperMissing: true,
     blockHelperMissing: true,
     each: true,
     if: true,
     unless: true,
     with: true,
     log: true,
     lookup: true } }
```

Ah, I see the issue is happening when I have registered helpers.

**Comment by kpdecker** [comment]
Released in 3.0.0
