### ISSUE TITLE
Different behavior of {{@last}} when {{#each}} in {{#each}}

### ISSUE THREAD

**Issue by zordius** [wycats/handlebars.js#910]
1. When {{#each}} on object, `{{@last}}` is undefined
2. When {{#each}} on array, `{{@last}}` will be true in last run
3. When {{#each}} inside another {{#each}} , `{{@last}}` will be set by outer {{#each}} and the behavior of 1 and 2 changed.

Sample code here:
http://jsfiddle.net/y4pd8qs2/1/

**Comment by kpdecker** [comment]
Released in 3.0.0
