### ISSUE TITLE
{{#switch}} helper

### ISSUE THREAD

**Issue by stevenvachon** [wycats/handlebars.js#927]
This is very useful and I think it'd be best if it were native to the library:

``` handlebars
{{#switch state}}
    {{#case "page1" "page2"}}toolbar{{/case}}
    {{#case "page1" break=true}}page1{{/case}}
    {{#case "page2" break=true}}page2{{/case}}
    {{#case "page3" break=true}}page3{{/case}}
    {{#default}}page0{{/default}}
{{/switch}}
```

**Comment by michaelhogg** [comment]
This page is currently the 3rd Google search result for "Handlebars switch helper". For the benefit of people arriving here from a search engine, here's [an implementation by Chris Montrois](http://chrismontrois.net/2016/01/30/handlebars-switch/) which supports single-value `case` clauses such as `{{#case "page1"}}`:

```javascript
Handlebars.registerHelper("switch", function(value, options) {
    this._switch_value_ = value;
    var html = options.fn(this); // Process the body of the switch block
    delete this._switch_value_;
    return html;
});

Handlebars.registerHelper("case", function(value, options) {
    if (value == this._switch_value_) {
        return options.fn(this);
    }
});
```

Here's an improved `case` helper which supports clauses with a variable number of values, such as `{{#case "page1" "page2"}}`:

```javascript
Handlebars.registerHelper("case", function() {
    // Convert "arguments" to a real array
    var args = Array.prototype.slice.call(arguments);

    var options    = args.pop();
    var caseValues = args;

    if (caseValues.indexOf(this._switch_value_) === -1) {
        return '';
    } else {
        return options.fn(this);
    }
});
```

**Comment by stevenvachon** [comment]
Very nice, short and sweet. I'd come across much longer ones in the past.

One thing to add might be `{{default}} {{/default}}`

**Comment by Billy-** [comment]
@stevenvachon As requested ;)
```javascript
module.exports = {
    switch: function(value, options) {
        this._switch_value_ = value;
        this._switch_break_ = false;
        var html = options.fn(this);
        delete this._switch_break_;
        delete this._switch_value_;
        return html;
    },
    case: function(value, options) {
        var args = Array.prototype.slice.call(arguments);
        var options    = args.pop();
        var caseValues = args;

        if (this._switch_break_ || caseValues.indexOf(this._switch_value_) === -1) {
            return '';
        } else {
            if (options.hash.break === true) {
                this._switch_break_ = true;
            }
            return options.fn(this);
        }
    },
    default: function(options) {
        if (!this._switch_break_) {
            return options.fn(this);
        }
    }
};
```

**Comment by jimkoul** [comment]
@Billy- Where should we include this?

**Comment by Billy-** [comment]
@jimkoul These are helper functions so it depends on your set up.

My set up (with Gulp + gulp-hb) supports specifying a glob pattern for js files which export helper functions, as above, so it looks like this:

``` js
// ...
.pipe(handlebars({
  helpers: 'handlebars/helpers/*.js'
})
// ...
```
If you're still not sure do a little research into how helper functions work with handlebars, and how to implement them with whatever implementation of handlebars you are using.

**Comment by poorpaddy** [comment]
@stevenvachon Would you mind posting what you ended up landing on?

I tried this but doesn't seem to do anything other than not bomb on the tag themselves.
`Handlebars.registerHelper("switch",function(value, options){
    this._switch_value_ = value;
    this._switch_break_ = false;
    var html = options.fn(this);
    delete this._switch_break_;
    delete this._switch_value_;
    return html;
});

Handlebars.registerHelper("case",function(value, options){
    var args = Array.prototype.slice.call(arguments);
    var options    = args.pop();
    var caseValues = args;

    if (this._switch_break_ || caseValues.indexOf(this._switch_value_) === -1) {
        return '';
    } else {
        if (options.hash.break === true) {
            this._switch_break_ = true;
        }
        return options.fn(this);
    }
});

Handlebars.registerHelper("default",function(options){
    if (!this._switch_break_) {
        return options.fn(this);
    }
});`

**Comment by poorpaddy** [comment]
It would be nice if we could pass variable thru the switch name and not have to write a complete `{{assign}}` thru each. That way the option becomes the variable value.

This is what I have for the helper
```
"use strict";
Handlebars.registerHelper("switch", function(value, options) {
    this._switch_value_ = value;
    this._switch_break_ = false;
    var html = options.fn(this);
    delete this._switch_break_;
    delete this._switch_value_;
    return html;
});

Handlebars.registerHelper("case", function(value, options) {
    var args = Array.prototype.slice.call(arguments);
    var options    = args.pop();
    var caseValues = args;

    if (this._switch_break_ || caseValues.indexOf(this._switch_value_) === -1) {
        return '';
    } else {
        if (options.hash.break === true) {
            this._switch_break_ = true;
        }
        return options.fn(this);
    }
});

Handlebars.registerHelper("default", function(options) {
    if (!this._switch_break_) {
        return options.fn(this);
    }
});
```
This is what I have in my hbs file:

```
{{#assign "testParam"}}bwahahaha{{/assign}}
{{#switch testParam}}
    {{#case "boo" break=true}}case1 has been met{{/case}}
    {{#case "foo" break=true}}case2 has been met{{/case}}
    {{#case "tried" break=true}}case3 has been met{{/case}}
    {{#case "bwahahaha" break=true}}case4 has been met{{/case}}
    {{#default}}nothing matched{{/default}}
{{/switch}}

{{#ttpartial "testSwitch.content"}}
        {{testParam}}
{{/ttpartial}}
```

**Comment by poorpaddy** [comment]
or some reason the above makes the default always take precedence even when one of the cases above are met.

**Comment by a-le** [comment]
Here's what I use:

```
Handlebars.registerHelper('switch', function(name, value, options) {
    this['_switch_value_' + name] = value;
    this['_switch_break_' + name] = false;
    var html = options.fn(this);
    delete this['_switch_break_' + name];
    delete this['_switch_value_' + name];
    return html;
});
Handlebars.registerHelper('case', function(name, value, options) {
    var args = Array.prototype.slice.call(arguments);
    var options    = args.pop();
    var caseValues = args;

    if ( this['_switch_break_' + name] || caseValues.indexOf(this['_switch_value_' + name]) === -1) {
        return '';
    } else {
        this['_switch_break_' + name] = true;
        return options.fn(this);
    }
});
Handlebars.registerHelper('default', function(name, options) {
    if ( !this['_switch_break_' + name] ) {
        return options.fn(this);
    }
});
```
The switch are named, so it is possible to branch them (imbrication ? not sure about the word...)
Also, break is always done when a condition is met 

ie:
```
    {{#switch "1" "aaa"}}
        {{#case "1" "aaa"}}
            {{#switch "2" "bbb"}}
                {{#case "2" "bbb"}}ok{{/case}}
            {{/switch}}
        {{/case}}
        {{#default "1"}}nok{{/default}}
    {{/switch}}
```

**Comment by infinityplusone** [comment]
I'm sure I'm failing to understand some of how this works, so I apologize for my confusion, but... Is it possible for the switch to work within an `each`? I've been trying it out, but I keep getting errors.

Here's what I've got:
```hbs
{{#each columns}}
    {{#switch this}}
        {{#case 'foo'}}
        {{/case}}
        {{#case 'bar'}}
        {{/case}}
    {{/switch}}
{{/each}}
```

But I'm getting this:
```js
Uncaught TypeError: Cannot create property '_switch_value_' on string 'name'
```

It seems to me that `this` must be something other than what is expected, but I don't really know.

**Comment by infinityplusone** [comment]
Looks like I was able to get it working by changing the `switch` as follows:
```js
Handlebars.registerHelper({
    switch: function(value, options) {
        return options.fn({
            _switch_value_: value,
            _switch_break_: false
        });
    },
    //...
});
```
But I'm guessing I'm losing something for other cases. This said, I could always attach these values to `options`, and I think it would work.

@Billy- @a-le ?

**Comment by Billy-** [comment]
@infinityplusone unfortunately I haven't used handlebars properly in years so I imagine that the helper implementation may have changed heavily since I wrote that, which is probably why it wasn't working as expected. I'm not sure though, sorry to disappoint.

**Comment by a-le** [comment]
@infinityplusone If you use my version, you have to "name" the switch.
So, with your example:  
```
{{#each columns}}
    {{#switch "myswitch" this}}
        {{#case "myswitch" 'foo'}}
        {{/case}}
        {{#case "myswitch" 'bar'}}
        {{/case}}
    {{/switch}}
{{/each}}
```

**Comment by hoon720823** [comment]
switch for nested context

Handlebars.__switch_stack__ = [];

Handlebars.registerHelper( "switch", function( value, options ) {
    Handlebars.__switch_stack__.push({
        switch_match : false,
        switch_value : value
    });
    var html = options.fn( this );
    Handlebars.__switch_stack__.pop();
    return html;
} );
Handlebars.registerHelper( "case", function( value, options ) {
    var args = Array.from( arguments );
    var options = args.pop();
    var caseValues = args;
    var stack = Handlebars.__switch_stack__[Handlebars.__switch_stack__.length - 1];
    
    if ( stack.switch_match || caseValues.indexOf( stack.switch_value ) === -1 ) {
        return '';
    } else {
        stack.switch_match = true;
        return options.fn( this );
    }
} );
Handlebars.registerHelper( "default", function( options ) {
    var stack = Handlebars.__switch_stack__[Handlebars.__switch_stack__.length - 1];
    if ( !stack.switch_match ) {
        return options.fn( this );
    }
} );


{{#switch state}}
    {{#case "page1" "page2"}}page 1 or 2{{/case}}
    {{#case "page3"}}page3{{/case}}
    {{#case "page4"}}page4{{/case}}
    {{#case "page5"}}
            {{#switch s}}
                {{#case "3"}}s = 3{{/case}}
                {{#case "2"}}s = 2{{/case}}
                {{#case "1"}}s = 1{{/case}}
                {{#default}}unknown{{/default}}
            {{/switch}}
	{{/case}}
    {{#default}}page0{{/default}}
{{/switch}}

var data = {
        state : 'page5',
        s : '1'
};
var html = template( data );

**Comment by hoon720823** [comment]
for nested switch block

```javascript
Handlebars.__switch_stack__ = [];

Handlebars.registerHelper( "switch", function( value, options ) {
    Handlebars.__switch_stack__.push({
        switch_match : false,
        switch_value : value
    });
    var html = options.fn( this );
    Handlebars.__switch_stack__.pop();
    return html;
} );
Handlebars.registerHelper( "case", function( value, options ) {
    var args = Array.from( arguments );
    var options = args.pop();
    var caseValues = args;
    var stack = Handlebars.__switch_stack__[Handlebars.__switch_stack__.length - 1];
    
    if ( stack.switch_match || caseValues.indexOf( stack.switch_value ) === -1 ) {
        return '';
    } else {
        stack.switch_match = true;
        return options.fn( this );
    }
} );
Handlebars.registerHelper( "default", function( options ) {
    var stack = Handlebars.__switch_stack__[Handlebars.__switch_stack__.length - 1];
    if ( !stack.switch_match ) {
        return options.fn( this );
    }
} );
```

```html
{{#switch state}}
    {{#case "page1" "page2"}}page 1 or 2{{/case}}
    {{#case "page3"}}page3{{/case}}
    {{#case "page4"}}page4{{/case}}
    {{#case "page5"}}
            {{#switch s}}
                {{#case "3"}}s = 3{{/case}}
                {{#case "2"}}s = 2{{/case}}
                {{#case "1"}}s = 1{{/case}}
                {{#default}}unknown{{/default}}
            {{/switch}}
	{{/case}}
    {{#default}}page0{{/default}}
{{/switch}}
```

```javascript
var data = {
    state : 'page5',
    s : '1'
};

var html = template( data );
```

**Comment by skout90** [comment]
How about this?
 just if you want to convert key to value.

````javascript
module.exports = function(input, cases, values) {
  const caseArray = cases.split(',')
  const valueArray = values.split(',')
  const index = caseArray.indexOf(input)
  
  return valueArray[index]
};
````
````handlebars
{{switch "Y" "Y,N,D", "YES,NO,DELETED"}}
````

**Comment by Mohsen-Bazmi** [comment]
For most of the use cases helpers are not needed.
A dynamic inline template should do the trick:
```handlebars
{{> (lookup . state) }}
{{#*inline "page1"}}page 1{{/inline}}
{{#*inline "page2"}}page 2{{/inline}}
```

**Comment by dhouck** [comment]
I donʼt think that quite works, because as far as I can tell `concat` also isnʼt built-in.  You donʼt need it, but it takes a bit of extra work to avoid polluting the global namespace if you might want to use other `state`-based partials.

Hereʼs what I managed to do, based on what you said.  Iʼm new to Handlebars; there may be obvious improvements  to someone who knows more ([playground](<https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%7B%7B!--%20Inline%20partials%20are%20block-scoped%2C%20so%20this%20keeps%20them%20from%20interfering%20elsewhere%20--%7D%7D%5Cn%7B%7B%23if%20true%7D%7D%5Cn%7B%7B~%23*inline%20%5C%22page1%5C%22%7D%7Dpage%201%7B%7B%2Finline~%7D%7D%5Cn%7B%7B~%23*inline%20%5C%22page2%5C%22%7D%7Dpage%202%7B%7B%2Finline~%7D%7D%5Cn%7B%7B~%23*inline%20%5C%22page3%5C%22%7D%7Dpage%203%7B%7B%2Finline~%7D%7D%5Cn%7B%7B!--%5Cn%20%20Use%20a%20partial%20block%20to%20provide%20a%20default%20value.%5Cn%20%20It%20must%20be%20closed%20with%20undefined%2C%20I%20think%20because%20dynamic%20partials%20don't%20have%20a%20name.%5Cn--%7D%7D%5Cn%7B%7B%23%3E%20(lookup%20.%20%5C%22state%5C%22)%20%7D%7Dpage0%7B%7B%2Fundefined%7D%7D%5Cn%7B%7B%2Fif%7D%7D%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20state%3A%20%5C%22Invalid%5C%22%5Cn%7D%5Cn%22%2C%22output%22%3A%22page0%5Cn%22%2C%22preparationScript%22%3A%22%22%2C%22handlebarsVersion%22%3A%224.7.9%22%7D>)):
```handlebars
{{!-- Inline partials are block-scoped, so this keeps them from interfering elsewhere --}}
{{#if true}}
{{~#*inline "page1"}}page 1{{/inline~}}
{{~#*inline "page2"}}page 2{{/inline~}}
{{~#*inline "page3"}}page 3{{/inline~}}
{{!--
  Use a partial block to provide a default value.
  It must be closed with undefined, I think because dynamic partials don't have a name.
--}}
{{#> (lookup . "state") }}page0{{/undefined}}
{{/if}}
```
