### ISSUE TITLE
Helper as Argument for If Block Helper

### ISSUE THREAD

**Issue by 58bits** [wycats/handlebars.js#934]
Is it possible to use a helper that returns true or false, as the argument for the If block helper? i.e.

```
module.exports = function isdev() {
  return (process.env.NODE_ENV && process.env.NODE_ENV === 'development');
};
```

And then on the template page...

```
{{#if isdev }}
    <p>stuff here</p>
{{/if}}
```

**Comment by doowb** [comment]
@58bits you just need to wrap the `isDev` helper in [sub-expression syntax](http://handlebarsjs.com/expressions.html#subexpressions):

```handlebars
{{#if (isDev)}}
  <p>stuff here</p>
{{/if}}
```

**Comment by 58bits** [comment]
Oh - thanks a bunch @doowb ! works fine, - and sorry I missed the docs for subexpressions.
