### ISSUE TITLE
A different Handlebars.print for re-printing an AST back to source code

### ISSUE THREAD

**Issue by fivetanley** [wycats/handlebars.js#935]
I'm not quite sure what to call it yet, other than Handlebars.print. Currently, Handlebars.print prints stuff like "BLOCK PARAMS[actual code]" https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/compiler/printer.js#L30

It'd be great to have a utility function for just reprinting an AST. The reason for this being I'm working on some tools to help users of Ember upgrade some of their deprecated syntax and check the result of that back into version control without otherwise changing the source code. Ideally, you could parse a template, pass the AST into this function, and have the string returned be identical to the template you parsed.

I can definitely work on this, I'm just wondering whether this belongs here or in its own project.

Thanks!

**Comment by kpdecker** [comment]
I'm fine with it in the core library as long it is not included in the
client builds.

**Comment by kpdecker** [comment]
@fivetanley are you bailing on this goal in addition to the PR?

**Comment by fivetanley** [comment]
Changing direction a bit. Will probably be a standalone library similar to benjamn/recast.

**Comment by zeppelin** [comment]
@fivetanley I wrote something like this for Handlebars: https://github.com/zeppelin/handlebars-serializer

Dunno if that helps, or you need any help regarding the same feature for HTMLBars

**Comment by zeppelin** [comment]
It is by no means feature-complete, but it does cover my use cases: https://github.com/zeppelin/handlebars-serializer/blob/master/packages/handlebars-serializer/tests/serializer-test.js

**Comment by satyajitnayk** [comment]
You can Try https://github.com/handlebars-lang/handlebars.js/issues/169#issuecomment-1772483796
