### ISSUE TITLE
The npm package for 2.0.0 contains the "coverage/" dir

### ISSUE THREAD

**Issue by dougwilson** [wycats/handlebars.js#937]
So it looks like you may have accidentally published the code coverage HTML with the 2.0.0 package. Can you publish a new package without this directory (and probably add it to your `.npmignore` ;) )?

**Comment by kpdecker** [comment]
Will certainly remove it. Not sure I want to go back and republish an existing build though. 3.x should be landing soon.

**Comment by dougwilson** [comment]
That's fine :) Getting it in whatever is next is good enough, even if that's v3 :)

**Comment by kpdecker** [comment]
Released in 3.0.0
