### ISSUE TITLE
Safestring not returning a string when an integer is passed as value

### ISSUE THREAD

**Issue by gonvaled** [wycats/handlebars.js#939]
I am now using Handlebars 2.0.0 (together with ember 1.9.1). My application is failing in an unexpected way. After some debugging, I have found that `SafeString` is returning an integer when passed an integer, and the ember internals are unable to process this (as they expect an string).

The workaround for me has been to do:

```
return new Ember.Handlebars.SafeString(value.toString());
```

in my handlebars helper, where originally I was just doing:

```
return new Ember.Handlebars.SafeString(value);
```

(`value` is the result of the processing done by my handlebars helper)

Is this really an intended change in `SafeString` for Handlebars, or maybe a bug? When did this change?

**Comment by kpdecker** [comment]
Can you point me to the code that fails?

**Comment by kpdecker** [comment]
The handlebars implementation of safe string does cast to a string. Not sure if Ember has a different implementation or if you are seeing something else, but closing this issue.

If you can create a fiddle showing the issue in handlebars itself then glad to reopen.

**Comment by kpdecker** [comment]
I had intended to reference this in the comment above: https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/safe-string.js#L7
