### ISSUE TITLE
Can't pass arguments to a method in the parent context

### ISSUE THREAD

**Issue by ricardograca** [wycats/handlebars.js#946]
Having a method in one context like so:

```javascript
var context = {
  thing: { name: 'A Thing', age: 'timeless' },
  doStuff: function(value) {
    return value
  }
}
```

This works:

```handlebars
{{doStuff 'happy to do stuff'}}

{{#with thing}}
  Name: {{name}}
  Age: {{age}}
{{/with}}
```

This doesn't:

```handlebars
{{#with thing}}
  Name: {{name}}
  Age: {{age}}
  {{@root.doStuff 'nah....'}}
{{/with}}
```

Using `@../` instead of `@root` also doesn't help. The error is:

    Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'CLOSE_SEXPR', got 'STRING'

Strangely this works just fine (although it doesn't output anything in this case, as expected):

```handlebars
{{#with thing}}
  Name: {{name}}
  Age: {{age}}
  {{@root.doStuff}}
{{/with}}
```

**Comment by kpdecker** [comment]
Under 2.0 execution of data fields is not allowed. This has been added as a feature in 3.0 (the current master, too be released soon). In the mean time you should be able to do `{{../doStuff}}` if the parent context is root.

**Comment by ricardograca** [comment]
@kpdecker Can you explain what are "data fields"?

**Comment by zordius** [comment]
it should be any `{{@foo}}` like tags , EX: `{{@root}}` , `{{@index}}`, `{{@key}}` , `{{@first}}` ...

**Comment by ricardograca** [comment]
Oh right I see. Thanks for the clarification. I'm glad this issue is fixed in the next version.
