### ISSUE TITLE
Handlebars is missing script and script/html encoding

### ISSUE THREAD

**Issue by gh-andre** [wycats/handlebars.js#947]
Handlebars will handle fine HTML encoding, as in:
```
<p title="{{title}}">{{text}}</p>
```
, if `title` contains `A"B`. However, there's no standard way to encode strings within JavaScript or JavaScript/HTML contexts. This is an example of where some built-in script encoding in Handlebars would come in handy:
```
<script>
var x = "{{text}}";     // won't work for A"B
var y = "{{{text}}}";   // even worse - no encoding at all
</script>
```
Similarly, for event handlers in HTML, script encoding is required followed by HTML encoding, and the code below won't work for `x` = `A"B`:
```
<a onclick="f(&quot;{{x}}&quot;)">link</a>
```
, because the result will be 
```
<a onclick="f(&quot;A&quot;B&quot;">link</a>
```
, which will then be passed to the JS engine as:
```
f("A"B")
```
Using helpers is the only way today to encode these values properly for each context, but given that pretty much everybody does it in their own way (and many probably don't do at all or use HTML encoding in JS), it would make a lot of sense if Handlebars would provide standard patterns for handling both cases.

Do you have any plans to introduce either of the forms of encoding in Handlebars?

**Comment by kpdecker** [comment]
I haven't really thought about it to be honest. Could you provide an example of what you would like this to look like if it is not a helper?

**Comment by gh-andre** [comment]
Thanks for getting back to me. This is just an example - much will depend on how you parse the text between braces and what you think your users would prefer. Thinking that having closing double braces is sufficient to locate the end of the tag, I would probably just add a single character after the opening braces to indicate the type of encoding. For example, this template:

```
<script>
var text = "{{\x}}";
</script>
```

, used with `x` assigned `A"B` would generate this JS-encoded output:

```
<script>
var text = "A\"B";
</script>
```

Similarly, this template:

```
<p onclick="f(&quot;{{#x}}&quot;)" title="{{x}}">some text</p>
```
, used with `x` assigned `A"B` would generate this JS/HTML-encoded (note the slash before the middle quote) and HTML-encoded output:

```
<p onclick="f(&quot;A\&quot;B&quot;)" title="A&quot;B">some text</p>
```

**Comment by gh-andre** [comment]
Just thought of one more thing. Any encoding qualifiers, like the `\` and '#` above, need to be invalid in the JavaScript context, so any existing code with `{{x}}` would work as-is. In other words, something like `{{!x}}` would not work because `!x` is valid JavaScript and could be used today in the field. 

My colleague just looked over my shoulder and suggested that with this syntax triple braces could be replaced with something like `{{=x}}`, which would mean "do not encode". This would be quite self-descriptive.

**Comment by kpdecker** [comment]
Thanks for the suggestion. I thought about this a bit over the past few days and I think using helpers is both clearer and keeps the language simple. We have very few control characters that we can use due to the tokenizer rules that we have in place and the ones that we do have lead to confusion as they often aren't explanatory.

Using helpers that return a `SafeString` instance is probably the best option for implementors here.

**Comment by gh-andre** [comment]
Disappointing. Most of your users don't even realize that their sites are vulnerable to XSS attacks and you could help a lot of them by offering a complete encoding solution. Oh well...
