### ISSUE TITLE
handlebars runtime amd build fails to work with require js.

### ISSUE THREAD

**Issue by mattkime** [wycats/handlebars.js#948]
it simply fails to return an object (handlebars or otherwise) 

it seems that if i want to use handlebars runtime in combo with requirejs / amd then i need to use the non-amd build and write a custom shim.

when i swap out the runtime version for the full version i have no such problem.

**Comment by mattkime** [comment]
while the amd build fails to work, the handlebars.runtime file provides amd functionality via umd. 

perhaps handlebars.runtime.amd should be removed from the repo.

**Comment by kpdecker** [comment]
Could you point me to the file that you were trying to reference? We've had a lot of confusion around trying to support the numerous different build/package ecosystems :(

**Comment by mattkime** [comment]
i'm not sure what to say aside from its the handlebars.runtime.amd file available via bower. it appears that its not check into this repo. 

it would be a huuuuuge help if the readme included a few words regarding amd / requirejs usage. it took me a couple of days to figure this out. part of the problem is that my project is currently on handlebars v1.3 which is broken in the same manner. its my impression that requirejs is by far the most common instance of amd usage. if it doesn't work with requirejs its broken in most amd environments.

**Comment by kpdecker** [comment]
Not using r.js myself, this is difficult for me to document. I'd be glad to
include any information you may have found from your investigation, if
you'd like to submit a PR!

**Comment by JSteunou** [comment]
I'm using full Handlebars 3.0.0 with requirejs in development mode and Handlebars runtime 3.0.0 with requirejs all compiled in one file in production mode without any issue.

**Comment by Tiendq** [comment]
@JSteunou  how could you do it? I spent a past how to just make typical paths/shim configure but Handlebars didn't work :(

It's too hard to use Handlebars with RequireJS, there are many versions but almost no document about using them at all :(

**Comment by JSteunou** [comment]
I'm using requirejs-hbs with that config

```
    packages: [
        {
            name: 'hbs',
            location: 'bower_components/requirejs-hbs',
            main: 'hbs'
        }
    ],
    ...
```

and those options in my build task

```
                exclude: ['handlebars-compiler'],
                paths: {
                    'handlebars': 'bower_components/handlebars/handlebars.runtime',
                    'handlebars-compiler': 'bower_components/handlebars/handlebars'
                }
```

**Comment by ashareye** [comment]
just change handlebars.runtime.js or handlebars.js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define(factory);
	else if(typeof exports === 'object')
		exports["Handlebars"] = factory();
	else
		root["Handlebars"] = factory();
})  ... ...
change to 
(function webpackUniversalModuleDefinition(root, factory) {
		root["Handlebars"] = factory();
}) ... ...

everything is ok!

**Comment by rafaelfaria** [comment]
The version 3.0.3 is also failing when i try to import it from ES6 file. 

It would import it, but than says that Handlebars is undefined.

any clues?

**Comment by kpdecker** [comment]
@rafaelfaria please post an example showing the failure case in another bug so we can keep things clear.

**Comment by lulessa** [comment]
Handlebars 3.0.3, either runtime or full version, does not work with RequireJS.
Failed to create a Handlebars object with either RequireJS 2.1.8 and 2.1.20

Do you need me to post an example page online?

**Comment by kpdecker** [comment]
Please.

**Comment by lulessa** [comment]
My apologies for a false alarm above. Let me be clear. Handlebars does work with require.js:
```js
// this works well
requirejs(["handlebars"], function(Handlebars) {
  // Handlebars-related templating code here
});
```
Passing tests:
http://lucaslessa.com/handlebars/qunit-load-handlebars-using-requirejs.html

The issue I have is when require.js is already loaded on the page, then loading handlebars.js afterwards, the `Handlebars` global object is nowhere to be found.

jQuery, on the other hand, still loads and makes its global objects `$` and `jQuery` available when its script tag comes after require.js. Can Handlebars do the same?

Tests - jQuery passes, Handlebars fails:
http://lucaslessa.com/handlebars/qunit-handlebars-loaded-after-requirejs.html

I ended up patching handlebars-v3.0.3.js so it no longer tries to use `define()` when loading and the problem went away.
```js
	else if(typeof define === 'function' && define.amd)
		define(factory);
```

**Comment by JSteunou** [comment]
Try using require-hbs plugin with the solution I posted above.

**Comment by lulessa** [comment]
@JSteunou Thanks for the suggestion. I'm loading handlebars.runtime as part of an app service asynchronously embedded on a number of different sites, where I don't have control of the page's javascript ecosystem. That's how I ran into the problem above, but only for those sites that load require.js before my app.

My solution patching handlebars.js was too forceful. Seeing what you did above, the following (similar) workaround is better suited to my app's js, does not need a plugin, and means I can use future handlebars releases without patching:
```js
if (typeof requirejs === 'function') {
  // define external/CDN paths - see http://requirejs.org/docs/optimization.html#empty
  requirejs.config({
      paths: {
          'handlebars/runtime': '//cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.3/handlebars.runtime'
      }
  });

  require(['handlebars/runtime'], function (myHandlebars) {
    myAppModule.handlebars = myHandlebars;
  });
} else // regular method of loading handlebars.runtime
```
