### ISSUE TITLE
docs say that `0` is truthy, but.. 

### ISSUE THREAD

**Issue by 75lb** [wycats/handlebars.js#949]
this template will output `one`, but not `zero`
```hbs
{{#if 0}}zero{{/if}}
{{#if 1}}one{{/if}}
```

yet the docs say 
> If its argument returns false, undefined, null, "" or `[]` (a "falsy" value), Handlebars will not render the block.

According to the docs, `zero` should have output.. is the issue with the docs, or the code?

what's the easiest way to have `0` evaluate to truthy? 

cheers!

**Comment by JosephClay** [comment]
The docs are correct. `0` is a falsy value in javascript, it's just not listed in the example alongside `false`, `undefined`, etc...

Can you use [`#unless`](http://handlebarsjs.com/builtin_helpers.html)? Otherwise, you could use a block helper:

```js
Handlebars.registerHelper('if_truthy_or_zero', function(val, options) {
    var isTruthy = !!val || val === 0;
    return isTruthy ? options.fn(this) : options.inverse(this);
});
```

**Comment by 75lb** [comment]
that helper looks just the ticket - thanks!

so, the docs need updating then to include `0` as a falsy value.. 

cheers!
