### ISSUE TITLE
Exclude Built-in helpers from template compile process

### ISSUE THREAD

**Issue by TonySergio** [wycats/handlebars.js#951]
I need to run template compilation process only with my own custom-helpers and ignore built-in helpers of Handlebars, may i do that , or  use another approach?

**Comment by kpdecker** [comment]
Create a custom handlebars environment via `Handlebars.create` and then replace the `helpers` object with your own i.e.

```
var myEnv = Handlebars.create();
myEnv.helpers = {};
myEnv.registerHelper('myHelper'...);
```
