### ISSUE TITLE
Handlebars AMD version

### ISSUE THREAD

**Issue by Jmunb** [wycats/handlebars.js#952]
Hello, where can I get a AMD runtime version of the handlebars v2?

**Comment by mattkime** [comment]
https://github.com/wycats/handlebars.js/issues/948

**Comment by kpdecker** [comment]
The UMD builds defined here https://github.com/components/handlebars.js/blob/master/handlebars.runtime.js are the current recommendation. There is a standalone amd build in that repository as well but there have been reports of it not working in all environments.
