### ISSUE TITLE
auto stringify object to json

### ISSUE THREAD

**Issue by JJia-OOOO** [wycats/handlebars.js#954]
is it reasonable to add json to an html data attribute?
and is it reasonable to auto stringify object to json?

e.g.

    var src = "<div data-x='{{this}}'>{{foo}}</div>";
    var tpl = Handlebars.compile(src);
    var html1 = tpl({foo:123}); // --> <div data-x='{"foo":123}'>123</div>
    var html2 = tpl({});        // --> <div data-x='{}'></div>
    var html3 = tpl(null);      // --> <div data-x=''></div> or nothing or error

**Comment by kpdecker** [comment]
Handlebars is agnostic to the output format. You'll want to either format the data prior to sending into the template or use a helper to perform the proper formatting.
