### ISSUE TITLE
Loading precompiled templates server side (Node JS)

### ISSUE THREAD

**Issue by RozzyNoder** [wycats/handlebars.js#955]
Every time I try to load precompiled templates like below:
`var compiledTemplate =  handlebars.templates['hello'];`
I get a cannot read property 'hello' of undefined. 

whereas the compile works fine like below:
`var uncompiledTemplate = handlebars.compile(template); `

So what is the  protocol or configuration  for loading these compiled templates so they get read in from the templates directory/file ? 
I checked my configuration, file names, the handlebar is  version (2.0 beta) and compiler version is six.  

Thanks.

**Comment by kpdecker** [comment]
This isn't enough information to reproduce. Can you provide an full example of what you are trying to do?

**Comment by RozzyNoder** [comment]
Sure, here we go.
```
var template = fs.readFileSync(“./hello.html", "utf8");
var data = {message : "Hello world!"};

var compileTemplate = handlebars.compile(template);
var finalPageHTML = compileTemplate(data);

// Simply trying to replace the last two lines above with the two below but get error

/* var preCompiledTemplate =  handlebars.templates['hello'];
	var finalPageHTML = preCompiledTemplate(data);
*/
```


**** hello.html ****
```
<html>
	<head>
		<title>Example</title>
	</head>
	<body>
		<p>Oh look, it's a message: {{message}}</p>
	</body>
</html>
```
****

I renamed the file above as hello.handlebars and compiled it to hello.js, put it in a directory called “templates” below my “js” directory.

So simply trying to load "precompiled" template to produce dynamic pages on server side.

**Comment by kpdecker** [comment]
Precompiled templates need to be compiled at some point and generally are not intended for use on servers as they require additional steps to work with them. Your first version is the recommended route, although I believe you can do something like

```
var template = require('./hello.handlebars');
```

**Comment by RozzyNoder** [comment]
Pardon me I don't understand "Precompiled templates need to be compiled". Precompiled means they are already compiled. Right ?

Handlebar templates get compiled to a .js file and then that is filled with db data or context to generate the final page. Correct ?

So I am just trying to precompile for speed so I can dynamically generate page off course feeding them with my db data at run time on the server side  for final transmission.as  "text/html" to client browser.

My question simply is  how to load the 'hello' template from hello.js created from hello,handlebar so I have a compiled template object ? Or say another template called "hello2" from a aggregate templates.js file  containing all my compiled templates. By the way I tried require, but that does not work.

Apologize, if I being senile.

**Comment by kpdecker** [comment]
Precompiled means that they are precompiled by you for your clients. They are not made available automatically to node consumers.

Your example using readFileSync is the easiest and likely the best way to load the templates, so you are on the right path there.

**Comment by ekskimn** [comment]
@RozzyNoder Hi I'm trying to do something similar to this.  Did you manage to make it work?  Every time I take the outputted precompiled templates to a file and then later try to read them into a variable the json parsing fails because json technically isn't supposed to have functions in them but of course the hbs templates are functions. 

I've also tried a dead simple example, one from the handlebars site itself 
    
     var templateSpec = Handlebars.precompile('{{foo}}');
     var template = Handlebars.template(templateSpec);
     template({});

and i get an error like:
    throw new _Exception2['default']('Unknown template object: ' + typeof temp
          ^
Error: Unknown template object: string
    at Object.template (/project/node_modules/handlebars/dist/cjs/handlebars/runtime.js:48:11)
    at HandlebarsEnvironment.hb.template (/project/node_modules/handlebars/dist/cjs/handlebars.runtime.js:46:20)


this is run via gulp, incidentally.

I would love any and all insight you might have.  I'm really stuck and I need this to work very soon (like as in tomorrow)

Thanks in advance.

**Comment by xpepermint** [comment]
@kpdecker I try to achieve the same as described by @ekskimn . I generate HTML code in a loop so I guess precompiling a template would speed up the process. What do you suggest?

**Comment by nknapp** [comment]
@xpepermint if you have a loop, from what I know it should be performant to do something like:
```js
var template = Handlebars.compile("{{title}}\n{{text}}");
largeArray.map(function(element) {
  return template(element);
});
```
Just compile the template before the loop and call the compiled function inside the loop.

**Comment by xpepermint** [comment]
@nknapp thx

**Comment by sido420** [comment]
Did anyone manage to use precompiled templates server side?

**Comment by ldgarcia** [comment]
@sido420 

I also wanted to use precompiled templates server side.

I am using a lambda function to send emails with HTML content, so I wanted to minimize my function's execution time and package size (`handlebars/runtime` is a smaller) as much as possible.

I have a script that generates precompiled templates (`mjml -> html -> handlebars precompiled`).

It is something like:

````javascript
const Handlebars = require('handlebars')
const precompiledContent = Handlebars.precompile('<b>{{ message }}</b>')
fs.writeFileSync('xyz/template.js', `module.exports = ${precompiledContent}`, 'utf8')
````

Then you can use the template like this:

````
const Handlebars = require('handlebars/runtime')
const message = 'Hi'
const template = require('./template.js')
const content = Handlebars.template(template)({ message })
````

**Comment by amruta-pani** [comment]
@RozzyNoder @ekskimn I managed to make this work but with a slight change. Instead of your reference to `hello.js` in your below code snippet, 

`var preCompiledTemplate =  handlebars.templates['hello'];
var finalPageHTML = preCompiledTemplate(data);`

refer the actual hbs file that is used to generate the .js file, i.e.

`var preCompiledTemplate =  handlebars.templates['hello.hbs']`
