### ISSUE TITLE
Release 2.0.1

### ISSUE THREAD

**Issue by RobLoach** [wycats/handlebars.js#958]
[Handlebars 2.0.0](https://github.com/wycats/handlebars.js/releases/tag/v2.0.0) was released more than five months ago. What's holding back a bug-fix release of `2.0.1`?

**Comment by kpdecker** [comment]
Master has breaking changes so we are doing a 3.0 release. This is in the final phases of documentation updates and should go out when all 3.0 tagged issues go out.
