### ISSUE TITLE
RequireJS problem

### ISSUE THREAD

**Issue by ram-you** [wycats/handlebars.js#963]
For require.js workaround, please change this line:
```javascript
if (typeof define === 'function' && define.amd) {
```
To this:
```javascript
if (typeof define === 'function' && define.amd && false) {
```
Thanks.
(credits https://github.com/nikolas )

**Comment by kpdecker** [comment]
We're not disabling the AMD support and particularly not doing it by a constant that invalidates the if branch. Can you describe the problem that you are seeing and the environment in more detail? Glad to reopen if more details are provided (but I'm about to go on vacation, so my responses my be delayed a bit)

**Comment by ram-you** [comment]
To not disabling the AMD support, this is another workaround:
Change:
```javascript
if (typeof define === 'function' && define.amd) {
 define([], factory);
```
To this:
```javascript
if (typeof define === 'function' && define.amd) {
  define([], function () {
            return (root.Handlebars = factory());
        });
```
Thanks.

**Comment by kpdecker** [comment]
Please let us know what the issue you are seeing is. We can't fix something
that we don't know is wrong.

**Comment by ram-you** [comment]
Sorry.
I'm using Handlebars with requirejs and when I migrated from v1.3.0 to v3.0.0 I had this error:
<b> Uncaught ReferenceError: Handlebars is not defined</b>
Changing the way I proposed, no more error.

**Comment by kpdecker** [comment]
You are using handlebars as a global within an AMD environment. This is not
the ideal and instead I'd recommend importing the library as an AMD
dependency. I.e

define(['handlebars/runtime'], function(Handlebars) ...

**Comment by ram-you** [comment]
In my project I defined all dependencies as globals. It will be a lot of work to define handlebars, the way you proposed in every view of the project (minimum of 30-40 views). For example Marionette.js, backbone.js and much others make the same as I proposed.

**Comment by kpdecker** [comment]
I would recommend not using AMD in that case. If you do need to for
whatever reason the. I would suggest you create a customs require call that
exports the value to the global space.

This is not something we can change in the library because it will piss
people off as many more people are expecting the AMD mode of the library to
not export anything in the global space.

**Comment by ram-you** [comment]
Ok. Thank you. I will do like you suggested.
