### ISSUE TITLE
"handlebars --version" does not work with v3.0.0

### ISSUE THREAD

**Issue by abloomston** [wycats/handlebars.js#966]
with handlebars v2.0.0:

    $ handlebars --version
    2.0.0
    
with handlebars v3.0.0:

    $ handlebars --version
    Precompile handlebar templates.
    Usage: node /usr/local/bin/handlebars [template|directory]...
    
    Options:
      -f, --output         Output File                                                           
      --map                Source Map File                                                         [string]  [default: undefined]
      -a, --amd            Exports amd style (require.js)                                        
      -c, --commonjs       Exports CommonJS style, path to Handlebars module                       [default: null]
      -h, --handlebarPath  Path to handlebar.js (only valid for amd-style)                         [default: ""]
      -k, --known          Known helpers                                                         
      -o, --knownOnly      Known helpers only                                                    
      -m, --min            Minimize output                                                       
      -n, --namespace      Template namespace                                                      [default: "Handlebars.templates"]
      -s, --simple         Output template function only.                                        
      -r, --root           Template root. Base value that will be stripped from template names.  
      -p, --partial        Compiling a partial template                                          
      -d, --data           Include data when compiling                                           
      -e, --extension      Template extension.                                                     [default: "handlebars"]
      -b, --bom            Removes the BOM (Byte Order Mark) from the beginning of the templates.
      -v, --version        Prints the current compiler version                                   
      --help               Outputs this message

**Comment by kpdecker** [comment]
Released in 3.0.1
