### ISSUE TITLE
How to bind html 'input' to template variable

### ISSUE THREAD

**Issue by zion03** [wycats/handlebars.js#968]
Problem, when I changing first input helper not recalculates value:

       <script id="payment" type="text/x-handlebars-template">
       <input type="text" value="{{ val }}">
       <input type="text" value="{{ rate val }}">
       </script>

        Handlebars.registerHelper('rate', function(val) {
                return val * 2;
        });

        var popupTpl = Handlebars.compile($('#payment').html());
         popupHTML = popupTpl({val:9});

How to bind html 'input' to template variable (val) in a right way?

**Comment by kpdecker** [comment]
This is outside of the scope of Handlebars proper as we only render a string and we are not aware of the actual content. The tildeio/htmlbars project would be a better forum to raise this question with as that is explicitly targeted at rendering HTML content.

**Comment by awb715** [comment]
Did anything ever come up about this? Looking to do something like this

**Comment by nknapp** [comment]
This still is not part of Handlebars, but maybe the. incremental-bars project is doing it.
