### ISSUE TITLE
Wrong context applied to function calls from template

### ISSUE THREAD

**Issue by jrf0110** [wycats/handlebars.js#971]
My problem is best illustrated by an example:

```javascript
var handlebars = require('handlebars');
var tmpl = handlebars.compile('hello, {{person.getName}}');
 
var bob = Object.create({
  name: 'Bob'
, getName: function(){
    console.log( 'this', this );
    return this.name;
  }
});
 
// this { name: 'Bob' }
// 'Bob'
bob.getName()
 
// this { person: { name: 'Bob' } }
// 'hello, '
tmpl({ person: bob })
```

Notice, when the function is called via the template, the `this` value is changed to the data parameter from `tmpl`.

I'm not sure if this was intended or not. Thoughts?

**Comment by difosfor** [comment]
+1 Also seeing similar issues with this argument value in Handlebars v3 (using pre-compiling).

**Comment by zordius** [comment]
`this` inside a custom helper means `current data context` , it is a feature. You can find document here:
 http://handlebarsjs.com/block_helpers.html , inside the first section `Basic Blocks`:
**Handlebars always invokes helpers with the current context as `this`, so you can invoke the block with `this` to evaluate the block in the current context.**

**Comment by jrf0110** [comment]
I didn't realize functions on data objects were treated as helpers. That seems funky

**Comment by zordius** [comment]
Sorry, maybe it can be handled differently for method of data objects. What I said is just for custom helper.

**Comment by kpdecker** [comment]
This applies for all helper execution, regardless of how they are found. This does differ from the javascript behavior and has caused some confusion. This behavior has been this way for years and is not something that we can easily change without potentially breaking numerous templates.

I'd recommend binding methods that you need to run against their host object rather than the current context.

**Comment by jrf0110** [comment]
@kpdecker Handlebars treats functions in the data passed into the template as helpers?

Is there any documentation that outlines the behavior of:

```javascript
handlebars.compile('{{myFn}}')({
  myFn: function(){ ... }
});
```

**Comment by difosfor** [comment]
Mustache does work as you and I would expect. Here's an excerpt from: https://github.com/janl/mustache.js:

View:
```javascript
{
  "beatles": [
    { "firstName": "John", "lastName": "Lennon" },
    { "firstName": "Paul", "lastName": "McCartney" },
    { "firstName": "George", "lastName": "Harrison" },
    { "firstName": "Ringo", "lastName": "Starr" }
  ],
  "name": function () {
    return this.firstName + " " + this.lastName;
  }
}
```

Template:
```html
{{#beatles}}
* {{name}}
{{/beatles}}
```

Output:
* John Lennon
* Paul McCartney
* George Harrison
* Ringo Starr

**Comment by jrf0110** [comment]
You also run into the same problem with ES5 getters:

```javascript
var handlebars = require('handlebars');
var tmpl = handlebars.compile('hello, {{person.fullname}}');

var bob = Object.create({
  first: 'Bob'
, last: 'Bill'
, get fullName(){
    return [ this.first, this.last ].join(' ');
  }
});

// 'Bob Bill'
bob.fullName

// 'hello, '
tmpl({ person: bob })
```

**Comment by difosfor** [comment]
After a more careful look I realized the Mustache example was not exactly the same. In fact, Mustache seems to work exactly the same as Handlebars in this case:

```javascript
var tmpl = '1:{{person.getName}} 2:{{#person}}{{getName}}{{/person}}';

var data = {
    person: {
        name: 'Bob',
        getName: function() {
            console.log('this', this);
            return this.name;
        }
    }
};

// this { name: 'Bob' }
// JavaScript Bob
console.log('JavaScript', data.person.getName());

// this { person: { name: 'Bob' } }
// this { name: 'Bob' }
// Mustache 1: 2:Bob
console.log('Mustache', Mustache.render(tmpl, data));

// this { person: { name: 'Bob' } }
// this { name: 'Bob' }
// Handlebars 1: 2:Bob
console.log('Handlebars', Handlebars.compile(tmpl)(data));
```
Fiddle: https://jsfiddle.net/peterpaul/ax3nqadg/

So apparently this is the way Mustache and Handlebars are supposed to work or at least have been working for a long time. As such I suppose this will not be changed here.

I'll consider whether I want to go along with this idiosyncrasy or look for or fork an alternative template engine. I'm not sure yet; I have run into some other issues with Handlebars that I still have to investigate as well.
