### ISSUE TITLE
Using SafeString to return an opening tag

### ISSUE THREAD

**Issue by sir-dunxalot** [wycats/handlebars.js#974]
I'll preface this by saying I haven't been able to figure out whether this is a Handlebars or browser issue.

I expect the following to return opening and closing HTML node tags around some content (I'm calling handlebars from inside an Ember helper):

```js
// app/helpers/open.js

export function open(/* params, hash */) {
    return new Ember.Handlebars.SafeString('<div>');
}
```

```js
// app/helpers/close.js

export function close(/* params, hash */) {
    return new Ember.Handlebars.SafeString('</div>');
}
```

```hbs
{{!--app/templates/index.hbs--}}

{{open}}
Some content
{{close}}
```

However, in the browser console, an inspection reveals the following DOM:

```
<div></div>
Some content
```

Is `Handlebars.SafeString` expected to automatically close an element like this or is this an issue better suited to Ember or browsers?

Thanks in advance for your help.

**Comment by kpdecker** [comment]
I would raise this issue with Ember as I suspect that this is related to their data binding additions, but if you can provide a jsfiddle using vanilla handlebars, I'd be glad to reopen this and help debug.
