### ISSUE TITLE
Syntax hightlighting in editor

### ISSUE THREAD

**Issue by ronan-paul** [wycats/handlebars.js#976]
First of all, this is a great tool ! 

I am currently experimenting javascript templates which I include in my PHP script with the <script type="text/template" id="whatever>...</script>.

I am using Zend Studio as an editor, and I could not find a way to have syntax highlighting for the template.

Any clue on how to achieve this ?

Regards,

Ronan

**Comment by kpdecker** [comment]
Closing this as I am not sure what this is requesting.
