### ISSUE TITLE
Cannot access parent in nested each with precompiled template

### ISSUE THREAD

**Issue by HorstBrack** [wycats/handlebars.js#977]
I have this object:
```
ProfileForm = [
 {
  'Q_ID' : 1, 
  'Q_TEXT' : 'Question one',
 'answers': [ {'A_ID':1,'A_TEXT':'YES'},{'A_ID':2,'A_TEXT':'No'} ] 
 },
{
  'Q_ID' : 2, 
  'Q_TEXT' : 'Question two',
 'answers': [ {'A_ID':1,'A_TEXT':'YES'},{'A_ID':2,'A_TEXT':'No'} ] 
}
];
```

I am trying to do displaying a simple Question/Answers multiple choice form like so:

```
{{#each ProfileForm}}
<div class="profileQuestion">
 {{Q_TEXT}} / {{Q_ID}}
{{#each answers}}
  <div class="radio">
   <label><input type="radio"  value="{{A_ID}}" name="Q_{{../Q_ID}}" id="Q_{{../Q_ID}}_{{A_ID}}" />
    <span>{{A_TEXT}}</span>
   </label>
  </div>
{{/each}}
</div>
{{/each}}
```

The {{../Q_ID}} should display the Question ID in the nested answers array.
**Actually it does**, but only when I insert this template into the html document with &lt;script&gt; tags.

But when I precompile it I receive the error
" Uncaught TypeError: Cannot read property '1' of undefined" in templates.profile.js:83

The corresponding line in templates.profile.js says:
*escapeExpression(lambda((depths[1] != null ? depths[1].Q_ID : depths[1]), depth0))*

Btw I also tried to loop with {{#ProfileForm}} and {{#answers}} instead of using each - no difference.

**Comment by difosfor** [comment]
+1 Also seeing references break down when they are nested within block helpers in general (also with {{#if x}} for example) when they are pre-compiled.

Might this also be related to #971?

**Comment by kpdecker** [comment]
@HorstBrack can you post this as a jsfiddle so I have something that I can debug against?

**Comment by kpdecker** [comment]
Also are you using the precompiler? What version of the runtime?

**Comment by HorstBrack** [comment]
I am using the precompiler installed by npm, it says
handlebars@3.0.0 when installing

My handlebars.runtime.min.js is v3.0.0

A jsfiddle is here:
http://jsfiddle.net/horstbrack/etwhat7b/8/

I hope I did that right, I copied the precompiled object into the js source. 

Actually I found a way around the problem by recoding my "ProfileForm" from an array of objects to an object of objects. That worked then with {{#each

**Comment by HorstBrack** [comment]
OK,
turned out I was fooled by two npm installations.
I had grunt do the pre compilation, and grunt-contrib-handlebars installs V2 of handlebars.
Sorry.

So, anybody coming across this issue, just install handlebars manually
(npm install handlebars), then 
- move to node_modules/grunt-contrib-handlebars/node_modules/
- remove the directory "handlebars" there
- copy node_modules/handlebars to node_modules/grunt-contrib-handlebars/node_modules/
Restart grunt and everything works
