### ISSUE TITLE
Precompiled code contains unused function arguments

### ISSUE THREAD

**Issue by difosfor** [wycats/handlebars.js#978]
UglifyJS is giving me tons of warnings each time I minify my precompiled templates (e.g. each change I make):
Dropping unused function argument data
Dropping unused function argument partials
Dropping unused function argument helpers
Dropping unused function argument depth0

Would be nice if the pre-compiler would only include those arguments when they are actually used.

**Comment by kpdecker** [comment]
This is what the minimizer is for. Adding tracking for this in the compiler adds a lot of complexity and overhead to the process and it's already handled by another tool.

**Comment by difosfor** [comment]
Too bad, I hoped it would have been easy to implement in the compiler. 

The reason why this is relevant to me is that I consider unused code to be a code smell so I want to warn about it during all phases of building with https://github.com/exmg/nbob. And unlike JSHint etc. UglifyJS2 does not facilitate suppressing these warnings using comments or anything.

I guess I will have to implement UglifyJS2 warning filtering myself.

Thanks for you time!
