### ISSUE TITLE
Parent context reference behaves strangely

### ISSUE THREAD

**Issue by difosfor** [wycats/handlebars.js#979]
In the following example, ../ seems to be equal to . so I have to use ../../ to get to the parent context. E.g: I would expect Y to work instead of Z.

It seems that adding a block helper like {{#if}} also adds another parent context level, even when the block context is equal to the parent context.

Is this intended behavior or a bug?

HTML:
```html
<script id="template" type="text/template">
	{{#each questions}}
	<div>
		{{#each answers}}
		<div>X: {{../id}}:{{code}}</div>
		{{#if @root.ready}}
		<div>Y: {{../id}}:{{code}}</div>
		<div>Z: {{../../id}}:{{code}}</div>
		{{/if}}
		{{/each}}
	</div>
	{{/each}}
</script>
```

JavaScript:
```javascript
var template = document.getElementById('template').innerHTML;
var compiled = Handlebars.compile(template);
var data = {
	ready: true,
	questions: [ {
		id: 1,
		answers: [ { code: 'a' } ]
	} ]
};
var html = compiled(data);
document.body.innerHTML = html;
```

Output:
```html
X: 1.a
Y: .a
Z: 1.a
```

Fiddle: http://jsfiddle.net/peterpaul/yd574m6n/

**Comment by kpdecker** [comment]
This is the intended behavior.
