### ISSUE TITLE
about handlebrasjs.com example Helpers

### ISSUE THREAD

**Issue by nimojs** [wycats/handlebars.js#980]
in http://handlebarsjs.com/expressions.html Helpers section
```
{{{link story}}}
```
and
```
Handlebars.registerHelper('link', function(object) {
  var url = Handlebars.escapeExpression(object.url),
      text = Handlebars.escapeExpression(object.text);

  return new Handlebars.SafeString(
    "<a href='" + url + "'>" + text + "</a>"
  );
});
```

> Handlebars to escape a value, use the "triple-stash", {{{ 

> you should return a Handlebars SafeString if you don't want it to be escaped by default

Why `{{{link story}}}` use `{{{`? 

What's the difference between with`{{link story}}`

Please teach me, thank you!

**PS:**
Question is：
This example has use `SafeString ` to prevent escape. 
Why am I still need to use `{{{` , Using `{{link story}}` can also work。

Demo: use `{{` http://jsfiddle.net/NimoChu/h4do3noc/ 
Demo: use `{{{` http://jsfiddle.net/NimoChu/h4do3noc/1/

**Comment by waynedpj** [comment]
just above the section of that page you are referencing there is an explanation of what the `{{{` `}}}` are for:
```
Handlebars HTML-escapes values returned by a {{expression}}. If you don't want Handlebars to escape a value, use the "triple-stash", {{{
```

hope that helps.

**Comment by nimojs** [comment]
@waynedpj 
Thank for your reply.

I konw the use the  `{{{`.

Question is：
This example has use `SafeString ` to prevent escape. 
Why am I still need to use `{{{` , Using `{{link story}}` can also work。

**Comment by waynedpj** [comment]
@nimojs sorry, i figured you might have missed that bit.

unfortunately i am not enough of an expert to know the difference in that example.  they do indeed seem to do the same thing.  perhaps it is simply a matter of using `Safestring` to make a helper's output not escaped by default, while using `{{{ }}}` allows escaping to be controlled in the template?

**Comment by kpdecker** [comment]
Functionally this behaves the same with the `{{{` syntax or the `SafeString` return. The generated code is slightly more optimized if the `{{{` form is used but the end result is the same.
