### ISSUE TITLE
When compiling with the partial flag, the file ex is included in the name

### ISSUE THREAD

**Issue by cfjedimaster** [wycats/handlebars.js#981]
When compiling a set of handlebars templates, given you have a name like mytemp.handlebars, when you compile, the resulting template is just "mytemp". But if you do the same with the -p flag and mypartial.partials, then you end up with a name "mypartial.partials". Shouldn't it just be mypartial?

**Comment by cfjedimaster** [comment]
Ok, it looks like if I use .handlebars for the filename, the code rips it out and it works fine, but I wanted to use a different extension so I could compile all my regular templates at once and all my partials at once.

**Comment by kpdecker** [comment]
The existing CLI is meant as a helper for the default use case. You might want to write your own build script to support your specific case (I don't believe .partial extension is common, etc)
