### ISSUE TITLE
Compile both partials and regular templates at the same time

### ISSUE THREAD

**Issue by cfjedimaster** [wycats/handlebars.js#982]
As far as I can tell, I can't compile a set of templates *and* partials in one command. So for ex, right now I do:

handlebars a b c -f templates.js
handlebars somepartial -p -f partials.js
cat templates.js partials.js > templates_all.js

Is it possible to specify a list of regular templates, then partials, and spit them out into one file?

**Comment by kpdecker** [comment]
This is something that I'd recommend writing your own build script to handle as well.
