### ISSUE TITLE
Byte-Order-Mark should be auto detected and removed for a partial view file

### ISSUE THREAD

**Issue by leoyoo** [wycats/handlebars.js#983]
If I put the partial view template in UTF-8 file, and sometimes BOM is auto added before the beginning in some editor, such as Webstorm. this situation is not auto handled by handlebars, so if the BOM is not removed, then a extra "" and newline will be added in the view, which will damage the css layout, for example, one more empty line inserted in the view, looks strange to the developer. and it's hard to find this issue to remove BOM. 
So I suggest the handlebars can detect this BOM and remove it if exist.

**Comment by kpdecker** [comment]
Use the `-b` option if using the integrated CLI. Otherwise this is up to whatever tool you are using to strip. The library itself explicitly avoid modifying templates based on specific use cases.
