### ISSUE TITLE
Partials shouldn't inherit parent indent after being parsed

### ISSUE THREAD

**Issue by matthiasmullie** [wycats/handlebars.js#985]
Unless when compiled with preventIndent: true, invokePartialWrapper re-applies parent indents to partials.

It does so by adding the indent in front of every line of the parsed partial result (https://github.com/wycats/handlebars.js/blob/master/lib/handlebars/runtime.js#L51), potentially adding it in wrong places.

E.g.
**parent.handlebars**
```html
    {{> child}}
```

**child.handlebars**
```html
{{some_var}}
```

If we were to assign some_var this value:
```html
<pre>this
is
some
text</pre>
```
it will eventually end up being rendered like this, because the parent indent is prepended to every partial output line:
```html
    <pre>this
    is
    some
    text</pre>
```

For most nodes, adding some whitespace won't visually affect anything. <pre> however preserves whitespace, so this behavior changes what's displayed.

I think whitespace should only be added to the partial source, not to the output after parsing in all variables and stuff.

**Comment by kpdecker** [comment]
This behavior is defined in the mustache spec. https://github.com/mustache/spec/blob/master/specs/partials.yml#L13-L15

The `preventIndent` flag provides you the mechanism to avoid this behavior if it does not work for your use case. This should be set if the default behavior from Mustache doesn't fit your needs.
