### ISSUE TITLE
Handlebars 2.0.0 suddenly broken in Ember app

### ISSUE THREAD

**Issue by panta82** [wycats/handlebars.js#987]
I'm using handlebars 2.0.0 as part of my Ember app's build process. I had to delete my `node_modules` directory. After an `npm install`, handlebars suddenly started producing garbage. Example:

```
data.buffer.push(this.escapeExpression,(,(helpers.partial || (depth0 && depth0.partial) || helpers.helperMissing).call(depth0,"main_menu",{"name":"partial","hash":{},"hashTypes":{},"hashContexts":{},"types":["StringLiteral"],"contexts":[depth0],"data":data}),));
```

I hunted down an old handlebars directory from backup and copied it over the one in my `node_modules` directory. Suddenly, things started working again:

```
data.buffer.push(escapeExpression(((helpers.partial || (depth0 && depth0.partial) || helperMissing).call(depth0, "main_menu", {"name":"partial","hash":{},"hashTypes":{},"hashContexts":{},"types":["STRING"],"contexts":[depth0],"data":data}))));
```

I checked and both versions are labeled "2.0.0" inside `package.json`.

I have no idea what happened here. Is it possible npm version got corrupted? Or was it updated without a version bump?

**Comment by kpdecker** [comment]
Handlebars was not repushed in npm to my knowledge and I believe I'm the only one with rights to push to it on npm. Have you `diff -r`ed the two directories?

**Comment by panta82** [comment]
The problem has disappeared.

In the meantime, I have deleted npm's local cache. That was probably what fixed it. Although how the thing got corrupted in such a way to produce garbled output instead of errors is anyone's guess.

As I didn't keep the broken copy, there's probably no way to figure out what had happened.
