### ISSUE TITLE
Handlebars unable to pass array value by index to helpers

### ISSUE THREAD

**Issue by jayavigneshksd** [wycats/handlebars.js#988]
{{#each fieldlist}}
        <span style="{{#ifCond this.3. '!=' '301'}}{{else}}display:none{{/ifCond}}"></span>
        {{/each}}
        fieldlist is a jsonobject of the format {key:["tester","sample",null,"301"]} ie key:jsonArray

        Handlebars.registerHelper('ifCond', function(param1, operator, param2, options) {
             switch(operator):
             {
                result =//based on case if condition is called
             }
             if(result){
             options.fn(this);
             }else{
             options.inverse(this);
             }  
        }

On debugging i found the values like this
param1 = 301  
operator = ["tester","sample",null,"301"]  
param2= "!="  
options = "301"

Seems like there might be an issue while parsing

**Comment by kpdecker** [comment]
`{{#ifCond this.3. '!=' 301}}` will pass a number rather than a string.
