### ISSUE TITLE
Source-map error with requirejs

### ISSUE THREAD

**Issue by SteppeEagle** [wycats/handlebars.js#989]
In version > 3.0.0, i get error:
```
Error: Module name "source-map" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    at makeError (require.js:166)
    at Object.localRequire [as require] (require.js:1400)
    at requirejs (require.js:1745)
    at handlebars.js:2459
    at handlebars.js:2610
    at Object.context.execCb (require.js:1658)
    at Object.Module.check (require.js:869)
    at Object.Module.enable (require.js:1151)
    at Object.Module.init (require.js:782)
    at callGetModule (require.js:1178)
```
but in vertion 2.0.0 - all fine.

I see in code (at handlebars.js:2459 - v.3.0.1) require call:
``` var SourceMap = require('source-map'), ```

i think it's incorrect use and this error linked with [issue #902 ](https://github.com/wycats/handlebars.js/pull/902)

**Comment by kpdecker** [comment]
This is another artifact of trying to fight all of the module systems in javascript. I believe we can hack around this by not requiring this module under AMD. Additionally, I've added test coverage to ensure that we don't get his with this again.

**Comment by kpdecker** [comment]
Released in 3.0.2

**Comment by vxpert** [comment]
i am using 3.0.3 and still facing the same issue.. i am using handlebar with dojo mvc app

**Comment by kpdecker** [comment]
@vxpert which build file are you linking to?
