### ISSUE TITLE
Allow passing null/undefined literals subexpressions

### ISSUE THREAD

**Issue by blimmer** [wycats/handlebars.js#990]
I originally [filed this](https://github.com/emberjs/ember.js/issues/10772) on the Ember.JS tracker but was directed here, instead.

It would be really great if subexpressions could handle `null` and `undefined` literals. It doesn't appear to work that way currently. I have an [EmberJS JSBin](http://jsbin.com/simosutano/4) that shows the issue I'm talking about.

**Comment by mmun** [comment]
Not just subexpressions. They would need to fit anywhere an Expression can go.

**Comment by mmun** [comment]
Thank you!! :)

**Comment by mmun** [comment]
BTW your patch doesn't support {{null}} and {{undefined}} so it diverges from how boolean/number/etc are treated. I don't really care that much though. Sorry to be a pain...

**Comment by kpdecker** [comment]
@mmun, dfd141c adds support for null and undefined in the helper name/path section.

**Comment by mmun** [comment]
Thanks.

**Comment by kpdecker** [comment]
Released in 3.0.2
