### ISSUE TITLE
version of download on http://handlebarsjs.com/

### ISSUE THREAD

**Issue by bardware** [wycats/handlebars.js#991]
Hi,

http://handlebarsjs.com/ offers to download version 3.0.0
Where's 3.0.1?

**Comment by jdr0dn3y** [comment]
From the README

> Alternatively, if you prefer having the latest version of handlebars from the 'master' branch, passing builds of the 'master' branch are automatically published to S3. You may download the latest passing master build by grabbing a handlebars-latest.js file from the builds page. When the build is published, it is also available as a handlebars-gitSHA.js file on the builds page if you need a version to refer to others. handlebars-runtime.js builds are also available.

**Comment by kpdecker** [comment]
Updated. Thanks for reporting this!
