### ISSUE TITLE
Template is not reading html codes properly in input field

### ISSUE THREAD

**Issue by metalshan** [wycats/handlebars.js#992]
If the value has an html code (suppose &lt; or &#8482) the value is displayed as it is. Handlebars prevent the browser to do its default work it seems.

**Comment by kpdecker** [comment]
I'm not sure what the issue is here. Could you provide some code examples to better explain it?

**Comment by metalshan** [comment]
My exact problem is, I have to make a name filter (autosuggest). In the autosuggest dropdown where I am using {{{displayValue}}} is working fine but the moment I select something from the dropdown and the value appears in the input box, it displays html code, not the output.

Check the link: http://emberjs.jsbin.com/javixobehi/2/edit
In the input box also it should display "TM" not as &# 8482;

**Comment by kpdecker** [comment]
Please raise the issue with the ember folks. This is an issue with the `input` helper.
