### ISSUE TITLE
Access Handlebars.Visitor in browser

### ISSUE THREAD

**Issue by tamlyn** [wycats/handlebars.js#994]
In node land I can get to `require('handlebars').Visitor` because this is explicitly exposed in `lib/index.js`. However in browser land (loading `dist/handlebars.js`) it seems that the `Visitor` object is closured out of reach. Is there any way to access it without using Browserify or AMD? If not, is there a reason for it being hidden?

**Comment by kpdecker** [comment]
Released in 3.0.2

**Comment by tamlyn** [comment]
Awesome. Thanks!
