### ISSUE TITLE
Standard solution for double processed handlebars blocks

### ISSUE THREAD

**Issue by husayt** [wycats/handlebars.js#995]
We have a scenario when we need to process templates twice. 
For example, email template to multiple recipients. On first run we inject names and and on second run we inject something else.

Currently we use something like this
```
[[fullName]] and {{someDate}}
```

during first run we inject  date, and then replace `[[` with `{{` and get this
```
{{fullName}} and 21.04.2016
```
Then we can process that with second context.

Rather than reinventing the wheel, I was wondering if there is a existing feature which does this. If not I would suggest this as a feature.

PS. Raw blocks and partials, don't solve this. 
PS. Merging contexts would not work either, as we might need to apply changes to result of first run, before doing the second go. Double run of a template is required.

**Comment by doowb** [comment]
Have you just tried escaping the delimiters that you want to process in the second pass?

```handlebars
\{{fullname}} and {{someDate}}
```

**Comment by kpdecker** [comment]
Yep, this should do it. @husayt I'm closing this but please let me know if this does not work for you.

Thanks @doowb!

**Comment by husayt** [comment]
Thanks. This is much better indeed.
