### ISSUE TITLE
Trying to use "each" to populate a table; only last row is showing?

### ISSUE THREAD

**Issue by Muzical84** [wycats/handlebars.js#997]
I have an array of objects returned from a WSDL through which I'm trying to loop, but only the last item is ever displayed.  Am I missing something?

```handlebars
<tr class="searchResults" id="searchResultsHTML"></tr>
<script id="result-template" type="text/x-handlebars-template">
    {{#each this}}
        {{log @index}}
        {{log this}}
        {{! create table rows with data from this }}
    {{else}}
        <tr class="alert largerError" id="errorMessageRow"><td class="empty" id="errorMessage" colspan="6">Either there has been an error, or your search did not return any records from any datasource.</td></tr>
    {{/each}}
</script>
```

And the JavaScript:
```javascript
    template=Handlebars.compile($("#result-template").html(),{data:{level:Handlebars.logger.DEBUG}});

    result=template(convertedData);
    $("#searchResultsHTML").html(result);
```

**Comment by kpdecker** [comment]
Can you post a JS fiddle demonstrating the issue?

**Comment by Muzical84** [comment]
Without giving away data and etc., if you want an exact copy....problem.  Here's a Fiddle, but because JSFiddle seems to be clamping down on loading external resources over HTTP, it will probably...not work.  It also might not work if you're using JSFiddle over HTTPS...  http://jsfiddle.net/Muzical/r023g1b5/  I also sliced out part of the middle, so <p> tags and such might not line up in this sample.  They DO line up in the actual file; I'm anal-retentive about that...

**Comment by kpdecker** [comment]
This fiddle has a number of syntax errors that prevent it from running. Can you fix those so that it's running similar to your local code?

**Comment by Muzical84** [comment]
OK...DevTools says "unexpected token u" but when I click the supposedly-offending line, it just highlights JSFiddle's DOCTYPE declaration...  Same thing happens in CodePen.io http://codepen.io/Muzical84/pen/BNBLom

I had to include everything that wasn't jQuery minified at the bottom of the JS area, due to HTTPS and MIME types and other irritatingness.  You may also have to tell your browser to allow unsafe scripts to get even that far...

**Comment by kpdecker** [comment]
Your data converter function is broken. The error is from JSON.parse trying to parse an undefined value. I can't really help with out a running example of the issue you are having.

**Comment by Muzical84** [comment]
I can view all of the data without incident in the console; wouldn't I be getting an error far sooner if JSON.parse() was failing?

**Comment by kpdecker** [comment]
I'm not seeing anything of the data in the log of the live example. Closing this for now but if you can put together a repo case that demonstrates an issue in the library, I'm glad to reopen.

**Comment by Muzical84** [comment]
My question wasn't really meant to suggest a case of a bug in the library; it was more that I wasn't super-sure from the documentation given if I was doing everything "right."  Templating is a new thing to me, but at times the official documentation doesn't seem designed for the 100% newbie =-\  (No offense.)
