### ISSUE TITLE
Change the name of SafeString as people are using it incorrectly.

### ISSUE THREAD

**Issue by wirepair** [wycats/handlebars.js#999]
The name is extremely misleading, and people are definitely using it incorrectly:
https://github.com/digitalsadhu/yeoman-require-boilerplate/blob/3049b94cd715fa3eb92bf2701e8089f00b68ea7a/app/scripts/helpers.js
https://github.com/thinkt4nk/frisk/blob/fd7d23ff2cb531591bb0bd1914fc79c8c4da6b8c/lib/view_helpers.js

I'd suggest renaming the method to UnescapedString or something to make the intent more obvious.

**Comment by kpdecker** [comment]
I'm not sure that renaming this is going to help for people aren't aware of these concerns and don't read the docs that discuss what this is doing. Since we'd have to do a breaking release to make this change, I don't think the cost out weigh the marginal benefit.

**Comment by wirepair** [comment]
you could keep it for backwards compatibility, but map UnsafeString (or UnescapedString) to it, update the docs on the site and you'd probably save a lot of new users from making mistakes.

**Comment by kpdecker** [comment]
This is only going to lead to further confusion. Have you reached out to these people to let them know what you've seen?
